import type { Question } from '../schema';

export const APP_QUESTIONS: Question[] = [
  // ------------------------------------------------------------- plans and apps
  {
    id: 'app-plan-shared-instances',
    domain: 'compute',
    skills: ['cp.app.plan', 'cp.app.create'],
    concepts: ['app-service-plan', 'app-service'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'Four apps and two deployment slots share one Standard App Service plan. Users report that one app becomes slow whenever a nightly report runs in another app. What is the most likely cause?',
    options: [
      { id: 'a', text: 'All the apps and slots run on the same VM instances and compete for the same CPU and memory', correct: true, why: 'Compute is dedicated at the plan level, not per app — everything in the plan shares the instances.' },
      { id: 'b', text: 'Standard tier apps are throttled to a fixed CPU quota each', why: 'CPU quotas apply to the Free and Shared tiers, not to dedicated tiers.' },
      { id: 'c', text: 'Deployment slots run on separate instances and steal capacity from the plan', why: 'Slots run on the same instances, but they do not have separate capacity to steal.' },
      { id: 'd', text: 'The apps must be in different resource groups to be isolated', why: 'Resource groups are a management boundary and have no effect on compute isolation.' },
    ],
    explanation: {
      correct: 'Microsoft is explicit that compute is dedicated at the plan level, not the per-app level: every app, slot, WebJob, backup and diagnostic log in a plan consumes the same instances. To isolate an app, move it to its own App Service plan.',
      conceptTested: 'The plan as the unit of compute and the unit of noisy-neighbour risk.',
      realWorld: 'Consolidating small apps into one plan saves money; putting a resource-intensive app in with them does not.',
      trap: 'An active slot counts as an active app for resource contention.',
    },
    sources: ['appservice-plans'],
  },
  {
    id: 'app-plan-tier-choice',
    domain: 'compute',
    skills: ['cp.app.plan'],
    concepts: ['app-service-plan', 'deployment-slot'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A web app must support a custom domain, a staging slot for zero-downtime releases and autoscaling. Which is the lowest App Service plan tier that meets all three requirements?',
    options: [
      { id: 'a', text: 'Standard', correct: true, why: 'Standard is the first tier that provides deployment slots and autoscale alongside custom domains.' },
      { id: 'b', text: 'Basic', why: 'Basic supports custom domains but provides no deployment slots.' },
      { id: 'c', text: 'Shared', why: 'Shared runs on shared compute and cannot scale out.' },
      { id: 'd', text: 'Premium v3', why: 'It meets the requirements but is not the lowest tier that does.' },
    ],
    explanation: {
      correct: 'Feature availability is tied to the pricing tier. Standard provides up to 10 instances, 5 deployment slots per app and autoscale — the cheapest tier that satisfies all three requirements.',
      conceptTested: 'Mapping feature requirements to the cheapest sufficient tier.',
      realWorld: 'Premium v3 is chosen for production scale and better price-performance, but Standard is the exam answer when the question asks for the minimum.',
      trap: 'Read "lowest tier" carefully — a higher tier that also works is a distractor.',
    },
    sources: ['appservice-plans', 'appservice-limits'],
  },
  {
    id: 'app-scale-up-vs-out',
    domain: 'compute',
    skills: ['cp.app.scaling'],
    concepts: ['app-service-plan'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'An app’s individual requests are slow and the process regularly runs out of memory, even at low traffic. What should you do?',
    options: [
      { id: 'a', text: 'Scale up: move the plan to a tier with larger instances', correct: true, why: 'More memory and CPU per instance is a scale-up change.' },
      { id: 'b', text: 'Scale out: add more instances to the plan', why: 'More instances serve more concurrent requests; they do not give a single request more memory.' },
      { id: 'c', text: 'Enable autoscale with an aggressive scale-out rule', why: 'Autoscale adds instances, which does not address per-request resource pressure.' },
      { id: 'd', text: 'Move the app to a different resource group', why: 'Resource groups have no effect on performance.' },
    ],
    explanation: {
      correct: 'Scale up changes the pricing tier and therefore the size of each instance. Scale out changes how many instances run. A memory-bound single request needs a bigger instance, not more of them.',
      conceptTested: 'Vertical versus horizontal scaling.',
      realWorld: 'The reverse is just as common: teams scale up an already-large instance when the real problem is concurrency, and the fix is more instances.',
    },
    sources: ['appservice-scale-up', 'appservice-plans'],
  },
  {
    id: 'app-autoscale-tier',
    domain: 'compute',
    skills: ['cp.app.scaling'],
    concepts: ['autoscale', 'app-service-plan'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'Evaluate each statement about scaling an App Service plan.',
    statements: [
      { id: 's1', text: 'Autoscale rules can be configured on a Basic tier plan.', answer: false, why: 'Autoscale requires Standard tier or higher; Basic supports manual scale out up to 3 instances.' },
      { id: 's2', text: 'Autoscale is configured on the App Service plan, so it affects every app in that plan.', answer: true, why: 'The autoscale target is the plan (Microsoft.Web/serverfarms), and apps in a plan scale together.' },
      { id: 's3', text: 'An app in the Free tier can be scaled out to three instances.', answer: false, why: 'Free and Shared apps run on a shared instance and cannot scale out.' },
    ],
    explanation: {
      correct: 'Scaling capability follows the tier: Free and Shared cannot scale out at all, Basic scales out manually to 3 instances, and autoscale starts at Standard where the ceiling is 10 instances.',
      conceptTested: 'Tier limits on scaling.',
      realWorld: 'A plan hosting several apps scales all of them together, which is a reason to separate a spiky app into its own plan.',
    },
    sources: ['appservice-limits', 'appservice-plans'],
  },

  // ------------------------------------------------------------- slots
  {
    id: 'app-slot-settings',
    domain: 'compute',
    skills: ['cp.app.slots'],
    concepts: ['deployment-slot', 'app-service'],
    kind: 'configuration',
    difficulty: 3,
    format: 'multi',
    stem: 'You swap a staging slot into production. Which two of the following stay with the slot they are configured on rather than moving with the swap? Select two.',
    options: [
      { id: 'a', text: 'Custom domain names', correct: true, why: 'Custom domain names are documented as not swapped.' },
      { id: 'b', text: 'Managed identities', correct: true, why: 'Managed identities are documented as not swapped.' },
      { id: 'c', text: 'The .NET framework version', why: 'Language framework settings are swapped.' },
      { id: 'd', text: 'App settings that are not marked as deployment slot settings', why: 'Ordinary app settings swap with the content.' },
    ],
    explanation: {
      correct: 'Configuration is divided into settings that follow the content across a swap and settings that stay with the slot. Custom domains, nonpublic certificates and TLS settings, scale settings, IP restrictions, Always On, diagnostics, CORS, managed identities and virtual network integration all stay put.',
      conceptTested: 'Swapped versus slot-specific configuration.',
      realWorld: 'This is why staging keeps its own restricted access and its own identity while the code moves into production.',
      trap: 'App settings and connection strings swap by default — pinning them requires the Deployment slot setting checkbox.',
    },
    sources: ['appservice-slots'],
  },
  {
    id: 'app-slot-tier',
    domain: 'compute',
    skills: ['cp.app.slots', 'cp.app.plan'],
    concepts: ['deployment-slot'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'An app currently uses seven deployment slots on a Premium v3 plan. To save money you want to move it to Standard. What happens?',
    options: [
      { id: 'a', text: 'You cannot scale down until the app uses no more than five slots, because Standard supports five', correct: true, why: 'The target tier must support the number of slots the app already has.' },
      { id: 'b', text: 'The scale down succeeds and the extra slots are archived', why: 'There is no archiving behaviour; the operation is blocked.' },
      { id: 'c', text: 'The scale down succeeds and the two oldest slots are deleted automatically', why: 'Azure does not silently delete slots.' },
      { id: 'd', text: 'Slots are unaffected because they are billed separately from the plan', why: 'Slots carry no extra charge and run on the plan’s instances; they are not billed separately.' },
    ],
    explanation: {
      correct: 'Deployment slots per app are a tier limit: 5 on Standard, 20 on Premium and Isolated. Microsoft states that to scale to a different tier, the target tier must support the number of slots the app already uses.',
      conceptTested: 'Slot limits as a constraint on scaling down.',
      realWorld: 'Most teams need two or three slots at most; seven usually signals slots being used as long-lived environments.',
    },
    sources: ['appservice-slots', 'appservice-limits'],
  },
  {
    id: 'app-slot-rollback',
    domain: 'compute',
    skills: ['cp.app.slots'],
    concepts: ['deployment-slot'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'Minutes after swapping a new release into production, users report errors. What is the fastest way to restore the previous version?',
    options: [
      { id: 'a', text: 'Swap the same two slots again', correct: true, why: 'After a swap the previous production app is in the staging slot, so swapping again restores it immediately.' },
      { id: 'b', text: 'Restore the app from the most recent automatic backup', why: 'A restore stops the app and takes far longer than a swap.' },
      { id: 'c', text: 'Redeploy the previous build from your pipeline to production', why: 'It works, but it requires a build and a cold start rather than an instant routing change.' },
      { id: 'd', text: 'Scale the plan out to add healthy instances', why: 'Every instance runs the same faulty code.' },
    ],
    explanation: {
      correct: 'A swap exchanges the contents of the two slots. Immediately after a bad swap, the last known good app is sitting in the staging slot, so swapping again is a routing change that takes effect at once.',
      conceptTested: 'Why slots are a release mechanism, not just a test environment.',
      realWorld: 'Teams that treat staging as a rollback buffer avoid deploying over it until the new release has soaked in production.',
    },
    sources: ['appservice-slots'],
  },

  // ------------------------------------------------------------- domains and TLS
  {
    id: 'app-domain-records',
    domain: 'compute',
    skills: ['cp.app.domain'],
    concepts: ['app-service'],
    kind: 'configuration',
    difficulty: 2,
    format: 'match',
    stem: 'Match each custom domain requirement with the DNS record you create for it.',
    prompts: [
      { id: 'p1', text: 'Map the root domain contoso.com to the app', answer: 'c1', why: 'A root domain uses an A record pointing at the app’s IP address; a CNAME is not valid at the apex.' },
      { id: 'p2', text: 'Map the subdomain www.contoso.com to the app', answer: 'c2', why: 'A CNAME to the app’s default hostname is recommended because the app’s IP address can change.' },
      { id: 'p3', text: 'Prove to App Service that you own www.contoso.com', answer: 'c3', why: 'The domain verification ID goes in a TXT record named asuid.<subdomain>.' },
      { id: 'p4', text: 'Map every subdomain of contoso.com to the app', answer: 'c4', why: 'A wildcard mapping uses a CNAME on * to the app’s default hostname.' },
    ],
    choices: [
      { id: 'c1', text: 'A record on @ pointing at the app’s IP address' },
      { id: 'c2', text: 'CNAME on www pointing at the app’s default hostname' },
      { id: 'c3', text: 'TXT record named asuid.www holding the domain verification ID' },
      { id: 'c4', text: 'CNAME on * pointing at the app’s default hostname' },
    ],
    explanation: {
      correct: 'Every custom domain in App Service needs two records: one that maps the name and one that verifies ownership. Root domains use an A record; subdomains and wildcards use a CNAME. The verification record is a TXT named asuid (root and wildcard) or asuid.<subdomain>.',
      conceptTested: 'The DNS records behind a custom domain.',
      realWorld: 'The asuid record is what stops another App Service app from claiming your dangling subdomain — a well-documented high-severity takeover risk.',
      trap: 'A CNAME at the root domain is invalid; the exam uses this as a distractor.',
    },
    sources: ['appservice-custom-domain'],
  },
  {
    id: 'app-domain-tier',
    domain: 'compute',
    skills: ['cp.app.domain', 'cp.app.plan'],
    concepts: ['app-service', 'app-service-plan'],
    kind: 'troubleshooting',
    difficulty: 1,
    format: 'single',
    stem: 'You try to add a custom domain to an app running on the Free (F1) tier and the option is unavailable. What must you do first?',
    options: [
      { id: 'a', text: 'Scale the App Service plan up to a paid tier', correct: true, why: 'Custom domains require a paid tier; the Free tier cannot host one.' },
      { id: 'b', text: 'Move the app to a different region', why: 'Region has nothing to do with custom domain support.' },
      { id: 'c', text: 'Create an Azure DNS zone for the domain', why: 'You can use any public DNS provider; Azure DNS is optional.' },
      { id: 'd', text: 'Add a private DNS zone for the domain', why: 'Custom domains must be in a public DNS zone — private zones are not supported.' },
    ],
    explanation: {
      correct: 'The documented prerequisite is a paid tier. Scaling up to Basic or higher also makes an App Service managed certificate available for the domain.',
      conceptTested: 'Tier prerequisites for custom domains.',
      realWorld: 'The F1 tier is for experiments; everything customer-facing starts at Basic or above.',
    },
    sources: ['appservice-custom-domain', 'appservice-plans'],
  },
  {
    id: 'app-tls-binding',
    domain: 'compute',
    skills: ['cp.app.tls'],
    concepts: ['app-service-certificate', 'app-service'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'single',
    stem: 'Several custom domains must be secured with their own certificates on a single app, at no additional cost for the bindings. Which binding type should you use?',
    options: [
      { id: 'a', text: 'SNI SSL', correct: true, why: 'SNI allows multiple certificates to secure multiple domains on the same IP address and the bindings are free.' },
      { id: 'b', text: 'IP-based SSL', why: 'Only one IP-based binding is allowed per app, it needs a dedicated IP address and it carries an hourly charge.' },
      { id: 'c', text: 'An App Service certificate purchased in Azure', why: 'That is where the certificate comes from, not how it is bound.' },
      { id: 'd', text: 'A private certificate imported from Key Vault', why: 'Again a source of the certificate, not a binding type.' },
    ],
    explanation: {
      correct: 'SNI (Server Name Indication) lets the server present the right certificate based on the hostname the client asks for, so many certificates share one IP address. Microsoft documents SNI TLS connections as free, while IP-based TLS connections carry an hourly charge and are limited to one per app.',
      conceptTested: 'SNI versus IP-based TLS bindings.',
      realWorld: 'IP-based SSL is reserved for clients that cannot do SNI; configuring it changes the app’s inbound IP, so A records must be remapped.',
    },
    sources: ['appservice-certs', 'appservice-custom-domain'],
  },

  // ------------------------------------------------------------- networking
  {
    id: 'app-net-direction',
    domain: 'compute',
    skills: ['cp.app.networking'],
    concepts: ['app-service', 'vnet-integration', 'private-endpoint'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'An App Service app must read from an Azure SQL database that only accepts connections from a subnet in your virtual network. Which feature do you configure on the app?',
    options: [
      { id: 'a', text: 'Virtual network integration', correct: true, why: 'VNet integration is the outbound feature that lets the app make calls into a virtual network.' },
      { id: 'b', text: 'A private endpoint for the app', why: 'A private endpoint is inbound — it controls who can reach the app, not what the app can reach.' },
      { id: 'c', text: 'Access restrictions', why: 'Access restrictions filter inbound requests to the app.' },
      { id: 'd', text: 'An app-assigned IP address', why: 'That gives the app a dedicated inbound address, which does not change its outbound path.' },
    ],
    explanation: {
      correct: 'Microsoft divides App Service networking into inbound features (app-assigned address, access restrictions, service endpoints, private endpoints) and outbound features (Hybrid Connections, virtual network integration). Features that control traffic to the app cannot solve problems with calls from the app.',
      conceptTested: 'Inbound versus outbound App Service networking features.',
      realWorld: 'VNet integration also removes the fragile practice of allow-listing the app’s shared outbound IP addresses, which change when the VM family changes.',
      trap: 'Private endpoint and VNet integration both "connect the app to a VNet" in casual speech; only one of them is outbound.',
    },
    sources: ['appservice-networking'],
  },
  {
    id: 'app-net-hybrid',
    domain: 'compute',
    skills: ['cp.app.networking'],
    concepts: ['app-service'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'An App Service app must call a single on-premises SQL Server instance. There is no VPN or ExpressRoute connection between the datacentre and Azure, and the network team will not open any inbound firewall ports. What should you use?',
    options: [
      { id: 'a', text: 'Hybrid Connections with Hybrid Connection Manager installed on a Windows Server host on-premises', correct: true, why: 'Hybrid Connections tunnels outbound TCP to one host and port through Azure Relay over port 443, with no inbound firewall rule.' },
      { id: 'b', text: 'Virtual network integration', why: 'It gives access into an Azure virtual network; without a VPN or ExpressRoute that network has no path on-premises.' },
      { id: 'c', text: 'A private endpoint on the app', why: 'That is an inbound feature and does nothing for outbound calls.' },
      { id: 'd', text: 'Service endpoints on the App Service subnet', why: 'Service endpoints secure Azure PaaS resources from a subnet; they do not reach on-premises.' },
    ],
    explanation: {
      correct: 'Hybrid Connections is built on Azure Relay. The relay agent makes an outbound connection to Azure on port 443, so no inbound firewall hole is needed, and each hybrid connection reaches exactly one host and port.',
      conceptTested: 'Choosing the outbound feature that matches the network reality.',
      realWorld: 'It is popular for lift-and-shift: move the web tier to App Service while the database stays on-premises.',
      trap: 'Hybrid Connections is per host and port — it is not a general network connection.',
    },
    sources: ['appservice-networking'],
  },

  // ------------------------------------------------------------- backup
  {
    id: 'app-backup-custom',
    domain: 'compute',
    skills: ['cp.app.backup'],
    concepts: ['app-service'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You must keep backups of an App Service app for longer than 30 days and be able to download them. Which option meets the requirement?',
    options: [
      { id: 'a', text: 'Configure custom backups to a storage account you own', correct: true, why: 'Custom backups support retention from 0–30 days or indefinite and are downloadable as Azure Storage blobs.' },
      { id: 'b', text: 'Rely on automatic backups and change the retention setting', why: 'Automatic backup retention is 30 days and is not configurable.' },
      { id: 'c', text: 'Enable automatic backups and download them from the Backups page', why: 'Automatic backups are documented as not downloadable.' },
      { id: 'd', text: 'Take a snapshot of the App Service plan', why: 'There is no plan snapshot feature.' },
    ],
    explanation: {
      correct: 'Automatic backups are hourly, 30 GB, retained for 30 days, not configurable and not downloadable. Custom backups require configuration and a storage account, but give you a schedule, retention of up to 30 days or indefinite, downloadable blobs and partial backups.',
      conceptTested: 'Automatic versus custom backups.',
      realWorld: 'Custom backups also work over a virtual network to a firewall-protected storage account, which automatic backups do not.',
      trap: 'Custom backups require a storage account that supports SAS-based authorization; managed identity is not supported for this operation.',
    },
    sources: ['appservice-backup'],
  },
  {
    id: 'app-backup-restore-slot',
    domain: 'compute',
    skills: ['cp.app.backup', 'cp.app.slots'],
    concepts: ['app-service', 'deployment-slot'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'You need to restore a backup of a production app while keeping downtime to a minimum. What should you do?',
    options: [
      { id: 'a', text: 'Restore the backup to a new deployment slot, verify it, then swap it into production', correct: true, why: 'App Service stops the target app or slot during a restore, so restoring to a slot keeps production online until the swap.' },
      { id: 'b', text: 'Restore the backup directly over the production app', why: 'That stops the production app and erases its file system while the restore runs.' },
      { id: 'c', text: 'Scale the plan out before restoring so other instances keep serving', why: 'The restore affects the app, not one instance; extra instances do not keep the old content serving.' },
      { id: 'd', text: 'Restore to a new App Service in another region and update DNS', why: 'It avoids downtime on the original app but requires a DNS change and propagation.' },
    ],
    explanation: {
      correct: 'Microsoft recommends restoring into a deployment slot and swapping, precisely because a restore stops the target and overwrites its file system.',
      conceptTested: 'Combining backup and slots to avoid downtime.',
      realWorld: 'The same pattern applies to risky configuration changes: make them in a slot, validate, then swap.',
    },
    sources: ['appservice-backup', 'appservice-slots'],
  },

  // ------------------------------------------------------------- containers
  {
    id: 'app-acr-sku',
    domain: 'compute',
    skills: ['cp.containers.acr'],
    concepts: ['container-registry'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A container registry must be replicated to three regions and reachable only over a private endpoint. Which pricing plan do you need?',
    options: [
      { id: 'a', text: 'Premium', correct: true, why: 'Geo-replication and private link with private endpoints are both Premium-only features.' },
      { id: 'b', text: 'Standard', why: 'Standard adds storage and throughput over Basic but supports neither geo-replication nor private endpoints.' },
      { id: 'c', text: 'Basic', why: 'Basic is the entry-level plan and supports neither feature.' },
      { id: 'd', text: 'Any plan — both features are available everywhere', why: 'Both are documented as Premium-only.' },
    ],
    explanation: {
      correct: 'Premium adds geo-replication, private link with private endpoints, IP access rules, customer-managed keys, content trust and the highest storage and throughput. You can change plan at any time without downtime, but geo-replications must be deleted before moving down from Premium.',
      conceptTested: 'Which ACR features are gated behind Premium.',
      realWorld: 'Geo-replication reduces pull latency and egress cost for clusters deployed in several regions.',
    },
    sources: ['acr-skus'],
  },
  {
    id: 'app-acr-pull-auth',
    domain: 'compute',
    skills: ['cp.containers.acr'],
    concepts: ['container-registry'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'A container app must pull images from Azure Container Registry with no credentials stored in its configuration. What should you configure?',
    options: [
      { id: 'a', text: 'A managed identity for the app, granted the AcrPull role on the registry', correct: true, why: 'Managed identity plus the AcrPull role removes stored credentials entirely.' },
      { id: 'b', text: 'The registry’s admin user, with the username and password as app settings', why: 'That stores a shared credential in configuration — the thing the requirement rules out.' },
      { id: 'c', text: 'A repository-scoped token stored as a secret', why: 'Still a stored credential, even if narrower in scope.' },
      { id: 'd', text: 'Anonymous pull access on the registry', why: 'That makes images publicly readable, which is a security regression, and it is not supported on Basic.' },
    ],
    explanation: {
      correct: 'Azure Container Registry integrates with Microsoft Entra ID. Assigning AcrPull to a managed identity lets the platform obtain tokens at pull time, so no secret ever exists to leak or rotate.',
      conceptTested: 'Credential-free authentication to a registry.',
      realWorld: 'ACI, Container Apps, App Service and AKS all support pulling with a managed identity.',
      trap: 'The admin account is a single shared identity, disabled by default and intended only for testing.',
    },
    sources: ['acr-auth', 'managed-identities'],
  },
  {
    id: 'app-aci-restart-policy',
    domain: 'compute',
    skills: ['cp.containers.aci'],
    concepts: ['container-instances'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You run a nightly data import as a container instance. The container should run, finish and stop — but if the process exits with an error it should be retried. Which restart policy should you set?',
    options: [
      { id: 'a', text: 'OnFailure', correct: true, why: 'OnFailure restarts the container only when the process exits with a nonzero exit code, and the container runs at least once.' },
      { id: 'b', text: 'Always', why: 'Always restarts the container even after a successful run — and it is the default, which is why run-once tasks must set a policy explicitly.' },
      { id: 'c', text: 'Never', why: 'Never means a successful exit is final, with no retry on failure guaranteed by you.' },
      { id: 'd', text: 'Manual', why: 'There is no Manual restart policy in Azure Container Instances.' },
    ],
    explanation: {
      correct: 'The three documented values are Always (the default), OnFailure and Never. OnFailure is the run-to-completion policy with retry. When a container with Never or OnFailure finishes, its state becomes Terminated and billing stops.',
      conceptTested: 'Restart policy as the definition of "finished" for a container task.',
      realWorld: 'Read the task’s output afterwards with az container logs, or have the container write results to an Azure Files share.',
      trap: 'Never only guarantees no restart after a zero exit code; the platform might still restart a container that exits with an error.',
    },
    sources: ['aci-restart-policy'],
  },
  {
    id: 'app-aci-group',
    domain: 'compute',
    skills: ['cp.containers.aci'],
    concepts: ['container-instances'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'Evaluate each statement about container groups in Azure Container Instances.',
    statements: [
      { id: 's1', text: 'Containers in a group share a lifecycle, local network and storage volumes.', answer: true, why: 'That is the documented definition of a container group — the same concept as a Kubernetes pod.' },
      { id: 's2', text: 'Multi-container groups are supported for Windows containers.', answer: false, why: 'Multi-container groups currently support Linux containers only; Windows supports a single container instance.' },
      { id: 's3', text: 'Containers inside a group can reach each other on localhost, even on ports that are not exposed externally.', answer: true, why: 'Within a group, container instances reach each other via localhost on any port.' },
    ],
    explanation: {
      correct: 'The container group is the top-level ACI resource: one host, one lifecycle, one local network, shared volumes, and a single public IP with a DNS name label if you request one. Multi-container groups are Linux-only.',
      conceptTested: 'What a container group is and what it shares.',
      realWorld: 'The sidecar pattern — an application container plus a logging or monitoring container — is the usual reason to use more than one container in a group.',
    },
    sources: ['aci-container-groups', 'aci-overview'],
  },
  {
    id: 'app-aca-scale-rule',
    domain: 'compute',
    skills: ['cp.containers.aca', 'cp.containers.scaling'],
    concepts: ['container-apps'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A Container Apps background worker has ingress disabled, no scale rule and minimum replicas set to 0. It processes messages for a while after deployment and then stops permanently. What is the cause and the fix?',
    options: [
      { id: 'a', text: 'It scaled to zero and has no trigger to start it again — add a custom (event-driven) scale rule or set minimum replicas to at least 1', correct: true, why: 'With no ingress and no scale rule, nothing can wake the app once it scales to zero.' },
      { id: 'b', text: 'The revision became inactive — create a new revision each time work arrives', why: 'Revisions do not deactivate themselves, and creating one per message is not a scaling mechanism.' },
      { id: 'c', text: 'The environment ran out of capacity — move the app to a new environment', why: 'Nothing in the symptom points to environment capacity.' },
      { id: 'd', text: 'The maximum replica count defaulted to 0 — raise it to 10', why: 'The documented default maximum is 10, and the minimum value for maximum replicas is 1.' },
    ],
    explanation: {
      correct: 'Microsoft calls this out explicitly: if ingress is disabled and you define neither minReplicas nor a custom scale rule, the app scales to zero and has no way of starting back up. An event-driven rule (for example an Azure Service Bus or storage queue scaler) gives it a trigger.',
      conceptTested: 'Scale to zero and what can wake an app back up.',
      realWorld: 'HTTP-facing apps are safe because a request itself is the trigger; background workers are the ones that go quiet.',
    },
    sources: ['aca-scale'],
  },
  {
    id: 'app-aca-revision',
    domain: 'compute',
    skills: ['cp.containers.aca'],
    concepts: ['container-apps'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'You want to release a new version of a container app to 10% of users first, then move everyone across once it looks healthy. Which Container Apps feature does this?',
    options: [
      { id: 'a', text: 'Revisions with weighted traffic splitting', correct: true, why: 'Each change creates an immutable revision, and traffic weights decide how requests are distributed between revisions.' },
      { id: 'b', text: 'Deployment slots with swap', why: 'Slots are an App Service feature, not a Container Apps one.' },
      { id: 'c', text: 'A second container app in the same environment', why: 'That works only if you add your own traffic distribution in front of it.' },
      { id: 'd', text: 'A custom scale rule on the new version', why: 'Scale rules control replica count, not how traffic is split.' },
    ],
    explanation: {
      correct: 'A revision is an immutable snapshot of a container app. In multiple-revision mode you assign traffic weights across revisions, which gives canary releases and instant rollback by shifting the weights back.',
      conceptTested: 'Revisions as the Container Apps release mechanism.',
      realWorld: 'Adding or editing a scale rule also creates a new revision — a detail worth knowing when traffic is split.',
    },
    sources: ['aca-containers', 'aca-scale'],
  },
  {
    id: 'app-aca-environment',
    domain: 'compute',
    skills: ['cp.containers.aca'],
    concepts: ['container-apps'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'What is the role of an Azure Container Apps environment?',
    options: [
      { id: 'a', text: 'A secure boundary around a group of container apps that share a virtual network and a logging destination, and can call each other', correct: true, why: 'That is the documented purpose of an environment.' },
      { id: 'b', text: 'A pricing tier that determines which features the container apps can use', why: 'Environments are not pricing tiers.' },
      { id: 'c', text: 'A staging copy of a container app used for testing before release', why: 'That is what revisions and traffic splitting are for.' },
      { id: 'd', text: 'A Kubernetes cluster you manage and patch yourself', why: 'Container Apps is a managed platform — there is no cluster for you to operate.' },
    ],
    explanation: {
      correct: 'The environment is the isolation boundary. Apps deployed into the same environment share a virtual network and write logs to the same destination, which is what lets them discover and call each other internally.',
      conceptTested: 'The Container Apps resource hierarchy.',
      realWorld: 'Group apps that belong to one system in one environment; keep unrelated systems apart.',
    },
    sources: ['aca-environment'],
  },
  {
    id: 'app-plan-os-immutable',
    domain: 'compute',
    skills: ['cp.app.plan', 'cp.app.create'],
    concepts: ['app-service-plan'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'Which property of an App Service plan cannot be changed after it is created?',
    options: [
      { id: 'a', text: 'The operating system', correct: true, why: 'A plan defines its OS at creation; moving between Windows and Linux means a new plan.' },
      { id: 'b', text: 'The pricing tier', why: 'Scaling up and down changes the tier at any time.' },
      { id: 'c', text: 'The number of VM instances', why: 'Scaling out and in changes the instance count.' },
      { id: 'd', text: 'The apps hosted in the plan', why: 'Apps can be moved between plans in the same resource group and region.' },
    ],
    explanation: {
      correct: 'A plan defines operating system, region, instance count and pricing tier. Instance count and tier are adjustable; OS and region are fixed for the life of the plan.',
      conceptTested: 'Creation-time versus adjustable plan properties.',
      realWorld: 'Migrating a Windows app to Linux means a new plan and a redeploy, so the OS decision belongs in the design.',
    },
    sources: ['appservice-plans'],
  },
];
