import type { Question } from '../schema';

export const BACKUP_QUESTIONS: Question[] = [
  // ------------------------------------------------------------ backup vs DR
  {
    id: 'bk-backup-vs-dr',
    domain: 'monitoring',
    skills: ['mo.backup.rsv', 'mo.backup.asr'],
    concepts: ['azure-backup', 'site-recovery'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'Ransomware encrypts the files on a production VM that is replicated to a second region with Azure Site Recovery and backed up daily with Azure Backup. How do you recover the data?',
    options: [
      { id: 'a', text: 'Restore from an Azure Backup recovery point taken before the encryption', correct: true, why: 'Only backups keep history you can go back to.' },
      { id: 'b', text: 'Fail over to the secondary region with Site Recovery', why: 'Replication is continuous, so the encrypted files were replicated within minutes — the copy is encrypted too.' },
      { id: 'c', text: 'Run a test failover and copy the files out of the test VM', why: 'The test VM is built from the same replicated — and therefore encrypted — data.' },
      { id: 'd', text: 'Reprotect the VM so replication reverses and restores the original files', why: 'Reprotect changes replication direction; it does not recover past data.' },
    ],
    explanation: {
      correct: 'Replication protects against losing the location; backup protects against losing the correctness of the data. Corruption, deletion and ransomware all replicate faithfully, so recovery has to come from a point-in-time backup.',
      conceptTested: 'The complementary roles of backup and disaster recovery.',
      realWorld: 'This is exactly why a vault’s soft delete and immutability features matter — they stop an attacker deleting the one copy that can save you.',
      trap: 'Having a second region feels like protection until the failure is data corruption rather than infrastructure loss.',
    },
    sources: ['rsv-overview', 'asr-architecture'],
  },
  {
    id: 'bk-rpo-rto',
    domain: 'monitoring',
    skills: ['mo.backup.asr', 'mo.backup.policy'],
    concepts: ['azure-backup', 'site-recovery'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'Evaluate each statement about recovery objectives.',
    statements: [
      { id: 's1', text: 'RPO describes how much data the business can afford to lose, expressed as a period of time.', answer: true, why: 'The recovery point objective is the maximum acceptable data loss.' },
      { id: 's2', text: 'RTO describes how long the business can afford the workload to be unavailable.', answer: true, why: 'The recovery time objective is the maximum acceptable downtime.' },
      { id: 's3', text: 'A daily Azure VM backup can deliver an RPO of one hour.', answer: false, why: 'A daily schedule means up to 24 hours of data loss; sub-daily RPO needs an Enhanced policy with hourly backups or replication.' },
    ],
    explanation: {
      correct: 'RPO and RTO are business numbers that select the technology, not the other way round. Daily backup gives a 24-hour RPO; an Enhanced policy can reach 4 hours; Site Recovery replication reaches minutes.',
      conceptTested: 'Translating recovery objectives into a technology choice.',
      realWorld: 'Writing the two numbers down per workload is the fastest way to find the workloads that are quietly under-protected.',
    },
    sources: ['vm-backup-enhanced', 'asr-architecture'],
  },

  // --------------------------------------------------------------- the vaults
  {
    id: 'bk-vault-type',
    domain: 'monitoring',
    skills: ['mo.backup.rsv', 'mo.backup.bv'],
    concepts: ['recovery-services-vault', 'backup-vault'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You must protect Azure VMs with Azure Backup and replicate the same VMs with Azure Site Recovery. Which vault type do you create?',
    options: [
      { id: 'a', text: 'A Recovery Services vault', correct: true, why: 'Recovery Services vaults hold Azure VM backups and Site Recovery replication.' },
      { id: 'b', text: 'A Backup vault', why: 'Backup vaults protect newer workloads such as blobs, disks and PostgreSQL, and do not host Site Recovery.' },
      { id: 'c', text: 'One of each — a Backup vault for the backups and a Recovery Services vault for replication', why: 'Azure VM backup belongs in the Recovery Services vault, so a Backup vault adds nothing here.' },
      { id: 'd', text: 'A storage account with immutable blob storage', why: 'Azure Backup manages vault storage itself; a storage account is not a substitute.' },
    ],
    explanation: {
      correct: 'A Recovery Services vault covers Azure IaaS VMs, SQL Server in Azure VMs, Azure Files and on-premises workloads through DPM, MABS and Windows Server — and it is also where Site Recovery replication is configured.',
      conceptTested: 'Which vault serves which workload.',
      realWorld: 'The vault also becomes the central monitoring point for both backup and Site Recovery jobs.',
    },
    sources: ['rsv-overview', 'backup-vault'],
  },
  {
    id: 'bk-vault-redundancy',
    domain: 'monitoring',
    skills: ['mo.backup.rsv'],
    concepts: ['recovery-services-vault', 'paired-region'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A Recovery Services vault protecting 200 VMs was created with locally redundant storage. Compliance now requires the backups to survive a regional failure. What must you do?',
    options: [
      { id: 'a', text: 'Create a new vault with geo-redundant storage and reconfigure protection for the VMs there', correct: true, why: 'Storage redundancy cannot be changed once backup items exist in the vault.' },
      { id: 'b', text: 'Change the vault’s backup storage redundancy to GeoRedundant', why: 'The setting is locked once the vault contains protected items.' },
      { id: 'c', text: 'Enable Cross Region Restore on the existing vault', why: 'Cross Region Restore requires geo-redundant storage, which this vault does not have.' },
      { id: 'd', text: 'Enable soft delete with a longer retention period', why: 'Soft delete protects against deletion, not against losing the region.' },
    ],
    explanation: {
      correct: 'Storage redundancy is chosen on an empty vault. After the first item is protected it cannot be changed, so the fix is a new vault with the right setting and re-protection of the workloads.',
      conceptTested: 'Vault settings that must be right before protection starts.',
      realWorld: 'The same applies to customer-managed key encryption — configure it before protecting anything.',
      trap: 'Cross Region Restore is an addition to GRS, not an alternative to it.',
    },
    sources: ['rsv-overview', 'storage-redundancy'],
  },
  {
    id: 'bk-soft-delete',
    domain: 'monitoring',
    skills: ['mo.backup.rsv'],
    concepts: ['recovery-services-vault', 'azure-backup'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'An administrator account is compromised and the attacker deletes the backups of a protected VM. What does soft delete provide?',
    options: [
      { id: 'a', text: 'The deleted backup data is retained for 14 additional days at no cost and can be recovered with no data loss', correct: true, why: 'That is the documented behaviour of soft delete in a Recovery Services vault.' },
      { id: 'b', text: 'The deletion is blocked outright and cannot be performed', why: 'That is closer to an immutable vault; soft delete allows the delete but retains the data.' },
      { id: 'c', text: 'The data is retained for 90 days and billed at the archive rate', why: 'The documented period is 14 additional days, at no cost.' },
      { id: 'd', text: 'The backups are replicated to the paired region for recovery', why: 'That is geo-redundant storage, not soft delete.' },
    ],
    explanation: {
      correct: 'Soft delete retains deleted backup data for 14 extra days at no charge, so the item can be recovered intact. Enhanced soft delete additionally lets you customise the retention period and make soft delete always-on so it cannot be disabled by an attacker.',
      conceptTested: 'Vault security features against malicious deletion.',
      realWorld: 'Pair enhanced soft delete with an immutable vault and multi-user authorisation for a backup estate that survives a compromised administrator.',
    },
    sources: ['rsv-overview'],
  },

  // -------------------------------------------------------------- policies
  {
    id: 'bk-enhanced-policy',
    domain: 'monitoring',
    skills: ['mo.backup.policy'],
    concepts: ['backup-policy', 'recovery-services-vault'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A business requires no more than four hours of data loss for an Azure VM that uses Premium SSD v2 disks. Which backup policy configuration meets the requirement?',
    options: [
      { id: 'a', text: 'An Enhanced policy with an hourly schedule at a four-hour interval', correct: true, why: 'The Enhanced policy supports multiple backups per day — as often as every 4 hours — and is the only policy type that supports Premium SSD v2.' },
      { id: 'b', text: 'A Standard policy running daily, with a longer retention range', why: 'Daily backups mean up to 24 hours of data loss, and the Standard policy does not support Premium SSD v2.' },
      { id: 'c', text: 'A Standard policy with instant restore retention set to 30 days', why: 'Snapshot retention does not change how often backups are taken.' },
      { id: 'd', text: 'Two Standard policies applied to the same VM, twelve hours apart', why: 'A VM is protected by one policy, and the RPO would still be 12 hours.' },
    ],
    explanation: {
      correct: 'The Enhanced policy offers hourly schedules at intervals of 4, 6, 8, 12 or 24 hours — a minimum RPO of 4 hours — and adds support for Trusted Launch VMs, Premium SSD v2 and Ultra Disks, none of which the Standard policy protects.',
      conceptTested: 'Matching a stated RPO and disk type to a policy type.',
      realWorld: 'More frequent snapshots reduce the maximum instant restore retention you can configure, so the two settings are chosen together.',
      trap: 'Once a VM is protected with an Enhanced policy, Azure Backup does not allow changing the policy type back to Standard.',
    },
    sources: ['vm-backup-enhanced'],
  },
  {
    id: 'bk-instant-restore',
    domain: 'monitoring',
    skills: ['mo.backup.policy'],
    concepts: ['backup-policy'],
    kind: 'configuration',
    difficulty: 3,
    format: 'single',
    stem: 'In an Azure VM backup policy, what does the instant restore retention setting control?',
    options: [
      { id: 'a', text: 'How many days recovery snapshots are kept in the operational tier for fast restores — 1 to 30 days, defaulting to 7', correct: true, why: 'That is the documented range and default for the Enhanced policy.' },
      { id: 'b', text: 'How long recovery points are kept in the vault before deletion', why: 'That is the retention range, configured separately per daily, weekly, monthly and yearly point.' },
      { id: 'c', text: 'How quickly a restore job starts after you trigger it', why: 'It is a retention setting, not a scheduling one.' },
      { id: 'd', text: 'How long the vault retains data after a backup item is deleted', why: 'That is soft delete.' },
    ],
    explanation: {
      correct: 'Instant restore keeps snapshots alongside the VM’s disks so recent restores do not read from the vault. Retention runs from 1 to 30 days with a default of 7, can never exceed the vault retention, and the achievable maximum falls as snapshot frequency rises.',
      conceptTested: 'The two independent retention settings in a backup policy.',
      realWorld: 'More snapshot days means faster recovery from recent mistakes, at a higher snapshot cost.',
    },
    sources: ['vm-backup-enhanced'],
  },

  // -------------------------------------------------------------- restores
  {
    id: 'bk-restore-option',
    domain: 'monitoring',
    skills: ['mo.backup.operations'],
    concepts: ['azure-backup', 'recovery-services-vault'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'A VM was deleted by mistake. Its backups are intact in the vault. Which restore option can you use?',
    options: [
      { id: 'a', text: 'Create new — or Restore disks and build the VM from the generated template', correct: true, why: 'Both work when the original VM no longer exists.' },
      { id: 'b', text: 'Replace existing', why: 'Replace existing requires the current VM to exist; if it has been deleted the option cannot be used.' },
      { id: 'c', text: 'File recovery', why: 'File recovery retrieves individual files; it does not rebuild a VM.' },
      { id: 'd', text: 'Cross Subscription Restore only', why: 'That governs which subscription you restore into, not whether the original VM exists.' },
    ],
    explanation: {
      correct: 'Create new builds a VM from the recovery point; Restore disks produces managed disks plus an ARM template, which is the option to use when the VM had a special network configuration such as a load balancer, multiple NICs or reserved IP addresses.',
      conceptTested: 'The three VM restore options and their prerequisites.',
      realWorld: 'A restored VM keeps the SKU the original had when the recovery point was taken, not any size change made afterwards.',
      trap: 'Replace existing is also unsupported for classic VMs, unmanaged VMs and generalized VMs.',
    },
    sources: ['vm-restore'],
  },
  {
    id: 'bk-crr-restore',
    domain: 'monitoring',
    skills: ['mo.backup.operations', 'mo.backup.rsv'],
    concepts: ['recovery-services-vault', 'paired-region'],
    kind: 'knowledge',
    difficulty: 3,
    format: 'multi',
    stem: 'Which two statements about Cross Region Restore for Azure VMs are correct? Select two.',
    options: [
      { id: 'a', text: 'It restores into the Azure paired secondary region and requires geo-redundant storage on the vault', correct: true, why: 'Cross Region Restore builds on GRS and targets the paired region.' },
      { id: 'b', text: 'It supports Create new and Restore disks, but not Replace existing', correct: true, why: 'Replace existing is documented as unsupported for secondary-region restores.' },
      { id: 'c', text: 'It can only be used after Microsoft declares an outage in the primary region', why: 'Cross Region Restore is specifically what lets you restore from the secondary region at any time, including for drills.' },
      { id: 'd', text: 'Instant restore snapshots are replicated to the secondary region for faster restores', why: 'Snapshots are not replicated — only vault data is, so secondary restores are vault-tier restores.' },
    ],
    explanation: {
      correct: 'Cross Region Restore is enabled at the vault level on a geo-redundant vault. Because only vault-tier data is replicated, the restore time in the secondary region is comparable to a vault-tier restore in the primary, and the staging storage account must be in the secondary region.',
      conceptTested: 'What Cross Region Restore adds on top of geo-redundant storage.',
      realWorld: 'Being able to restore without an outage is what makes an annual compliance drill possible.',
    },
    sources: ['vm-restore', 'rsv-overview', 'regions-paired'],
  },
  {
    id: 'bk-file-recovery',
    domain: 'monitoring',
    skills: ['mo.backup.operations'],
    concepts: ['azure-backup'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'A user deleted three configuration files from a production VM this morning. The application still runs. What is the least disruptive way to get them back?',
    options: [
      { id: 'a', text: 'Use file recovery to mount the recovery point as a drive, copy the files, then unmount it', correct: true, why: 'File recovery retrieves individual files without touching the running VM.' },
      { id: 'b', text: 'Use Replace existing to roll the VM disks back to this morning’s recovery point', why: 'That discards every change made since the recovery point and takes the VM down.' },
      { id: 'c', text: 'Create a new VM from the recovery point and swap it into production', why: 'Far more disruptive than copying three files.' },
      { id: 'd', text: 'Fail the VM over to the secondary region with Site Recovery', why: 'Replication copied the deletion, and failing over does not recover files.' },
    ],
    explanation: {
      correct: 'File recovery downloads a script that mounts the recovery point as a drive on a machine you choose. You copy what you need and unmount — no VM is created and nothing about the running workload changes.',
      conceptTested: 'Matching the restore granularity to the loss.',
      realWorld: 'Always unmount when finished; the mounted recovery point holds resources open in the vault.',
    },
    sources: ['vm-restore'],
  },

  // ------------------------------------------------------------- monitoring
  {
    id: 'bk-reports-prereq',
    domain: 'monitoring',
    skills: ['mo.backup.reports'],
    concepts: ['recovery-services-vault', 'diagnostic-settings', 'log-analytics-workspace'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You open Backup Reports for a vault that has been protecting VMs for a year and it shows no data. What is the cause?',
    options: [
      { id: 'a', text: 'No diagnostic setting sends the vault’s backup data to a Log Analytics workspace', correct: true, why: 'Backup Reports is a workbook built on vault diagnostic data in a workspace.' },
      { id: 'b', text: 'The vault uses locally redundant storage', why: 'Redundancy has no bearing on reporting.' },
      { id: 'c', text: 'The backup policy is Standard rather than Enhanced', why: 'Policy type does not affect reporting.' },
      { id: 'd', text: 'Soft delete is disabled on the vault', why: 'Unrelated to report data.' },
    ],
    explanation: {
      correct: 'The vault’s built-in job and item views work with no configuration, but historical reporting requires a diagnostic setting sending backup data to a Log Analytics workspace — and the report only covers the period since that setting was created.',
      conceptTested: 'Reporting prerequisites for Azure Backup.',
      realWorld: 'Send several vaults to one workspace so a single report covers the whole estate.',
      trap: 'Enabling it today does not backfill last year.',
    },
    sources: ['backup-reports', 'diagnostic-settings'],
  },

  // ----------------------------------------------------------- site recovery
  {
    id: 'bk-asr-commit',
    domain: 'monitoring',
    skills: ['mo.backup.failover'],
    concepts: ['site-recovery'],
    kind: 'knowledge',
    difficulty: 3,
    format: 'single',
    stem: 'After failing VMs over to the secondary region, what does the Commit operation do?',
    options: [
      { id: 'a', text: 'It finishes the failover and deletes all remaining recovery points for the VM, so the recovery point can no longer be changed', correct: true, why: 'That is the documented effect of commit.' },
      { id: 'b', text: 'It starts replicating the VM back to the primary region', why: 'That is Reprotect.' },
      { id: 'c', text: 'It deletes the source VMs in the primary region', why: 'Commit does not delete source resources.' },
      { id: 'd', text: 'It creates a new recovery point in the secondary region', why: 'Commit removes recovery points rather than creating them.' },
    ],
    explanation: {
      correct: 'Before committing you can still select a different recovery point with Change recovery point. Commit ends that option by deleting the remaining points, so verify the failed-over VM is running and correctly sized first.',
      conceptTested: 'The failover lifecycle: failover → verify → commit → reprotect.',
      realWorld: 'Until you reprotect, the workload is running in the secondary region with no disaster recovery protection at all.',
    },
    sources: ['asr-failover'],
  },
  {
    id: 'bk-asr-recovery-point',
    domain: 'monitoring',
    skills: ['mo.backup.failover'],
    concepts: ['site-recovery'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'single',
    stem: 'During a failover you must minimise data loss, accepting extra time for the failover itself. Which recovery point do you choose?',
    options: [
      { id: 'a', text: 'Latest', correct: true, why: 'Latest processes all data already sent to Site Recovery before failing over, giving the lowest RPO.' },
      { id: 'b', text: 'Latest processed', why: 'It gives the lowest RTO because no processing is needed, at the cost of slightly more data loss.' },
      { id: 'c', text: 'Latest app-consistent', why: 'Safest for application state, but typically an older point than the latest crash-consistent one.' },
      { id: 'd', text: 'Custom', why: 'Custom targets a specific earlier point and is only available for a single VM without a recovery plan.' },
    ],
    explanation: {
      correct: 'Latest creates a recovery point for each VM from all the data Site Recovery has received, minimising RPO. Latest processed skips that work and minimises RTO instead. The scenario’s wording — minimise data loss, accept extra time — names Latest.',
      conceptTested: 'RPO versus RTO expressed as a recovery point choice.',
      realWorld: 'Database tiers often use Latest app-consistent so they come up in a consistent state without a lengthy recovery.',
    },
    sources: ['asr-failover'],
  },
  {
    id: 'bk-asr-reprotect',
    domain: 'monitoring',
    skills: ['mo.backup.asr', 'mo.backup.failover'],
    concepts: ['site-recovery'],
    kind: 'multi-step',
    difficulty: 3,
    format: 'order',
    stem: 'Put the Azure-to-Azure Site Recovery operations in the order you would perform them for a planned regional migration.',
    items: [
      { id: 'i1', text: 'Enable replication from the primary to the secondary region' },
      { id: 'i2', text: 'Run a test failover into an isolated network and validate the application' },
      { id: 'i3', text: 'Run the failover, choosing a recovery point' },
      { id: 'i4', text: 'Verify the VMs in the secondary region, then Commit' },
      { id: 'i5', text: 'Reprotect so the VMs replicate back to the primary region' },
    ],
    why: 'Replication must exist before anything can be tested. The drill validates the plan without touching production. Failover creates the VMs, commit finalises the choice of recovery point, and reprotect restores disaster recovery coverage in the new direction.',
    explanation: {
      correct: 'Enable replication → test failover → failover → commit → reprotect. Microsoft recommends running a drill before any real failover, and the VM status must show Failover committed before reprotect can start.',
      conceptTested: 'The Site Recovery lifecycle end to end.',
      realWorld: 'A recovery plan turns a multi-VM version of this into one ordered operation, with the database tier brought up before the application tier.',
    },
    sources: ['asr-failover', 'asr-architecture'],
  },
];
