import type { Question } from '../schema';

export const COMPUTE_QUESTIONS: Question[] = [
  // ---------------------------------------------------------------- availability
  {
    id: 'cmp-zones-sla',
    domain: 'compute',
    skills: ['cp.vm.availability'],
    concepts: ['availability-set', 'availability-zone'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'You must maximise the availability SLA for a set of virtual machines running the same application in a single region. Which deployment gives the highest SLA?',
    options: [
      { id: 'a', text: 'Two or more VMs spread across two or more availability zones', correct: true, why: 'Zonal spreading uses physically separate datacentres and carries the highest single-region VM SLA.' },
      { id: 'b', text: 'Two or more VMs in the same availability set', why: 'An availability set protects against rack-level and update-related failures inside one datacentre, and carries a lower SLA than zones.' },
      { id: 'c', text: 'A single VM with all Premium SSD disks', why: 'A single-instance SLA is lower than any multi-instance option, however good the disks.' },
      { id: 'd', text: 'Two VMs in the same zone behind a Standard load balancer', why: 'Both VMs share one datacentre, so a zone failure takes out the whole application.' },
    ],
    explanation: {
      correct: 'Availability zones are physically separate locations within a region, each with independent power, cooling and networking. Spreading instances across zones survives the loss of an entire datacentre; an availability set only survives failures within one.',
      conceptTested: 'The availability ladder: single instance → availability set → availability zones.',
      realWorld: 'Production workloads that must survive a datacentre fire or flood are deployed zonally; always confirm the region actually offers zones.',
      trap: 'Availability sets and availability zones are not alternatives of equal strength — zones protect against a strictly larger class of failures.',
    },
    sources: ['availability-zones', 'availability-sets', 'vm-availability'],
  },
  {
    id: 'cmp-zonal-vs-redundant',
    domain: 'compute',
    skills: ['cp.vm.availability'],
    concepts: ['availability-zone'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'single',
    stem: 'A colleague says the new VMs are "zone-redundant". You check and find each VM was created pinned to a specific zone. What is the accurate description?',
    options: [
      { id: 'a', text: 'They are zonal resources; the deployment is zone-redundant only if instances are placed in different zones and fronted by a zone-redundant service', correct: true, why: 'A VM is always a zonal resource — redundancy comes from how you spread instances and the services in front of them.' },
      { id: 'b', text: 'They are zone-redundant, because any VM in a zone-enabled region is automatically replicated to other zones', why: 'Azure never replicates a VM to another zone automatically.' },
      { id: 'c', text: 'They are regional resources, because the resource group is regional', why: 'The resource group location only stores metadata; it does not decide where a VM runs.' },
      { id: 'd', text: 'They are zone-redundant only if the disks are configured as Premium SSD v2', why: 'Disk SKU does not create zone redundancy for the VM.' },
    ],
    explanation: {
      correct: 'Azure distinguishes zonal resources (pinned to one zone, such as a VM or a zonal public IP) from zone-redundant resources (the service replicates across zones for you, such as ZRS storage or a Standard zone-redundant load balancer). VM resilience is built by placing instances in different zones yourself.',
      conceptTested: 'Zonal vs zone-redundant — a distinction the exam tests directly.',
      realWorld: 'Teams often believe zone selection alone gives resilience; a single zonal VM is still a single point of failure.',
      trap: 'The words are similar; the behaviour is not.',
    },
    sources: ['availability-zones', 'vm-availability'],
  },
  {
    id: 'cmp-avset-add',
    domain: 'compute',
    skills: ['cp.vm.availability'],
    concepts: ['availability-set', 'virtual-machine'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'An existing VM was created without an availability set. The application owner now wants it in one. What must you do?',
    options: [
      { id: 'a', text: 'Delete the VM (keeping its disks) and recreate it in the availability set', correct: true, why: 'Availability set membership is set at creation; changing it requires recreating the VM from its existing disks.' },
      { id: 'b', text: 'Stop the VM, then set the availability set in the VM’s Configuration blade', why: 'There is no such setting on an existing VM — membership cannot be changed in place.' },
      { id: 'c', text: 'Resize the VM to a size that supports availability sets', why: 'Size is unrelated to availability set membership.' },
      { id: 'd', text: 'Move the VM to the resource group containing the availability set', why: 'Moving resource groups does not change availability set membership.' },
    ],
    explanation: {
      correct: 'A VM’s availability set is assigned when the VM is created. To change it, delete the VM while retaining the OS and data disks, then create a new VM from those disks inside the target availability set. The same is true for availability zone placement.',
      conceptTested: 'Creation-time-only properties of a VM.',
      realWorld: 'This is a planned maintenance window: it means downtime, so availability decisions belong in the design, not in operations.',
      trap: 'Deleting the VM deletes attached disks too unless the delete-with-VM behaviour is disabled — check before you delete.',
    },
    sources: ['availability-sets', 'vm-availability'],
  },

  // ---------------------------------------------------------------- VM lifecycle and sizing
  {
    id: 'cmp-vm-deallocate',
    domain: 'compute',
    skills: ['cp.vm.create', 'cp.vm.sizes'],
    concepts: ['virtual-machine'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'Your manager asks you to stop paying for a test VM overnight while keeping its configuration and data. Which action achieves this?',
    options: [
      { id: 'a', text: 'Stop (deallocate) the VM from the Azure portal or with az vm deallocate', correct: true, why: 'Deallocation releases the compute resources, so compute charges stop while disks remain.' },
      { id: 'b', text: 'Shut the VM down from inside the guest operating system', why: 'A guest shutdown leaves the VM in the Stopped (not deallocated) state and compute charges continue.' },
      { id: 'c', text: 'Resize the VM to the smallest available size each evening', why: 'A smaller size still bills for compute and adds a restart each time.' },
      { id: 'd', text: 'Delete the VM and redeploy it each morning from a template', why: 'It would stop charges, but it does not keep the running configuration and is far more work than deallocating.' },
    ],
    explanation: {
      correct: 'Only deallocating releases the underlying compute. Storage for the managed disks, plus any static public IP and reserved resources, continues to be billed.',
      conceptTested: 'VM power states and what each one costs.',
      realWorld: 'Auto-shutdown schedules and start/stop automation are the standard cost control for dev and test VMs.',
      trap: 'Stopped (not deallocated) still bills for compute — the exam tests this wording specifically.',
    },
    sources: ['vm-availability'],
  },
  {
    id: 'cmp-vm-resize',
    domain: 'compute',
    skills: ['cp.vm.sizes'],
    concepts: ['virtual-machine'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You try to resize a running VM, but the size you need is not offered in the list. What is the most likely reason?',
    options: [
      { id: 'a', text: 'The target size is not available on the hardware cluster currently hosting the VM', correct: true, why: 'The resize list for a running VM only shows sizes supported by its current cluster; deallocating frees the VM to be placed elsewhere.' },
      { id: 'b', text: 'Resizing is only supported for VMs in an availability set', why: 'Availability set membership does not enable resizing — though all VMs in a set must be stopped for sizes outside the current cluster.' },
      { id: 'c', text: 'The VM uses managed disks, which fix the size family', why: 'Managed disks do not restrict VM size families.' },
      { id: 'd', text: 'Resizing requires the VM to be generalized first', why: 'Generalizing is for image capture and would make the VM unusable.' },
    ],
    explanation: {
      correct: 'Azure can resize a running VM only within the sizes the current hardware cluster supports. Deallocate the VM and the resize list widens to everything available in the region; for VMs in an availability set, all VMs in the set may need to be deallocated.',
      conceptTested: 'Why a resize option is missing and how to widen the choice.',
      realWorld: 'Plan a maintenance window for size changes that cross size families — they always involve a restart.',
      trap: 'Regional capacity and quota also limit sizes; check both before assuming a cluster restriction.',
    },
    sources: ['vm-availability'],
  },
  {
    id: 'cmp-run-command',
    domain: 'compute',
    skills: ['cp.vm.create'],
    concepts: ['virtual-machine'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'A production Linux VM has no public IP, no Bastion host deployed, and its NSG denies all inbound traffic. You need to restart a service inside the guest immediately. What should you use?',
    options: [
      { id: 'a', text: 'Run Command', correct: true, why: 'Run Command executes a script through the Azure agent over the control plane, needing no inbound network path.' },
      { id: 'b', text: 'Temporarily add an NSG rule allowing SSH from your public IP', why: 'It works, but it opens inbound access to production when a control-plane option exists.' },
      { id: 'c', text: 'Deploy Azure Bastion into the virtual network', why: 'Bastion is the right long-term answer but takes time to deploy and requires a dedicated subnet.' },
      { id: 'd', text: 'Reset the VM’s credentials with the VMAccess extension', why: 'That changes credentials; it does not restart a service and still needs a connection path.' },
    ],
    explanation: {
      correct: 'Run Command sends a script to the guest through the Azure VM agent, so it works with no inbound connectivity at all. It requires the appropriate RBAC permission on the VM rather than a network path.',
      conceptTested: 'Choosing the operational tool that fits the available access path.',
      realWorld: 'Run Command is also how you recover from a misconfigured guest firewall that locked you out of RDP or SSH.',
      trap: 'Opening an NSG "just for a minute" is the tempting distractor; the exam prefers the option that does not weaken security.',
    },
    sources: ['bastion-config', 'nsg-overview'],
  },
  {
    id: 'cmp-vm-move-region',
    domain: 'compute',
    skills: ['cp.vm.move'],
    concepts: ['virtual-machine'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'A VM in East US must run in West Europe instead. Which approach achieves this?',
    options: [
      { id: 'a', text: 'Use Azure Resource Mover, or redeploy the VM in West Europe from a template, image or restored disks', correct: true, why: 'Region changes require replication or redeployment — there is no in-place region move.' },
      { id: 'b', text: 'Move the VM to a resource group located in West Europe', why: 'A resource group’s location only stores metadata; the VM keeps running in East US.' },
      { id: 'c', text: 'Move the VM to a subscription whose default region is West Europe', why: 'Subscriptions have no region, and a subscription move never relocates a resource.' },
      { id: 'd', text: 'Change the location property of the VM with az vm update', why: 'Location is immutable for a deployed resource.' },
    ],
    explanation: {
      correct: 'Moving between resource groups or subscriptions is a metadata operation: the VM keeps running in the same region. Changing region means new infrastructure, which Azure Resource Mover orchestrates for supported resources.',
      conceptTested: 'What a resource move does and does not change.',
      realWorld: 'Region migrations are projects: IP addressing, DNS, dependencies and data all move with the workload.',
      trap: 'A resource group in another region is the classic distractor — the group’s location does not relocate its contents.',
    },
    sources: ['move-resources'],
  },

  // ---------------------------------------------------------------- disks and encryption
  {
    id: 'cmp-disk-os',
    domain: 'compute',
    skills: ['cp.vm.disks'],
    concepts: ['managed-disk', 'virtual-machine'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'single',
    stem: 'Which statement about the temporary disk on an Azure VM is correct?',
    options: [
      { id: 'a', text: 'Its contents are lost when the VM is deallocated or moves to another host', correct: true, why: 'The temporary disk is local to the host and is not a managed disk, so its data is not preserved.' },
      { id: 'b', text: 'It is a managed disk that is backed up with the VM', why: 'The temporary disk is not a managed disk and is excluded from backup.' },
      { id: 'c', text: 'It is where the operating system is installed', why: 'The OS lives on the OS managed disk.' },
      { id: 'd', text: 'It can be resized independently in the Disks blade', why: 'Its size is determined by the VM size, not configured separately.' },
    ],
    explanation: {
      correct: 'The temporary disk provides short-term scratch space (typically the page or swap file) on storage local to the host. Any maintenance event, deallocation or host move discards its contents, so nothing you need to keep belongs on it. Some VM sizes have no temporary disk at all.',
      conceptTested: 'The three disk roles on a VM: OS disk, data disks, temporary disk.',
      realWorld: 'Applications configured to write logs or databases to D: (Windows) or /mnt (Linux) lose that data at the worst possible moment.',
    },
    sources: ['disk-types'],
  },
  {
    id: 'cmp-disk-choice',
    domain: 'compute',
    skills: ['cp.vm.disks'],
    concepts: ['managed-disk'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A production database VM needs consistently low disk latency and a disk-level SLA. Which managed disk type should you attach for its data disks?',
    options: [
      { id: 'a', text: 'Premium SSD', correct: true, why: 'Premium SSD is the production-grade tier for latency-sensitive workloads and supports a single-instance VM SLA.' },
      { id: 'b', text: 'Standard HDD', why: 'Standard HDD targets backup and infrequently accessed data, not a production database.' },
      { id: 'c', text: 'Standard SSD', why: 'Standard SSD improves consistency over HDD but targets lightly used workloads, not low-latency databases.' },
      { id: 'd', text: 'The temporary disk that comes with the VM size', why: 'The temporary disk loses its data on deallocation or host maintenance.' },
    ],
    explanation: {
      correct: 'Premium SSD (or Premium SSD v2 / Ultra Disk for higher and independently configurable performance) is the choice for latency-sensitive production workloads. Only Premium disks on all disks qualify a single-instance VM for the highest single-VM SLA.',
      conceptTested: 'Matching disk type to workload requirements.',
      realWorld: 'Disk type and size together determine IOPS and throughput, so under-sizing a disk starves a database even on Premium.',
      trap: 'Watch for questions that also require independently tunable IOPS — that points to Premium SSD v2 or Ultra Disk.',
    },
    sources: ['disk-types'],
  },
  {
    id: 'cmp-encryption-host',
    domain: 'compute',
    skills: ['cp.vm.encryption'],
    concepts: ['encryption-at-host', 'managed-disk'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'single',
    stem: 'You must ensure that the temporary disk and disk caches of a VM are encrypted, with the encryption performed on the host rather than inside the guest. What should you configure?',
    options: [
      { id: 'a', text: 'Enable encryption at host on the VM, after registering the feature for the subscription', correct: true, why: 'Encryption at host encrypts OS and data disks, caches and the temporary disk on the host itself.' },
      { id: 'b', text: 'Enable Azure Disk Encryption with BitLocker or dm-crypt', why: 'Azure Disk Encryption runs inside the guest operating system, which is exactly what the requirement excludes.' },
      { id: 'c', text: 'Rely on server-side encryption with platform-managed keys', why: 'Server-side encryption protects data at rest in storage but does not cover the temporary disk or host caches.' },
      { id: 'd', text: 'Use a customer-managed key on the disk encryption set only', why: 'A customer-managed key changes who controls the key; it does not extend coverage to caches and the temporary disk.' },
    ],
    explanation: {
      correct: 'Encryption at host encrypts data on the VM host before it is written to storage, covering the temporary disk and the OS and data disk caches. It is an opt-in feature that must be registered for the subscription and enabled per VM, and the VM must be deallocated to turn it on.',
      conceptTested: 'The three encryption layers for VM storage and what each one covers.',
      realWorld: 'Compliance requirements that mention "encryption of ephemeral storage" are answered by encryption at host, not by Azure Disk Encryption.',
      trap: 'Both options contain the word encryption; the discriminator is where the encryption happens — host versus guest.',
    },
    sources: ['disk-encryption', 'storage-encryption'],
  },

  // ---------------------------------------------------------------- scale sets and autoscale
  {
    id: 'cmp-vmss-mode',
    domain: 'compute',
    skills: ['cp.vm.vmss'],
    concepts: ['vmss'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You created a scale set with the Uniform orchestration mode and now need the Flexible mode instead. What must you do?',
    options: [
      { id: 'a', text: 'Create a new scale set in Flexible mode and migrate the workload', correct: true, why: 'Orchestration mode is fixed when the scale set is created.' },
      { id: 'b', text: 'Change the orchestration mode in the scale set’s Configuration blade', why: 'There is no setting to switch orchestration mode on an existing scale set.' },
      { id: 'c', text: 'Scale the set to zero instances, then change the mode and scale back up', why: 'Scaling to zero does not unlock the mode; it is immutable.' },
      { id: 'd', text: 'Upgrade the scale set’s model definition to the latest API version', why: 'The API version does not change orchestration mode.' },
    ],
    explanation: {
      correct: 'Orchestration mode is chosen at creation and cannot be changed afterwards. Flexible is the recommended default: instances are standard VM resources, can span zones and fault domains, and can mix sizes. Uniform manages instances as a set of identical VMs.',
      conceptTested: 'Creation-time-only decisions in scale sets.',
      realWorld: 'Choosing Uniform by habit means rebuilding later when you need per-instance control or a feature that only Flexible supports.',
    },
    sources: ['vmss-modes'],
  },
  {
    id: 'cmp-autoscale-rules',
    domain: 'compute',
    skills: ['cp.vm.vmss'],
    concepts: ['autoscale', 'vmss'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A scale set has a scale-out rule at average CPU above 70% and a scale-in rule at average CPU below 65%. Instances are repeatedly added and removed within minutes. What should you change?',
    options: [
      { id: 'a', text: 'Widen the gap between the thresholds and increase the cool-down period', correct: true, why: 'Thresholds that are too close, with short cool-downs, cause the scale set to oscillate.' },
      { id: 'b', text: 'Remove the scale-in rule so the scale set only ever grows', why: 'That prevents flapping by never reclaiming capacity, which wastes money and hides the real problem.' },
      { id: 'c', text: 'Switch the metric from CPU to available memory', why: 'A different metric with the same narrow thresholds would flap in exactly the same way.' },
      { id: 'd', text: 'Reduce the maximum instance count to two', why: 'A lower ceiling does not stop the repeated add/remove cycle below that ceiling.' },
    ],
    explanation: {
      correct: 'Flapping happens when the scale-in threshold is so close to the scale-out threshold that removing an instance immediately pushes the average back above the scale-out threshold. Leave clear headroom between the two, and give each action a cool-down long enough for the metric to settle.',
      conceptTested: 'Reading autoscale rules as a control loop, not a pair of independent settings.',
      realWorld: 'Flapping shows up as a sawtooth in the instance-count metric and causes repeated cold starts for users.',
      trap: 'The rules can both be "correct" individually and still be wrong together.',
    },
    sources: ['vmss-modes', 'metrics-overview'],
  },

  // ---------------------------------------------------------------- infrastructure as code
  {
    id: 'cmp-arm-sections',
    domain: 'compute',
    skills: ['cp.iac.interpret', 'cp.iac.modify-arm'],
    concepts: ['arm-template'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You must let the person deploying an ARM template choose the storage account redundancy from an approved list, without editing the template. Which section do you modify?',
    exhibit: {
      title: 'Template excerpt',
      kind: 'code',
      lang: 'json',
      code: `"resources": [
  {
    "type": "Microsoft.Storage/storageAccounts",
    "apiVersion": "2025-06-01",
    "name": "[variables('storageAccountName')]",
    "location": "[parameters('location')]",
    "sku": { "name": "Standard_LRS" },
    "kind": "StorageV2"
  }
]`,
    },
    options: [
      { id: 'a', text: 'Add a parameter with allowedValues, then reference it from the resource’s sku.name', correct: true, why: 'Parameters supply values at deployment time and allowedValues restricts them to an approved list.' },
      { id: 'b', text: 'Add a variable with the approved list and reference it from sku.name', why: 'Variables are computed inside the template and cannot be supplied by the person deploying it.' },
      { id: 'c', text: 'Add the values to the outputs section', why: 'Outputs return values after deployment; they do not accept input.' },
      { id: 'd', text: 'Change the apiVersion so the resource accepts a list of SKUs', why: 'The API version determines the resource schema, not who supplies a value.' },
    ],
    explanation: {
      correct: 'Parameters are the template’s input surface. Adding allowedValues turns the parameter into a guarded list, and defaultValue makes it optional. Variables, by contrast, are internal values the caller cannot set.',
      conceptTested: 'The roles of the parameters, variables, resources and outputs sections.',
      realWorld: 'Parameter files per environment (dev, test, prod) are the standard way to deploy one template into several environments.',
      trap: 'Parameters versus variables is the most common template comprehension question.',
    },
    sources: ['arm-overview', 'arm-deployment-modes'],
  },
  {
    id: 'cmp-bicep-decompile',
    domain: 'compute',
    skills: ['cp.iac.export', 'cp.iac.modify-bicep'],
    concepts: ['bicep', 'arm-template'],
    kind: 'configuration',
    difficulty: 1,
    format: 'single',
    stem: 'Your team has an existing ARM template in JSON and wants to continue working in Bicep. Which command converts the file?',
    options: [
      { id: 'a', text: 'az bicep decompile --file azuredeploy.json', correct: true, why: 'Decompile converts ARM JSON into Bicep on a best-effort basis.' },
      { id: 'b', text: 'az bicep build --file azuredeploy.json', why: 'Build goes the other way: Bicep to ARM JSON.' },
      { id: 'c', text: 'az deployment group export --template-file azuredeploy.json', why: 'That is not a conversion command.' },
      { id: 'd', text: 'az group export --name rg-app', why: 'That exports a resource group’s current state as a template; it does not convert an existing file.' },
    ],
    explanation: {
      correct: 'az bicep decompile produces a .bicep file from ARM JSON. The result is a starting point: review the warnings, replace hard-coded values with parameters, and note that characters such as periods in parameter names are converted to underscores.',
      conceptTested: 'The direction of build versus decompile.',
      realWorld: 'Decompiling an exported template is the usual first step when bringing a manually built environment under source control.',
    },
    sources: ['bicep-decompile'],
  },
  {
    id: 'cmp-deployment-mode',
    domain: 'compute',
    skills: ['cp.iac.deploy'],
    concepts: ['arm-template', 'bicep'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A resource group contains a virtual network, a storage account and three VMs. You deploy a template that defines only the virtual network, using complete mode. What is the result?',
    options: [
      { id: 'a', text: 'The virtual network is created or updated and the storage account and VMs are deleted', correct: true, why: 'Complete mode removes everything in the resource group that the template does not define.' },
      { id: 'b', text: 'The virtual network is created or updated and the other resources are left unchanged', why: 'That is the behaviour of incremental mode, the default.' },
      { id: 'c', text: 'The deployment fails because the template does not describe every existing resource', why: 'Complete mode does not fail; it deletes.' },
      { id: 'd', text: 'The other resources are moved to a new resource group', why: 'Deployments never move resources.' },
    ],
    explanation: {
      correct: 'In complete mode, the template is the definition of the resource group: resources not in the template are deleted. Incremental mode, the default, leaves them alone. Complete mode is not available at subscription scope or in the portal, and nested deployments always run incrementally.',
      conceptTested: 'The difference between the two deployment modes.',
      realWorld: 'Run what-if before any deployment that might delete something; Microsoft now recommends incremental mode and deployment stacks for managed deletion.',
      trap: 'The exam wording rarely says "delete" — it asks what happens to the other resources.',
    },
    sources: ['arm-deployment-modes'],
  },
  {
    id: 'cmp-deployment-incremental-props',
    domain: 'compute',
    skills: ['cp.iac.deploy'],
    concepts: ['arm-template', 'bicep'],
    kind: 'knowledge',
    difficulty: 3,
    format: 'yesno',
    stem: 'A storage account already exists with a tag and a custom minimum TLS version. You redeploy it with a template in incremental mode; the template defines the account but omits the tag. Evaluate each statement.',
    statements: [
      { id: 's1', text: 'Other resources in the resource group that are not in the template are left untouched.', answer: true, why: 'That is exactly what incremental mode means.' },
      { id: 's2', text: 'The omitted tag is preserved on the storage account because the property was not specified.', answer: false, why: 'Properties of a resource that the template does define are set to the template’s values or reset to defaults — the template describes the whole resource.' },
      { id: 's3', text: 'Running the same template a second time with no changes produces no further changes.', answer: true, why: 'Deployments are idempotent: the same template produces the same end state.' },
    ],
    explanation: {
      correct: 'Incremental mode protects other resources, not other properties. For a resource the template defines, any property left out is set to its default value, so the template must describe the complete desired state of that resource.',
      conceptTested: 'Idempotency and the scope of "incremental".',
      realWorld: 'Tags applied by hand disappear on the next pipeline run — one reason to apply tags through Azure Policy or in the template itself.',
      trap: 'Incremental sounds like "only changes what I mention"; at the property level, it does not.',
    },
    sources: ['arm-deployment-modes'],
  },

  // ---------------------------------------------------------------- service selection
  {
    id: 'cmp-responsibility-patching',
    domain: 'compute',
    skills: ['cp.vm.create', 'cp.app.create'],
    concepts: ['virtual-machine', 'app-service'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'single',
    stem: 'Who is responsible for applying operating system security updates to an application hosted on Azure App Service?',
    options: [
      { id: 'a', text: 'Microsoft, as part of the managed platform', correct: true, why: 'App Service is a PaaS offering; Microsoft maintains the underlying operating system.' },
      { id: 'b', text: 'The customer, using Azure Update Manager', why: 'That is the model for VMs, where the guest OS belongs to the customer.' },
      { id: 'c', text: 'The customer, by redeploying the application monthly', why: 'Redeploying an application does not patch the host operating system.' },
      { id: 'd', text: 'Neither — App Service does not run on an operating system', why: 'It does run on one; Microsoft simply manages it.' },
    ],
    explanation: {
      correct: 'The higher up the stack the service sits, the more Microsoft manages. On App Service, Microsoft handles the OS and the platform runtime; you keep responsibility for the application, its configuration, its data, and identity and access.',
      conceptTested: 'The shared responsibility model applied to Azure compute.',
      realWorld: 'Removing OS patching is often the strongest argument for moving a simple web application off VMs.',
    },
    sources: ['appservice-plans'],
  },
  {
    id: 'cmp-choose-aci',
    domain: 'compute',
    skills: ['cp.containers.aci'],
    concepts: ['container-instances'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A nightly data import runs as a single container image, takes about five minutes and needs no ingress, scaling or service discovery. Which service fits best?',
    options: [
      { id: 'a', text: 'Azure Container Instances', correct: true, why: 'ACI runs a single container on demand with fast start-up and per-second billing, with no orchestrator to manage.' },
      { id: 'b', text: 'Azure Container Apps', why: 'Container Apps adds ingress, revisions and scale rules this workload does not need.' },
      { id: 'c', text: 'A dedicated virtual machine with Docker installed', why: 'That means paying for an idle VM and patching it for a five-minute job.' },
      { id: 'd', text: 'An App Service plan running a container', why: 'App Service targets long-running web applications and bills for the plan continuously.' },
    ],
    explanation: {
      correct: 'Azure Container Instances is the simplest way to run a container: no orchestrator, no cluster, start it, let it finish, pay for the seconds it ran.',
      conceptTested: 'Matching a container workload’s shape to the right hosting service.',
      realWorld: 'ACI is often triggered from a scheduler or a logic app for exactly this kind of batch task.',
      trap: 'Both container services are plausible; the discriminator is that the job is short-lived and needs no scaling.',
    },
    sources: ['aci-overview'],
  },
  {
    id: 'cmp-choose-aca',
    domain: 'compute',
    skills: ['cp.containers.aca', 'cp.containers.scaling'],
    concepts: ['container-apps'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A set of containerized microservices must scale on queue length, scale to zero when idle, and support safe rollout of new versions. Which service should you choose?',
    options: [
      { id: 'a', text: 'Azure Container Apps', correct: true, why: 'Container Apps provides revisions, ingress and event-driven scale rules including scale to zero.' },
      { id: 'b', text: 'Azure Container Instances', why: 'ACI has no scaling rules, revisions or built-in service discovery.' },
      { id: 'c', text: 'Virtual Machine Scale Sets', why: 'Scale sets scale VMs, leaving you with the OS, and they do not scale to zero.' },
      { id: 'd', text: 'App Service on a Basic plan', why: 'Basic plans do not autoscale, and App Service does not scale to zero on a dedicated plan.' },
    ],
    explanation: {
      correct: 'Azure Container Apps is the serverless container platform for microservices: it supports scale rules driven by HTTP traffic, events or queue length, can scale to zero, and manages revisions for controlled rollouts.',
      conceptTested: 'Recognising the signals — scale to zero, event-driven scaling, revisions — that name Container Apps.',
      realWorld: 'Scale to zero makes Container Apps attractive for bursty internal services that are idle most of the day.',
      trap: 'If the requirement is node-level control or Kubernetes APIs, the answer is AKS instead.',
    },
    sources: ['aca-containers', 'aca-scale'],
  },

  // ---------------------------------------------------------------- extra coverage
  {
    id: 'cmp-vm-create-order',
    domain: 'compute',
    skills: ['cp.vm.create'],
    concepts: ['virtual-machine', 'managed-disk'],
    kind: 'multi-step',
    difficulty: 2,
    format: 'order',
    stem: 'Put the steps for deploying a production Linux VM into a new environment in the correct order.',
    items: [
      { id: 'i1', text: 'Create the resource group in the target region' },
      { id: 'i2', text: 'Create the virtual network and subnet' },
      { id: 'i3', text: 'Create the network security group and associate it with the subnet' },
      { id: 'i4', text: 'Create the VM, attaching the NIC to the subnet' },
      { id: 'i5', text: 'Attach and initialise the data disks' },
      { id: 'i6', text: 'Install the Azure Monitor Agent and associate a data collection rule' },
    ],
    why: 'Networking must exist before the VM’s NIC can be placed in a subnet, and the VM must exist before disks and agents can be attached to it. Creating the NSG before the VM means the subnet is protected from the first boot.',
    explanation: {
      correct: 'Resource group → network → security → VM → storage → monitoring. Each step depends on the one before it, and applying the NSG before the VM exists avoids a window where the subnet is unprotected.',
      conceptTested: 'Dependency order in a VM deployment.',
      realWorld: 'Templates encode this order automatically; doing it by hand is where the order matters.',
    },
    sources: ['nsg-overview', 'ama-overview'],
  },
  {
    id: 'cmp-vm-sizes-family',
    domain: 'compute',
    skills: ['cp.vm.sizes'],
    concepts: ['virtual-machine'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'Which statement best describes how Azure VM size families are used when sizing a workload?',
    options: [
      { id: 'a', text: 'Families group sizes by workload profile — general purpose, compute optimized, memory optimized, storage optimized, GPU — and the size within a family sets the vCPU, memory and disk limits', correct: true, why: 'Family chooses the profile; the size within it chooses the scale.' },
      { id: 'b', text: 'Families indicate the region a VM can run in', why: 'Availability varies by region, but families describe hardware profiles, not locations.' },
      { id: 'c', text: 'Families determine which managed disk types can be attached', why: 'Disk type is chosen independently, though some sizes support premium storage and others do not.' },
      { id: 'd', text: 'Families determine the VM’s availability SLA', why: 'The SLA depends on instance placement and disk type, not on family.' },
    ],
    explanation: {
      correct: 'Pick the family from the workload’s bottleneck — CPU-bound, memory-bound, storage-bound or GPU — then pick the size within that family for the amount of resource needed. Each size also caps attached disks, NICs and network bandwidth.',
      conceptTested: 'How to approach VM sizing systematically.',
      realWorld: 'Oversizing to be safe is the most common source of avoidable VM spend; Azure Advisor flags underused VMs for resizing.',
    },
    sources: ['disk-types', 'advisor'],
  },
  {
    id: 'cmp-vmss-scale-in-policy',
    domain: 'compute',
    skills: ['cp.vm.vmss'],
    concepts: ['vmss', 'autoscale', 'availability-zone'],
    kind: 'configuration',
    difficulty: 3,
    format: 'multi',
    stem: 'You are configuring a zone-spanning scale set for a web tier. Which two settings directly affect how the scale set behaves during a scale-in event? Select two.',
    options: [
      { id: 'a', text: 'The autoscale scale-in rule’s threshold and cool-down', correct: true, why: 'It decides when instances are removed and how long Azure waits before acting again.' },
      { id: 'b', text: 'The scale-in policy (default, NewestVM or OldestVM)', correct: true, why: 'It decides which instance is removed, and the default policy keeps balance across zones and fault domains.' },
      { id: 'c', text: 'The orchestration mode chosen at creation', why: 'It shapes what the scale set can do overall but is not a scale-in behaviour setting.' },
      { id: 'd', text: 'The VM size chosen in the scale set model', why: 'Size affects capacity per instance, not which instance is removed or when.' },
    ],
    explanation: {
      correct: 'Two independent decisions govern scale-in: the autoscale rule decides when and how many, and the scale-in policy decides which instance goes. The default policy balances across zones first, then fault domains, before removing the newest instance.',
      conceptTested: 'Separating the trigger from the selection in scale set behaviour.',
      realWorld: 'A scale-in policy of OldestVM is useful when instances accumulate state or drift over time and you want them recycled.',
    },
    sources: ['vmss-modes'],
  },
  {
    id: 'cmp-iac-what-if',
    domain: 'compute',
    skills: ['cp.iac.deploy'],
    concepts: ['arm-template', 'bicep'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'You inherited a Bicep file and must deploy it to a production resource group you did not build. What should you do first?',
    options: [
      { id: 'a', text: 'Run a what-if deployment against the resource group and review the reported changes', correct: true, why: 'What-if shows exactly which resources would be created, modified or deleted, before anything changes.' },
      { id: 'b', text: 'Deploy in complete mode so the resource group matches the file exactly', why: 'That would delete everything the file does not define — the opposite of a safe first step.' },
      { id: 'c', text: 'Export the resource group template and compare the JSON by hand', why: 'Useful context, but slower and less accurate than what-if for predicting the deployment result.' },
      { id: 'd', text: 'Apply a read-only lock to the resource group and then deploy', why: 'A read-only lock blocks the deployment itself.' },
    ],
    explanation: {
      correct: 'What-if performs a dry run through Resource Manager and reports Create, Modify, Delete, Deploy, Ignore and NoChange per resource. It is the cheapest safeguard available for an unfamiliar environment.',
      conceptTested: 'Safe deployment practice with templates.',
      realWorld: 'What-if is commonly a required pipeline stage, with the output reviewed before an approval gate.',
    },
    sources: ['arm-deployment-modes', 'locks'],
  },
  {
    id: 'cmp-availability-match',
    domain: 'compute',
    skills: ['cp.vm.availability'],
    concepts: ['availability-set', 'availability-zone', 'vmss'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'match',
    stem: 'Match each availability requirement with the feature that addresses it.',
    prompts: [
      { id: 'p1', text: 'Protect against the loss of an entire datacentre within a region', answer: 'c2', why: 'Availability zones are physically separate datacentres with independent power, cooling and networking.' },
      { id: 'p2', text: 'Protect VMs in one datacentre from rack-level hardware failure and staged platform updates', answer: 'c1', why: 'An availability set spreads instances across fault domains and update domains.' },
      { id: 'p3', text: 'Add and remove identical instances automatically as load changes', answer: 'c3', why: 'A scale set with autoscale rules adjusts instance count in response to metrics.' },
      { id: 'p4', text: 'Recover a workload in a different Azure region after a regional outage', answer: 'c4', why: 'Cross-region recovery is a disaster recovery design, handled by replication such as Azure Site Recovery.' },
    ],
    choices: [
      { id: 'c1', text: 'Availability set' },
      { id: 'c2', text: 'Availability zones' },
      { id: 'c3', text: 'Virtual Machine Scale Sets with autoscale' },
      { id: 'c4', text: 'Region-pair disaster recovery with replication' },
    ],
    explanation: {
      correct: 'Each mechanism addresses a different blast radius: fault and update domains inside a datacentre, zones across datacentres in a region, scale sets for capacity, and cross-region replication for regional loss.',
      conceptTested: 'Mapping a failure scenario to the right availability construct.',
      realWorld: 'Designs frequently combine them: a zone-spanning scale set for availability plus replication for disaster recovery.',
      trap: 'Availability and disaster recovery are not the same requirement — read the blast radius in the question.',
    },
    sources: ['availability-sets', 'availability-zones', 'vmss-modes', 'regions-paired'],
  },
];
