import type { Question } from '../schema';

export const GOVERNANCE_QUESTIONS: Question[] = [
  {
    id: 'gov-mg-scope-policy',
    domain: 'identity-governance',
    skills: ['ig.gov.mg', 'ig.gov.policy'],
    concepts: ['management-group', 'azure-policy'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'Your company has 18 subscriptions under a management group named Production. Security requires that resources in all current and future production subscriptions can be deployed only to the West Europe and North Europe regions. You need to meet the requirement with the least administrative effort. What should you do?',
    options: [
      { id: 'a', text: 'Assign the built-in Allowed locations policy to the Production management group.', correct: true, why: 'Policy assignments are inherited by every child scope, including subscriptions moved under Production later.' },
      { id: 'b', text: 'Assign the Allowed locations policy to each of the 18 subscriptions.', why: 'It enforces the rule today, but needs 18 assignments and does nothing for subscriptions added in the future.' },
      { id: 'c', text: 'Add a read-only lock to the Production management group.', why: 'Locks cannot be applied to management groups, and locks do not restrict regions.' },
      { id: 'd', text: 'Create a budget scoped to the Production management group with a filter for the two regions.', why: 'Budgets only send cost notifications. They never block deployments.' },
    ],
    explanation: {
      correct: 'Azure Policy assignments made at a management group apply to all subscriptions, resource groups and resources beneath it. The *Allowed locations* built-in policy uses the deny effect, so non-compliant deployments are blocked across the whole branch with one assignment.',
      conceptTested: 'Choosing the right scope for a policy assignment in the management group hierarchy.',
      realWorld: 'Platform teams assign region, SKU and tagging guardrails at management groups so new subscriptions are compliant the moment they are placed in the branch.',
      trap: 'Per-subscription assignments technically work — but “least administrative effort” and “future subscriptions” both point to the management group.',
    },
    sources: ['management-groups', 'policy-overview'],
  },
  {
    id: 'gov-tags-inheritance',
    domain: 'identity-governance',
    skills: ['ig.gov.tags', 'ig.gov.policy'],
    concepts: ['tags', 'azure-policy', 'management-group'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'A resource group named rg-finance has the tag CostCenter=4410. It contains a storage account and a virtual machine that have no tags. For each statement, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'The storage account automatically has the CostCenter=4410 tag.', answer: false, why: 'Resources do not inherit tags from their resource group or subscription.' },
      { id: 's2', text: 'An Azure Policy that inherits a tag from the resource group can add CostCenter=4410 to the resources in rg-finance.', answer: true, why: 'Tag inheritance is implemented with Azure Policy using the modify effect. New and updated resources are tagged, and a remediation task can fix existing resources.' },
      { id: 's3', text: 'You can apply the CostCenter tag to the management group that contains the subscription.', answer: false, why: 'Tags can be applied to subscriptions, resource groups and resources, but not to management groups.' },
    ],
    explanation: {
      correct: 'Tags are metadata on a single object. Unlike Azure RBAC and Azure Policy, they do not flow down the hierarchy — you use Azure Policy to require or inherit them.',
      conceptTested: 'Which governance features inherit through the hierarchy and where tags can be applied.',
      realWorld: 'Cost reports grouped by tag show “untagged” spend when teams assume resource group tags flow down. Tag policies close that gap.',
      trap: 'RBAC and policy inherit, so it feels natural that tags do too. They do not.',
    },
    sources: ['tags', 'policy-overview'],
  },
  {
    id: 'gov-mg-depth',
    domain: 'identity-governance',
    skills: ['ig.gov.mg'],
    concepts: ['management-group'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about management groups, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A management group hierarchy can be up to six levels deep, not counting the root level or the subscription level.', answer: true, why: 'Six levels of depth are supported below the root.' },
      { id: 's2', text: 'A subscription can belong to two management groups at the same time.', answer: false, why: 'Each subscription and management group has exactly one parent.' },
      { id: 's3', text: 'The Tenant root group can be deleted after all subscriptions are moved out of it.', answer: false, why: 'The root management group can’t be moved or deleted.' },
    ],
    explanation: {
      correct: 'The hierarchy is a single tree per directory: one root that can’t be removed, one parent per child, and up to six levels of depth.',
      conceptTested: 'Management group structure and limits.',
      realWorld: 'Knowing that each subscription has one parent forces deliberate design — a subscription can’t sit in both “Finance” and “Production” branches.',
    },
    sources: ['management-groups'],
  },
  {
    id: 'gov-mg-move-permissions',
    domain: 'identity-governance',
    skills: ['ig.gov.mg', 'ig.gov.subscriptions'],
    concepts: ['management-group', 'subscription'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'You need to move subscription Sub7 from management group MG-Old to management group MG-New. Which set of permissions is required?',
    options: [
      { id: 'a', text: 'Management group write on MG-Old and MG-New, plus Owner (role assignment write) on Sub7', correct: true, why: 'Moving requires write access on both parents and Owner-level rights on the subscription.' },
      { id: 'b', text: 'Reader on MG-New only', why: 'Reader can’t modify the hierarchy.' },
      { id: 'c', text: 'Contributor on Sub7 only', why: 'Contributor on the subscription lacks role assignment write and has no rights on the management groups.' },
      { id: 'd', text: 'Global Administrator in Microsoft Entra ID only', why: 'Entra roles don’t grant Azure management group permissions without elevation or Azure roles.' },
    ],
    explanation: {
      correct: 'To move a subscription you need management group write permission on the current and target parent management groups, and Owner-level access (role assignment write) on the subscription itself.',
      conceptTested: 'Permissions required to reorganize the hierarchy.',
      realWorld: 'Platform teams typically hold these rights centrally so individual subscription owners can’t move themselves out of guardrails.',
    },
    sources: ['management-groups'],
  },
  {
    id: 'gov-subscription-tenant-move',
    domain: 'identity-governance',
    skills: ['ig.gov.subscriptions'],
    concepts: ['subscription', 'entra-tenant', 'role-assignment'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'After an acquisition, you associate subscription Sub-Acq with your company’s Microsoft Entra tenant. The next day, the acquired company’s engineers can no longer manage resources in Sub-Acq. What happened?',
    options: [
      { id: 'a', text: 'Azure role assignments from the previous tenant were removed when the subscription changed directory', correct: true, why: 'Role assignments don’t transfer when a subscription is associated with a different tenant.' },
      { id: 'b', text: 'The subscription was moved to a different region', why: 'Changing directory doesn’t change regions.' },
      { id: 'c', text: 'A resource lock was added automatically', why: 'Changing directory doesn’t create locks.' },
      { id: 'd', text: 'The subscription’s billing owner changed', why: 'Changing the directory doesn’t change billing ownership.' },
    ],
    explanation: {
      correct: 'A subscription trusts one tenant. When it’s associated with a different tenant, existing Azure RBAC assignments are lost and must be recreated for identities in the new tenant. Managed identities and Key Vault tenant IDs also need attention.',
      conceptTested: 'The relationship between subscriptions and Microsoft Entra tenants.',
      realWorld: 'Mergers are the most common reason subscriptions change directories, and access planning is critical beforehand.',
    },
    sources: ['subscription-tenant'],
  },
  {
    id: 'gov-move-facts',
    domain: 'identity-governance',
    skills: ['ig.gov.rg'],
    concepts: ['resource-move', 'resource-group'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'You move a virtual machine and its dependent resources from resource group RG1 (in subscription Sub1) to resource group RG2 in subscription Sub2 in the same tenant. For each statement, select Yes if it is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'The VM keeps running during the move.', answer: true, why: 'Moves don’t cause downtime; RG1 and RG2 are locked against changes during the move.' },
      { id: 's2', text: 'The VM is moved to Sub2’s default region.', answer: false, why: 'Moving between resource groups or subscriptions never changes the region.' },
      { id: 's3', text: 'Role assignments applied directly to the VM move with it.', answer: false, why: 'Role assignments on moved resources don’t move and must be recreated.' },
    ],
    explanation: {
      correct: 'A move changes the resource group and subscription (and therefore the resource ID) while resources keep running. Region and direct role assignments don’t come along.',
      conceptTested: 'What changes and what doesn’t when resources move.',
      realWorld: 'Reorganizations often break access because teams forget to recreate role assignments after moves.',
    },
    sources: ['move-resources'],
  },
  {
    id: 'gov-rg-delete-lock',
    domain: 'identity-governance',
    skills: ['ig.gov.rg', 'ig.gov.locks'],
    concepts: ['resource-group', 'resource-lock'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You run a command to delete resource group RG-Test, which contains 12 resources. One storage account in RG-Test has a CanNotDelete lock. What is the result?',
    options: [
      { id: 'a', text: 'The deletion fails and no resources are deleted', correct: true, why: 'A lock on any resource blocks the resource group deletion entirely.' },
      { id: 'b', text: '11 resources are deleted and the storage account remains', why: 'Resource group deletion doesn’t partially succeed because of a lock.' },
      { id: 'c', text: 'All resources are deleted because you are the Owner', why: 'Locks apply to everyone, including Owners.' },
      { id: 'd', text: 'The lock is removed automatically and the resource group is deleted', why: 'Locks must be removed explicitly.' },
    ],
    explanation: {
      correct: 'When a resource in a resource group has a delete lock, Resource Manager rejects the resource group deletion as a whole.',
      conceptTested: 'How locks interact with resource group deletion.',
      realWorld: 'Teams use this deliberately: a delete lock on one critical resource protects the entire resource group from accidental removal.',
    },
    sources: ['locks'],
  },
  {
    id: 'gov-policy-vs-rbac',
    domain: 'identity-governance',
    skills: ['ig.gov.policy', 'ig.access.interpret'],
    concepts: ['azure-policy', 'azure-rbac'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'A user with the Owner role on a subscription tries to create a VM of size Standard_M128s. The deployment fails with the error RequestDisallowedByPolicy. What should you do to allow the deployment if the business approves it?',
    options: [
      { id: 'a', text: 'Create a policy exemption for the resource group, or adjust the allowed SKUs parameter of the assignment', correct: true, why: 'The block comes from Azure Policy, so the fix is in the policy assignment or an exemption.' },
      { id: 'b', text: 'Assign the user the Virtual Machine Contributor role', why: 'The user already has Owner; permissions aren’t the problem.' },
      { id: 'c', text: 'Remove the CanNotDelete lock from the subscription', why: 'A delete lock doesn’t block creating resources.' },
      { id: 'd', text: 'Register the Microsoft.Compute resource provider', why: 'The error is a policy denial, not a registration error.' },
    ],
    explanation: {
      correct: 'RequestDisallowedByPolicy means Azure Policy denied the request after RBAC authorized it. Owners aren’t exempt from policy.',
      conceptTested: 'Distinguishing authorization failures from policy denials.',
      realWorld: 'Allowed VM SKU policies commonly block expensive sizes; exceptions should be deliberate and documented.',
      trap: 'Adding more roles never overrides a policy deny.',
    },
    sources: ['policy-overview', 'rbac-overview'],
  },
  {
    id: 'gov-policy-effects-match',
    domain: 'identity-governance',
    skills: ['ig.gov.policy'],
    concepts: ['policy-effect', 'azure-policy'],
    kind: 'configuration',
    difficulty: 2,
    format: 'match',
    stem: 'Match each requirement to the Azure Policy effect that meets it.',
    prompts: [
      { id: 'p1', text: 'Block the creation of storage accounts that allow public blob access', answer: 'deny', why: 'deny rejects non-compliant create and update requests.' },
      { id: 'p2', text: 'Automatically add an Environment tag with the resource group’s value when resources are created', answer: 'modify', why: 'modify changes properties such as tags during the request.' },
      { id: 'p3', text: 'Report VMs without a required extension, without changing anything', answer: 'aine', why: 'auditIfNotExists checks for a related resource and reports non-compliance.' },
      { id: 'p4', text: 'Create diagnostic settings for new Key Vaults automatically', answer: 'dine', why: 'deployIfNotExists deploys the missing related resource.' },
    ],
    choices: [
      { id: 'deny', text: 'deny' },
      { id: 'modify', text: 'modify' },
      { id: 'aine', text: 'auditIfNotExists' },
      { id: 'dine', text: 'deployIfNotExists' },
      { id: 'disabled', text: 'disabled' },
    ],
    explanation: {
      correct: 'Each effect has a distinct purpose: block (deny), change (modify), report a missing related resource (auditIfNotExists), or deploy it (deployIfNotExists).',
      conceptTested: 'Choosing policy effects.',
      realWorld: 'Mature environments combine all four: deny for hard rules, modify for tags, and deployIfNotExists for monitoring coverage.',
    },
    sources: ['policy-effects'],
  },
  {
    id: 'gov-policy-remediation',
    domain: 'identity-governance',
    skills: ['ig.gov.policy'],
    concepts: ['azure-policy', 'managed-identity'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'You assign a policy with the modify effect that adds a CostCenter tag. New resources are tagged correctly, but 400 existing resources remain untagged. What should you do?',
    options: [
      { id: 'a', text: 'Create a remediation task for the policy assignment', correct: true, why: 'Remediation tasks apply modify and deployIfNotExists changes to existing non-compliant resources.' },
      { id: 'b', text: 'Change the effect to deny', why: 'Deny blocks future requests and doesn’t change existing resources.' },
      { id: 'c', text: 'Wait for the 24-hour compliance scan to tag them', why: 'The scan evaluates compliance; it doesn’t remediate.' },
      { id: 'd', text: 'Assign the policy again at the resource group scope', why: 'Another assignment doesn’t remediate existing resources either.' },
    ],
    explanation: {
      correct: 'Policy evaluation marks existing resources non-compliant, but modify and deployIfNotExists act on them only through a remediation task, which uses the assignment’s managed identity.',
      conceptTested: 'Remediating existing resources.',
      realWorld: 'Rolling out tagging policies always includes a remediation step for the existing estate.',
    },
    sources: ['policy-overview'],
  },
  {
    id: 'gov-policy-child-override',
    domain: 'identity-governance',
    skills: ['ig.gov.policy'],
    concepts: ['azure-policy', 'policy-exemption'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'A deny policy assigned at the Corp management group blocks public IP addresses. One resource group, rg-vpn, in a subscription under Corp legitimately needs a public IP. What should you do?',
    options: [
      { id: 'a', text: 'Create a policy exemption for rg-vpn (or exclude rg-vpn from the assignment)', correct: true, why: 'Exemptions and exclusions are how child scopes are released from a parent assignment.' },
      { id: 'b', text: 'Assign a policy that allows public IPs at the rg-vpn scope', why: 'A more permissive child assignment can’t override a parent deny.' },
      { id: 'c', text: 'Assign the Owner role on rg-vpn to the network team', why: 'Owners are still subject to policy.' },
      { id: 'd', text: 'Move rg-vpn to another region', why: 'Region doesn’t affect this policy, and resource groups can’t be moved between regions.' },
    ],
    explanation: {
      correct: 'Azure Policy is explicit-deny. Use an exemption (tracked as Exempt, optionally with expiry, category Waiver or Mitigated) or an exclusion on the parent assignment.',
      conceptTested: 'Handling exceptions to inherited policy.',
      realWorld: 'Documented exemptions with expiry dates keep audits clean while allowing justified exceptions.',
    },
    sources: ['policy-overview', 'policy-exemptions'],
  },
  {
    id: 'gov-tag-contributor',
    domain: 'identity-governance',
    skills: ['ig.gov.tags', 'ig.access.builtin'],
    concepts: ['tags', 'role-definition'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'The finance team must be able to apply and update tags on all resources in a subscription, but must not be able to change any resource configuration. Which role should you assign?',
    options: [
      { id: 'a', text: 'Tag Contributor', correct: true, why: 'Tag Contributor manages tags without granting access to the resources themselves.' },
      { id: 'b', text: 'Contributor', why: 'Contributor can change resource configuration.' },
      { id: 'c', text: 'Reader', why: 'Reader can’t write tags.' },
      { id: 'd', text: 'Resource Policy Contributor', why: 'This manages policy assignments, not tags directly.' },
    ],
    explanation: {
      correct: 'Tag Contributor has write access to Microsoft.Resources/tags, letting users manage tags without write access to the resources.',
      conceptTested: 'Least-privilege tag management.',
      realWorld: 'FinOps teams often need to fix tags for chargeback without being able to modify production.',
    },
    sources: ['tags'],
  },
  {
    id: 'gov-tag-merge',
    domain: 'identity-governance',
    skills: ['ig.gov.tags'],
    concepts: ['tags'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'A storage account has the tags Owner=web-team and Environment=Production. You need to add CostCenter=4410 without removing the existing tags. Which command should you run?',
    options: [
      { id: 'a', text: '`az tag update --resource-id <id> --operation Merge --tags CostCenter=4410`', correct: true, why: 'Merge adds the new tag and leaves the others in place.' },
      { id: 'b', text: '`az tag update --resource-id <id> --operation Replace --tags CostCenter=4410`', why: 'Replace leaves only CostCenter, removing Owner and Environment.' },
      { id: 'c', text: '`az tag update --resource-id <id> --operation Delete --tags CostCenter=4410`', why: 'Delete removes the specified tags.' },
      { id: 'd', text: '`az lock create --name tag --lock-type CanNotDelete --resource-group <rg>`', why: 'Locks don’t set tags.' },
    ],
    explanation: {
      correct: '`az tag update` supports Merge, Replace and Delete operations. Merge is the safe way to add tags.',
      conceptTested: 'Tag operations.',
      realWorld: 'Accidentally replacing tag sets in scripts is a common cause of broken cost reports.',
    },
    sources: ['tags'],
  },
  {
    id: 'gov-lock-readonly-vm',
    domain: 'identity-governance',
    skills: ['ig.gov.locks'],
    concepts: ['resource-lock', 'virtual-machine'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'An operator with the Virtual Machine Contributor role can view VM1 but can’t start it after a maintenance window. The error mentions a scope lock. VM1 is in resource group RG-Prod. What is the most likely cause?',
    options: [
      { id: 'a', text: 'A ReadOnly lock exists on RG-Prod or its subscription', correct: true, why: 'ReadOnly blocks POST operations such as starting or restarting VMs.' },
      { id: 'b', text: 'A CanNotDelete lock exists on RG-Prod', why: 'CanNotDelete allows starting VMs; it only blocks deletion.' },
      { id: 'c', text: 'Virtual Machine Contributor can’t start VMs', why: 'The role includes start, restart and deallocate.' },
      { id: 'd', text: 'The VM’s NSG blocks port 3389', why: 'NSGs affect network traffic, not Resource Manager operations.' },
    ],
    explanation: {
      correct: 'ReadOnly locks block operations that are implemented as POST requests, including VM start/restart. Remove or change the lock.',
      conceptTested: 'Side effects of ReadOnly locks.',
      realWorld: 'ReadOnly locks placed “for safety” on production resource groups frequently break operational runbooks.',
    },
    sources: ['locks'],
  },
  {
    id: 'gov-lock-data-plane',
    domain: 'identity-governance',
    skills: ['ig.gov.locks'],
    concepts: ['resource-lock', 'control-plane-data-plane', 'blob-soft-delete'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'Storage account stdocs has a CanNotDelete lock. For each statement, select Yes if it is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'An Owner of the subscription can delete the storage account without removing the lock.', answer: false, why: 'Locks apply to all users, including Owners.' },
      { id: 's2', text: 'A user with Storage Blob Data Contributor can still delete blobs in stdocs.', answer: true, why: 'Locks apply to control plane operations, not data plane operations such as deleting blobs.' },
      { id: 's3', text: 'A user with Contributor can change the storage account’s redundancy setting.', answer: true, why: 'CanNotDelete allows modifications; only deletion is blocked.' },
    ],
    explanation: {
      correct: 'A CanNotDelete lock blocks deleting the resource for everyone, allows updates, and doesn’t affect data plane operations.',
      conceptTested: 'The scope and limits of resource locks.',
      realWorld: 'Protect the account with a lock and the data with soft delete, versioning and least-privilege data roles.',
      trap: 'A lock is not a data protection feature.',
    },
    sources: ['locks', 'control-data-plane'],
  },
  {
    id: 'gov-budget-stop',
    domain: 'identity-governance',
    skills: ['ig.gov.costs'],
    concepts: ['budget', 'action-group'],
    kind: 'architecture',
    difficulty: 3,
    format: 'single',
    stem: 'A development subscription must automatically deallocate all VMs when monthly actual costs reach 100% of a set amount. What should you configure?',
    options: [
      { id: 'a', text: 'A budget with an actual-cost alert at 100% that triggers an action group running an automation runbook to deallocate VMs', correct: true, why: 'Budgets alert; the action group and runbook perform the stop.' },
      { id: 'b', text: 'A budget with a 100% threshold — budgets stop resources when exceeded', why: 'Budgets never stop resources by themselves.' },
      { id: 'c', text: 'An Azure Advisor cost recommendation', why: 'Advisor suggests changes but doesn’t act on budget thresholds.' },
      { id: 'd', text: 'A ReadOnly lock on the subscription', why: 'Locks don’t stop running VMs and would block the deallocation itself.' },
    ],
    explanation: {
      correct: 'Budgets evaluate costs and send alerts. At subscription and resource group scopes, alerts can call action groups that start automation such as Azure Automation runbooks or Logic Apps.',
      conceptTested: 'What budgets can and can’t do.',
      realWorld: 'Sandbox subscriptions commonly use budget-driven automation to prevent runaway costs.',
    },
    sources: ['budgets'],
  },
  {
    id: 'gov-budget-forecast',
    domain: 'identity-governance',
    skills: ['ig.gov.costs'],
    concepts: ['budget'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'Project owners want an email early in the month if spending is on track to exceed the monthly budget, before the money is actually spent. Which alert should you add to the budget?',
    options: [
      { id: 'a', text: 'A forecasted cost alert at 100%', correct: true, why: 'Forecasted alerts fire when projected costs will reach the threshold.' },
      { id: 'b', text: 'An actual cost alert at 100%', why: 'This fires only after spending has reached the budget.' },
      { id: 'c', text: 'An activity log alert on resource creation', why: 'Activity log alerts don’t evaluate cost.' },
      { id: 'd', text: 'An alert processing rule', why: 'Processing rules modify fired alerts; they don’t create cost alerts.' },
    ],
    explanation: {
      correct: 'Budgets support actual and forecasted alert conditions. Forecasted conditions provide advance warning.',
      conceptTested: 'Budget alert types.',
      realWorld: 'Forecasted alerts give teams time to right-size or shut down resources before month end.',
    },
    sources: ['budgets'],
  },
  {
    id: 'gov-advisor-categories',
    domain: 'identity-governance',
    skills: ['ig.gov.costs'],
    concepts: ['azure-advisor'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'multi',
    stem: 'Which three are recommendation categories in Azure Advisor? Each correct answer presents part of the solution.',
    options: [
      { id: 'a', text: 'Cost', correct: true, why: 'Advisor identifies savings such as underutilized VMs.' },
      { id: 'b', text: 'Reliability', correct: true, why: 'Advisor recommends resiliency improvements.' },
      { id: 'c', text: 'Operational excellence', correct: true, why: 'Advisor recommends process and deployment improvements.' },
      { id: 'd', text: 'Licensing', why: 'Licensing isn’t an Advisor category.' },
      { id: 'e', text: 'Identity governance', why: 'Not an Advisor category.' },
    ],
    explanation: {
      correct: 'Advisor’s five categories are Reliability, Security, Performance, Cost and Operational excellence.',
      conceptTested: 'Azure Advisor recommendation categories.',
      realWorld: 'Reviewing Advisor cost recommendations monthly is one of the quickest ways to reduce spend.',
    },
    sources: ['advisor'],
  },
  {
    id: 'gov-guardrail-match',
    domain: 'identity-governance',
    skills: ['ig.gov.policy', 'ig.gov.locks', 'ig.gov.tags', 'ig.gov.costs'],
    concepts: ['azure-policy', 'resource-lock', 'tags', 'budget'],
    kind: 'architecture',
    difficulty: 2,
    format: 'match',
    stem: 'Match each requirement to the Azure feature that meets it.',
    prompts: [
      { id: 'p1', text: 'Nobody, including Owners, can accidentally delete the hub virtual network', answer: 'lock', why: 'A CanNotDelete lock blocks deletion for everyone.' },
      { id: 'p2', text: 'Resources can’t be created with SKUs outside an approved list', answer: 'policy', why: 'A deny policy restricts allowed SKUs.' },
      { id: 'p3', text: 'Costs in the invoice can be grouped by application', answer: 'tags', why: 'Tags appear in cost analysis and usage data.' },
      { id: 'p4', text: 'The app owner is emailed when spending is forecast to exceed $2,000', answer: 'budget', why: 'Budgets send forecasted and actual cost alerts.' },
    ],
    choices: [
      { id: 'lock', text: 'Resource lock' },
      { id: 'policy', text: 'Azure Policy' },
      { id: 'tags', text: 'Tags' },
      { id: 'budget', text: 'Budget' },
      { id: 'rbac', text: 'Azure RBAC' },
    ],
    explanation: {
      correct: 'Each governance feature answers a different question: protect (locks), enforce (policy), describe (tags), warn about spend (budgets).',
      conceptTested: 'Selecting governance tools for requirements.',
      realWorld: 'Governance designs fail when one tool is stretched to do another’s job.',
    },
    sources: ['locks', 'policy-overview', 'tags', 'budgets'],
  },
];
