import type { Question } from '../schema';

export const IDENTITY_QUESTIONS: Question[] = [
  {
    id: 'id-dynamic-group-rule',
    domain: 'identity-governance',
    skills: ['ig.entra.create', 'ig.entra.properties'],
    concepts: ['dynamic-group', 'entra-user'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You need a Microsoft Entra security group that automatically contains every user whose Department attribute is Sales. Users who move to another department must be removed automatically. What should you configure?',
    options: [
      { id: 'a', text: 'A security group with Membership type set to Dynamic User and the rule `user.department -eq "Sales"`', correct: true, why: 'Dynamic user membership evaluates the rule and adds or removes users as their department changes.' },
      { id: 'b', text: 'A security group with Membership type set to Assigned, plus a weekly access review', why: 'Assigned membership never changes by itself; an access review is manual and periodic.' },
      { id: 'c', text: 'A Microsoft 365 group with Membership type set to Dynamic Device', why: 'Device rules evaluate device properties, and Microsoft 365 groups can’t contain devices.' },
      { id: 'd', text: 'An administrative unit named Sales', why: 'Administrative units scope administration; they don’t create group membership.' },
    ],
    explanation: {
      correct: 'Dynamic membership groups calculate members from a rule on user or device properties. A rule on `user.department` keeps membership aligned with HR data automatically.',
      conceptTested: 'Creating groups with rule-based (dynamic) membership.',
      realWorld: 'Joiner-mover-leaver automation depends on dynamic groups driven by reliable HR attributes.',
      trap: 'Remember the licence: dynamic groups need Microsoft Entra ID P1 for each unique user member.',
    },
    sources: ['dynamic-groups'],
  },
  {
    id: 'id-group-types',
    domain: 'identity-governance',
    skills: ['ig.entra.create'],
    concepts: ['entra-group', 'dynamic-group'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about Microsoft Entra groups, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A Microsoft 365 group can have a dynamic membership rule that adds devices.', answer: false, why: 'Microsoft 365 groups contain users only, so device rules aren’t allowed.' },
      { id: 's2', text: 'You can manually add an extra member to a group whose membership type is Dynamic User.', answer: false, why: 'Dynamic groups don’t allow manual membership changes.' },
      { id: 's3', text: 'A security group can be assigned an Azure role such as Reader.', answer: true, why: 'Security groups are security principals and are the recommended way to receive Azure roles.' },
    ],
    explanation: {
      correct: 'Security groups can contain users, devices, service principals and other groups and receive roles. Microsoft 365 groups contain users. Dynamic groups are fully rule-driven.',
      conceptTested: 'Differences between group types and membership types.',
      realWorld: 'Choosing the wrong group type forces a rebuild later — for example when a team suddenly needs device-based policies.',
    },
    sources: ['dynamic-groups', 'rbac-overview'],
  },
  {
    id: 'id-dynamic-license-requirement',
    domain: 'identity-governance',
    skills: ['ig.entra.licenses', 'ig.entra.create'],
    concepts: ['dynamic-group', 'group-based-licensing'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'single',
    stem: 'Your tenant uses only Microsoft Entra ID Free licences. You plan to create dynamic membership groups for 400 users. What must you do first?',
    options: [
      { id: 'a', text: 'Obtain Microsoft Entra ID P1 (or higher) licences covering the users who will be members of dynamic groups', correct: true, why: 'Dynamic membership requires a P1 licence for each unique user member.' },
      { id: 'b', text: 'Enable password writeback', why: 'Writeback relates to hybrid password reset, not group membership.' },
      { id: 'c', text: 'Create an administrative unit', why: 'Administrative units aren’t required for dynamic groups.' },
      { id: 'd', text: 'Nothing — dynamic groups are included with Entra ID Free', why: 'Dynamic groups are a premium feature.' },
    ],
    explanation: {
      correct: 'Dynamic membership groups require Microsoft Entra ID P1 licensing for each unique user who is a member of one or more dynamic groups.',
      conceptTested: 'Licensing prerequisites for dynamic groups.',
      realWorld: 'Licensing gaps are a common reason automation projects stall after design.',
    },
    sources: ['dynamic-groups'],
  },
  {
    id: 'id-license-nested',
    domain: 'identity-governance',
    skills: ['ig.entra.licenses'],
    concepts: ['group-based-licensing', 'entra-group'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You assign a Microsoft 365 E5 licence to a security group named Engineering. Engineering contains 20 users and a nested group named Developers with 15 users. Some engineers report they have no licence. Which users received a licence?',
    options: [
      { id: 'a', text: 'Only the 20 direct members of Engineering', correct: true, why: 'Group-based licensing applies to direct members; nested group members aren’t licensed.' },
      { id: 'b', text: 'All 35 users', why: 'Nested groups aren’t supported for group-based licensing.' },
      { id: 'c', text: 'Only the 15 members of Developers', why: 'The licence is on Engineering, so its direct members receive it.' },
      { id: 'd', text: 'No users until each user has a usage location set manually', why: 'Users without a usage location inherit the tenant location for group-based licensing.' },
    ],
    explanation: {
      correct: 'Group-based licensing assigns licences only to first-level (direct) members of the licensed group. License Developers directly, or add its users to Engineering.',
      conceptTested: 'How group-based licensing handles nested groups.',
      realWorld: 'Organizations that mirror their org chart with nested groups often discover unlicensed users this way.',
      trap: 'Azure RBAC does honour nested groups — licensing doesn’t. Don’t mix the two rules.',
    },
    sources: ['group-licensing'],
  },
  {
    id: 'id-license-move-groups',
    domain: 'identity-governance',
    skills: ['ig.entra.licenses'],
    concepts: ['group-based-licensing'],
    kind: 'first-step',
    difficulty: 2,
    format: 'order',
    stem: 'A user moves from the Sales team to the Marketing team. Both teams’ groups assign licences. The user must not lose access to licensed services during the move. Put the steps in the correct order.',
    items: [
      { id: '1', text: 'Add the user to the Marketing group' },
      { id: '2', text: 'Confirm the licences from the Marketing group are applied to the user' },
      { id: '3', text: 'Remove the user from the Sales group' },
    ],
    why: 'Adding to the new group first means the user keeps a licence throughout; removing from the old group last avoids a gap in service.',
    explanation: {
      correct: 'Microsoft recommends adding the user to the new licensed group, confirming assignment, and only then removing them from the original group.',
      conceptTested: 'Managing licences through group membership changes.',
      realWorld: 'Removing first can briefly remove mailbox or app access, generating help desk tickets.',
    },
    sources: ['group-licensing'],
  },
  {
    id: 'id-guest-inviter',
    domain: 'identity-governance',
    skills: ['ig.entra.external'],
    concepts: ['b2b-collaboration', 'entra-roles'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'External collaboration settings in your tenant are set to "Only users assigned to specific admin roles can invite guest users". A project manager who holds no administrative role must be able to invite partner users. You must follow least privilege. What should you do?',
    options: [
      { id: 'a', text: 'Assign the Guest Inviter role to the project manager', correct: true, why: 'Guest Inviter lets a user invite guests even when invitations are restricted to admin roles — and grants nothing else.' },
      { id: 'b', text: 'Assign the User Administrator role to the project manager', why: 'User Administrator can invite guests but also manages users and groups — far more than required.' },
      { id: 'c', text: 'Change the setting to "Anyone in the organization can invite guest users including guests and non-admins"', why: 'This lets every user and guest invite, which breaks the restriction for everyone.' },
      { id: 'd', text: 'Assign the Owner role on the subscription', why: 'Azure roles don’t control directory invitations.' },
    ],
    explanation: {
      correct: 'The Guest Inviter Microsoft Entra role exists specifically to allow invitations without broader admin rights.',
      conceptTested: 'Guest invite settings and delegated invitation rights.',
      realWorld: 'Business owners of partner relationships often need to invite guests without becoming directory admins.',
      trap: 'User Administrator works technically but fails the least-privilege requirement.',
    },
    sources: ['external-collab'],
  },
  {
    id: 'id-guest-defaults',
    domain: 'identity-governance',
    skills: ['ig.entra.external'],
    concepts: ['b2b-collaboration', 'guest-user'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'You have a new Microsoft Entra tenant with default external collaboration settings. For each statement, select Yes if it is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'Existing guest users can invite other guest users.', answer: true, why: 'By default, anyone in the organization, including guests and non-admins, can invite guest users.' },
      { id: 's2', text: 'Guest users have the same directory access as member users.', answer: false, why: 'The default is limited access to properties and memberships of directory objects.' },
      { id: 's3', text: 'You can configure both an allow list and a deny list of domains at the same time.', answer: false, why: 'Collaboration restrictions use either an allow list or a deny list.' },
    ],
    explanation: {
      correct: 'Default settings are permissive for invitations but limited for guest directory visibility; domain restrictions are one list type or the other.',
      conceptTested: 'Default external collaboration settings.',
      realWorld: 'Many tenants never review these defaults, so guests can end up inviting other guests.',
    },
    sources: ['external-collab'],
  },
  {
    id: 'id-sspr-license',
    domain: 'identity-governance',
    skills: ['ig.entra.sspr'],
    concepts: ['sspr'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'Your organization has only cloud-only users and Microsoft Entra ID Free licences. Users must be able to reset forgotten passwords themselves. What is the minimum licensing change?',
    options: [
      { id: 'a', text: 'Assign Microsoft Entra ID P1 (or Microsoft 365 Business Standard/Premium) licences to the users', correct: true, why: 'Self-service password reset for cloud-only users requires one of these licences.' },
      { id: 'b', text: 'No change — Entra ID Free includes self-service password reset for cloud users', why: 'Free covers self-service password change, not reset of forgotten passwords.' },
      { id: 'c', text: 'Assign Microsoft Entra ID P2 licences; P1 isn’t enough', why: 'P1 is sufficient; P2 is more than required.' },
      { id: 'd', text: 'Deploy Microsoft Entra Connect with password writeback', why: 'Writeback is only for synchronized users; the users are cloud-only.' },
    ],
    explanation: {
      correct: 'Cloud-only password reset is included in Microsoft 365 Business Standard, Business Premium, and Microsoft Entra ID P1/P2. Entra ID Free supports only password change.',
      conceptTested: 'SSPR licensing for cloud-only users.',
      realWorld: 'Budget approvals for SSPR projects depend on getting this licensing right up front.',
      trap: '“Change” and “reset” are different capabilities with different licensing.',
    },
    sources: ['sspr-licensing'],
  },
  {
    id: 'id-sspr-writeback',
    domain: 'identity-governance',
    skills: ['ig.entra.sspr'],
    concepts: ['sspr', 'entra-user'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'Users are synchronized from on-premises Active Directory with Microsoft Entra Connect. SSPR is enabled for all users. A user completes verification but is told to contact an administrator. Cloud-only users can reset successfully. What is the most likely cause?',
    options: [
      { id: 'a', text: 'Password writeback isn’t configured', correct: true, why: 'Synchronized users’ passwords are mastered on-premises, so resets need writeback.' },
      { id: 'b', text: 'The number of methods required is set to two', why: 'That affects verification, which the user already completed.' },
      { id: 'c', text: 'The user isn’t assigned the User Administrator role', why: 'Users don’t need an admin role to reset their own password.' },
      { id: 'd', text: 'Registration reconfirmation is set to 0 days', why: '0 means users are never asked to reconfirm; it doesn’t block resets.' },
    ],
    explanation: {
      correct: 'Without password writeback, SSPR can’t update passwords for users whose passwords are managed in on-premises AD, so they’re directed to contact an administrator.',
      conceptTested: 'SSPR for hybrid identities and password writeback.',
      realWorld: 'Writeback is a standard part of hybrid SSPR deployments, configured in Microsoft Entra Connect or cloud sync.',
    },
    sources: ['sspr-howitworks', 'sspr-licensing'],
  },
  {
    id: 'id-sspr-settings',
    domain: 'identity-governance',
    skills: ['ig.entra.sspr'],
    concepts: ['sspr'],
    kind: 'configuration',
    difficulty: 2,
    format: 'match',
    stem: 'Match each SSPR requirement to the setting you should configure.',
    prompts: [
      { id: 'p1', text: 'Only the 50 users in the pilot group can use SSPR', answer: 'c1', why: 'Setting SSPR enabled to Selected scopes it to the chosen group.' },
      { id: 'p2', text: 'Users must prove their identity with two different methods', answer: 'c2', why: 'Number of methods required to reset can be one or two.' },
      { id: 'p3', text: 'Users are prompted every six months to confirm their authentication information', answer: 'c3', why: 'Reconfirmation can be set between 0 and 730 days.' },
      { id: 'p4', text: 'Resets by synchronized users update on-premises Active Directory', answer: 'c4', why: 'Password writeback sends the new password to on-premises AD.' },
    ],
    choices: [
      { id: 'c1', text: 'Self service password reset enabled: Selected' },
      { id: 'c2', text: 'Number of methods required to reset' },
      { id: 'c3', text: 'Number of days before users are asked to reconfirm' },
      { id: 'c4', text: 'Password writeback' },
      { id: 'c5', text: 'Guest invite settings' },
    ],
    explanation: {
      correct: 'Each requirement maps to a specific SSPR setting on the Password reset pages.',
      conceptTested: 'Configuring SSPR scope, methods, registration and writeback.',
      realWorld: 'A staged SSPR rollout typically starts with a selected pilot group and strong method requirements.',
    },
    sources: ['sspr-howitworks'],
  },
  {
    id: 'id-rbac-contributor-assign',
    domain: 'identity-governance',
    skills: ['ig.access.builtin'],
    concepts: ['role-definition', 'azure-rbac'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A team lead must create and manage all resources in a resource group and must also be able to grant other engineers access to that resource group. Which single built-in role meets the requirement?',
    options: [
      { id: 'a', text: 'Owner', correct: true, why: 'Owner grants full management access and the ability to assign roles.' },
      { id: 'b', text: 'Contributor', why: 'Contributor manages resources but can’t assign roles.' },
      { id: 'c', text: 'User Access Administrator', why: 'It can assign roles but doesn’t grant permission to manage resources.' },
      { id: 'd', text: 'Reader', why: 'Reader can only view resources.' },
    ],
    explanation: {
      correct: 'Only Owner combines full resource management with role assignment. Alternatively, Contributor plus User Access Administrator would work — but the question asks for a single role.',
      conceptTested: 'Capabilities of the fundamental built-in roles.',
      realWorld: 'Owner is powerful; many organizations keep it for a small group and delegate with Contributor.',
      trap: 'Contributor looks like “can do everything”, but role assignment is explicitly excluded.',
    },
    sources: ['roles-compare'],
  },
  {
    id: 'id-rbac-least-privilege',
    domain: 'identity-governance',
    skills: ['ig.access.scopes', 'ig.access.builtin'],
    concepts: ['rbac-scope', 'role-assignment'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'Your subscription contains resource groups rg-web, rg-data and rg-network. A contractor must restart and resize VMs in rg-web only. You must follow the principle of least privilege. What should you do?',
    options: [
      { id: 'a', text: 'Assign Virtual Machine Contributor to the contractor at the rg-web scope', correct: true, why: 'A VM-specific role at the narrowest scope that contains the VMs.' },
      { id: 'b', text: 'Assign Contributor to the contractor at the subscription scope', why: 'Too broad in both role and scope.' },
      { id: 'c', text: 'Assign Virtual Machine Contributor to the contractor at the subscription scope', why: 'Right role, but it also covers VMs in rg-data and rg-network.' },
      { id: 'd', text: 'Assign Owner to the contractor at the rg-web scope', why: 'Owner also allows managing every resource type and granting access.' },
    ],
    explanation: {
      correct: 'Least privilege means the narrowest role (Virtual Machine Contributor) at the narrowest scope (rg-web) that satisfies the requirement.',
      conceptTested: 'Choosing role and scope together.',
      realWorld: 'Contractors are a common source of over-privileged accounts; tight scoping limits blast radius.',
    },
    sources: ['rbac-overview'],
  },
  {
    id: 'id-rbac-interpret-table',
    domain: 'identity-governance',
    skills: ['ig.access.interpret', 'ig.access.scopes'],
    concepts: ['azure-rbac', 'rbac-scope', 'role-assignment'],
    kind: 'multi-step',
    difficulty: 3,
    format: 'yesno',
    stem: 'User1 is a member of Group1. Review the role assignments in the exhibit. For each statement, select Yes if the statement is true. Otherwise, select No.',
    exhibit: {
      title: 'Role assignments',
      kind: 'table',
      columns: ['Principal', 'Role', 'Scope'],
      rows: [
        ['User1', 'Reader', 'Subscription Sub1'],
        ['Group1', 'Contributor', 'Resource group RG1'],
        ['User1', 'Virtual Machine Contributor', 'Virtual machine VM2 (in RG2)'],
      ],
    },
    statements: [
      { id: 's1', text: 'User1 can delete a storage account in RG1.', answer: true, why: 'Group1 has Contributor at RG1, and User1 is a member of Group1.' },
      { id: 's2', text: 'User1 can create a virtual network in RG2.', answer: false, why: 'At RG2, User1 only inherits Reader from Sub1; VM Contributor is scoped to VM2 and doesn’t cover creating VNets.' },
      { id: 's3', text: 'User1 can assign the Reader role to another user on RG1.', answer: false, why: 'Contributor can’t create role assignments.' },
    ],
    explanation: {
      correct: 'Effective access is the union of assignments at the target scope and its parents, including group assignments. None of User1’s roles allow role assignment.',
      conceptTested: 'Interpreting role assignments across scopes and groups.',
      realWorld: 'This is exactly how access investigations work — gather assignments from resource up to management group, including groups.',
      trap: 'Reader at the subscription doesn’t reduce Contributor at RG1; RBAC is additive.',
    },
    sources: ['rbac-overview', 'roles-compare'],
  },
  {
    id: 'id-rbac-additive',
    domain: 'identity-governance',
    skills: ['ig.access.interpret'],
    concepts: ['azure-rbac', 'role-assignment'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'An administrator assigns the Reader role to Maria on resource group RG-Finance to stop her changing resources there. Maria can still modify resources in RG-Finance. Maria has Contributor on the subscription. What should the administrator do?',
    options: [
      { id: 'a', text: 'Remove or rescope Maria’s Contributor assignment at the subscription, then grant Contributor only where she needs it', correct: true, why: 'Inherited Contributor still applies; only removing it reduces her access.' },
      { id: 'b', text: 'Wait up to 24 hours for the Reader assignment to take effect', why: 'Timing isn’t the issue — Reader never overrides Contributor.' },
      { id: 'c', text: 'Add a NotActions entry to the Reader role', why: 'You can’t modify built-in roles, and NotActions wouldn’t deny another role’s permissions.' },
      { id: 'd', text: 'Assign Reader to Maria at the subscription as well', why: 'Adding more Reader assignments doesn’t remove Contributor.' },
    ],
    explanation: {
      correct: 'Azure RBAC is additive. Effective permissions are the union of all assignments, so the subscription-level Contributor assignment keeps granting write access in every resource group.',
      conceptTested: 'The additive model and inheritance.',
      realWorld: 'Trying to “downgrade” by adding a weaker role at a lower scope is one of the most common RBAC misunderstandings.',
    },
    sources: ['rbac-overview'],
  },
  {
    id: 'id-custom-role-scope',
    domain: 'identity-governance',
    skills: ['ig.access.builtin', 'ig.access.scopes'],
    concepts: ['custom-role'],
    kind: 'knowledge',
    difficulty: 3,
    format: 'multi',
    stem: 'You are creating an Azure custom role. Which two values are NOT allowed in the AssignableScopes property? Each correct answer presents a complete solution.',
    options: [
      { id: 'a', text: '"/"', correct: true, why: 'The root scope can’t be used in AssignableScopes for custom roles.' },
      { id: 'b', text: '"/subscriptions/*"', correct: true, why: 'Wildcards aren’t allowed in AssignableScopes.' },
      { id: 'c', text: '"/subscriptions/1111-…/resourceGroups/rg-app"', why: 'A resource group is a valid assignable scope.' },
      { id: 'd', text: '"/providers/Microsoft.Management/managementGroups/mg-prod"', why: 'One management group can be listed as an assignable scope.' },
    ],
    explanation: {
      correct: 'Custom role AssignableScopes can include management groups (only one), subscriptions and resource groups, but not the root scope or wildcards.',
      conceptTested: 'Custom role definition constraints.',
      realWorld: 'Custom roles are often defined at a management group so every subscription beneath can use them.',
    },
    sources: ['rbac-custom-roles'],
  },
  {
    id: 'id-global-admin-azure',
    domain: 'identity-governance',
    skills: ['ig.access.builtin'],
    concepts: ['entra-roles', 'azure-rbac'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'A newly hired Global Administrator signs in to the Azure portal and can’t see any subscriptions. What is the most likely reason?',
    options: [
      { id: 'a', text: 'Microsoft Entra roles don’t grant access to Azure resources; the user needs an Azure role assignment or must elevate access', correct: true, why: 'Global Administrator manages the directory, not subscriptions, until elevation or an Azure role is assigned.' },
      { id: 'b', text: 'Global Administrators can only use the Microsoft Entra admin center, not the Azure portal', why: 'The portal is available; it just shows no subscriptions without Azure roles.' },
      { id: 'c', text: 'The user needs a Microsoft Entra ID P2 licence', why: 'Licensing doesn’t grant Azure resource access.' },
      { id: 'd', text: 'Subscriptions are hidden until the Co-Administrator role is assigned', why: 'Classic administrator roles are retired; Azure RBAC is used.' },
    ],
    explanation: {
      correct: 'Azure roles and Microsoft Entra roles are separate systems. A Global Administrator can elevate to User Access Administrator at root scope, or simply be assigned an Azure role.',
      conceptTested: 'Azure roles vs Microsoft Entra roles.',
      realWorld: 'Separating directory and resource administration limits what a single compromised account can do.',
    },
    sources: ['roles-compare'],
  },
  {
    id: 'id-mi-user-assigned',
    domain: 'identity-governance',
    skills: ['ig.access.scopes'],
    concepts: ['managed-identity'],
    kind: 'architecture',
    difficulty: 2,
    format: 'single',
    stem: 'Ten Azure function apps must read secrets from the same key vault. Function apps are frequently deleted and redeployed by a pipeline. You want to grant access once and avoid storing credentials. What should you use?',
    options: [
      { id: 'a', text: 'One user-assigned managed identity attached to all ten function apps, granted access to the key vault', correct: true, why: 'A user-assigned identity is shareable and survives redeployment, so the access grant is made once.' },
      { id: 'b', text: 'A system-assigned managed identity on each function app', why: 'Each identity is deleted with its app, so access must be re-granted after every redeployment.' },
      { id: 'c', text: 'A service principal with a client secret stored in each app’s settings', why: 'This stores a credential, which the requirement prohibits.' },
      { id: 'd', text: 'The storage account access key', why: 'Unrelated to Key Vault and still a stored credential.' },
    ],
    explanation: {
      correct: 'User-assigned managed identities have an independent lifecycle and can be attached to multiple resources, making them ideal for shared, stable permissions.',
      conceptTested: 'Choosing between system-assigned and user-assigned managed identities.',
      realWorld: 'Platform teams pre-provision user-assigned identities and role assignments so pipelines can recreate apps safely.',
    },
    sources: ['managed-identities'],
  },
  {
    id: 'id-bulk-users',
    domain: 'identity-governance',
    skills: ['ig.entra.create', 'ig.entra.properties'],
    concepts: ['entra-user'],
    kind: 'configuration',
    difficulty: 1,
    format: 'single',
    stem: 'You need to create 300 new cloud-only users in Microsoft Entra ID from a spreadsheet provided by HR, using the portal. What should you use?',
    options: [
      { id: 'a', text: 'Users → Bulk create, using the downloadable CSV template', correct: true, why: 'Bulk create accepts a CSV file based on the template and creates member users (at least User Administrator is required).' },
      { id: 'b', text: 'New user → Invite external user, 300 times', why: 'Invite creates guests, not member users, and is one at a time.' },
      { id: 'c', text: 'A dynamic membership group with a rule based on the spreadsheet', why: 'Dynamic groups manage membership of existing users; they don’t create users.' },
      { id: 'd', text: 'An Azure Resource Manager template deployment', why: 'ARM templates deploy Azure resources, not Microsoft Entra users.' },
    ],
    explanation: {
      correct: 'The Users page offers Bulk create, which uses a CSV template to create many users in one operation. PowerShell or the Azure CLI are scripted alternatives.',
      conceptTested: 'Creating users at scale.',
      realWorld: 'Seasonal hiring and school enrolment commonly use bulk creation before automation is in place.',
    },
    sources: ['users-bulk-add'],
  },
  {
    id: 'id-usage-location',
    domain: 'identity-governance',
    skills: ['ig.entra.properties', 'ig.entra.licenses'],
    concepts: ['entra-user', 'group-based-licensing'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'You add a new user who has no usage location to a group that assigns Microsoft 365 licences. What happens?',
    options: [
      { id: 'a', text: 'The user inherits the tenant’s location for group-based licensing, and the licence is assigned', correct: true, why: 'Group-based licensing uses the tenant location when a user has no usage location.' },
      { id: 'b', text: 'The licence assignment fails permanently until the user is deleted and recreated', why: 'No recreation is needed.' },
      { id: 'c', text: 'The user receives the licence only after being added to a dynamic group', why: 'Membership type doesn’t affect usage location handling.' },
      { id: 'd', text: 'The group is converted to a Microsoft 365 group', why: 'Group type never changes automatically.' },
    ],
    explanation: {
      correct: 'Usage location matters for licensing because services are not available everywhere. With group-based licensing, a missing usage location is filled by the tenant location.',
      conceptTested: 'User properties that affect licensing.',
      realWorld: 'Multinational tenants should set usage location explicitly so users get services allowed in their country.',
    },
    sources: ['group-licensing'],
  },
  {
    id: 'id-role-assignable-group',
    domain: 'identity-governance',
    skills: ['ig.entra.create'],
    concepts: ['entra-group', 'entra-roles'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'single',
    stem: 'You want to assign the Helpdesk Administrator Microsoft Entra role to a group, and you want membership to update automatically based on job title. What is the problem with this plan?',
    options: [
      { id: 'a', text: 'Groups that can be assigned Microsoft Entra roles must use assigned membership, not dynamic membership', correct: true, why: 'Role-assignable groups require assigned membership.' },
      { id: 'b', text: 'Microsoft Entra roles can only be assigned to Microsoft 365 groups', why: 'Security groups can be role-assignable.' },
      { id: 'c', text: 'Job title can’t be used in dynamic rules', why: '`user.jobTitle` is a supported property.' },
      { id: 'd', text: 'Dynamic groups can only contain devices', why: 'Dynamic groups can contain users or devices.' },
    ],
    explanation: {
      correct: 'To prevent privilege escalation through attribute changes, groups used for Microsoft Entra role assignments require assigned membership.',
      conceptTested: 'Constraints on role-assignable groups.',
      realWorld: 'If a dynamic group held an admin role, anyone able to edit a user’s job title could grant admin rights.',
    },
    sources: ['dynamic-groups'],
  },
  {
    id: 'id-rbac-scope-order',
    domain: 'identity-governance',
    skills: ['ig.access.scopes'],
    concepts: ['rbac-scope', 'management-group'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'order',
    stem: 'Arrange the Azure RBAC scopes from broadest to narrowest.',
    items: [
      { id: '1', text: 'Management group' },
      { id: '2', text: 'Subscription' },
      { id: '3', text: 'Resource group' },
      { id: '4', text: 'Resource' },
    ],
    why: 'Role assignments at a broader scope are inherited by every narrower scope beneath it.',
    explanation: {
      correct: 'Azure has four levels of scope: management group, subscription, resource group and resource.',
      conceptTested: 'The scope hierarchy used for inheritance.',
      realWorld: 'Choosing the right level is the single biggest factor in keeping access manageable.',
    },
    sources: ['rbac-overview'],
  },
  {
    id: 'id-check-access',
    domain: 'identity-governance',
    skills: ['ig.access.interpret'],
    concepts: ['azure-rbac'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'A user reports that they can’t start a VM named VM5. You need to quickly determine the user’s effective role assignments at VM5, including inherited assignments and group memberships. What should you do first?',
    options: [
      { id: 'a', text: 'Open VM5 → Access control (IAM) → Check access, and select the user', correct: true, why: 'Check access shows the user’s effective assignments at that scope, including inherited and group-based ones.' },
      { id: 'b', text: 'Open the user in Microsoft Entra ID and review Assigned roles', why: 'That shows Microsoft Entra directory roles, not Azure resource roles.' },
      { id: 'c', text: 'Run IP flow verify for VM5', why: 'IP flow verify diagnoses network filtering, not authorization.' },
      { id: 'd', text: 'Review the VM’s boot diagnostics', why: 'Boot diagnostics show OS startup, not permissions.' },
    ],
    explanation: {
      correct: 'Check access in the IAM blade evaluates role assignments for a principal at the selected scope.',
      conceptTested: 'Tools for interpreting access.',
      realWorld: 'Most “I can’t do X” tickets are resolved faster by checking effective access than by reading assignments one by one.',
    },
    sources: ['rbac-overview'],
  },
];
