import type { Question } from '../schema';

export const MONITORING_QUESTIONS: Question[] = [
  // ------------------------------------------------------------------ metrics
  {
    id: 'mon-metrics-retention',
    domain: 'monitoring',
    skills: ['mo.monitor.metrics'],
    concepts: ['metrics', 'azure-monitor'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'An auditor asks for 12 months of CPU data for a virtual machine. Platform metrics are already being collected. What must you do?',
    options: [
      { id: 'a', text: 'Create a diagnostic setting that sends the platform metrics to a Log Analytics workspace or storage account', correct: true, why: 'Platform metrics are retained for 93 days; longer retention requires routing them to another destination.' },
      { id: 'b', text: 'Nothing — platform metrics are retained for two years', why: 'Platform and custom metrics are stored for 93 days.' },
      { id: 'c', text: 'Increase the metric retention setting on the virtual machine', why: 'There is no per-resource metric retention setting.' },
      { id: 'd', text: 'Install the Azure Monitor Agent on the VM', why: 'The agent collects guest data; it does not extend platform metric retention.' },
    ],
    explanation: {
      correct: 'Platform and custom metrics are stored for 93 days. Microsoft documents sending platform metrics to a Log Analytics workspace for long-term trending, where retention is configurable.',
      conceptTested: 'Metric retention and how to extend it.',
      realWorld: 'A single metrics chart can also only span 30 days at a time — pan the chart to see the rest of the 93-day window.',
      trap: 'Retention and chart span are different limits: 93 days of data, 30 days per chart.',
    },
    sources: ['metrics-overview', 'diagnostic-settings'],
  },
  {
    id: 'mon-metrics-aggregation',
    domain: 'monitoring',
    skills: ['mo.monitor.metrics'],
    concepts: ['metrics'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'Users report the application freezes for a minute or two several times an hour. The VM’s CPU chart, using the default aggregation over the last 24 hours, shows a steady 22%. What should you change to see the problem?',
    options: [
      { id: 'a', text: 'Change the aggregation to Max and narrow the time range', correct: true, why: 'Average over a long window smooths short spikes; maximum exposes them.' },
      { id: 'b', text: 'Change the aggregation to Sum', why: 'Sum of a percentage metric is not meaningful.' },
      { id: 'c', text: 'Switch from platform metrics to guest metrics', why: 'Guest metrics add memory and disk detail but do not fix an aggregation that hides spikes.' },
      { id: 'd', text: 'Send the metric to a Log Analytics workspace and query it', why: 'Possible, but the chart already holds the answer once the aggregation is right.' },
    ],
    explanation: {
      correct: 'The aggregation determines what the chart says. A VM at 100% for two minutes out of ten averages about 20% — which is exactly the reading in the scenario. Maximum over a short granularity shows the spikes.',
      conceptTested: 'Aggregation as part of the question you are asking.',
      realWorld: 'The same mistake in an alert rule means the alert never fires: build spike alerts on max, not average.',
      trap: 'The default aggregation is not always the right one.',
    },
    sources: ['metrics-overview'],
  },
  {
    id: 'mon-guest-metrics',
    domain: 'monitoring',
    skills: ['mo.monitor.metrics', 'mo.monitor.logs'],
    concepts: ['azure-monitor-agent', 'metrics'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'You need available memory and free disk space for a set of Azure VMs. Neither appears in Metrics explorer. Why?',
    options: [
      { id: 'a', text: 'They are guest OS metrics, which require the Azure Monitor Agent and a data collection rule', correct: true, why: 'Platform metrics come from the Azure platform; anything measured inside the OS needs an agent.' },
      { id: 'b', text: 'They are only available in the Free tier of Azure Monitor', why: 'There is no such tier gate on these metrics.' },
      { id: 'c', text: 'They require a diagnostic setting on the virtual machine', why: 'A diagnostic setting routes platform logs and metrics; it does not reach inside the guest.' },
      { id: 'd', text: 'They are only available for VMs in an availability set', why: 'Availability set membership has no bearing on metric collection.' },
    ],
    explanation: {
      correct: 'Azure can see how much CPU a VM consumes from the host, but not how much memory the guest OS has free. Guest metrics and logs require the Azure Monitor Agent plus a data collection rule associated with the machine.',
      conceptTested: 'The boundary between platform and guest telemetry.',
      realWorld: 'Installing the agent without associating a data collection rule collects nothing — a very common cause of empty VM insights.',
    },
    sources: ['ama-overview', 'metrics-overview'],
  },

  // --------------------------------------------------------------------- logs
  {
    id: 'mon-activity-retention',
    domain: 'monitoring',
    skills: ['mo.monitor.logs'],
    concepts: ['activity-log'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'Evaluate each statement about the Azure activity log.',
    statements: [
      { id: 's1', text: 'The activity log is collected automatically, with no configuration required.', answer: true, why: 'Azure Monitor collects activity log entries by default; the entries are system generated and cannot be changed or deleted.' },
      { id: 's2', text: 'Azure retains activity log events for 90 days and then deletes them.', answer: true, why: 'That is the documented default retention.' },
      { id: 's3', text: 'The activity log records the contents of requests made to a resource, such as which blob was read.', answer: false, why: 'Those are data-plane operations recorded by resource logs, which need a diagnostic setting.' },
    ],
    explanation: {
      correct: 'The activity log records control-plane operations — create, update, delete and actions on resources — automatically, for 90 days. Data-plane detail lives in resource logs, which are off by default.',
      conceptTested: 'Activity log versus resource logs, and the 90-day retention.',
      realWorld: 'The activity log is the only place that records who created a resource, so exporting it to a workspace is standard practice.',
    },
    sources: ['activity-log', 'control-data-plane'],
  },
  {
    id: 'mon-diag-destination',
    domain: 'monitoring',
    skills: ['mo.monitor.logs'],
    concepts: ['diagnostic-settings', 'log-analytics-workspace'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'match',
    stem: 'Match each requirement with the diagnostic setting destination that satisfies it.',
    prompts: [
      { id: 'p1', text: 'Run KQL queries across logs from many resources and create log alert rules', answer: 'c1', why: 'Only a Log Analytics workspace provides the query language and log alert rules.' },
      { id: 'p2', text: 'Keep seven years of logs as cheaply as possible for an audit', answer: 'c2', why: 'A storage account is the low-cost archive destination.' },
      { id: 'p3', text: 'Stream events to a non-Microsoft SIEM outside Azure', answer: 'c3', why: 'An event hub streams records as JSON for external consumers.' },
    ],
    choices: [
      { id: 'c1', text: 'Log Analytics workspace' },
      { id: 'c2', text: 'Storage account' },
      { id: 'c3', text: 'Event hub' },
    ],
    explanation: {
      correct: 'A diagnostic setting routes selected log categories and metrics to one or more destinations. The choice follows the purpose: query, archive, or stream.',
      conceptTested: 'Matching a monitoring requirement to a destination.',
      realWorld: 'One diagnostic setting can send to several destinations at once — query in a workspace and archive in storage.',
    },
    sources: ['diagnostic-settings', 'activity-log'],
  },
  {
    id: 'mon-resource-logs-default',
    domain: 'monitoring',
    skills: ['mo.monitor.logs'],
    concepts: ['diagnostic-settings', 'activity-log'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'A security review asks which identities read secrets from a key vault last month. Nothing has been configured on the vault beyond its default settings. What is the outcome?',
    options: [
      { id: 'a', text: 'The data does not exist — resource logs are not collected until a diagnostic setting is created', correct: true, why: 'Data-plane operations are recorded only when resource logs are enabled and routed somewhere.' },
      { id: 'b', text: 'The activity log holds the answer, because it records all operations on resources', why: 'The activity log records control-plane operations and does not typically capture reads.' },
      { id: 'c', text: 'Azure Monitor metrics hold the answer, filtered by the caller dimension', why: 'Metrics are numeric aggregates; they do not identify individual callers.' },
      { id: 'd', text: 'The data is in the vault’s Insights view for the last 90 days', why: 'Insights visualise data that is already being collected; nothing was collected.' },
    ],
    explanation: {
      correct: 'Resource logs are off by default. Without a diagnostic setting created before the events, the data-plane history does not exist anywhere. The correct next action is to enable it now so the question can be answered in future.',
      conceptTested: 'Resource logs are opt-in and cannot be recovered retroactively.',
      realWorld: 'This is why an Azure Policy that enforces diagnostic settings on new resources is one of the highest-value guardrails a team can deploy.',
      trap: 'The activity log feels like it should have the answer, but reads are data-plane operations.',
    },
    sources: ['diagnostic-settings', 'activity-log', 'control-data-plane'],
  },

  // ---------------------------------------------------------------------- KQL
  {
    id: 'mon-kql-summarize',
    domain: 'monitoring',
    skills: ['mo.monitor.query'],
    concepts: ['kql', 'log-analytics-workspace'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'What does this query return?',
    exhibit: {
      title: 'Query',
      kind: 'code',
      lang: 'kusto',
      code: `Perf
| where TimeGenerated > ago(7d)
| where CounterName == "Available MBytes"
| summarize avg(CounterValue) by bin(TimeGenerated, 1h), Computer`,
    },
    options: [
      { id: 'a', text: 'The average available memory for each computer, in one-hour buckets, over the last seven days', correct: true, why: 'summarize groups by the binned timestamp and Computer, and averages the counter value in each group.' },
      { id: 'b', text: 'Every Available MBytes sample from the last seven days, sorted by time', why: 'summarize aggregates rows; it does not return the raw samples.' },
      { id: 'c', text: 'The single lowest available memory value across all computers', why: 'That would need min() and no grouping column.' },
      { id: 'd', text: 'One row per computer with the latest available memory reading', why: 'That would need arg_max(TimeGenerated, *) rather than avg with a time bin.' },
    ],
    explanation: {
      correct: '`bin(TimeGenerated, 1h)` rounds each timestamp down to the hour, so grouping by it produces a time series. Without `bin`, grouping by TimeGenerated would create a group per distinct millisecond.',
      conceptTested: 'Reading a summarize with a time bin.',
      realWorld: 'Add `| render timechart` and this becomes a chart of memory pressure per machine.',
    },
    sources: ['kql-getting-started'],
  },
  {
    id: 'mon-kql-project-extend',
    domain: 'monitoring',
    skills: ['mo.monitor.query'],
    concepts: ['kql'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'What is the difference between `project` and `extend` in KQL?',
    options: [
      { id: 'a', text: '`project` returns only the columns you list (and can rename or compute them); `extend` adds computed columns while keeping all the originals', correct: true, why: 'That is exactly the documented behaviour of each operator.' },
      { id: 'b', text: '`project` filters rows; `extend` filters columns', why: '`where` filters rows — neither of these does.' },
      { id: 'c', text: '`project` sorts the results; `extend` limits them', why: 'Those are `sort` and `take`.' },
      { id: 'd', text: 'They are aliases for the same operator', why: 'They produce different column sets.' },
    ],
    explanation: {
      correct: 'Use `project` to reduce a wide table to the columns you care about, and `extend` when you need a derived value but still want the rest of the record.',
      conceptTested: 'Column-shaping operators.',
      realWorld: 'Projecting early in a query reduces the data moved through the rest of the pipeline.',
    },
    sources: ['kql-getting-started'],
  },

  // ------------------------------------------------------------------- alerts
  {
    id: 'mon-alert-type',
    domain: 'monitoring',
    skills: ['mo.monitor.alerts'],
    concepts: ['alert-rule', 'activity-log'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'You must be notified whenever anyone deletes a virtual machine in the production resource group. Which alert type should you create?',
    options: [
      { id: 'a', text: 'An activity log alert', correct: true, why: 'Deletion is a control-plane event recorded in the activity log, which is exactly what activity log alerts match.' },
      { id: 'b', text: 'A metric alert', why: 'There is no metric that represents “a VM was deleted”.' },
      { id: 'c', text: 'A log search alert on the Perf table', why: 'Perf holds performance counters, not management operations.' },
      { id: 'd', text: 'A Resource Health alert', why: 'Resource Health reports whether Azure considers a resource healthy, not who deleted it.' },
    ],
    explanation: {
      correct: 'Activity log alerts fire when a new activity log event matches the defined conditions — the standard answer for “notify me when someone creates, changes or deletes X”.',
      conceptTested: 'Choosing the alert type from the signal.',
      realWorld: 'Activity log alerts are stateless: they fire per event and stay in the Fired condition, because there is no ongoing condition to resolve.',
    },
    sources: ['alerts-types', 'activity-log'],
  },
  {
    id: 'mon-alert-suppress',
    domain: 'monitoring',
    skills: ['mo.monitor.alerts'],
    concepts: ['alert-processing-rule', 'action-group'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'Patching runs every Saturday between 22:00 and midnight and fires dozens of alerts. You must stop the notifications during that window without losing alert coverage. What should you configure?',
    options: [
      { id: 'a', text: 'An alert processing rule with a weekly schedule that removes all action groups for the affected scope', correct: true, why: 'Alert processing rules modify alerts as they fire and can run on a schedule, suppressing notifications while the rules keep evaluating.' },
      { id: 'b', text: 'Disable the alert rules every Saturday evening and re-enable them afterwards', why: 'Manual, error-prone and it loses coverage entirely.' },
      { id: 'c', text: 'Delete the action group and recreate it on Sunday', why: 'That breaks every other rule that references it.' },
      { id: 'd', text: 'Raise the severity of the alerts so they are filtered out', why: 'Severity does not suppress notifications.' },
    ],
    explanation: {
      correct: 'An alert processing rule can add or suppress action groups, filter by scope and alert properties, and run on a predefined schedule. The alerts still fire and are recorded; only the notifications stop.',
      conceptTested: 'The third piece of the alerting model — processing rules.',
      realWorld: 'The same mechanism adds an extra action group for a particular subscription without editing every rule.',
    },
    sources: ['alert-processing-rules', 'alerts-overview'],
  },
  {
    id: 'mon-action-group',
    domain: 'monitoring',
    skills: ['mo.monitor.alerts'],
    concepts: ['action-group', 'alert-rule'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'multi',
    stem: 'Which two of the following can an action group do when an alert fires? Select two.',
    options: [
      { id: 'a', text: 'Send an email, SMS or push notification', correct: true, why: 'Notification methods are core action group functionality.' },
      { id: 'b', text: 'Start an automation runbook, an Azure Function or a Logic App', correct: true, why: 'Action groups support automation actions as well as notifications.' },
      { id: 'c', text: 'Change the alert rule’s threshold automatically', why: 'Action groups do not modify alert rules.' },
      { id: 'd', text: 'Suppress other alerts during a maintenance window', why: 'That is an alert processing rule.' },
    ],
    explanation: {
      correct: 'An action group is a reusable list of notifications (email, SMS, push) and actions (automation runbooks, Azure Functions, ITSM, Logic Apps, webhooks and secure webhooks, event hubs). Many alert rules reference the same action group.',
      conceptTested: 'The division of labour between rule, action group and processing rule.',
      realWorld: 'Keeping notifications in action groups means an on-call change is one edit, not thirty.',
    },
    sources: ['alerts-overview'],
  },

  // ----------------------------------------------------------------- insights
  {
    id: 'mon-vm-insights-prereq',
    domain: 'monitoring',
    skills: ['mo.monitor.insights'],
    concepts: ['vm-insights', 'azure-monitor-agent'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'VM insights shows platform charts for a virtual machine but the performance and map views are empty. The Azure Monitor Agent is installed. What is missing?',
    options: [
      { id: 'a', text: 'A data collection rule associated with the virtual machine', correct: true, why: 'The agent collects nothing until a data collection rule tells it what to collect and where to send it.' },
      { id: 'b', text: 'A diagnostic setting on the virtual machine', why: 'Diagnostic settings route platform logs and metrics; they do not collect guest data.' },
      { id: 'c', text: 'A public IP address on the virtual machine', why: 'The agent does not need inbound connectivity.' },
      { id: 'd', text: 'A premium Log Analytics workspace tier', why: 'There is no such prerequisite for VM insights.' },
    ],
    explanation: {
      correct: 'The Azure Monitor Agent is a transport. A data collection rule defines which counters, event logs and syslog facilities to collect and which workspace receives them, and the rule must be associated with the machine.',
      conceptTested: 'Agent plus data collection rule as a pair.',
      realWorld: 'Running the retired Log Analytics agent alongside the Azure Monitor Agent produces duplicate records — a second common symptom.',
    },
    sources: ['ama-overview'],
  },

  // ---------------------------------------------------------------- network
  {
    id: 'mon-connection-monitor-agent',
    domain: 'monitoring',
    skills: ['mo.monitor.network-watcher'],
    concepts: ['connection-monitor', 'network-watcher'],
    kind: 'configuration',
    difficulty: 3,
    format: 'single',
    stem: 'You are configuring Connection monitor to test connectivity from two Azure VMs to an external URL. What must be installed, and where?',
    options: [
      { id: 'a', text: 'The Network Watcher agent extension on the two source VMs; the destination needs nothing', correct: true, why: 'Azure VMs and scale sets must run the Network Watcher extension to act as sources; destination endpoints do not require it.' },
      { id: 'b', text: 'The Network Watcher agent on both the sources and the destination', why: 'Destination endpoints — URLs, FQDNs, IP addresses and Azure resources — do not require the extension.' },
      { id: 'c', text: 'The Azure Monitor Agent on the source VMs', why: 'That is the requirement for Azure Arc-enabled on-premises sources, not Azure VMs.' },
      { id: 'd', text: 'Nothing — Connection monitor tests entirely from the Azure platform', why: 'Connection monitor relies on lightweight executables running on the source endpoints.' },
    ],
    explanation: {
      correct: 'Connection monitor runs checks from the source. Azure VMs and scale sets need the Network Watcher agent extension; on-premises sources need Azure Arc and then the Azure Monitor Agent. Destinations are just targets.',
      conceptTested: 'Connection monitor prerequisites.',
      realWorld: 'The portal enables the required extensions automatically when you create a connection monitor there.',
    },
    sources: ['connection-monitor'],
  },
  {
    id: 'mon-flowlogs-vs-monitor',
    domain: 'monitoring',
    skills: ['mo.monitor.network-watcher'],
    concepts: ['connection-monitor', 'network-watcher'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'single',
    stem: 'An intermittent connectivity problem between two subnets happened overnight and has now cleared. You need to know whether traffic was reaching the destination and what happened to it. Which tool gives you that history?',
    options: [
      { id: 'a', text: 'Virtual network flow logs', correct: true, why: 'Flow logs record the traffic that was allowed or denied, so they answer questions about what actually happened.' },
      { id: 'b', text: 'IP flow verify', why: 'It evaluates the rules right now for a hypothetical packet; it holds no history.' },
      { id: 'c', text: 'Next hop', why: 'It reports where a packet would be routed now, not what happened overnight.' },
      { id: 'd', text: 'Effective security rules', why: 'It shows the rules currently in force, not past traffic.' },
    ],
    explanation: {
      correct: 'Flow logs are the record of traffic; the other Network Watcher tools are point-in-time evaluations of current configuration. Connection monitor sits between the two: continuous synthetic tests with metrics you can alert on and look back at.',
      conceptTested: 'History versus current-state network tools.',
      realWorld: 'Traffic Analytics builds on flow logs to summarise traffic patterns and top talkers.',
    },
    sources: ['network-watcher', 'connection-monitor'],
  },

  // ---------------------------------------------------------- troubleshooting
  {
    id: 'mon-who-changed',
    domain: 'monitoring',
    skills: ['mo.monitor.logs', 'mo.monitor.query'],
    concepts: ['activity-log', 'kql'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'An application broke overnight and the team insists nothing was deployed. Where do you look first to find out whether anything changed?',
    options: [
      { id: 'a', text: 'The activity log, filtered to the Administrative category around the time the symptom started', correct: true, why: 'The activity log records control-plane changes and names the caller that made each one.' },
      { id: 'b', text: 'Metrics explorer, charting CPU for the affected resources', why: 'Useful for saturation, but it does not show whether a change was made.' },
      { id: 'c', text: 'The Perf table in Log Analytics', why: 'Performance counters do not record configuration changes.' },
      { id: 'd', text: 'Azure Advisor recommendations', why: 'Advisor suggests improvements; it does not audit changes.' },
    ],
    explanation: {
      correct: 'The activity log answers “what changed and who did it”. Opening an event and using Change history shows the resource’s property values before and after the operation.',
      conceptTested: 'The triage habit of checking for change first.',
      realWorld: 'Automation accounts, policy remediation tasks and pipelines all appear in the Caller column — “nobody changed anything” is usually wrong.',
    },
    sources: ['activity-log'],
  },
  {
    id: 'mon-first-check',
    domain: 'monitoring',
    skills: ['mo.monitor.metrics', 'mo.monitor.logs'],
    concepts: ['resource-health', 'activity-log'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'A production VM has become unreachable and your team made no changes. What should you check first?',
    options: [
      { id: 'a', text: 'Resource Health for the VM, then Service Health for the region', correct: true, why: 'They tell you immediately whether the cause is on the Azure side, which is the one cause you cannot fix.' },
      { id: 'b', text: 'The application logs inside the guest', why: 'A reasonable later step, but it assumes the platform is healthy.' },
      { id: 'c', text: 'The subscription’s cost analysis', why: 'Unrelated to availability.' },
      { id: 'd', text: 'Azure Advisor’s reliability recommendations', why: 'Advisor gives forward-looking advice, not incident state.' },
    ],
    explanation: {
      correct: 'Resource Health reports the current and past health of a specific resource and whether Microsoft is acting on it; Service Health reports outages, planned maintenance and advisories affecting the services your subscription uses. Both are activity log based and take seconds to check.',
      conceptTested: 'Triage order: rule out the platform before investigating your own workload.',
      realWorld: 'Service Health alerts turn this into a push notification rather than something you have to remember to check.',
    },
    sources: ['alerts-types', 'activity-log'],
  },
];
