import type { Question } from '../schema';

export const NETWORKING_QUESTIONS: Question[] = [
  {
    id: 'nw-subnet-usable',
    domain: 'networking',
    skills: ['nw.vnet.create'],
    concepts: ['subnet', 'vnet'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'You create a subnet with the address prefix 10.1.4.0/28. How many IP addresses are available for virtual machines?',
    options: [
      { id: 'a', text: '11', correct: true, why: '16 total addresses minus the 5 Azure reserves.' },
      { id: 'b', text: '16', why: 'That is the total address count, before Azure’s reservations.' },
      { id: 'c', text: '14', why: 'That would be the usable count in a traditional network (minus network and broadcast only).' },
      { id: 'd', text: '8', why: 'A /29 has 8 total addresses.' },
    ],
    explanation: {
      correct: 'Azure reserves five addresses in every subnet: the network address, the default gateway, two for Azure DNS mapping, and the broadcast address. A /28 therefore offers 11 usable addresses.',
      conceptTested: 'Subnet sizing and Azure’s reserved addresses.',
      realWorld: 'Undersized subnets block scale-out later, and subnets can’t be resized while resources are deployed.',
      trap: 'Standard networking math (2^n − 2) gives 14 and is wrong in Azure.',
    },
    sources: ['vnet-faq'],
  },
  {
    id: 'nw-vnet-overlap',
    domain: 'networking',
    skills: ['nw.vnet.create', 'nw.vnet.peering'],
    concepts: ['vnet', 'vnet-peering'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'VNet1 (10.0.0.0/16) in West Europe and VNet2 (10.0.0.0/16) in North Europe must communicate privately. What must you do first?',
    options: [
      { id: 'a', text: 'Re-address one of the virtual networks so the address spaces don’t overlap', correct: true, why: 'Peering requires non-overlapping address spaces.' },
      { id: 'b', text: 'Create a global peering — overlapping ranges are supported across regions', why: 'Overlap isn’t allowed for local or global peering.' },
      { id: 'c', text: 'Add a user-defined route in each VNet for the other VNet’s range', why: 'Routes can’t resolve duplicate address spaces.' },
      { id: 'd', text: 'Enable gateway transit on both virtual networks', why: 'Gateway transit shares a gateway; it doesn’t fix overlap.' },
    ],
    explanation: {
      correct: 'Two networks with the same address space can’t be peered — Azure has no way to decide where 10.0.1.4 lives. One network must be re-addressed (or connected another way, such as through NAT on an appliance).',
      conceptTested: 'IP planning as a prerequisite for connectivity.',
      realWorld: 'Duplicate 10.0.0.0/16 ranges from quick-start deployments are a common blocker during mergers.',
    },
    sources: ['peering', 'vnet-faq'],
  },
  {
    id: 'nw-public-ip-standard',
    domain: 'networking',
    skills: ['nw.vnet.public-ip'],
    concepts: ['public-ip', 'nsg'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You attach a new Standard SKU public IP address to a VM that runs a web server on port 80. Users can’t reach the site. The web server responds correctly from inside the VM. What is the most likely cause?',
    options: [
      { id: 'a', text: 'No NSG rule allows inbound TCP 80 — Standard public IPs are closed by default', correct: true, why: 'Standard public IPs are secure by default and require an explicit NSG allow rule.' },
      { id: 'b', text: 'Standard public IPs use dynamic allocation, so the address changed', why: 'Standard public IPs are always static.' },
      { id: 'c', text: 'A Standard public IP can’t be assigned to a VM NIC', why: 'It can be assigned to a VM NIC.' },
      { id: 'd', text: 'The VM needs a NAT gateway to receive inbound traffic', why: 'NAT gateways provide outbound connectivity only.' },
    ],
    explanation: {
      correct: 'With the Basic SKU retired, Standard is the current public IP SKU: static allocation and inbound traffic blocked until an NSG rule allows it.',
      conceptTested: 'Standard public IP behaviour.',
      realWorld: 'Teams migrating from Basic IPs often hit this after the migration because Basic allowed inbound by default.',
    },
    sources: ['public-ip', 'nsg-overview'],
  },
  {
    id: 'nw-default-outbound',
    domain: 'networking',
    skills: ['nw.vnet.public-ip', 'nw.vnet.troubleshoot'],
    concepts: ['nat-gateway', 'subnet'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A new VM in a newly created virtual network can’t reach Windows Update or any internet endpoint. It has no public IP address, the NSG allows all outbound traffic, and there are no user-defined routes. What should you do?',
    options: [
      { id: 'a', text: 'Associate a NAT gateway with the subnet to provide explicit outbound connectivity', correct: true, why: 'Subnets in new VNets are private by default and need an explicit outbound method.' },
      { id: 'b', text: 'Add an outbound NSG rule allowing port 443 to the Internet service tag', why: 'Outbound is already allowed; the problem is that no outbound path exists.' },
      { id: 'c', text: 'Enable a service endpoint for Microsoft.Storage on the subnet', why: 'Service endpoints affect specific Azure services, not general internet access.' },
      { id: 'd', text: 'Peer the virtual network with another virtual network', why: 'Peering doesn’t provide internet access.' },
    ],
    explanation: {
      correct: 'For API versions released after March 31, 2026, subnets in new virtual networks are private by default: VMs need a NAT gateway, a Standard Load Balancer outbound rule, a public IP, or routing through a firewall.',
      conceptTested: 'Default outbound access changes.',
      realWorld: 'Microsoft recommends a NAT gateway as the standard explicit outbound method.',
      trap: 'The NSG looks fine because outbound is allowed — the missing piece is an outbound path, not a rule.',
    },
    sources: ['default-outbound'],
  },
  {
    id: 'nw-nsg-priority',
    domain: 'networking',
    skills: ['nw.secure.nsg'],
    concepts: ['nsg'],
    kind: 'multi-step',
    difficulty: 3,
    format: 'single',
    stem: 'Review the inbound rules of NSG1, which is applied to subnet snet-app. A request arrives from the internet to TCP 443 on a VM in snet-app. What happens?',
    exhibit: {
      title: 'NSG1 inbound rules',
      kind: 'table',
      columns: ['Priority', 'Name', 'Source', 'Destination', 'Port', 'Protocol', 'Action'],
      rows: [
        ['150', 'Deny-Internet-All', 'Internet', 'Any', 'Any', 'Any', 'Deny'],
        ['200', 'Allow-HTTPS', 'Internet', 'Any', '443', 'TCP', 'Allow'],
        ['65000', 'AllowVNetInBound', 'VirtualNetwork', 'VirtualNetwork', 'Any', 'Any', 'Allow'],
        ['65500', 'DenyAllInbound', 'Any', 'Any', 'Any', 'Any', 'Deny'],
      ],
    },
    options: [
      { id: 'a', text: 'The request is denied by rule 150', correct: true, why: 'Rules are processed lowest number first and the first match wins.' },
      { id: 'b', text: 'The request is allowed by rule 200', why: 'Rule 150 matches first and stops evaluation.' },
      { id: 'c', text: 'The request is allowed by AllowVNetInBound', why: 'The source is the internet, not the VirtualNetwork tag.' },
      { id: 'd', text: 'Both rules apply, and allow takes precedence over deny', why: 'NSGs don’t combine rules — the first match decides.' },
    ],
    explanation: {
      correct: 'NSG rules are evaluated in priority order (100 → 4096). Rule 150 matches all internet traffic and denies it, so rule 200 is never reached. Give the allow rule a lower number than the deny rule.',
      conceptTested: 'NSG rule priority and first-match evaluation.',
      realWorld: 'Broad deny rules with low numbers silently break later exceptions.',
    },
    sources: ['nsg-overview'],
  },
  {
    id: 'nw-asg-same-vnet',
    domain: 'networking',
    skills: ['nw.secure.nsg'],
    concepts: ['asg', 'nsg'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about application security groups, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A network interface can belong to more than one application security group.', answer: true, why: 'NICs can be members of multiple ASGs.' },
      { id: 's2', text: 'An application security group can contain NICs from two different virtual networks.', answer: false, why: 'All NICs in an ASG must be in the same virtual network.' },
      { id: 's3', text: 'ASGs can be used as the source or destination of an NSG rule.', answer: true, why: 'That is their purpose: rules by role rather than IP address.' },
    ],
    explanation: {
      correct: 'ASGs group NICs within one virtual network so NSG rules survive scaling and re-addressing.',
      conceptTested: 'Application security group behaviour and limits.',
      realWorld: 'Three-tier designs use asg-web, asg-app and asg-db to keep rules readable.',
    },
    sources: ['asg'],
  },
  {
    id: 'nw-effective-two-nsgs',
    domain: 'networking',
    skills: ['nw.secure.effective'],
    concepts: ['nsg', 'effective-security-rules'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A VM has an NSG on its subnet that allows inbound TCP 3389 from the office range, and a second NSG on its network interface that has no custom rules. RDP connections from the office fail. Why?',
    options: [
      { id: 'a', text: 'The NIC NSG denies the traffic through its default DenyAllInbound rule', correct: true, why: 'Inbound traffic must be allowed by both the subnet NSG and the NIC NSG.' },
      { id: 'b', text: 'The subnet NSG overrides the NIC NSG, so the traffic should work — the problem must be DNS', why: 'Neither NSG overrides the other; both must allow.' },
      { id: 'c', text: 'NSGs can’t filter RDP traffic', why: 'NSGs filter any TCP/UDP port, including 3389.' },
      { id: 'd', text: 'Default rules only apply when no NSG is attached', why: 'Default rules exist in every NSG and can only be overridden by higher-priority rules.' },
    ],
    explanation: {
      correct: 'With NSGs on both the subnet and the NIC, inbound traffic passes the subnet NSG first and then the NIC NSG. The NIC NSG has no allow rule, so DenyAllInbound (65500) drops the connection.',
      conceptTested: 'Combined evaluation of subnet and NIC NSGs.',
      realWorld: 'Checking Effective security rules on the NIC shows the combined view immediately.',
      trap: 'An allow rule in one NSG is never enough when a second NSG also applies.',
    },
    sources: ['nsg-overview', 'vnet-faq'],
  },
  {
    id: 'nw-ip-flow-verify',
    domain: 'networking',
    skills: ['nw.secure.effective', 'nw.vnet.troubleshoot'],
    concepts: ['network-watcher', 'effective-security-rules'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'Users report that a VM no longer accepts connections on TCP 8080. You need to determine quickly whether a network security rule blocks the traffic and which rule is responsible. What should you use?',
    options: [
      { id: 'a', text: 'Network Watcher IP flow verify', correct: true, why: 'It evaluates a specific flow and returns Allow or Deny plus the matching rule name.' },
      { id: 'b', text: 'Network Watcher Next hop', why: 'Next hop diagnoses routing, not filtering.' },
      { id: 'c', text: 'Network Watcher Topology', why: 'Topology shows resources and relationships, not rule decisions.' },
      { id: 'd', text: 'Azure Advisor', why: 'Advisor gives recommendations, not per-flow diagnostics.' },
    ],
    explanation: {
      correct: 'IP flow verify takes direction, protocol, local and remote IP and port, then reports whether the packet is allowed or denied and which NSG rule decided.',
      conceptTested: 'Choosing the right diagnostic tool for filtering problems.',
      realWorld: 'It’s the fastest way to end “is it the firewall?” debates with evidence.',
    },
    sources: ['network-watcher'],
  },
  {
    id: 'nw-route-longest-prefix',
    domain: 'networking',
    skills: ['nw.vnet.udr'],
    concepts: ['route-table'],
    kind: 'multi-step',
    difficulty: 3,
    format: 'single',
    stem: 'A subnet has the route table shown in the exhibit, in addition to the default system routes. A VM in the subnet sends traffic to 10.2.1.50. Which next hop is used?',
    exhibit: {
      title: 'Route table rt-app',
      kind: 'table',
      columns: ['Route', 'Address prefix', 'Next hop type', 'Next hop IP'],
      rows: [
        ['to-firewall', '0.0.0.0/0', 'Virtual appliance', '10.0.100.4'],
        ['to-spoke-b', '10.2.0.0/16', 'Virtual appliance', '10.0.100.4'],
        ['direct-subnet', '10.2.1.0/24', 'Virtual network', '—'],
      ],
    },
    options: [
      { id: 'a', text: 'Virtual network — the 10.2.1.0/24 route is the longest prefix match', correct: true, why: 'Azure selects the most specific matching prefix.' },
      { id: 'b', text: 'Virtual appliance 10.0.100.4 through the 10.2.0.0/16 route', why: '/16 is less specific than /24.' },
      { id: 'c', text: 'Virtual appliance 10.0.100.4 through the 0.0.0.0/0 route', why: 'The default route is the least specific match.' },
      { id: 'd', text: 'Internet, because 10.2.1.50 is outside the VNet', why: 'Private ranges aren’t routed to the internet by these routes.' },
    ],
    explanation: {
      correct: 'Azure evaluates routes by longest prefix match. 10.2.1.0/24 is more specific than 10.2.0.0/16 and 0.0.0.0/0, so its next hop wins.',
      conceptTested: 'Route selection with user-defined routes.',
      realWorld: 'Exception routes like this are how teams bypass a firewall for specific flows — deliberately or accidentally.',
    },
    sources: ['routing'],
  },
  {
    id: 'nw-udr-nva',
    domain: 'networking',
    skills: ['nw.vnet.udr'],
    concepts: ['route-table', 'network-virtual-appliance'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'You create a user-defined route sending 0.0.0.0/0 to a firewall VM at 10.0.100.4 and associate it with the application subnet. Traffic from the application VMs now fails completely. The firewall VM is running and its rules allow the traffic. What is the most likely cause?',
    options: [
      { id: 'a', text: 'IP forwarding isn’t enabled on the firewall VM’s network interface', correct: true, why: 'Without IP forwarding, Azure drops packets not addressed to the NIC.' },
      { id: 'b', text: 'The route table must be associated with the firewall’s subnet instead', why: 'Route tables apply to traffic leaving the associated subnet — the application subnet is correct.' },
      { id: 'c', text: 'User-defined routes can’t use 0.0.0.0/0', why: 'That prefix is the standard forced-tunneling route.' },
      { id: 'd', text: 'Next hop type should be Virtual network gateway', why: 'That next hop is for VPN gateways, not an appliance VM.' },
    ],
    explanation: {
      correct: 'A network virtual appliance must have IP forwarding enabled on its NIC (and forwarding configured in the guest OS) so it can forward traffic addressed to other destinations.',
      conceptTested: 'Requirements for routing through an NVA.',
      realWorld: 'Also place the appliance in its own subnet so its own traffic isn’t routed back to itself.',
    },
    sources: ['routing'],
  },
  {
    id: 'nw-peering-transitive',
    domain: 'networking',
    skills: ['nw.vnet.peering'],
    concepts: ['vnet-peering', 'hub-spoke'],
    kind: 'architecture',
    difficulty: 2,
    format: 'single',
    stem: 'VNet-Hub is peered with VNet-A and with VNet-B. A VM in VNet-A can’t reach a VM in VNet-B. Both peerings are Connected and no NSG blocks the traffic. What should you do?',
    options: [
      { id: 'a', text: 'Route spoke-to-spoke traffic through an appliance in the hub with user-defined routes, or peer VNet-A and VNet-B directly', correct: true, why: 'Peering isn’t transitive, so traffic needs an explicit path.' },
      { id: 'b', text: 'Enable “allow gateway transit” on both spoke peerings', why: 'Gateway transit shares a VPN/ExpressRoute gateway; it doesn’t enable spoke-to-spoke routing.' },
      { id: 'c', text: 'Wait for the peering to finish propagating', why: 'The peerings are already Connected.' },
      { id: 'd', text: 'Re-create the peerings with “allow virtual network access” disabled', why: 'That would remove connectivity entirely.' },
    ],
    explanation: {
      correct: 'Peering is not transitive. Spoke-to-spoke communication requires either a direct peering or routing through a hub NVA, with user-defined routes in both spokes, allow forwarded traffic on the peerings, and IP forwarding on the appliance.',
      conceptTested: 'Non-transitive peering and hub-and-spoke routing.',
      realWorld: 'This is the single most common surprise when teams build hub-and-spoke networks.',
    },
    sources: ['peering', 'routing'],
  },
  {
    id: 'nw-peering-gateway-transit',
    domain: 'networking',
    skills: ['nw.vnet.peering'],
    concepts: ['vnet-peering', 'vpn-gateway'],
    kind: 'configuration',
    difficulty: 3,
    format: 'match',
    stem: 'A hub virtual network contains a VPN gateway. Spoke virtual networks must reach on-premises through that gateway. Match each peering setting to where you enable it.',
    prompts: [
      { id: 'p1', text: 'Allow gateway transit', answer: 'hub', why: 'The VNet that owns the gateway offers transit.' },
      { id: 'p2', text: 'Use remote gateways', answer: 'spoke', why: 'The spoke consumes the hub’s gateway and must not have its own.' },
      { id: 'p3', text: 'Allow forwarded traffic', answer: 'both', why: 'Needed where traffic that didn’t originate in the peer must be accepted, typically on both sides in hub-and-spoke.' },
    ],
    choices: [
      { id: 'hub', text: 'On the hub’s peering' },
      { id: 'spoke', text: 'On the spoke’s peering' },
      { id: 'both', text: 'On both peerings' },
    ],
    explanation: {
      correct: 'Gateway transit is offered by the hub and consumed by the spoke. Allow forwarded traffic lets a VNet accept traffic forwarded by an appliance or gateway rather than originating in the peer.',
      conceptTested: 'Peering settings for hub-and-spoke.',
      realWorld: 'One gateway serving all spokes saves significant cost compared with a gateway per VNet.',
    },
    sources: ['peering'],
  },
  {
    id: 'nw-bastion-subnet',
    domain: 'networking',
    skills: ['nw.secure.bastion'],
    concepts: ['bastion', 'subnet'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'You are deploying Azure Bastion into an existing virtual network. Which subnet configuration is required?',
    options: [
      { id: 'a', text: 'A subnet named AzureBastionSubnet with a prefix of /26 or larger', correct: true, why: 'The name is fixed and the subnet must be at least /26.' },
      { id: 'b', text: 'A subnet named GatewaySubnet with a prefix of /27 or larger', why: 'GatewaySubnet is for virtual network gateways.' },
      { id: 'c', text: 'Any subnet, as long as it has a Standard public IP attached', why: 'Public IPs attach to the Bastion host, not the subnet, and the subnet name matters.' },
      { id: 'd', text: 'A subnet named AzureBastionSubnet with a prefix of /29', why: 'A /29 is too small for Bastion deployments.' },
    ],
    explanation: {
      correct: 'Azure Bastion requires a dedicated subnet named exactly AzureBastionSubnet, sized /26 or larger for deployments since November 2, 2021, in the same virtual network as the host.',
      conceptTested: 'Bastion prerequisites.',
      realWorld: 'Leaving room for AzureBastionSubnet and GatewaySubnet is part of VNet address planning.',
    },
    sources: ['bastion-config'],
  },
  {
    id: 'nw-bastion-sku',
    domain: 'networking',
    skills: ['nw.secure.bastion'],
    concepts: ['bastion'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'Administrators must connect to Azure VMs using their local Windows RDP client (not the browser) through Azure Bastion, and the team wants to scale the number of Bastion instances during busy periods. Which SKU meets the requirements at the lowest level?',
    options: [
      { id: 'a', text: 'Standard', correct: true, why: 'Standard supports native client connections and host scaling.' },
      { id: 'b', text: 'Basic', why: 'Basic runs two instances and doesn’t support native client connections.' },
      { id: 'c', text: 'Developer', why: 'The Developer SKU is for lightweight, occasional access without a dedicated deployment.' },
      { id: 'd', text: 'Premium', why: 'Premium meets the needs but adds session recording and private-only deployment that aren’t required.' },
    ],
    explanation: {
      correct: 'Host scaling, custom ports, shareable links and native client support come with the Standard SKU; Premium adds session recording and private-only deployments.',
      conceptTested: 'Bastion SKU features.',
      realWorld: 'Native client support matters for administrators who use RDP file transfer and multi-monitor setups.',
    },
    sources: ['bastion-config'],
  },
  {
    id: 'nw-pe-dns',
    domain: 'networking',
    skills: ['nw.secure.private-endpoints', 'nw.dnslb.dns'],
    concepts: ['private-endpoint', 'private-dns-zone'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'You create a private endpoint for a storage account in subnet snet-data. A VM in the same virtual network still resolves the storage account name to a public IP address. What is missing?',
    options: [
      { id: 'a', text: 'A privatelink.blob.core.windows.net private DNS zone with an A record for the account, linked to the virtual network', correct: true, why: 'Without the linked private zone, the name resolves through public DNS to the public IP.' },
      { id: 'b', text: 'A service endpoint for Microsoft.Storage on snet-data', why: 'Service endpoints are an alternative approach and don’t change DNS.' },
      { id: 'c', text: 'An NSG rule allowing TCP 443 to the private endpoint', why: 'That would affect connectivity, not name resolution.' },
      { id: 'd', text: 'A user-defined route to the private endpoint IP address', why: 'Traffic to a private IP in the same VNet is routed automatically.' },
    ],
    explanation: {
      correct: 'Azure publishes a CNAME from the service name to the privatelink name. A private DNS zone (ideally managed by a DNS zone group) linked to the client VNet returns the private IP. Without it, clients keep resolving the public address.',
      conceptTested: 'Private endpoint DNS integration.',
      realWorld: 'Nine out of ten private endpoint problems are DNS problems.',
      trap: 'Creating the private endpoint isn’t enough — and disabling public access separately is what actually blocks the public path.',
    },
    sources: ['private-endpoint-dns'],
  },
  {
    id: 'nw-se-vs-pe',
    domain: 'networking',
    skills: ['nw.secure.service-endpoints', 'nw.secure.private-endpoints'],
    concepts: ['service-endpoint', 'private-endpoint'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'yesno',
    stem: 'For each statement comparing service endpoints and private endpoints, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A service endpoint gives the Azure service a private IP address inside your virtual network.', answer: false, why: 'Service endpoints keep using the service’s public endpoint; only private endpoints add a private IP.' },
      { id: 's2', text: 'On-premises clients connected over VPN can reach a service through a private endpoint.', answer: true, why: 'Private endpoints are reachable over VPN or ExpressRoute with appropriate routing and DNS.' },
      { id: 's3', text: 'Service endpoints are charged per hour and per gigabyte processed.', answer: false, why: 'Service endpoints are free; private endpoints have hourly and data processing charges.' },
    ],
    explanation: {
      correct: 'Service endpoint: subnet trust on a public endpoint, free, no DNS change. Private endpoint: private IP for one resource, reachable from peered and on-premises networks, requires DNS, and is billed.',
      conceptTested: 'Choosing between service endpoints and private endpoints.',
      realWorld: 'Regulated environments standardize on private endpoints so public access can be disabled entirely.',
    },
    sources: ['private-endpoint-dns', 'storage-firewall', 'vnet-faq'],
  },
  {
    id: 'nw-dns-delegation',
    domain: 'networking',
    skills: ['nw.dnslb.dns'],
    concepts: ['azure-dns'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'You create a public DNS zone named contoso.com in Azure DNS and add an A record for www. Internet users still resolve www.contoso.com to the old provider’s address. What should you do?',
    options: [
      { id: 'a', text: 'Update the name server (NS) records at the domain registrar to the Azure DNS name servers for the zone', correct: true, why: 'Delegation at the registrar is what points the internet to Azure DNS.' },
      { id: 'b', text: 'Create a private DNS zone with the same name and link it to the virtual network', why: 'Private zones resolve only inside linked VNets.' },
      { id: 'c', text: 'Add a CNAME record pointing contoso.com to Azure DNS', why: 'Delegation uses NS records at the registrar, and apex CNAMEs aren’t allowed.' },
      { id: 'd', text: 'Enable autoregistration on the zone', why: 'Autoregistration applies to private zones and VM records.' },
    ],
    explanation: {
      correct: 'Hosting a zone in Azure DNS doesn’t change anything until the domain is delegated: copy the four Azure name servers into the registrar’s NS configuration.',
      conceptTested: 'Public DNS zone delegation.',
      realWorld: 'Delegation changes propagate according to the parent zone’s TTL, so plan cutovers.',
    },
    sources: ['dns-autoregistration', 'appservice-custom-domain'],
  },
  {
    id: 'nw-private-dns-autoreg',
    domain: 'networking',
    skills: ['nw.dnslb.dns'],
    concepts: ['private-dns-zone'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about Azure private DNS zones, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A virtual network can be linked to multiple private DNS zones with autoregistration enabled.', answer: false, why: 'A VNet can have autoregistration enabled on only one private DNS zone link.' },
      { id: 's2', text: 'Autoregistration creates A records for virtual machines in the linked virtual network.', answer: true, why: 'Records are created for VMs (primary NIC) automatically.' },
      { id: 's3', text: 'A private DNS zone can be linked to virtual networks in different subscriptions.', answer: true, why: 'Zones can be linked to multiple VNets, including across subscriptions.' },
    ],
    explanation: {
      correct: 'Private zones resolve only for linked VNets; autoregistration is limited to one zone per VNet and covers VMs only.',
      conceptTested: 'Private DNS zone links and autoregistration.',
      realWorld: 'Hub-and-spoke designs keep privatelink zones central and link them to every spoke.',
    },
    sources: ['dns-autoregistration', 'private-endpoint-dns'],
  },
  {
    id: 'nw-lb-inbound-nat',
    domain: 'networking',
    skills: ['nw.dnslb.lb'],
    concepts: ['load-balancer'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'Three VMs sit behind a public Standard Load Balancer. You must allow an administrator to RDP to one specific VM through the load balancer’s public IP address on port 50001. What should you create?',
    options: [
      { id: 'a', text: 'An inbound NAT rule mapping frontend port 50001 to port 3389 on that VM', correct: true, why: 'Inbound NAT rules forward a frontend port to a single backend instance.' },
      { id: 'b', text: 'A load-balancing rule for port 50001', why: 'Load-balancing rules distribute traffic across all healthy instances.' },
      { id: 'c', text: 'An outbound rule for port 3389', why: 'Outbound rules configure SNAT for outgoing connections.' },
      { id: 'd', text: 'An additional health probe on port 3389', why: 'Probes determine health; they don’t forward traffic.' },
    ],
    explanation: {
      correct: 'Inbound NAT rules provide port forwarding to a specific VM, which is how administrators reach individual instances behind a load balancer (Bastion is usually the better option).',
      conceptTested: 'Load balancer rule types.',
      realWorld: 'Many organizations replace inbound NAT rules for RDP with Azure Bastion to avoid exposing management ports.',
    },
    sources: ['lb-components'],
  },
  {
    id: 'nw-lb-probe-unhealthy',
    domain: 'networking',
    skills: ['nw.dnslb.troubleshoot', 'nw.dnslb.lb'],
    concepts: ['health-probe', 'load-balancer', 'nsg'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'multi',
    stem: 'All instances behind a Standard Load Balancer show as unhealthy. The web application responds correctly when tested from inside each VM. Which two causes should you investigate? Each correct answer presents a possible cause.',
    options: [
      { id: 'a', text: 'An NSG rule denies traffic from the AzureLoadBalancer service tag', correct: true, why: 'Probes originate from 168.63.129.16 and must be allowed.' },
      { id: 'b', text: 'The HTTP probe path returns a status code other than 200', correct: true, why: 'HTTP probes are healthy only on 200 responses.' },
      { id: 'c', text: 'The load balancer uses a Standard public IP address', why: 'That is required and normal for Standard load balancers.' },
      { id: 'd', text: 'The backend VMs are in the same virtual network as the load balancer', why: 'Backend instances must be in a single virtual network — this is expected.' },
    ],
    explanation: {
      correct: 'Probe failures usually come from blocked probe traffic (NSG or guest firewall) or from an endpoint that doesn’t return HTTP 200 — redirects and authentication responses count as unhealthy.',
      conceptTested: 'Diagnosing health probe failures.',
      realWorld: 'A dedicated, unauthenticated /health endpoint returning 200 avoids most probe problems.',
    },
    sources: ['lb-probes', 'nsg-overview'],
  },
  {
    id: 'nw-watcher-tools',
    domain: 'networking',
    skills: ['nw.vnet.troubleshoot'],
    concepts: ['network-watcher', 'connection-monitor'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'match',
    stem: 'Match each troubleshooting need to the Network Watcher capability that addresses it.',
    prompts: [
      { id: 'p1', text: 'Determine which NSG rule blocks a specific packet', answer: 'ipflow', why: 'IP flow verify returns the decision and rule name.' },
      { id: 'p2', text: 'Find out whether traffic to a destination is routed to an appliance', answer: 'nexthop', why: 'Next hop shows the next hop type and route table.' },
      { id: 'p3', text: 'Continuously measure latency and failures between two servers', answer: 'connmon', why: 'Connection monitor runs scheduled tests and records metrics.' },
      { id: 'p4', text: 'Capture actual packets on a VM for deep analysis', answer: 'capture', why: 'Packet capture records traffic using the Network Watcher extension.' },
    ],
    choices: [
      { id: 'ipflow', text: 'IP flow verify' },
      { id: 'nexthop', text: 'Next hop' },
      { id: 'connmon', text: 'Connection monitor' },
      { id: 'capture', text: 'Packet capture' },
      { id: 'topology', text: 'Topology' },
    ],
    explanation: {
      correct: 'Each Network Watcher tool answers one question: filtering (IP flow verify), routing (Next hop), continuous testing (Connection monitor), packet-level detail (Packet capture).',
      conceptTested: 'Selecting Network Watcher tools.',
      realWorld: 'Knowing the right tool turns a two-hour investigation into a two-minute check.',
    },
    sources: ['network-watcher', 'connection-monitor'],
  },
  {
    id: 'nw-troubleshoot-order',
    domain: 'networking',
    skills: ['nw.vnet.troubleshoot'],
    concepts: ['network-watcher', 'nsg', 'route-table'],
    kind: 'multi-step',
    difficulty: 2,
    format: 'order',
    stem: 'A VM can’t connect to a database server in a peered virtual network. Put the troubleshooting steps in the most efficient order.',
    items: [
      { id: '1', text: 'Confirm the destination name resolves to the expected IP address' },
      { id: '2', text: 'Check effective routes / Next hop for the destination prefix' },
      { id: '3', text: 'Run IP flow verify on the source and destination VMs' },
      { id: '4', text: 'Verify the database service is listening and the guest firewall allows the port' },
    ],
    why: 'Work along the path: resolve the name, check where the packet goes, check whether it’s allowed, then check the destination service.',
    explanation: {
      correct: 'A consistent order avoids random changes: DNS → routing → filtering → destination service.',
      conceptTested: 'A repeatable troubleshooting method.',
      realWorld: 'Documented order also makes handovers between teams far quicker.',
    },
    sources: ['network-watcher'],
  },
  {
    id: 'nw-service-endpoint-config',
    domain: 'networking',
    skills: ['nw.secure.service-endpoints'],
    concepts: ['service-endpoint', 'storage-firewall'],
    kind: 'configuration',
    difficulty: 2,
    format: 'order',
    stem: 'You must allow only VMs in subnet snet-app to reach a storage account over the Azure backbone, using service endpoints. Put the configuration steps in order.',
    items: [
      { id: '1', text: 'Enable the Microsoft.Storage service endpoint on snet-app' },
      { id: '2', text: 'Set the storage account firewall to allow selected networks only' },
      { id: '3', text: 'Add a virtual network rule for snet-app on the storage account' },
      { id: '4', text: 'Test access from a VM in snet-app and from an unauthorized network' },
    ],
    why: 'The subnet must carry the service endpoint before the service can trust it; then restrict the firewall and add the rule; always verify both allowed and denied paths.',
    explanation: {
      correct: 'Service endpoints are a two-sided configuration: the subnet enables the endpoint, and the service adds a virtual network rule.',
      conceptTested: 'Configuring service endpoints end to end.',
      realWorld: 'Testing the denied path is what proves the restriction actually works.',
    },
    sources: ['storage-firewall', 'vnet-faq'],
  },
];
