import type { Question } from '../schema';

export const STORAGE_QUESTIONS: Question[] = [
  {
    id: 'st-cli-storage-sku',
    domain: 'storage',
    skills: ['st.accounts.create', 'st.accounts.redundancy'],
    concepts: ['storage-account', 'storage-redundancy', 'azure-cli'],
    kind: 'configuration',
    difficulty: 1,
    format: 'single',
    stem: 'You run the following command:\n\n`az storage account create --name stlogs01 --resource-group rg-logs --location eastus --kind StorageV2 --sku Standard_RAGZRS`\n\nWhich statement describes the resulting account?',
    options: [
      { id: 'a', text: 'A general-purpose v2 account that replicates across availability zones in East US and asynchronously to the paired region, with read access to the secondary', correct: true, why: 'Standard_RAGZRS = Standard performance, GZRS redundancy with read access to the secondary.' },
      { id: 'b', text: 'A premium block blob account with three copies in one datacenter', why: 'Premium block blobs use kind BlockBlobStorage and support only LRS or ZRS.' },
      { id: 'c', text: 'A general-purpose v2 account with three copies in one datacenter and a readable secondary', why: 'That would be RA-GRS (LRS in the primary), not RA-GZRS.' },
      { id: 'd', text: 'A general-purpose v1 account with geo-redundancy', why: 'StorageV2 is general-purpose v2.' },
    ],
    explanation: {
      correct: 'The `--sku` value combines performance and redundancy. RAGZRS means zone-redundant in the primary region, geo-replicated to the paired region, with the secondary always readable.',
      conceptTested: 'Reading storage account SKUs in CLI commands.',
      realWorld: 'Reviewing infrastructure scripts means decoding these SKU names quickly.',
    },
    sources: ['storage-redundancy', 'storage-account-overview'],
  },
  {
    id: 'st-account-type',
    domain: 'storage',
    skills: ['st.accounts.create'],
    concepts: ['storage-account'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'You need a storage account that hosts blob containers, Azure file shares and queues, supports the archive tier, and uses geo-redundant storage. Which account type should you create?',
    options: [
      { id: 'a', text: 'Standard general-purpose v2', correct: true, why: 'GPv2 supports blobs, files, queues and tables, access tiers including archive, and GRS.' },
      { id: 'b', text: 'Premium block blobs', why: 'Blob only, LRS/ZRS only, and no access tiers.' },
      { id: 'c', text: 'Premium file shares', why: 'Azure Files only, LRS/ZRS only.' },
      { id: 'd', text: 'Premium page blobs', why: 'Page blobs only.' },
    ],
    explanation: {
      correct: 'Only Standard general-purpose v2 combines all data services, access tiers and geo-redundancy.',
      conceptTested: 'Storage account type capabilities.',
      realWorld: 'Most storage accounts in production are Standard GPv2; premium types are chosen for specific performance needs.',
    },
    sources: ['storage-account-overview'],
  },
  {
    id: 'st-account-name',
    domain: 'storage',
    skills: ['st.accounts.create'],
    concepts: ['storage-account'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'single',
    stem: 'Which name is valid for a new storage account?',
    options: [
      { id: 'a', text: 'contosodata2026', correct: true, why: 'Lowercase letters and numbers, 15 characters.' },
      { id: 'b', text: 'Contoso-Data', why: 'Uppercase letters and hyphens aren’t allowed.' },
      { id: 'c', text: 'st', why: 'Names must be at least 3 characters.' },
      { id: 'd', text: 'contoso_data_archive_storage', why: 'Underscores aren’t allowed and the name exceeds 24 characters.' },
    ],
    explanation: {
      correct: 'Storage account names must be 3–24 characters of lowercase letters and numbers, unique across Azure, because they form the endpoint hostname.',
      conceptTested: 'Storage account naming rules.',
      realWorld: 'Naming conventions often add a short random suffix to guarantee global uniqueness.',
    },
    sources: ['storage-account-overview'],
  },
  {
    id: 'st-redundancy-choice',
    domain: 'storage',
    skills: ['st.accounts.redundancy'],
    concepts: ['storage-redundancy'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'An application stores product images in a storage account in West Europe. Requirements: the images must remain available for read and write if an availability zone fails, and the application must be able to read images from another region during a regional outage without waiting for a failover. Costs should be minimized. Which redundancy option should you choose?',
    options: [
      { id: 'a', text: 'RA-GZRS', correct: true, why: 'Zone-redundant in the primary region plus a readable secondary in the paired region.' },
      { id: 'b', text: 'RA-GRS', why: 'The primary is LRS, so a zone failure can affect availability.' },
      { id: 'c', text: 'GZRS', why: 'The secondary is readable only after a failover.' },
      { id: 'd', text: 'ZRS', why: 'No copy in another region.' },
    ],
    explanation: {
      correct: 'Zone outage resilience requires ZRS in the primary; reading from the secondary without failover requires a read-access option. Only RA-GZRS satisfies both.',
      conceptTested: 'Selecting redundancy by failure scenario.',
      realWorld: 'Customer-facing read-heavy content often uses RA-GZRS so reads can fall back to the secondary endpoint.',
    },
    sources: ['storage-redundancy'],
  },
  {
    id: 'st-redundancy-archive',
    domain: 'storage',
    skills: ['st.accounts.redundancy', 'st.data.tiers'],
    concepts: ['storage-redundancy', 'access-tier'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'multi',
    stem: 'You plan to move blobs to the archive tier. Which two redundancy options support the archive tier? Each correct answer presents a complete solution.',
    options: [
      { id: 'a', text: 'LRS', correct: true, why: 'Archive is supported with LRS.' },
      { id: 'b', text: 'RA-GRS', correct: true, why: 'Archive is supported with GRS and RA-GRS.' },
      { id: 'c', text: 'ZRS', why: 'Archive isn’t supported on ZRS accounts.' },
      { id: 'd', text: 'GZRS', why: 'Archive isn’t supported on GZRS accounts.' },
    ],
    explanation: {
      correct: 'The archive tier is supported only for accounts using LRS, GRS or RA-GRS.',
      conceptTested: 'Feature compatibility between redundancy and access tiers.',
      realWorld: 'Compliance archives are commonly placed on GRS accounts separate from zone-redundant application storage.',
    },
    sources: ['storage-redundancy', 'access-tiers'],
  },
  {
    id: 'st-redundancy-not-backup',
    domain: 'storage',
    skills: ['st.accounts.redundancy', 'st.data.blob-soft-delete'],
    concepts: ['storage-redundancy', 'blob-soft-delete'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'A developer accidentally deletes 2,000 blobs in an RA-GZRS account. Blob soft delete and versioning are disabled. What can you recover from the secondary region?',
    options: [
      { id: 'a', text: 'Nothing — the deletions were replicated to all copies', correct: true, why: 'Redundancy replicates deletes; it isn’t a backup.' },
      { id: 'b', text: 'All blobs, by reading the secondary endpoint', why: 'The secondary receives the deletes too.' },
      { id: 'c', text: 'All blobs, by initiating a customer-managed failover', why: 'Failover makes the secondary primary, which already contains the deletes.' },
      { id: 'd', text: 'Only blobs in the archive tier', why: 'Archive isn’t supported on RA-GZRS, and deletes still replicate.' },
    ],
    explanation: {
      correct: 'Every replica applies deletes and overwrites. Soft delete, versioning or backups are required to recover from logical errors.',
      conceptTested: 'The difference between redundancy and data protection.',
      realWorld: 'Many teams discover this only after an incident — enable data protection alongside redundancy.',
    },
    sources: ['storage-redundancy', 'blob-soft-delete'],
  },
  {
    id: 'st-encryption-options',
    domain: 'storage',
    skills: ['st.accounts.encryption'],
    concepts: ['storage-encryption', 'key-vault'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about Azure Storage encryption, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'You can disable encryption at rest for a storage account to improve performance.', answer: false, why: 'Storage service encryption is always on and can’t be disabled.' },
      { id: 's2', text: 'Customer-managed keys for a storage account can be stored in Azure Key Vault.', answer: true, why: 'Customer-managed keys are stored in Key Vault or Key Vault Managed HSM.' },
      { id: 's3', text: 'You can enable infrastructure encryption on an existing storage account at any time.', answer: false, why: 'Infrastructure encryption must be enabled when the account is created.' },
    ],
    explanation: {
      correct: 'Encryption at rest is mandatory; you choose key management, and infrastructure (double) encryption is a creation-time decision.',
      conceptTested: 'Storage encryption options.',
      realWorld: 'Regulated workloads decide on customer-managed keys and double encryption before creating accounts.',
    },
    sources: ['storage-encryption'],
  },
  {
    id: 'st-azcopy-auth',
    domain: 'storage',
    skills: ['st.accounts.tools'],
    concepts: ['azcopy', 'role-assignment'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'You are the Owner of a subscription. You run `azcopy login`, then `azcopy copy ./reports https://stfin01.blob.core.windows.net/reports --recursive=true`, and receive an authorization error. What should you do?',
    options: [
      { id: 'a', text: 'Assign yourself the Storage Blob Data Contributor role on the storage account or container', correct: true, why: 'Entra authorization for blob data requires a data plane role.' },
      { id: 'b', text: 'Assign yourself the Contributor role on the storage account', why: 'Contributor is a control plane role with no blob DataActions.' },
      { id: 'c', text: 'Enable blob versioning', why: 'Versioning doesn’t affect authorization.' },
      { id: 'd', text: 'Change the account’s redundancy to LRS', why: 'Redundancy doesn’t affect authorization.' },
    ],
    explanation: {
      correct: 'Owner manages the account but doesn’t grant data access with Microsoft Entra ID. AzCopy with `azcopy login` needs Storage Blob Data Contributor (to write) or Reader (to read). Alternatively, use a SAS token.',
      conceptTested: 'AzCopy authorization.',
      realWorld: 'This is one of the most common AzCopy errors in new environments.',
    },
    sources: ['azcopy'],
  },
  {
    id: 'st-tools-choice',
    domain: 'storage',
    skills: ['st.accounts.tools'],
    concepts: ['azcopy', 'storage-explorer'],
    kind: 'scenario',
    difficulty: 1,
    format: 'match',
    stem: 'Match each task to the most appropriate tool.',
    prompts: [
      { id: 'p1', text: 'Nightly scripted copy of 2 TB of new files from an on-premises server to Blob Storage', answer: 'azcopy', why: 'AzCopy is designed for scripted, high-performance transfers.' },
      { id: 'p2', text: 'A support engineer browses a container and downloads one blob interactively on a Mac', answer: 'explorer', why: 'Storage Explorer is a cross-platform graphical tool.' },
      { id: 'p3', text: 'Copy a container from Amazon S3 into Azure Blob Storage', answer: 'azcopy', why: 'AzCopy supports copying from Amazon S3.' },
    ],
    choices: [
      { id: 'azcopy', text: 'AzCopy' },
      { id: 'explorer', text: 'Azure Storage Explorer' },
      { id: 'lifecycle', text: 'Lifecycle management' },
    ],
    explanation: {
      correct: 'AzCopy suits automation and large or cross-cloud transfers; Storage Explorer suits interactive work.',
      conceptTested: 'Choosing storage management tools.',
      realWorld: 'Teams often prototype a transfer in Storage Explorer, then automate it with AzCopy.',
    },
    sources: ['azcopy'],
  },
  {
    id: 'st-tier-rehydrate',
    domain: 'storage',
    skills: ['st.data.tiers'],
    concepts: ['access-tier'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'A legal team needs to read a blob that is in the archive tier. What must happen first?',
    options: [
      { id: 'a', text: 'Rehydrate the blob to an online tier (hot, cool or cold) by changing its tier or copying it', correct: true, why: 'Archived blobs are offline and must be rehydrated before reading.' },
      { id: 'b', text: 'Create a lifecycle rule that moves the blob back to hot', why: 'Lifecycle management can’t rehydrate archived blobs.' },
      { id: 'c', text: 'Generate a SAS token with read permission', why: 'A SAS doesn’t make offline data readable.' },
      { id: 'd', text: 'Enable blob versioning', why: 'Versioning doesn’t rehydrate blobs.' },
    ],
    explanation: {
      correct: 'Rehydration to an online tier can take up to 15 hours at Standard priority; High priority is faster for urgent requests.',
      conceptTested: 'Working with the archive tier.',
      realWorld: 'Archive retrieval times should be documented in legal and compliance procedures.',
    },
    sources: ['access-tiers'],
  },
  {
    id: 'st-tier-early-delete',
    domain: 'storage',
    skills: ['st.data.tiers'],
    concepts: ['access-tier'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'match',
    stem: 'Match each access tier to its minimum retention period before early deletion charges stop applying.',
    prompts: [
      { id: 'p1', text: 'Cool', answer: 'c30', why: 'Cool has a 30-day minimum.' },
      { id: 'p2', text: 'Cold', answer: 'c90', why: 'Cold has a 90-day minimum.' },
      { id: 'p3', text: 'Archive', answer: 'c180', why: 'Archive has a 180-day minimum.' },
    ],
    choices: [
      { id: 'none', text: 'No minimum' },
      { id: 'c30', text: '30 days' },
      { id: 'c90', text: '90 days' },
      { id: 'c180', text: '180 days' },
    ],
    explanation: {
      correct: 'Deleting, overwriting or moving a blob before the minimum period incurs a prorated early deletion charge. Hot has no minimum.',
      conceptTested: 'Access tier minimum retention.',
      realWorld: 'Lifecycle rules should respect these minimums to avoid paying twice.',
    },
    sources: ['access-tiers'],
  },
  {
    id: 'st-default-tier',
    domain: 'storage',
    skills: ['st.data.tiers', 'st.data.container'],
    concepts: ['access-tier', 'blob-storage'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'single',
    stem: 'Which value can you NOT set as the default access tier of a general-purpose v2 storage account?',
    options: [
      { id: 'a', text: 'Archive', correct: true, why: 'Archive can be set per blob but not as the account default.' },
      { id: 'b', text: 'Hot', why: 'Hot is a valid default (and the default for new GPv2 accounts).' },
      { id: 'c', text: 'Cool', why: 'Cool is a valid account default.' },
      { id: 'd', text: 'Cold', why: 'Cold is a valid account default.' },
    ],
    explanation: {
      correct: 'The account default tier applies to blobs without an explicit tier and can be hot, cool or cold.',
      conceptTested: 'Account-level access tier settings.',
      realWorld: 'Archive is always a deliberate per-blob or lifecycle decision because data becomes offline.',
    },
    sources: ['access-tiers'],
  },
  {
    id: 'st-soft-delete-container',
    domain: 'storage',
    skills: ['st.data.blob-soft-delete'],
    concepts: ['blob-soft-delete'],
    kind: 'scenario',
    difficulty: 2,
    format: 'yesno',
    stem: 'A storage account has blob soft delete enabled with 14 days retention. Container soft delete is disabled. Versioning is disabled. For each statement, select Yes if it is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'A blob deleted yesterday can be restored.', answer: true, why: 'Blob soft delete retains deleted blobs for 14 days.' },
      { id: 's2', text: 'A container deleted yesterday can be restored with all its blobs.', answer: false, why: 'Recovering a deleted container requires container soft delete.' },
      { id: 's3', text: 'If the storage account is deleted, its blobs can be restored with Undelete.', answer: false, why: 'Soft delete doesn’t protect against account deletion — use a resource lock.' },
    ],
    explanation: {
      correct: 'Blob soft delete, container soft delete and account protection are separate. Enable blob and container soft delete together and lock important accounts.',
      conceptTested: 'The scope of blob and container soft delete.',
      realWorld: 'Deleting the wrong container is a common scripting accident.',
    },
    sources: ['blob-soft-delete', 'container-soft-delete'],
  },
  {
    id: 'st-soft-delete-retention',
    domain: 'storage',
    skills: ['st.data.blob-soft-delete'],
    concepts: ['blob-soft-delete'],
    kind: 'knowledge',
    difficulty: 1,
    format: 'single',
    stem: 'What is the maximum retention period you can configure for blob soft delete?',
    options: [
      { id: 'a', text: '365 days', correct: true, why: 'Retention can be set from 1 to 365 days.' },
      { id: 'b', text: '30 days', why: 'Longer retention is supported.' },
      { id: 'c', text: '90 days', why: 'Longer retention is supported.' },
      { id: 'd', text: '7 years', why: 'The maximum is 365 days.' },
    ],
    explanation: {
      correct: 'Blob and container soft delete retention can both be set between 1 and 365 days.',
      conceptTested: 'Soft delete retention limits.',
      realWorld: 'Longer retention costs more because soft-deleted data is billed like active data.',
    },
    sources: ['blob-soft-delete', 'container-soft-delete'],
  },
  {
    id: 'st-versioning-restore',
    domain: 'storage',
    skills: ['st.data.versioning'],
    concepts: ['blob-versioning'],
    kind: 'first-step',
    difficulty: 2,
    format: 'single',
    stem: 'Blob versioning is enabled. An application overwrote config.json with invalid content an hour ago. How do you restore the previous content?',
    options: [
      { id: 'a', text: 'Copy the previous version of config.json over the current blob', correct: true, why: 'Promoting a previous version restores it as the current version.' },
      { id: 'b', text: 'Run Undelete on the blob', why: 'Undelete restores soft-deleted blobs; the blob wasn’t deleted.' },
      { id: 'c', text: 'Initiate a storage account failover', why: 'Failover doesn’t roll back overwrites.' },
      { id: 'd', text: 'Rehydrate the blob from archive', why: 'The blob isn’t archived.' },
    ],
    explanation: {
      correct: 'Each write creates a new version; the prior state remains as an immutable previous version that you can copy over the base blob.',
      conceptTested: 'Restoring blobs with versioning.',
      realWorld: 'Versioning is the fastest recovery path for application overwrites.',
    },
    sources: ['blob-versioning'],
  },
  {
    id: 'st-object-replication-prereq',
    domain: 'storage',
    skills: ['st.accounts.object-replication'],
    concepts: ['object-replication', 'blob-versioning'],
    kind: 'configuration',
    difficulty: 3,
    format: 'multi',
    stem: 'You plan to configure object replication from storage account STSRC to STDST. Which two settings are required? Each correct answer presents part of the solution.',
    options: [
      { id: 'a', text: 'Blob versioning enabled on both STSRC and STDST', correct: true, why: 'Versioning is required on source and destination.' },
      { id: 'b', text: 'Change feed enabled on STSRC', correct: true, why: 'The source uses change feed to track changes.' },
      { id: 'c', text: 'Hierarchical namespace enabled on both accounts', why: 'Object replication isn’t supported with hierarchical namespace.' },
      { id: 'd', text: 'GZRS redundancy on STDST', why: 'Redundancy isn’t a prerequisite.' },
      { id: 'e', text: 'Change feed enabled on STDST', why: 'Change feed is required on the source only.' },
    ],
    explanation: {
      correct: 'Object replication requires blob versioning on both accounts and change feed on the source account.',
      conceptTested: 'Object replication prerequisites.',
      realWorld: 'Missing change feed on the source is the most common setup failure.',
    },
    sources: ['object-replication'],
  },
  {
    id: 'st-object-replication-dest',
    domain: 'storage',
    skills: ['st.accounts.object-replication'],
    concepts: ['object-replication'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'After configuring object replication, an application writing to the destination container receives HTTP 409 Conflict errors. Why?',
    options: [
      { id: 'a', text: 'The destination container is read-only while the replication policy is active', correct: true, why: 'Writes to a replication destination container are rejected.' },
      { id: 'b', text: 'Versioning was disabled on the source', why: 'Versioning can’t be disabled while policies exist, and it wouldn’t cause 409 on the destination.' },
      { id: 'c', text: 'The SAS token has expired', why: 'An expired SAS returns 403, not 409.' },
      { id: 'd', text: 'The destination account uses LRS', why: 'Redundancy doesn’t block writes.' },
    ],
    explanation: {
      correct: 'Object replication makes destination containers read-only (reads and deletes are allowed) to keep them consistent with the source.',
      conceptTested: 'Behavior of object replication destinations.',
      realWorld: 'Use a different container for writes in the destination region.',
    },
    sources: ['object-replication'],
  },
  {
    id: 'st-lifecycle-json',
    domain: 'storage',
    skills: ['st.data.lifecycle'],
    concepts: ['lifecycle-management', 'access-tier'],
    kind: 'configuration',
    difficulty: 3,
    format: 'yesno',
    stem: 'Review the lifecycle management rule in the exhibit. For each statement, select Yes if the statement is true. Otherwise, select No.',
    exhibit: {
      title: 'Lifecycle rule',
      kind: 'code',
      lang: 'json',
      code: `{
  "enabled": true, "name": "logs", "type": "Lifecycle",
  "definition": {
    "filters": { "blobTypes": ["blockBlob"], "prefixMatch": ["applogs/web"] },
    "actions": {
      "baseBlob": {
        "tierToCool": { "daysAfterModificationGreaterThan": 30 },
        "delete": { "daysAfterModificationGreaterThan": 365 }
      }
    }
  }
}`,
    },
    statements: [
      { id: 's1', text: 'A blob in container applogs under the path web/ that was last modified 45 days ago is in the cool tier (once the policy has run).', answer: true, why: 'It matches the prefix and is older than 30 days.' },
      { id: 's2', text: 'Blobs in container backups older than 365 days are deleted.', answer: false, why: 'The prefix filter limits the rule to container applogs, path web.' },
      { id: 's3', text: 'The rule takes effect within five minutes of being saved.', answer: false, why: 'Policy changes can take up to 24 hours to take effect.' },
    ],
    explanation: {
      correct: 'Filters restrict the rule to block blobs whose names match `applogs/web`; actions tier after 30 days and delete after 365 days, with up to 24 hours before a new policy runs.',
      conceptTested: 'Interpreting lifecycle management rules.',
      realWorld: 'Log retention policies are one of the simplest, highest-value cost optimizations.',
    },
    sources: ['lifecycle'],
  },
  {
    id: 'st-files-port',
    domain: 'storage',
    skills: ['st.data.file-share'],
    concepts: ['azure-files'],
    kind: 'troubleshooting',
    difficulty: 2,
    format: 'single',
    stem: 'Users at a branch office can’t map an Azure file share. Users at head office, which connects to Azure through a site-to-site VPN, can map it. What should you check first at the branch office?',
    options: [
      { id: 'a', text: 'Whether outbound TCP port 445 is allowed from the branch network', correct: true, why: 'SMB uses TCP 445, which ISPs and firewalls often block.' },
      { id: 'b', text: 'Whether the storage account uses customer-managed keys', why: 'Encryption keys don’t affect mounting from one site but not another.' },
      { id: 'c', text: 'Whether blob versioning is enabled', why: 'Blob features don’t affect Azure Files.' },
      { id: 'd', text: 'Whether the share uses NFS', why: 'Head office can mount it, so the protocol works.' },
    ],
    explanation: {
      correct: 'Azure Files SMB access uses TCP 445. Test with `Test-NetConnection <account>.file.core.windows.net -Port 445`; if blocked, route over VPN/ExpressRoute with a private endpoint.',
      conceptTested: 'Azure Files connectivity requirements.',
      realWorld: 'Blocked port 445 is the leading cause of Azure Files mount failures.',
    },
    sources: ['files-planning'],
  },
  {
    id: 'st-files-recover',
    domain: 'storage',
    skills: ['st.data.files-snapshots', 'st.data.file-share'],
    concepts: ['share-snapshot', 'azure-files'],
    kind: 'discrimination',
    difficulty: 2,
    format: 'match',
    stem: 'Match each Azure Files recovery need to the feature that meets it.',
    prompts: [
      { id: 'p1', text: 'Restore a spreadsheet that a user overwrote this morning', answer: 'snap', why: 'Share snapshots hold read-only, point-in-time copies of files.' },
      { id: 'p2', text: 'Recover an entire file share that an administrator deleted', answer: 'softdel', why: 'Share soft delete retains deleted shares for the retention period.' },
      { id: 'p3', text: 'Keep daily, weekly, monthly and yearly restore points managed centrally', answer: 'backup', why: 'Azure Backup schedules and retains share snapshots with GFS retention.' },
    ],
    choices: [
      { id: 'snap', text: 'Share snapshot' },
      { id: 'softdel', text: 'Share soft delete' },
      { id: 'backup', text: 'Azure Backup' },
      { id: 'versioning', text: 'Blob versioning' },
    ],
    explanation: {
      correct: 'Snapshots recover files; soft delete recovers whole shares; Azure Backup manages scheduled, retained snapshots.',
      conceptTested: 'Azure Files data protection options.',
      realWorld: 'Most organizations enable share soft delete and Azure Backup together for file shares.',
    },
    sources: ['files-snapshots', 'files-soft-delete'],
  },
  {
    id: 'st-files-snapshot-limits',
    domain: 'storage',
    skills: ['st.data.files-snapshots'],
    concepts: ['share-snapshot'],
    kind: 'knowledge',
    difficulty: 2,
    format: 'yesno',
    stem: 'For each statement about Azure Files share snapshots, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'You can keep up to 200 snapshots per share.', answer: true, why: 'The limit is 200 snapshots per share.' },
      { id: 's2', text: 'Deleting a file share keeps its snapshots.', answer: false, why: 'Deleting a share deletes its snapshots.' },
      { id: 's3', text: 'Share snapshots are incremental.', answer: true, why: 'Only changed data since the previous snapshot is stored.' },
    ],
    explanation: {
      correct: 'Share snapshots are read-only, incremental, limited to 200 per share, retained up to 10 years, and removed with the share.',
      conceptTested: 'Share snapshot behavior.',
      realWorld: 'Enable share soft delete so a deleted share (and its snapshots) can be recovered.',
    },
    sources: ['files-snapshots'],
  },
  {
    id: 'st-files-roles',
    domain: 'storage',
    skills: ['st.access.files-identity'],
    concepts: ['files-identity-auth'],
    kind: 'scenario',
    difficulty: 2,
    format: 'single',
    stem: 'An Azure file share uses AD DS authentication. Department heads must read and write files and also change NTFS permissions on folders. Which share-level role should you assign?',
    options: [
      { id: 'a', text: 'Storage File Data SMB Share Elevated Contributor', correct: true, why: 'Elevated Contributor adds the ability to modify Windows ACLs.' },
      { id: 'b', text: 'Storage File Data SMB Share Contributor', why: 'Contributor can read, write and delete but not change ACLs.' },
      { id: 'c', text: 'Storage Account Contributor', why: 'A control plane role that doesn’t grant SMB share access.' },
      { id: 'd', text: 'Storage Blob Data Owner', why: 'A Blob Storage role.' },
    ],
    explanation: {
      correct: 'Share-level roles control what identities can do over SMB. Elevated Contributor includes permission to modify ACLs; NTFS ACLs then control folder-level access.',
      conceptTested: 'Share-level permissions for identity-based access.',
      realWorld: 'Delegating ACL management to data owners reduces IT tickets for folder access.',
    },
    sources: ['files-share-permissions'],
  },
  {
    id: 'st-files-identity-source',
    domain: 'storage',
    skills: ['st.access.files-identity'],
    concepts: ['files-identity-auth', 'entra-id'],
    kind: 'architecture',
    difficulty: 3,
    format: 'single',
    stem: 'A company has only cloud-only user accounts in Microsoft Entra ID, no domain controllers, and Microsoft Entra joined Windows devices. Users must access an Azure file share with their own identities and NTFS permissions. Which identity source should you enable?',
    options: [
      { id: 'a', text: 'Microsoft Entra Kerberos', correct: true, why: 'It supports cloud-only identities on Entra joined devices without domain controllers.' },
      { id: 'b', text: 'On-premises AD DS', why: 'Requires AD DS and hybrid identities.' },
      { id: 'c', text: 'Storage account key', why: 'Not identity-based and grants full access.' },
      { id: 'd', text: 'NFS host-based authentication', why: 'NFS doesn’t support identity-based authentication and is Linux-only.' },
    ],
    explanation: {
      correct: 'Microsoft Entra Kerberos issues Kerberos tickets for Azure Files to hybrid or cloud-only identities on Entra joined or hybrid joined clients, without line of sight to domain controllers.',
      conceptTested: 'Choosing an Azure Files identity source.',
      realWorld: 'Cloud-first organizations use Entra Kerberos for file shares and FSLogix profiles.',
    },
    sources: ['files-identity', 'files-planning'],
  },
  {
    id: 'st-sas-revoke',
    domain: 'storage',
    skills: ['st.access.policies', 'st.access.sas'],
    concepts: ['stored-access-policy', 'sas'],
    kind: 'scenario',
    difficulty: 3,
    format: 'single',
    stem: 'You issue several shared access signatures to a partner for container exports. You must be able to revoke only the partner’s access at any time without affecting other applications that use the storage account keys. What should you do when creating the tokens?',
    options: [
      { id: 'a', text: 'Create a stored access policy on the exports container and generate service SAS tokens linked to it', correct: true, why: 'Deleting or changing the policy revokes all linked service SAS tokens.' },
      { id: 'b', text: 'Generate account SAS tokens and regenerate key1 when access must be revoked', why: 'Regenerating the key breaks other applications using it.' },
      { id: 'c', text: 'Generate ad hoc service SAS tokens with a one-year expiry', why: 'Ad hoc tokens can’t be revoked individually.' },
      { id: 'd', text: 'Create a stored access policy and link account SAS tokens to it', why: 'Stored access policies work only with service SAS.' },
    ],
    explanation: {
      correct: 'Stored access policies give server-side control over service SAS tokens: delete the policy, rename its identifier, or set its expiry in the past to revoke.',
      conceptTested: 'Revocable SAS with stored access policies.',
      realWorld: 'Partner integrations should always have a revocation plan that doesn’t require key rotation.',
      trap: 'Stored access policies can’t be used with account SAS or user delegation SAS.',
    },
    sources: ['stored-access-policy', 'sas-overview'],
  },
  {
    id: 'st-sas-types',
    domain: 'storage',
    skills: ['st.access.sas', 'st.access.keys'],
    concepts: ['sas', 'access-keys'],
    kind: 'discrimination',
    difficulty: 3,
    format: 'yesno',
    stem: 'For each statement about shared access signatures, select Yes if the statement is true. Otherwise, select No.',
    statements: [
      { id: 's1', text: 'Regenerating the storage account key that signed an account SAS invalidates that SAS.', answer: true, why: 'Account and service SAS are signed with an account key.' },
      { id: 's2', text: 'Regenerating the storage account keys invalidates user delegation SAS tokens.', answer: false, why: 'User delegation SAS uses a key obtained through Microsoft Entra ID, not the account keys.' },
      { id: 's3', text: 'A SAS with a valid signature can bypass the storage account firewall.', answer: false, why: 'Network rules still apply to SAS requests.' },
    ],
    explanation: {
      correct: 'Know what each SAS is signed with — that determines how it’s revoked — and remember network rules apply regardless of the credential.',
      conceptTested: 'SAS types, revocation and network rules.',
      realWorld: 'Incident response for leaked tokens depends on knowing which revocation step actually works.',
    },
    sources: ['sas-overview', 'access-keys', 'storage-firewall'],
  },
  {
    id: 'st-key-rotation',
    domain: 'storage',
    skills: ['st.access.keys'],
    concepts: ['access-keys'],
    kind: 'multi-step',
    difficulty: 2,
    format: 'order',
    stem: 'Applications use key1 of a storage account. You must rotate both keys without application downtime. Put the steps in order.',
    items: [
      { id: '1', text: 'Update applications to use key2' },
      { id: '2', text: 'Regenerate key1' },
      { id: '3', text: 'Update applications to use the new key1' },
      { id: '4', text: 'Regenerate key2' },
    ],
    why: 'Always move applications off a key before regenerating it; the two keys exist to allow this.',
    explanation: {
      correct: 'The recommended rotation moves clients to the secondary key, regenerates the primary, moves clients back, then regenerates the secondary.',
      conceptTested: 'Manual access key rotation.',
      realWorld: 'Storing keys in Key Vault makes this a configuration change rather than a redeployment.',
    },
    sources: ['access-keys'],
  },
  {
    id: 'st-firewall-ip-rule',
    domain: 'storage',
    skills: ['st.access.firewall'],
    concepts: ['storage-firewall', 'service-endpoint'],
    kind: 'troubleshooting',
    difficulty: 3,
    format: 'single',
    stem: 'A storage account firewall allows the IP range 10.20.1.0/24, which is the address range of subnet snet-app where the application VMs run. The VMs still receive 403 errors. What should you do?',
    options: [
      { id: 'a', text: 'Enable a Microsoft.Storage service endpoint on snet-app and add a virtual network rule for the subnet', correct: true, why: 'Private ranges can’t be used in IP rules; subnets are allowed with virtual network rules.' },
      { id: 'b', text: 'Change the IP rule to 10.20.0.0/16', why: 'Private addresses aren’t valid in IP rules regardless of range size.' },
      { id: 'c', text: 'Regenerate the storage account keys', why: 'The requests are blocked by network rules, not authorization.' },
      { id: 'd', text: 'Enable blob soft delete', why: 'Data protection doesn’t affect network access.' },
    ],
    explanation: {
      correct: 'IP network rules accept public IP addresses only. Traffic from Azure subnets is allowed through virtual network rules (with a service endpoint) or through a private endpoint.',
      conceptTested: 'Storage firewall rule types.',
      realWorld: 'This misconfiguration is common when teams translate on-premises firewall habits to Azure.',
    },
    sources: ['storage-firewall'],
  },
  {
    id: 'st-firewall-service-endpoint',
    domain: 'storage',
    skills: ['st.access.firewall'],
    concepts: ['storage-firewall', 'private-endpoint', 'service-endpoint'],
    kind: 'architecture',
    difficulty: 3,
    format: 'single',
    stem: 'On-premises servers connected to Azure over ExpressRoute private peering must access a storage account over a private IP address. Public network access to the account must be disabled. What should you implement?',
    options: [
      { id: 'a', text: 'A private endpoint for the storage account with private DNS resolution available to on-premises clients', correct: true, why: 'A private endpoint provides a private IP reachable over private connectivity and works with public access disabled.' },
      { id: 'b', text: 'A Microsoft.Storage service endpoint on the GatewaySubnet', why: 'Service endpoints don’t give on-premises clients a private IP and keep using the public endpoint.' },
      { id: 'c', text: 'An IP network rule for the on-premises private address range', why: 'IP rules accept only public addresses, and public access must be disabled.' },
      { id: 'd', text: 'A stored access policy', why: 'Authorization, not network connectivity.' },
    ],
    explanation: {
      correct: 'Private endpoints map the storage account into a VNet with a private IP. On-premises clients reach it over VPN or ExpressRoute and resolve the privatelink name through DNS forwarding.',
      conceptTested: 'Private endpoints vs service endpoints for storage.',
      realWorld: 'Regulated organizations disable public access on storage and rely on private endpoints end to end.',
    },
    sources: ['storage-firewall', 'private-endpoint-dns'],
  },
  {
    id: 'st-container-access',
    domain: 'storage',
    skills: ['st.data.container', 'st.access.firewall'],
    concepts: ['blob-storage', 'storage-account'],
    kind: 'configuration',
    difficulty: 2,
    format: 'single',
    stem: 'Security policy requires that no container in a storage account can ever be configured for anonymous (public) read access, even by account administrators. What should you configure?',
    options: [
      { id: 'a', text: 'Disable “Allow enabling anonymous access on individual containers” on the storage account', correct: true, why: 'The account setting prevents any container from allowing anonymous access.' },
      { id: 'b', text: 'Set every container’s access level to Private', why: 'Administrators could still change a container later.' },
      { id: 'c', text: 'Enable blob versioning', why: 'Versioning doesn’t control anonymous access.' },
      { id: 'd', text: 'Create a stored access policy on each container', why: 'Stored access policies govern SAS tokens, not anonymous access.' },
    ],
    explanation: {
      correct: 'Disabling anonymous access at the account level overrides container access levels. Azure Policy can enforce the setting across accounts.',
      conceptTested: 'Controlling anonymous access to containers.',
      realWorld: 'Accidentally public containers are a frequent source of data exposure.',
    },
    sources: ['storage-account-overview'],
  },
];
