import type { LessonMeta, Module } from './schema';

/**
 * The learning path. Ordered for understanding (foundations → identity →
 * governance → storage → networking → compute → monitoring → recovery), not in
 * the order of the official outline. Lesson bodies live in ./lessons and load on
 * demand; this file stays small so navigation and search are instant.
 */
export const MODULES: Module[] = [
  {
    id: 'foundations',
    number: 1,
    title: 'Azure foundations',
    tagline: 'Build the mental model everything else hangs on.',
    summary:
      'How Azure is organized from tenant to resource, where your resources physically run, and how every request flows through Azure Resource Manager.',
    area: 'foundations',
    domains: ['identity-governance'],
    icon: 'cloud',
    mentalModel:
      'Azure is a hierarchy of containers (tenant → management groups → subscriptions → resource groups → resources) sitting on top of a global footprint (regions and zones). Every management action is an authenticated request to Azure Resource Manager, which checks identity, permissions and policy before a resource provider does the work.',
    outcomes: [
      'Explain the Azure resource hierarchy and why each level exists',
      'Choose regions and availability zones for resilience',
      'Describe how Azure Resource Manager processes requests',
      'Use the portal, Cloud Shell, Azure CLI and PowerShell interchangeably',
    ],
    chapters: [
      {
        id: 'shape-of-azure',
        title: 'The shape of Azure',
        lessons: [
          {
            id: 'azure-hierarchy',
            title: 'How Azure is organized: from tenant to resource',
            summary: 'The five levels of the Azure hierarchy and how access, policy and billing flow through them.',
            minutes: 18,
            level: 1,
            tier: 'must',
            skills: ['ig.gov.mg', 'ig.gov.subscriptions', 'ig.gov.rg'],
            concepts: ['entra-tenant', 'management-group', 'subscription', 'resource-group', 'azure-resource'],
            keywords: ['hierarchy', 'scope', 'inheritance', 'billing boundary'],
          },
          {
            id: 'regions-zones',
            title: 'Regions, availability zones and region pairs',
            summary: 'Where Azure resources physically run and how that shapes availability and disaster recovery.',
            minutes: 14,
            level: 1,
            tier: 'must',
            skills: ['cp.vm.availability', 'st.accounts.redundancy'],
            concepts: ['region', 'availability-zone', 'paired-region'],
            keywords: ['datacenter', 'zone-redundant', 'zonal', 'geography'],
          },
          {
            id: 'resource-manager',
            title: 'Azure Resource Manager: the control plane',
            summary: 'How every portal click, CLI command and template becomes an authorized ARM request.',
            minutes: 16,
            level: 2,
            tier: 'must',
            skills: ['cp.iac.deploy', 'ig.access.interpret'],
            concepts: ['azure-resource-manager', 'resource-provider', 'control-plane-data-plane', 'resource-id'],
            keywords: ['management.azure.com', 'resource provider registration', 'data plane'],
          },
        ],
      },
      {
        id: 'toolkit',
        title: 'Your toolkit',
        lessons: [
          {
            id: 'admin-toolkit',
            title: "The administrator's toolkit: portal, Cloud Shell, CLI and PowerShell",
            summary: 'When to click, when to script, and how the tools map to the same ARM operations.',
            minutes: 14,
            level: 2,
            tier: 'should',
            skills: ['cp.iac.deploy'],
            concepts: ['azure-portal', 'cloud-shell', 'azure-cli', 'azure-powershell'],
            keywords: ['az', 'Az module', 'bash', 'automation'],
          },
        ],
      },
    ],
  },
  {
    id: 'identity',
    number: 2,
    title: 'Identity & access',
    tagline: 'Who are you, what can you do, and where can you do it?',
    summary:
      'Microsoft Entra ID users, groups, licenses, guests and password reset — then Azure RBAC, the system that decides what identities can do with Azure resources.',
    area: 'identity-governance',
    domains: ['identity-governance'],
    icon: 'identity',
    mentalModel:
      'Authentication (Microsoft Entra ID) proves who you are. Authorization (Azure RBAC for Azure resources, Microsoft Entra roles for the directory) decides what you may do. An Azure role assignment always answers three questions at once: which security principal, which role definition, at which scope.',
    outcomes: [
      'Create and manage users, groups and dynamic membership',
      'Assign licenses at scale with group-based licensing',
      'Control guest access and configure self-service password reset',
      'Assign and interpret Azure roles at the right scope',
      'Use managed identities instead of stored credentials',
    ],
    chapters: [
      {
        id: 'entra',
        title: 'Microsoft Entra ID',
        lessons: [
          {
            id: 'entra-users-groups',
            title: 'Users and groups in Microsoft Entra ID',
            summary: 'Member and guest users, security and Microsoft 365 groups, assigned and dynamic membership.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['ig.entra.create', 'ig.entra.properties'],
            concepts: ['entra-id', 'entra-user', 'entra-group', 'dynamic-group'],
            keywords: ['membership rule', 'user.department', 'bulk create', 'usage location'],
          },
          {
            id: 'entra-licenses',
            title: 'Licenses and group-based licensing',
            summary: 'Assign product licenses to groups so access follows membership automatically.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['ig.entra.licenses'],
            concepts: ['group-based-licensing', 'entra-group'],
            keywords: ['usage location', 'license errors', 'nested groups'],
          },
          {
            id: 'entra-external-users',
            title: 'External users and B2B collaboration',
            summary: 'Invite guests, control what they can see, and restrict who can invite whom.',
            minutes: 14,
            level: 2,
            tier: 'must',
            skills: ['ig.entra.external'],
            concepts: ['b2b-collaboration', 'guest-user'],
            keywords: ['Guest Inviter', 'collaboration restrictions', 'cross-tenant access'],
          },
          {
            id: 'entra-sspr',
            title: 'Self-service password reset (SSPR)',
            summary: 'Let users reset their own passwords securely — and understand the licensing and writeback rules.',
            minutes: 14,
            level: 2,
            tier: 'must',
            skills: ['ig.entra.sspr'],
            concepts: ['sspr'],
            keywords: ['authentication methods', 'writeback', 'registration', 'number of methods'],
          },
        ],
      },
      {
        id: 'rbac',
        title: 'Azure role-based access control',
        lessons: [
          {
            id: 'rbac-fundamentals',
            title: 'Azure RBAC: security principal, role and scope',
            summary: 'The anatomy of a role assignment, the fundamental built-in roles, and how scope works.',
            minutes: 22,
            level: 3,
            tier: 'must',
            skills: ['ig.access.builtin', 'ig.access.scopes'],
            concepts: ['azure-rbac', 'role-assignment', 'role-definition', 'rbac-scope', 'entra-roles'],
            keywords: ['Owner', 'Contributor', 'Reader', 'User Access Administrator', 'IAM'],
          },
          {
            id: 'rbac-interpret',
            title: 'Interpreting access: inheritance, additive roles and custom roles',
            summary: 'Work out exactly what someone can do by following assignments down the hierarchy.',
            minutes: 18,
            level: 4,
            tier: 'must',
            skills: ['ig.access.interpret', 'ig.access.scopes'],
            concepts: ['azure-rbac', 'role-assignment', 'custom-role', 'rbac-scope'],
            keywords: ['NotActions', 'DataActions', 'deny assignment', 'check access', 'AssignableScopes'],
          },
          {
            id: 'managed-identities',
            title: 'Managed identities and service principals',
            summary: 'Give Azure resources an identity so they can reach other services without secrets.',
            minutes: 14,
            level: 3,
            tier: 'should',
            skills: ['ig.access.scopes'],
            concepts: ['managed-identity', 'service-principal'],
            keywords: ['system-assigned', 'user-assigned', 'no credentials'],
          },
        ],
      },
    ],
  },
  {
    id: 'governance',
    number: 3,
    title: 'Governance & cost',
    tagline: 'Guardrails that keep a growing estate consistent, compliant and affordable.',
    summary:
      'Organize subscriptions with management groups, enforce standards with Azure Policy, label resources with tags, prevent accidents with locks, and keep spend visible with budgets and Advisor.',
    area: 'identity-governance',
    domains: ['identity-governance'],
    icon: 'policy',
    mentalModel:
      'RBAC controls what people can do. Azure Policy controls what resources may look like, regardless of who creates them. Tags describe resources, and locks protect them from everyone — even Owners. All of them flow down the hierarchy from the scope where you apply them.',
    outcomes: [
      'Design a management group and subscription structure',
      'Manage resource groups and move resources safely',
      'Implement Azure Policy with the right effects and exemptions',
      'Apply tags, locks, budgets and Advisor recommendations',
    ],
    chapters: [
      {
        id: 'organize',
        title: 'Organizing the estate',
        lessons: [
          {
            id: 'management-groups-subscriptions',
            title: 'Management groups and subscriptions',
            summary: 'Group subscriptions so access and policy apply once and inherit everywhere.',
            minutes: 18,
            level: 2,
            tier: 'must',
            skills: ['ig.gov.mg', 'ig.gov.subscriptions'],
            concepts: ['management-group', 'subscription'],
            keywords: ['Tenant root group', 'six levels', 'move subscription'],
          },
          {
            id: 'resource-groups',
            title: 'Resource groups and moving resources',
            summary: 'Lifecycle containers for resources, and what really happens when you move them.',
            minutes: 14,
            level: 2,
            tier: 'must',
            skills: ['ig.gov.rg', 'cp.vm.move'],
            concepts: ['resource-group', 'resource-move'],
            keywords: ['validateMoveResources', 'dependent resources', 'resource ID changes'],
          },
        ],
      },
      {
        id: 'guardrails',
        title: 'Guardrails',
        lessons: [
          {
            id: 'azure-policy',
            title: 'Azure Policy: definitions, initiatives, effects and exemptions',
            summary: 'Enforce organizational standards and measure compliance at scale.',
            minutes: 24,
            level: 3,
            tier: 'must',
            skills: ['ig.gov.policy'],
            concepts: ['azure-policy', 'policy-initiative', 'policy-effect', 'policy-exemption'],
            keywords: ['deny', 'audit', 'modify', 'deployIfNotExists', 'remediation', 'compliance'],
          },
          {
            id: 'tags',
            title: 'Tags for organization and cost reporting',
            summary: 'Name-value metadata that powers cost allocation and automation — and why it does not inherit.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['ig.gov.tags'],
            concepts: ['tags'],
            keywords: ['tag inheritance', 'Tag Contributor', 'cost center'],
          },
          {
            id: 'resource-locks',
            title: 'Resource locks',
            summary: 'Delete and read-only locks, inheritance, and the surprising things a read-only lock blocks.',
            minutes: 12,
            level: 4,
            tier: 'must',
            skills: ['ig.gov.locks'],
            concepts: ['resource-lock'],
            keywords: ['CanNotDelete', 'ReadOnly', 'control plane'],
          },
        ],
      },
      {
        id: 'cost-strategy',
        title: 'Cost and strategy',
        lessons: [
          {
            id: 'cost-management',
            title: 'Budgets, cost alerts and Azure Advisor',
            summary: 'Make spend visible, get warned early, and act on optimization recommendations.',
            minutes: 14,
            level: 2,
            tier: 'must',
            skills: ['ig.gov.costs'],
            concepts: ['budget', 'azure-advisor'],
            keywords: ['forecasted alert', 'action group', 'cost analysis'],
          },
          {
            id: 'governance-strategy',
            title: 'Designing a governance strategy',
            summary: 'Combine RBAC, Policy, tags and locks across the hierarchy for a real organization.',
            minutes: 16,
            level: 5,
            tier: 'should',
            skills: ['ig.gov.mg', 'ig.gov.policy', 'ig.gov.tags', 'ig.gov.locks', 'ig.access.scopes'],
            concepts: ['management-group', 'azure-policy', 'azure-rbac', 'tags', 'resource-lock'],
            keywords: ['landing zone', 'least privilege', 'guardrails'],
          },
        ],
      },
    ],
  },
  {
    id: 'storage',
    number: 4,
    title: 'Storage',
    tagline: 'Durable, secure data — and the right trade-offs for each workload.',
    summary:
      'Storage accounts, redundancy, Blob Storage tiers and data protection, Azure Files, and every way to control access to data.',
    area: 'storage',
    domains: ['storage'],
    icon: 'storage',
    mentalModel:
      'A storage account is a namespace with one set of account-wide decisions (performance, redundancy, networking, encryption) that hosts up to four data services. Inside it, data protection features (soft delete, versioning, snapshots) protect against mistakes, redundancy protects against hardware and site failures, and access is layered: network rules decide who can reach the endpoint, then keys, SAS or Microsoft Entra ID decide who can use the data.',
    outcomes: [
      'Create storage accounts with the right type and redundancy',
      'Choose access tiers and automate them with lifecycle management',
      'Protect data with soft delete, versioning, snapshots and replication',
      'Configure Azure Files including identity-based access',
      'Secure access with network rules, keys, SAS and stored access policies',
    ],
    chapters: [
      {
        id: 'accounts',
        title: 'Storage accounts',
        lessons: [
          {
            id: 'storage-accounts',
            title: 'Storage accounts and the four data services',
            summary: 'Account types, performance tiers, endpoints, and when to use blobs, files, queues or tables.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['st.accounts.create'],
            concepts: ['storage-account', 'blob-storage', 'azure-files', 'queue-storage', 'table-storage'],
            keywords: ['general-purpose v2', 'premium block blobs', 'account name rules', 'endpoints'],
          },
          {
            id: 'storage-redundancy',
            title: 'Redundancy: LRS, ZRS, GRS, GZRS and read access',
            summary: 'How many copies, where they live, and what each option survives.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['st.accounts.redundancy'],
            concepts: ['storage-redundancy', 'paired-region'],
            keywords: ['RA-GRS', 'RA-GZRS', 'failover', 'secondary endpoint', 'durability'],
          },
          {
            id: 'storage-encryption',
            title: 'Storage account encryption',
            summary: 'Always-on encryption, customer-managed keys, infrastructure encryption and encryption scopes.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['st.accounts.encryption'],
            concepts: ['storage-encryption', 'key-vault'],
            keywords: ['Microsoft-managed keys', 'customer-managed keys', 'double encryption'],
          },
          {
            id: 'storage-tools',
            title: 'Managing data with Storage Explorer and AzCopy',
            summary: 'Move data interactively or at scale, with the right authorization.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['st.accounts.tools'],
            concepts: ['azcopy', 'storage-explorer'],
            keywords: ['azcopy copy', 'azcopy sync', 'azcopy login'],
          },
        ],
      },
      {
        id: 'blobs',
        title: 'Blob Storage',
        lessons: [
          {
            id: 'blob-containers-tiers',
            title: 'Blob containers and access tiers',
            summary: 'Hot, cool, cold and archive — and the early deletion and rehydration rules that catch people out.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['st.data.container', 'st.data.tiers'],
            concepts: ['blob-storage', 'access-tier'],
            keywords: ['rehydration', 'early deletion', 'default access tier', 'anonymous access'],
          },
          {
            id: 'blob-data-protection',
            title: 'Protecting blobs: soft delete and versioning',
            summary: 'Recover from accidental deletes and overwrites — and know what each feature does not protect.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['st.data.blob-soft-delete', 'st.data.versioning'],
            concepts: ['blob-soft-delete', 'blob-versioning'],
            keywords: ['Undelete Blob', 'container soft delete', 'previous version', 'retention'],
          },
          {
            id: 'blob-lifecycle-replication',
            title: 'Lifecycle management and object replication',
            summary: 'Automate tiering and deletion, and copy blobs asynchronously to another account.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['st.data.lifecycle', 'st.accounts.object-replication'],
            concepts: ['lifecycle-management', 'object-replication'],
            keywords: ['tierToCool', 'daysAfterModificationGreaterThan', 'change feed', 'replication policy'],
          },
        ],
      },
      {
        id: 'files',
        title: 'Azure Files',
        lessons: [
          {
            id: 'azure-files',
            title: 'Azure Files: shares, snapshots and soft delete',
            summary: 'Managed SMB and NFS file shares, and how to recover files and whole shares.',
            minutes: 18,
            level: 2,
            tier: 'must',
            skills: ['st.data.file-share', 'st.data.files-snapshots'],
            concepts: ['azure-files', 'share-snapshot'],
            keywords: ['SMB', 'NFS', 'port 445', 'provisioned v2', 'previous versions'],
          },
          {
            id: 'files-identity',
            title: 'Identity-based access for Azure Files',
            summary: 'Replace storage keys with AD DS, Microsoft Entra Domain Services or Microsoft Entra Kerberos.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['st.access.files-identity'],
            concepts: ['files-identity-auth'],
            keywords: ['share-level permissions', 'Windows ACLs', 'Kerberos', 'default share-level permission'],
          },
        ],
      },
      {
        id: 'storage-access',
        title: 'Securing access to storage',
        lessons: [
          {
            id: 'storage-keys-sas',
            title: 'Access keys, SAS tokens and stored access policies',
            summary: 'Delegate exactly the access needed, for exactly as long as needed — and revoke it when needed.',
            minutes: 22,
            level: 3,
            tier: 'must',
            skills: ['st.access.keys', 'st.access.sas', 'st.access.policies'],
            concepts: ['access-keys', 'sas', 'stored-access-policy'],
            keywords: ['user delegation SAS', 'service SAS', 'account SAS', 'key rotation', 'revoke'],
          },
          {
            id: 'storage-networking',
            title: 'Storage firewalls, virtual networks and private access',
            summary: 'Control which networks can reach the storage endpoint before any authorization happens.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['st.access.firewall'],
            concepts: ['storage-firewall', 'service-endpoint', 'private-endpoint'],
            keywords: ['selected networks', 'trusted services', 'resource instance rules'],
          },
        ],
      },
    ],
  },
  {
    id: 'networking',
    number: 5,
    title: 'Virtual networking',
    tagline: 'Follow the packet: address it, route it, filter it, resolve it, balance it.',
    summary:
      'Virtual networks and IP planning, NSGs and effective rules, routing, peering, Bastion, service and private endpoints, Azure DNS, load balancing and troubleshooting.',
    area: 'networking',
    domains: ['networking'],
    icon: 'vnet',
    mentalModel:
      'Every connection is a packet that must be resolved (DNS), routed (system routes, peering routes, UDRs), allowed (NSGs on the subnet and NIC, evaluated in order) and delivered (the target is listening and, for load balancers, healthy). Troubleshooting is simply checking each of those stages in order.',
    outcomes: [
      'Plan address spaces and subnets without overlap',
      'Write and evaluate NSG and ASG rules',
      'Control routing with user-defined routes',
      'Connect networks with peering and reach PaaS privately',
      'Configure Azure DNS and Azure Load Balancer',
      'Troubleshoot connectivity with Network Watcher',
    ],
    chapters: [
      {
        id: 'net-foundations',
        title: 'Network foundations',
        lessons: [
          {
            id: 'vnets-subnets',
            title: 'Virtual networks, subnets and IP address planning',
            summary: 'Address spaces, CIDR, the five reserved addresses and planning for growth and peering.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['nw.vnet.create'],
            concepts: ['vnet', 'subnet'],
            keywords: ['CIDR', '/29', 'reserved IPs', 'overlap', 'address space'],
          },
          {
            id: 'ip-addressing',
            title: 'Public IPs, private IPs and outbound access',
            summary: 'Standard public IPs, static vs dynamic, NICs, and why new subnets need explicit outbound access.',
            minutes: 16,
            level: 2,
            tier: 'must',
            skills: ['nw.vnet.public-ip'],
            concepts: ['public-ip', 'network-interface', 'nat-gateway'],
            keywords: ['Standard SKU', 'zone-redundant', 'default outbound access', 'private subnet'],
          },
        ],
      },
      {
        id: 'filter-route',
        title: 'Filtering and routing',
        lessons: [
          {
            id: 'nsg-asg',
            title: 'Network security groups and application security groups',
            summary: 'Priority-ordered, stateful rules — and grouping VMs by role instead of IP.',
            minutes: 22,
            level: 3,
            tier: 'must',
            skills: ['nw.secure.nsg'],
            concepts: ['nsg', 'asg', 'service-tag'],
            keywords: ['priority', 'default rules', 'AllowVNetInBound', 'DenyAllInbound', 'stateful'],
          },
          {
            id: 'effective-security-rules',
            title: 'Evaluating effective security rules',
            summary: 'When a subnet NSG and a NIC NSG both apply, work out the verdict every time.',
            minutes: 16,
            level: 4,
            tier: 'must',
            skills: ['nw.secure.effective'],
            concepts: ['nsg', 'effective-security-rules'],
            keywords: ['IP flow verify', 'subnet then NIC', 'NIC then subnet'],
          },
          {
            id: 'routing-udr',
            title: 'Routing and user-defined routes',
            summary: 'System routes, longest prefix match, and forcing traffic through a network virtual appliance.',
            minutes: 18,
            level: 4,
            tier: 'must',
            skills: ['nw.vnet.udr'],
            concepts: ['route-table', 'network-virtual-appliance'],
            keywords: ['next hop', 'VirtualAppliance', 'IP forwarding', '0.0.0.0/0', 'effective routes'],
          },
        ],
      },
      {
        id: 'connect',
        title: 'Connecting networks',
        lessons: [
          {
            id: 'vnet-peering',
            title: 'Virtual network peering and hub-and-spoke',
            summary: 'Private, low-latency connectivity between VNets — and why peering is not transitive.',
            minutes: 20,
            level: 3,
            tier: 'must',
            skills: ['nw.vnet.peering'],
            concepts: ['vnet-peering', 'hub-spoke'],
            keywords: ['global peering', 'gateway transit', 'allow forwarded traffic', 'Initiated', 'Connected'],
          },
          {
            id: 'hybrid-connectivity',
            title: 'Hybrid connectivity concepts: VPN Gateway and ExpressRoute',
            summary: 'Context for connecting on-premises networks — useful background for gateway transit and DNS.',
            minutes: 10,
            level: 1,
            tier: 'advanced',
            skills: [],
            concepts: ['vpn-gateway', 'expressroute'],
            keywords: ['site-to-site', 'point-to-site', 'GatewaySubnet'],
          },
        ],
      },
      {
        id: 'secure-access',
        title: 'Secure access to VMs and PaaS',
        lessons: [
          {
            id: 'azure-bastion',
            title: 'Azure Bastion',
            summary: 'RDP and SSH to VMs over TLS without public IPs on the VMs.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['nw.secure.bastion'],
            concepts: ['bastion'],
            keywords: ['AzureBastionSubnet', '/26', 'SKUs', 'native client'],
          },
          {
            id: 'service-private-endpoints',
            title: 'Service endpoints vs private endpoints',
            summary: 'Two ways to reach PaaS from a VNet — one keeps the public endpoint, one brings the service inside.',
            minutes: 22,
            level: 4,
            tier: 'must',
            skills: ['nw.secure.service-endpoints', 'nw.secure.private-endpoints'],
            concepts: ['service-endpoint', 'private-endpoint'],
            keywords: ['Private Link', 'privatelink DNS zone', 'Microsoft.Storage', 'data exfiltration'],
          },
        ],
      },
      {
        id: 'dns-lb',
        title: 'Name resolution and load balancing',
        lessons: [
          {
            id: 'azure-dns',
            title: 'Azure DNS: public and private zones',
            summary: 'Host public domains, resolve private names inside VNets, and auto-register VMs.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['nw.dnslb.dns'],
            concepts: ['azure-dns', 'private-dns-zone'],
            keywords: ['record sets', 'virtual network link', 'autoregistration', '168.63.129.16'],
          },
          {
            id: 'load-balancer',
            title: 'Azure Load Balancer: configure and troubleshoot',
            summary: 'Frontends, backend pools, health probes and rules — and why backends go unhealthy.',
            minutes: 22,
            level: 4,
            tier: 'must',
            skills: ['nw.dnslb.lb', 'nw.dnslb.troubleshoot'],
            concepts: ['load-balancer', 'health-probe'],
            keywords: ['public', 'internal', 'HA ports', 'inbound NAT rule', 'outbound rules'],
          },
        ],
      },
      {
        id: 'net-troubleshooting',
        title: 'Troubleshooting',
        lessons: [
          {
            id: 'network-troubleshooting',
            title: 'Troubleshooting connectivity with Network Watcher',
            summary: 'A repeatable method and the right diagnostic tool for each stage of a connection.',
            minutes: 20,
            level: 4,
            tier: 'must',
            skills: ['nw.vnet.troubleshoot', 'mo.monitor.network-watcher'],
            concepts: ['network-watcher', 'effective-security-rules'],
            keywords: ['IP flow verify', 'next hop', 'connection troubleshoot', 'packet capture'],
          },
        ],
      },
    ],
  },
  {
    id: 'virtual-machines',
    number: 6,
    title: 'Virtual machines',
    tagline: 'Full control of the operating system — and full responsibility for it.',
    summary:
      'VM anatomy and sizing, managed disks, encryption at host, availability sets and zones, scale sets, moving VMs and day-to-day operations.',
    area: 'compute',
    domains: ['compute'],
    icon: 'vm',
    mentalModel:
      'A VM is not one resource but a small system: a compute resource plus NICs, disks, and usually a public IP and NSG, all living in a VNet. Availability comes from spreading identical VMs across fault domains or zones; scale comes from scale sets; and protection comes from encryption, backup and replication layered on top.',
    outcomes: [
      'Create VMs and choose sizes and disk types',
      'Enable encryption at host',
      'Deploy to availability zones, availability sets and scale sets',
      'Move VMs between resource groups, subscriptions and regions',
    ],
    chapters: [
      {
        id: 'build-vms',
        title: 'Building VMs',
        lessons: [
          {
            id: 'vm-anatomy',
            title: 'Anatomy of a VM and choosing a size',
            summary: 'Everything a VM deployment creates, and how to pick and change VM sizes.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['cp.vm.create', 'cp.vm.sizes'],
            concepts: ['virtual-machine', 'network-interface', 'managed-disk'],
            keywords: ['resize', 'deallocate', 'VM series', 'image'],
          },
          {
            id: 'vm-disks',
            title: 'Managed disks',
            summary: 'OS, data and temporary disks; disk types; resizing and snapshots.',
            minutes: 18,
            level: 2,
            tier: 'must',
            skills: ['cp.vm.disks'],
            concepts: ['managed-disk'],
            keywords: ['Premium SSD v2', 'Ultra Disk', 'host caching', 'temporary disk', 'expand disk'],
          },
          {
            id: 'vm-encryption',
            title: 'Encryption at host and disk encryption options',
            summary: 'What server-side encryption covers, what encryption at host adds, and why ADE is retiring.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['cp.vm.encryption'],
            concepts: ['encryption-at-host', 'managed-disk'],
            keywords: ['EncryptionAtHost', 'disk encryption set', 'Azure Disk Encryption retirement'],
          },
        ],
      },
      {
        id: 'availability-scale',
        title: 'Availability and scale',
        lessons: [
          {
            id: 'vm-availability',
            title: 'Availability sets and availability zones',
            summary: 'Fault domains, update domains, zones and the SLAs each design earns.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['cp.vm.availability'],
            concepts: ['availability-set', 'availability-zone'],
            keywords: ['fault domain', 'update domain', '99.95%', '99.99%'],
          },
          {
            id: 'vmss',
            title: 'Virtual Machine Scale Sets',
            summary: 'Flexible and Uniform orchestration, autoscale rules and upgrade policies.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['cp.vm.vmss'],
            concepts: ['vmss', 'autoscale'],
            keywords: ['Flexible', 'Uniform', 'scale-out rule', 'cooldown', 'instance protection'],
          },
        ],
      },
      {
        id: 'operate-vms',
        title: 'Operating VMs',
        lessons: [
          {
            id: 'vm-move',
            title: 'Moving VMs across resource groups, subscriptions and regions',
            summary: 'Move dependent resources together, and use Azure Resource Mover to change regions.',
            minutes: 12,
            level: 3,
            tier: 'must',
            skills: ['cp.vm.move'],
            concepts: ['resource-move', 'virtual-machine'],
            keywords: ['Resource Mover', 'dependent resources', 'same tenant'],
          },
          {
            id: 'vm-operations',
            title: 'Connecting, extensions and VM troubleshooting',
            summary: 'Bastion and Run Command, VM extensions, boot diagnostics and serial console.',
            minutes: 16,
            level: 4,
            tier: 'should',
            skills: ['cp.vm.create'],
            concepts: ['virtual-machine', 'bastion'],
            keywords: ['Custom Script Extension', 'boot diagnostics', 'serial console', 'redeploy'],
          },
        ],
      },
    ],
  },
  {
    id: 'infrastructure-as-code',
    number: 7,
    title: 'Infrastructure as code',
    tagline: 'Describe the environment once; deploy it the same way every time.',
    summary: 'Read, modify, deploy and export ARM templates and Bicep files, and convert between them.',
    area: 'compute',
    domains: ['compute'],
    icon: 'code',
    mentalModel:
      'ARM templates (JSON) and Bicep files describe the desired end state of resources. Azure Resource Manager compares that description with what exists and makes the changes. Bicep compiles to ARM JSON, so both deploy through the same engine with the same modes and permissions.',
    outcomes: [
      'Interpret the structure of ARM templates and Bicep files',
      'Modify parameters, variables, resources and outputs safely',
      'Deploy with the CLI or PowerShell and choose a deployment mode',
      'Export templates and decompile JSON to Bicep',
    ],
    chapters: [
      {
        id: 'templates',
        title: 'Templates',
        lessons: [
          {
            id: 'arm-templates',
            title: 'Reading and modifying ARM templates',
            summary: 'Schema, parameters, variables, resources, functions and outputs.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['cp.iac.interpret', 'cp.iac.modify-arm'],
            concepts: ['arm-template'],
            keywords: ['parameters', 'variables', 'dependsOn', 'resourceId()', 'outputs'],
          },
          {
            id: 'bicep',
            title: 'Bicep files',
            summary: 'The same deployments with cleaner syntax, symbolic names and automatic dependencies.',
            minutes: 18,
            level: 2,
            tier: 'must',
            skills: ['cp.iac.interpret', 'cp.iac.modify-bicep'],
            concepts: ['bicep'],
            keywords: ['param', 'var', 'resource', 'module', 'decorators', '@allowed'],
          },
          {
            id: 'deployments',
            title: 'Deploying, exporting and converting templates',
            summary: 'Deployment modes, what-if, exporting from the portal and decompiling to Bicep.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['cp.iac.deploy', 'cp.iac.export'],
            concepts: ['arm-template', 'bicep'],
            keywords: ['incremental', 'complete', 'what-if', 'az bicep decompile', 'export template'],
          },
        ],
      },
    ],
  },
  {
    id: 'compute-services',
    number: 8,
    title: 'Choosing compute',
    tagline: 'Pick the service that fits the workload, not the one you know best.',
    summary:
      'Compare VMs, scale sets, App Service, Container Instances and Container Apps — and understand what you manage in each.',
    area: 'compute',
    domains: ['compute'],
    icon: 'server',
    mentalModel:
      'Every compute choice trades control for convenience. The more of the stack Azure manages (PaaS, serverless containers), the less you patch and scale by hand — and the fewer knobs you can turn. Choose the least control you actually need.',
    outcomes: [
      'Explain the IaaS–PaaS responsibility split',
      'Choose between VMs, scale sets, App Service, ACI and Container Apps for a scenario',
    ],
    chapters: [
      {
        id: 'choose',
        title: 'Service selection',
        lessons: [
          {
            id: 'iaas-paas',
            title: 'IaaS, PaaS and serverless: what do you manage?',
            summary: 'The shared responsibility model applied to Azure compute.',
            minutes: 10,
            level: 1,
            tier: 'should',
            skills: ['cp.vm.create', 'cp.app.create'],
            concepts: ['virtual-machine', 'app-service', 'container-apps'],
            keywords: ['shared responsibility', 'patching', 'managed service'],
          },
          {
            id: 'choosing-compute',
            title: 'Choosing the right compute service',
            summary: 'A decision framework for hosting web apps, APIs, jobs and containers.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['cp.app.create', 'cp.containers.aci', 'cp.containers.aca', 'cp.vm.vmss'],
            concepts: ['virtual-machine', 'vmss', 'app-service', 'container-instances', 'container-apps'],
            keywords: ['decision tree', 'web app hosting', 'batch job', 'microservices'],
          },
        ],
      },
    ],
  },
  {
    id: 'app-service',
    number: 9,
    title: 'Azure App Service',
    tagline: 'Run web apps without running servers.',
    summary: 'App Service plans, scaling, deployment slots, custom domains and TLS, networking and backup.',
    area: 'compute',
    domains: ['compute'],
    icon: 'app-service',
    mentalModel:
      'An App Service plan is the set of VMs you pay for; apps are tenants on that plan. The plan tier unlocks features (custom domains, TLS, slots, autoscale, backups, VNet integration) and every app and slot in a plan shares its instances. Inbound features control traffic to the app; outbound features control traffic from it.',
    outcomes: [
      'Provision plans and apps in the right tier',
      'Scale up and scale out, manually and automatically',
      'Use deployment slots for zero-downtime releases',
      'Map custom domains and secure them with TLS',
      'Configure inbound and outbound networking and backups',
    ],
    chapters: [
      {
        id: 'plans-apps',
        title: 'Plans and apps',
        lessons: [
          {
            id: 'app-service-plans',
            title: 'App Service and App Service plans',
            summary: 'Tiers, what they unlock, and App Service compared with running your own VM.',
            minutes: 18,
            level: 2,
            tier: 'must',
            skills: ['cp.app.plan', 'cp.app.create'],
            concepts: ['app-service', 'app-service-plan'],
            keywords: ['Free', 'Basic', 'Standard', 'Premium v3', 'Isolated v2', 'shared vs dedicated'],
          },
          {
            id: 'app-service-scaling',
            title: 'Scaling App Service',
            summary: 'Scale up for power and features, scale out for capacity, and automate it.',
            minutes: 14,
            level: 3,
            tier: 'must',
            skills: ['cp.app.scaling'],
            concepts: ['app-service-plan', 'autoscale'],
            keywords: ['scale up', 'scale out', 'autoscale rules', 'instance limits'],
          },
          {
            id: 'deployment-slots',
            title: 'Deployment slots',
            summary: 'Stage, warm up and swap releases — and know which settings travel with the swap.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['cp.app.slots'],
            concepts: ['deployment-slot'],
            keywords: ['swap', 'slot setting', 'swap with preview', 'traffic routing'],
          },
        ],
      },
      {
        id: 'app-secure',
        title: 'Domains, security, networking and backup',
        lessons: [
          {
            id: 'app-service-domains-tls',
            title: 'Custom domains, certificates and TLS',
            summary: 'Verify and map your domain, then bind a certificate for HTTPS.',
            minutes: 16,
            level: 2,
            tier: 'must',
            skills: ['cp.app.domain', 'cp.app.tls'],
            concepts: ['app-service', 'app-service-certificate'],
            keywords: ['CNAME', 'A record', 'asuid TXT', 'managed certificate', 'SNI SSL'],
          },
          {
            id: 'app-service-networking',
            title: 'App Service networking',
            summary: 'Inbound: access restrictions and private endpoints. Outbound: VNet integration and hybrid connections.',
            minutes: 18,
            level: 4,
            tier: 'must',
            skills: ['cp.app.networking'],
            concepts: ['app-service', 'vnet-integration', 'private-endpoint'],
            keywords: ['access restrictions', 'VNet integration', 'Hybrid Connections', 'outbound IPs'],
          },
          {
            id: 'app-service-backup',
            title: 'Backing up App Service',
            summary: 'Automatic and custom backups, what they include and how to restore safely.',
            minutes: 10,
            level: 2,
            tier: 'must',
            skills: ['cp.app.backup'],
            concepts: ['app-service'],
            keywords: ['automatic backups', 'custom backups', 'restore to slot'],
          },
        ],
      },
    ],
  },
  {
    id: 'containers',
    number: 10,
    title: 'Containers',
    tagline: 'Package once, run anywhere — from a single container to event-driven apps.',
    summary: 'Container images and Azure Container Registry, Azure Container Instances, and Azure Container Apps sizing and scaling.',
    area: 'compute',
    domains: ['compute'],
    icon: 'container',
    mentalModel:
      'An image is a packaged app; a registry stores images; a container is a running image. Azure Container Instances runs containers directly with no orchestration. Azure Container Apps adds revisions, ingress and event-driven autoscaling (including to zero) on a managed Kubernetes-based platform.',
    outcomes: [
      'Create and secure an Azure Container Registry',
      'Run containers with Azure Container Instances',
      'Deploy and scale apps with Azure Container Apps',
    ],
    chapters: [
      {
        id: 'containers-core',
        title: 'Running containers on Azure',
        lessons: [
          {
            id: 'containers-acr',
            title: 'Containers and Azure Container Registry',
            summary: 'Images, registries, SKUs and secure authentication for pulls and pushes.',
            minutes: 16,
            level: 2,
            tier: 'must',
            skills: ['cp.containers.acr'],
            concepts: ['container-registry'],
            keywords: ['AcrPull', 'admin user', 'geo-replication', 'Premium'],
          },
          {
            id: 'container-instances',
            title: 'Azure Container Instances',
            summary: 'Container groups, restart policies, networking, storage and sizing.',
            minutes: 14,
            level: 2,
            tier: 'must',
            skills: ['cp.containers.aci', 'cp.containers.scaling'],
            concepts: ['container-instances'],
            keywords: ['container group', 'restart policy', 'DNS name label', 'CPU and memory'],
          },
          {
            id: 'container-apps',
            title: 'Azure Container Apps: deploy, size and scale',
            summary: 'Environments, revisions, ingress and KEDA-based scale rules.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['cp.containers.aca', 'cp.containers.scaling'],
            concepts: ['container-apps'],
            keywords: ['scale to zero', 'HTTP scaling', 'min replicas', 'workload profiles'],
          },
        ],
      },
    ],
  },
  {
    id: 'monitoring',
    number: 11,
    title: 'Monitoring',
    tagline: 'See what is happening, know when it matters, and find out why.',
    summary:
      'Azure Monitor metrics and logs, diagnostic settings and agents, KQL, alerts, Insights, Connection monitor and troubleshooting workflows.',
    area: 'monitoring',
    domains: ['monitoring', 'networking'],
    icon: 'monitor',
    mentalModel:
      'Azure Monitor has two data stores: metrics (numbers over time, collected automatically, fast) and logs (rich records in Log Analytics, collected by configuration). Activity logs record control-plane changes; resource logs record what happens inside a resource. Alerts watch either store and hand off to action groups.',
    outcomes: [
      'Interpret metrics and choose the right aggregation',
      'Route logs with diagnostic settings and the Azure Monitor Agent',
      'Query logs with KQL',
      'Build alert rules, action groups and alert processing rules',
      'Use Insights and Connection monitor to monitor workloads and networks',
    ],
    chapters: [
      {
        id: 'data-platform',
        title: 'The data platform',
        lessons: [
          {
            id: 'monitor-metrics',
            title: 'Azure Monitor and metrics',
            summary: 'Metrics vs logs, platform metrics, aggregations and dimensions.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['mo.monitor.metrics'],
            concepts: ['azure-monitor', 'metrics'],
            keywords: ['metrics explorer', 'aggregation', 'dimensions', '93 days'],
          },
          {
            id: 'monitor-logs',
            title: 'Activity logs, resource logs and diagnostic settings',
            summary: 'Which logs exist by default, which you must turn on, and where to send them.',
            minutes: 20,
            level: 2,
            tier: 'must',
            skills: ['mo.monitor.logs'],
            concepts: ['activity-log', 'diagnostic-settings', 'log-analytics-workspace', 'azure-monitor-agent'],
            keywords: ['resource logs', 'data collection rule', 'Log Analytics', 'Event Hubs'],
          },
          {
            id: 'kql',
            title: 'Querying logs with KQL',
            summary: 'The handful of Kusto operators that answer most administrator questions.',
            minutes: 18,
            level: 3,
            tier: 'must',
            skills: ['mo.monitor.query'],
            concepts: ['kql', 'log-analytics-workspace'],
            keywords: ['where', 'summarize', 'bin', 'ago', 'project', 'render'],
          },
        ],
      },
      {
        id: 'act',
        title: 'Acting on signals',
        lessons: [
          {
            id: 'alerts',
            title: 'Alert rules, action groups and alert processing rules',
            summary: 'Detect conditions, notify the right people, and suppress noise during maintenance.',
            minutes: 20,
            level: 3,
            tier: 'must',
            skills: ['mo.monitor.alerts'],
            concepts: ['alert-rule', 'action-group', 'alert-processing-rule'],
            keywords: ['metric alert', 'log search alert', 'activity log alert', 'severity', 'stateful'],
          },
          {
            id: 'insights',
            title: 'Insights for VMs, storage accounts and networks',
            summary: 'Curated monitoring experiences and what each needs to light up.',
            minutes: 14,
            level: 3,
            tier: 'must',
            skills: ['mo.monitor.insights'],
            concepts: ['vm-insights', 'azure-monitor-agent'],
            keywords: ['VM insights', 'Storage insights', 'Network insights', 'workbooks'],
          },
          {
            id: 'connection-monitor',
            title: 'Connection monitor and flow logs',
            summary: 'Continuously test connectivity and log traffic for investigation.',
            minutes: 14,
            level: 3,
            tier: 'must',
            skills: ['mo.monitor.network-watcher'],
            concepts: ['connection-monitor', 'network-watcher'],
            keywords: ['test group', 'checks failed', 'round-trip time', 'virtual network flow logs'],
          },
          {
            id: 'monitoring-troubleshooting',
            title: 'Troubleshooting workflows: from symptom to cause',
            summary: 'What to check first when CPU spikes, something changed, or a resource is unhealthy.',
            minutes: 14,
            level: 4,
            tier: 'should',
            skills: ['mo.monitor.metrics', 'mo.monitor.query', 'mo.monitor.logs'],
            concepts: ['activity-log', 'metrics', 'resource-health'],
            keywords: ['who changed it', 'Resource Health', 'Service Health', 'change history'],
          },
        ],
      },
    ],
  },
  {
    id: 'backup-recovery',
    number: 12,
    title: 'Backup & recovery',
    tagline: 'Backup is not disaster recovery — you need to know both.',
    summary:
      'Backup vs DR, Recovery Services vaults and Backup vaults, backup policies, restore operations, Azure Site Recovery failover, and backup reports and alerts.',
    area: 'monitoring',
    domains: ['monitoring'],
    icon: 'backup',
    mentalModel:
      'Backups are point-in-time copies you restore from after data is lost or corrupted — measured in days of history. Disaster recovery keeps a continuously replicated copy ready in another region so the whole workload can run there — measured in minutes of data loss (RPO) and time to recover (RTO). Most production workloads need both.',
    outcomes: [
      'Explain backup vs disaster recovery in RPO and RTO terms',
      'Create Recovery Services vaults and Backup vaults',
      'Configure backup policies and perform restores',
      'Replicate VMs with Site Recovery and run failovers',
      'Configure backup reports and alerts',
    ],
    chapters: [
      {
        id: 'backup',
        title: 'Azure Backup',
        lessons: [
          {
            id: 'backup-vs-dr',
            title: 'Backup vs disaster recovery',
            summary: 'RPO, RTO and the failures each strategy protects against.',
            minutes: 12,
            level: 1,
            tier: 'must',
            skills: ['mo.backup.rsv', 'mo.backup.asr'],
            concepts: ['azure-backup', 'site-recovery'],
            keywords: ['RPO', 'RTO', 'ransomware', 'regional outage'],
          },
          {
            id: 'backup-vaults',
            title: 'Recovery Services vaults and Backup vaults',
            summary: 'Which vault protects which workload, storage redundancy and vault security features.',
            minutes: 16,
            level: 2,
            tier: 'must',
            skills: ['mo.backup.rsv', 'mo.backup.bv'],
            concepts: ['recovery-services-vault', 'backup-vault'],
            keywords: ['soft delete', 'Cross Region Restore', 'immutable vault', 'GRS'],
          },
          {
            id: 'backup-policies',
            title: 'Backup policies for Azure VMs',
            summary: 'Standard vs Enhanced policies, schedules, instant restore and retention.',
            minutes: 14,
            level: 3,
            tier: 'must',
            skills: ['mo.backup.policy'],
            concepts: ['backup-policy', 'recovery-services-vault'],
            keywords: ['Enhanced policy', 'every 4 hours', 'instant restore', 'Trusted Launch'],
          },
          {
            id: 'backup-restore',
            title: 'Backup and restore operations',
            summary: 'On-demand backups, restore options for VMs, files and Azure Files.',
            minutes: 16,
            level: 3,
            tier: 'must',
            skills: ['mo.backup.operations'],
            concepts: ['azure-backup', 'recovery-services-vault'],
            keywords: ['create new VM', 'restore disks', 'replace existing', 'file recovery', 'Cross Region Restore'],
          },
          {
            id: 'backup-reports-alerts',
            title: 'Backup reports and alerts',
            summary: 'Send vault diagnostics to Log Analytics for reports, and route backup alerts.',
            minutes: 12,
            level: 2,
            tier: 'must',
            skills: ['mo.backup.reports'],
            concepts: ['recovery-services-vault', 'diagnostic-settings', 'alert-processing-rule'],
            keywords: ['Backup Reports', 'diagnostic settings', 'Resiliency', 'job failure alerts'],
          },
        ],
      },
      {
        id: 'dr',
        title: 'Disaster recovery',
        lessons: [
          {
            id: 'site-recovery',
            title: 'Azure Site Recovery: replicate and fail over',
            summary: 'Azure-to-Azure replication, test failover, failover, commit and reprotect.',
            minutes: 18,
            level: 4,
            tier: 'must',
            skills: ['mo.backup.asr', 'mo.backup.failover'],
            concepts: ['site-recovery'],
            keywords: ['cache storage account', 'recovery point', 'test failover', 'reprotect', 'recovery plan'],
          },
        ],
      },
    ],
  },
];

export interface LessonRef extends LessonMeta {
  moduleId: string;
  moduleNumber: number;
  moduleTitle: string;
  chapterId: string;
  chapterTitle: string;
  index: number;
}

export const LESSONS: LessonRef[] = MODULES.flatMap((m) =>
  m.chapters.flatMap((c) =>
    c.lessons.map((l) => ({
      ...l,
      moduleId: m.id,
      moduleNumber: m.number,
      moduleTitle: m.title,
      chapterId: c.id,
      chapterTitle: c.title,
      index: 0,
    })),
  ),
).map((l, i) => ({ ...l, index: i }));

export const LESSON_INDEX: Record<string, LessonRef> = Object.fromEntries(LESSONS.map((l) => [l.id, l]));
export const MODULE_INDEX: Record<string, Module> = Object.fromEntries(MODULES.map((m) => [m.id, m]));

export function lessonsForModule(moduleId: string): LessonRef[] {
  return LESSONS.filter((l) => l.moduleId === moduleId);
}

export function adjacentLessons(lessonId: string): { prev?: LessonRef; next?: LessonRef } {
  const l = LESSON_INDEX[lessonId];
  if (!l) return {};
  return { prev: LESSONS[l.index - 1], next: LESSONS[l.index + 1] };
}
