import type { AreaId, IconKey, Level } from './schema';

export interface SimulatorMeta {
  /** Key in the interactive registry. */
  id: string;
  title: string;
  summary: string;
  area: AreaId;
  icon: IconKey;
  level: Level;
  skills: string[];
  concepts: string[];
  /** Lesson that introduces the underlying concept. */
  lesson?: { moduleId: string; lessonId: string };
}

/** Standalone simulators listed on the Labs page. Each also appears inside lessons. */
export const SIMULATORS: SimulatorMeta[] = [
  {
    id: 'hierarchy-builder',
    title: 'Hierarchy builder',
    summary: 'Arrange tenant, management groups, subscriptions, resource groups and resources — then see how access and policy inherit.',
    area: 'foundations',
    icon: 'management-group',
    level: 1,
    skills: ['ig.gov.mg', 'ig.gov.subscriptions', 'ig.gov.rg'],
    concepts: ['management-group', 'subscription', 'resource-group'],
    lesson: { moduleId: 'foundations', lessonId: 'azure-hierarchy' },
  },
  {
    id: 'rbac-evaluator',
    title: 'RBAC access evaluator',
    summary: 'Pick a user, an action and a scope. Watch Azure collect inherited role assignments and decide whether the action is allowed.',
    area: 'identity-governance',
    icon: 'role',
    level: 4,
    skills: ['ig.access.interpret', 'ig.access.scopes'],
    concepts: ['azure-rbac', 'role-assignment', 'rbac-scope'],
    lesson: { moduleId: 'identity', lessonId: 'rbac-interpret' },
  },
  {
    id: 'policy-effects',
    title: 'Azure Policy effect simulator',
    summary: 'Send create and update requests through policy assignments with different effects and see what gets denied, modified or audited.',
    area: 'identity-governance',
    icon: 'policy',
    level: 3,
    skills: ['ig.gov.policy'],
    concepts: ['azure-policy', 'policy-effect'],
    lesson: { moduleId: 'governance', lessonId: 'azure-policy' },
  },
  {
    id: 'lock-evaluator',
    title: 'Resource lock evaluator',
    summary: 'Apply delete and read-only locks at different scopes and test which everyday operations still succeed.',
    area: 'identity-governance',
    icon: 'lock',
    level: 4,
    skills: ['ig.gov.locks'],
    concepts: ['resource-lock'],
    lesson: { moduleId: 'governance', lessonId: 'resource-locks' },
  },
  {
    id: 'storage-account-builder',
    title: 'Storage account builder',
    summary: 'Configure a storage account for a business scenario and get feedback on type, redundancy, networking and data protection.',
    area: 'storage',
    icon: 'storage',
    level: 3,
    skills: ['st.accounts.create', 'st.accounts.redundancy', 'st.data.blob-soft-delete', 'st.access.firewall'],
    concepts: ['storage-account', 'storage-redundancy'],
    lesson: { moduleId: 'storage', lessonId: 'storage-accounts' },
  },
  {
    id: 'redundancy-explorer',
    title: 'Redundancy failure explorer',
    summary: 'Choose LRS, ZRS, GRS or GZRS (with or without read access) and trigger failures to see what stays available.',
    area: 'storage',
    icon: 'region',
    level: 3,
    skills: ['st.accounts.redundancy'],
    concepts: ['storage-redundancy'],
    lesson: { moduleId: 'storage', lessonId: 'storage-redundancy' },
  },
  {
    id: 'sas-builder',
    title: 'SAS token builder',
    summary: 'Build a shared access signature, read every query parameter, and learn how each type of SAS can be revoked.',
    area: 'storage',
    icon: 'key-vault',
    level: 3,
    skills: ['st.access.sas', 'st.access.policies', 'st.access.keys'],
    concepts: ['sas', 'stored-access-policy', 'access-keys'],
    lesson: { moduleId: 'storage', lessonId: 'storage-keys-sas' },
  },
  {
    id: 'blob-protection',
    title: 'Blob data protection simulator',
    summary: 'Delete and overwrite blobs with soft delete and versioning on or off, then try to recover.',
    area: 'storage',
    icon: 'blob',
    level: 3,
    skills: ['st.data.blob-soft-delete', 'st.data.versioning'],
    concepts: ['blob-soft-delete', 'blob-versioning'],
    lesson: { moduleId: 'storage', lessonId: 'blob-data-protection' },
  },
  {
    id: 'subnet-planner',
    title: 'Subnet and CIDR planner',
    summary: 'Plan a VNet address space, carve subnets, and catch overlaps, reserved addresses and peering conflicts.',
    area: 'networking',
    icon: 'subnet',
    level: 2,
    skills: ['nw.vnet.create', 'nw.vnet.peering'],
    concepts: ['vnet', 'subnet'],
    lesson: { moduleId: 'networking', lessonId: 'vnets-subnets' },
  },
  {
    id: 'nsg-evaluator',
    title: 'NSG effective rules evaluator',
    summary: 'Send packets through a subnet NSG and a NIC NSG and watch rules evaluate in priority order.',
    area: 'networking',
    icon: 'nsg',
    level: 4,
    skills: ['nw.secure.nsg', 'nw.secure.effective'],
    concepts: ['nsg', 'effective-security-rules'],
    lesson: { moduleId: 'networking', lessonId: 'effective-security-rules' },
  },
  {
    id: 'route-simulator',
    title: 'Route and next hop simulator',
    summary: 'Combine system routes and user-defined routes, then find the next hop for any destination.',
    area: 'networking',
    icon: 'route',
    level: 4,
    skills: ['nw.vnet.udr', 'nw.vnet.troubleshoot'],
    concepts: ['route-table', 'network-virtual-appliance'],
    lesson: { moduleId: 'networking', lessonId: 'routing-udr' },
  },
  {
    id: 'peering-simulator',
    title: 'Peering connectivity simulator',
    summary: 'Peer hub and spoke networks and test which VMs can reach each other — and why peering is not transitive.',
    area: 'networking',
    icon: 'peering',
    level: 3,
    skills: ['nw.vnet.peering'],
    concepts: ['vnet-peering', 'hub-spoke'],
    lesson: { moduleId: 'networking', lessonId: 'vnet-peering' },
  },
  {
    id: 'private-endpoint-dns',
    title: 'Private endpoint DNS resolver',
    summary: 'Resolve a storage account name from inside and outside a VNet and fix the private DNS configuration.',
    area: 'networking',
    icon: 'private-endpoint',
    level: 4,
    skills: ['nw.secure.private-endpoints', 'nw.dnslb.dns'],
    concepts: ['private-endpoint', 'private-dns-zone'],
    lesson: { moduleId: 'networking', lessonId: 'service-private-endpoints' },
  },
  {
    id: 'lb-probe-simulator',
    title: 'Load balancer health probe simulator',
    summary: 'Configure probes and backend VMs, then find out why instances are marked unhealthy.',
    area: 'networking',
    icon: 'lb',
    level: 4,
    skills: ['nw.dnslb.lb', 'nw.dnslb.troubleshoot'],
    concepts: ['load-balancer', 'health-probe'],
    lesson: { moduleId: 'networking', lessonId: 'load-balancer' },
  },
  {
    id: 'availability-simulator',
    title: 'VM availability failure simulator',
    summary: 'Place VMs in a single location, an availability set or across zones, and simulate rack, maintenance and zone failures.',
    area: 'compute',
    icon: 'zone',
    level: 3,
    skills: ['cp.vm.availability'],
    concepts: ['availability-set', 'availability-zone'],
    lesson: { moduleId: 'virtual-machines', lessonId: 'vm-availability' },
  },
  {
    id: 'deployment-modes',
    title: 'ARM deployment mode simulator',
    summary: 'Deploy the same template in incremental and complete mode and compare what happens to existing resources.',
    area: 'compute',
    icon: 'code',
    level: 3,
    skills: ['cp.iac.deploy'],
    concepts: ['arm-template'],
    lesson: { moduleId: 'infrastructure-as-code', lessonId: 'deployments' },
  },
  {
    id: 'slot-swap',
    title: 'Deployment slot swap visualizer',
    summary: 'Swap staging into production and see which settings move with the code and which stay with the slot.',
    area: 'compute',
    icon: 'app-service',
    level: 3,
    skills: ['cp.app.slots'],
    concepts: ['deployment-slot'],
    lesson: { moduleId: 'app-service', lessonId: 'deployment-slots' },
  },
  {
    id: 'autoscale-simulator',
    title: 'Autoscale simulator',
    summary: 'Tune scale-out and scale-in rules against a day of load and watch instance counts respond.',
    area: 'compute',
    icon: 'vmss',
    level: 3,
    skills: ['cp.vm.vmss', 'cp.app.scaling', 'cp.containers.scaling'],
    concepts: ['autoscale', 'vmss'],
    lesson: { moduleId: 'virtual-machines', lessonId: 'vmss' },
  },
  {
    id: 'kql-builder',
    title: 'KQL query builder',
    summary: 'Build Kusto queries step by step against sample data and see each operator transform the results.',
    area: 'monitoring',
    icon: 'log-analytics',
    level: 3,
    skills: ['mo.monitor.query'],
    concepts: ['kql', 'log-analytics-workspace'],
    lesson: { moduleId: 'monitoring', lessonId: 'kql' },
  },
  {
    id: 'backup-dr-timeline',
    title: 'Backup vs disaster recovery timeline',
    summary: 'Replay incidents — accidental deletion, ransomware, a regional outage — and see what backups and Site Recovery can restore.',
    area: 'monitoring',
    icon: 'recovery',
    level: 3,
    skills: ['mo.backup.policy', 'mo.backup.asr', 'mo.backup.failover'],
    concepts: ['azure-backup', 'site-recovery'],
    lesson: { moduleId: 'backup-recovery', lessonId: 'backup-vs-dr' },
  },
];

export const SIMULATOR_INDEX: Record<string, SimulatorMeta> = Object.fromEntries(SIMULATORS.map((s) => [s.id, s]));
