import type { Flashcard } from '../schema';

export const COMPUTE_CARDS: Flashcard[] = [
  // ------------------------------------------------------------------- VMs
  {
    id: 'fc-vm-deallocate',
    front: 'Stopped or deallocated — which stops the compute charges?',
    back: '**Deallocated**. A guest-OS shutdown leaves the VM "Stopped (not deallocated)" and compute billing continues. Disks and static public IPs are billed either way.',
    concept: 'virtual-machine',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-vm-temp-disk',
    front: 'What is the temporary disk on an Azure VM for?',
    back: 'Short-term scratch space on storage local to the host. Its contents are lost on deallocation or a host move, it is not a managed disk, and it is excluded from backup.',
    concept: 'managed-disk',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-vm-resize-cluster',
    front: 'Why is the size you want missing from a running VM’s resize list?',
    back: 'The current hardware cluster does not support it. Deallocate the VM and the list widens to everything available in the region.',
    concept: 'virtual-machine',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-avset-domains',
    front: 'What does an availability set spread instances across?',
    back: '**Fault domains** (separate racks with separate power and network) and **update domains** (rebooted in stages during platform maintenance) — within one datacentre.',
    concept: 'availability-set',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-avset-immutable',
    front: 'Can you add an existing VM to an availability set?',
    back: 'No. Availability set membership — like zone placement — is fixed at creation. You must delete the VM, keeping its disks, and recreate it in the set.',
    concept: 'availability-set',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-encryption-at-host',
    front: 'Which VM encryption option covers the temporary disk and disk caches?',
    back: '**Encryption at host** — it encrypts on the host before data reaches storage. Azure Disk Encryption runs inside the guest; server-side encryption covers only data at rest in storage.',
    concept: 'encryption-at-host',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-vmss-mode',
    front: 'Can a scale set’s orchestration mode be changed after creation?',
    back: 'No. Flexible or Uniform is fixed at creation — changing it means a new scale set. Flexible is the recommended default.',
    concept: 'vmss',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-autoscale-flapping',
    front: 'Why does a scale set add and remove instances every few minutes?',
    back: 'The scale-in and scale-out thresholds are too close, so removing an instance immediately pushes the metric back over the scale-out threshold. Widen the gap and lengthen the cool-down.',
    concept: 'autoscale',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-vm-move-region',
    front: 'How do you move a VM from one region to another?',
    back: 'Azure Resource Mover, or redeploy from a template, image or restored disks. Resource group and subscription moves never change the region.',
    concept: 'virtual-machine',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-run-command',
    front: 'How do you run a script inside a VM with no public IP, no Bastion and all inbound traffic denied?',
    back: '**Run Command** — it goes through the Azure VM agent over the control plane, so it needs RBAC permission rather than a network path.',
    concept: 'virtual-machine',
    domain: 'compute',
    tier: 'must',
  },

  // ------------------------------------------------------------------- IaC
  {
    id: 'fc-arm-sections',
    front: 'Name the sections of an ARM template.',
    back: '`$schema`, `contentVersion`, `parameters`, `variables`, `resources` and `outputs`. Parameters are supplied at deployment; variables are computed inside the template.',
    concept: 'arm-template',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-deployment-modes',
    front: 'What is the difference between incremental and complete deployment mode?',
    back: 'Incremental (the default) leaves resources not in the template alone. **Complete deletes them.** Complete is unsupported at subscription scope and in the portal; nested deployments are always incremental.',
    concept: 'arm-template',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-incremental-properties',
    front: 'In incremental mode, what happens to a property you omit from a resource the template defines?',
    back: 'It is reset to its default. Incremental protects other **resources**, not other **properties** — the template must describe the full desired state of what it defines.',
    concept: 'arm-template',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-bicep-decompile',
    front: 'Which command converts an ARM JSON template to Bicep?',
    back: '`az bicep decompile --file template.json`. `az bicep build` goes the other way. Decompiled output is a starting point that needs review and parameterization.',
    concept: 'bicep',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-what-if',
    front: 'What does a what-if deployment report?',
    back: 'Create, Modify, Delete, Deploy, Ignore or NoChange per resource — a dry run through Resource Manager before anything changes.',
    concept: 'arm-template',
    domain: 'compute',
    tier: 'must',
  },

  // ------------------------------------------------------------ App Service
  {
    id: 'fc-plan-sharing',
    front: 'What do apps in the same App Service plan share?',
    back: 'The plan’s VM instances — and so do their deployment slots, WebJobs, backups and diagnostic logging. Compute is dedicated at the **plan** level, not per app.',
    concept: 'app-service-plan',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-plan-immutable',
    front: 'Which App Service plan property cannot be changed after creation?',
    back: 'The operating system (and the region). Pricing tier and instance count are both adjustable.',
    concept: 'app-service-plan',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-scale-up-vs-out',
    front: 'Scale up or scale out — which changes the pricing tier?',
    back: '**Scale up** changes the tier, giving larger instances and unlocking features. **Scale out** changes the instance count.',
    concept: 'app-service-plan',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-slot-tier',
    front: 'Which App Service tiers support deployment slots, and how many?',
    back: 'Standard, Premium and Isolated. Standard allows 5 slots per app; Premium and Isolated allow 20.',
    concept: 'deployment-slot',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-slot-sticky',
    front: 'Name four settings that do *not* swap between deployment slots.',
    back: 'Custom domain names, nonpublic certificates and TLS settings, scale settings, IP restrictions — plus Always On, diagnostic log settings, CORS, managed identities and VNet integration.',
    concept: 'deployment-slot',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-slot-setting',
    front: 'What does marking an app setting as a "deployment slot setting" do?',
    back: 'It makes the setting sticky — it stays with the slot instead of travelling with the code during a swap. This is how staging keeps the staging database.',
    concept: 'deployment-slot',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-slot-rollback',
    front: 'How do you roll back a bad release that was swapped into production?',
    back: 'Swap the same two slots again — the previous production app is now sitting in the staging slot, so the rollback is a routing change.',
    concept: 'deployment-slot',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-domain-records',
    front: 'Which DNS records map a custom domain to an App Service app?',
    back: 'Root domain → **A record**; subdomain or wildcard → **CNAME**. Plus a **TXT record named `asuid`** (or `asuid.<subdomain>`) holding the domain verification ID.',
    concept: 'app-service',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-sni-vs-ip-ssl',
    front: 'SNI SSL or IP-based SSL?',
    back: 'SNI lets many certificates secure many domains on one IP address and the bindings are free. IP-based SSL is one per app, needs Standard tier or above, is charged hourly and changes the app’s inbound IP.',
    concept: 'app-service-certificate',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-appservice-net-direction',
    front: 'Private endpoint or VNet integration — which lets an App Service app *reach into* a virtual network?',
    back: '**VNet integration** (outbound). A private endpoint is inbound — it gives the app a private IP so clients in your network can reach it.',
    concept: 'vnet-integration',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-hybrid-connections',
    front: 'How does an App Service app reach one on-premises server with no VPN or ExpressRoute?',
    back: '**Hybrid Connections** — Hybrid Connection Manager on a Windows Server host makes an outbound connection to Azure Relay on port 443 and tunnels to a single host and port.',
    concept: 'app-service',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-appservice-backup-types',
    front: 'Automatic or custom App Service backups — which needs a storage account?',
    back: '**Custom**. Automatic backups are hourly, 30 GB, retained 30 days, not configurable and not downloadable. Custom backups are configurable, downloadable and support partial backups.',
    concept: 'app-service',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-appservice-restore-slot',
    front: 'How do you restore an App Service app with minimal downtime?',
    back: 'Restore into a deployment slot, verify it, then swap. A direct restore stops the target app and erases its file system.',
    concept: 'app-service',
    domain: 'compute',
    tier: 'must',
  },

  // ------------------------------------------------------------- containers
  {
    id: 'fc-acr-premium',
    front: 'Which Azure Container Registry features require the Premium plan?',
    back: 'Geo-replication, private link with private endpoints, IP access rules, customer-managed keys and content trust.',
    concept: 'container-registry',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-acr-auth',
    front: 'What is the most secure way for an Azure service to pull images from ACR?',
    back: 'A **managed identity** granted the **AcrPull** role. The admin user is a single shared credential, disabled by default and intended for testing.',
    concept: 'container-registry',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-aci-restart-policy',
    front: 'Name the three Azure Container Instances restart policies and the default.',
    back: '**Always** (the default), **OnFailure** and **Never**. OnFailure is the run-to-completion policy with retry; a finished container shows as Terminated.',
    concept: 'container-instances',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-aci-container-group',
    front: 'What do containers in an ACI container group share?',
    back: 'A host, a lifecycle, a local network and storage volumes — like a Kubernetes pod. Multi-container groups support Linux containers only.',
    concept: 'container-instances',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-aca-scale-zero',
    front: 'What stops a Container Apps background worker from ever starting again?',
    back: 'Ingress disabled, no scale rule and minReplicas 0 — it scales to zero with nothing to wake it. Add an event-driven scale rule or set minReplicas to at least 1.',
    concept: 'container-apps',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-aca-defaults',
    front: 'What are the default replica limits for a container app?',
    back: 'Minimum 0 and maximum 10 per revision, configurable up to 1,000. With no scale rule the default is an HTTP trigger.',
    concept: 'container-apps',
    domain: 'compute',
    tier: 'should',
  },
  {
    id: 'fc-aca-revision',
    front: 'How do you release a Container Apps version to 10% of traffic first?',
    back: 'Revisions with weighted traffic splitting. Each change creates an immutable revision; shifting the weights back is an instant rollback.',
    concept: 'container-apps',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-aci-vs-aca',
    front: 'ACI or Container Apps for a five-minute nightly job?',
    back: '**Container Instances** — one container, fast start, per-second billing, no orchestration. Container Apps is for microservices needing ingress, revisions and event-driven scaling.',
    concept: 'container-instances',
    domain: 'compute',
    tier: 'must',
  },
  {
    id: 'fc-shared-responsibility',
    front: 'Who patches the operating system on App Service?',
    back: 'Microsoft. On a VM it is yours. Identity, access and data are your responsibility in every model.',
    concept: 'app-service',
    domain: 'compute',
    tier: 'must',
  },
];
