import type { Flashcard } from '../schema';

export const IDENTITY_CARDS: Flashcard[] = [
  {
    id: 'fc-entra-vs-ad',
    front: 'Is Microsoft Entra ID a cloud version of Active Directory Domain Services?',
    back: 'No. Entra ID is an identity provider for modern protocols (OAuth 2.0, OpenID Connect, SAML). It has no domain join, Group Policy, LDAP or Kerberos in the AD DS sense.',
    concept: 'entra-id',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-user-types',
    front: 'What are the three user types in Microsoft Entra ID?',
    back: 'Cloud-only (created in Entra ID), synchronised from on-premises AD DS, and guest users invited through [[b2b-collaboration|B2B collaboration]].',
    concept: 'entra-user',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-bulk-users',
    front: 'How do you create hundreds of users at once in the portal?',
    back: 'Bulk create from a CSV — download the template from **Users → Bulk operations**, fill it in and upload it. Bulk invite, bulk delete and bulk restore work the same way.',
    concept: 'entra-user',
    domain: 'identity-governance',
    tier: 'should',
  },
  {
    id: 'fc-group-types',
    front: 'Security group or Microsoft 365 group — which one do you use for Azure RBAC?',
    back: 'A **security group**. Microsoft 365 groups add shared mailboxes and collaboration features and are not the vehicle for Azure resource permissions.',
    concept: 'entra-group',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-dynamic-group',
    front: 'What is a dynamic group and what does it require?',
    back: 'Membership is calculated from a rule over user or device attributes, so it updates automatically. Dynamic group membership requires Microsoft Entra ID P1 licensing.',
    concept: 'dynamic-group',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-dynamic-group-membership',
    front: 'Can you add a member manually to a dynamic group?',
    back: 'No. Membership type is chosen at creation and dynamic membership is entirely rule-driven — manual additions and removals are not possible.',
    concept: 'dynamic-group',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-group-licensing',
    front: 'What is group-based licensing?',
    back: 'Assigning a licence to a group so every member inherits it, and loses it when they leave the group. It needs enough available licences and a usage location on each user.',
    concept: 'group-based-licensing',
    domain: 'identity-governance',
    tier: 'should',
  },
  {
    id: 'fc-guest-invite',
    front: 'Where does a guest user’s account and credential live?',
    back: 'The credential stays in the guest’s home directory. Your tenant holds a guest **user object** that you grant access to — you never manage their password.',
    concept: 'guest-user',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-sspr-scope',
    front: 'What are the scope choices when enabling self-service password reset?',
    back: 'None, Selected (specific groups) or All. Administrators always have SSPR enabled with a stricter, non-configurable method policy.',
    concept: 'sspr',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-rbac-scopes',
    front: 'List the four Azure RBAC scope levels.',
    back: 'Management group → subscription → resource group → resource. A role assigned at one scope is inherited by everything below it.',
    concept: 'rbac-scope',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-rbac-additive',
    front: 'How does Azure RBAC combine multiple role assignments?',
    back: 'Permissions are **additive** — the effective access is the union of every assignment. The exception is a deny assignment, which always wins.',
    concept: 'azure-rbac',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-rbac-vs-entra-roles',
    front: 'Azure RBAC roles or Microsoft Entra roles — which manages users and groups?',
    back: '**Entra roles** (such as User Administrator) manage identity objects. **Azure RBAC roles** (such as Contributor) manage Azure resources. The two systems are separate.',
    concept: 'entra-roles',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-owner-vs-uaa',
    front: 'What can Owner do that Contributor cannot?',
    back: 'Grant access — Contributor can manage everything except role assignments. User Access Administrator can grant access but not manage resources.',
    concept: 'role-definition',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-notactions',
    front: 'What does NotActions do in a role definition?',
    back: 'It subtracts permissions from Actions. It is not a deny rule — a different assignment can still grant the excluded permission.',
    concept: 'role-definition',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-custom-role-storage',
    front: 'Where is a custom Azure role definition stored?',
    back: 'In the Microsoft Entra tenant, with `AssignableScopes` listing where it may be used. Custom roles cannot be assigned outside those scopes.',
    concept: 'custom-role',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-managed-identity-types',
    front: 'System-assigned or user-assigned managed identity — what is the difference?',
    back: 'A **system-assigned** identity is tied to one resource and deleted with it. A **user-assigned** identity is its own resource, shared by many resources and independent of their lifecycle.',
    concept: 'managed-identity',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-managed-identity-why',
    front: 'Why prefer a managed identity over a service principal with a secret?',
    back: 'There is no credential to store, rotate or leak — Azure manages it. The identity gets tokens from the platform and is granted RBAC roles like any other principal.',
    concept: 'managed-identity',
    domain: 'identity-governance',
    tier: 'must',
  },
  {
    id: 'fc-service-principal',
    front: 'What is a service principal?',
    back: 'The identity an application uses inside a tenant. It can authenticate with a secret or certificate — which is exactly the credential that a managed identity removes.',
    concept: 'service-principal',
    domain: 'identity-governance',
    tier: 'should',
  },
];
