import type { Flashcard } from '../schema';

export const MONITORING_CARDS: Flashcard[] = [
  // -------------------------------------------------------------- monitoring
  {
    id: 'fc-metrics-vs-logs',
    front: 'Metrics or logs: which is collected automatically and which needs configuration?',
    back: '**Platform metrics** are collected automatically, at no cost, at a one-minute frequency. **Resource logs** are off until a [[diagnostic-settings|diagnostic setting]] routes them somewhere.',
    concept: 'azure-monitor',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-metrics-retention',
    front: 'How long are platform and custom metrics retained?',
    back: '**93 days** — but a single chart can only span 30 days at a time. For longer retention, send them to a Log Analytics workspace.',
    concept: 'metrics',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-aggregation',
    front: 'Why does a CPU chart show 22% when the VM is repeatedly pegged at 100%?',
    back: 'The aggregation is **average** over a long window. Short spikes only appear with **maximum** over a narrower granularity — and the same mistake in an alert rule means it never fires.',
    concept: 'metrics',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-guest-metrics',
    front: 'Why is guest memory missing from Metrics explorer?',
    back: 'Memory and free disk space are **guest OS** metrics. They require the [[azure-monitor-agent|Azure Monitor Agent]] plus a data collection rule associated with the machine.',
    concept: 'azure-monitor-agent',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-ama-dcr',
    front: 'What does installing the Azure Monitor Agent collect on its own?',
    back: 'Nothing. A **data collection rule** defines what to collect and which workspace receives it, and must be associated with the machine.',
    concept: 'azure-monitor-agent',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-activity-log-retention',
    front: 'How long does Azure keep activity log events?',
    back: '**90 days**, then deletes them. Export to a Log Analytics workspace (up to 12 years), a storage account or an event hub for longer retention.',
    concept: 'activity-log',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-activity-vs-resource-logs',
    front: 'Activity log or resource logs: which records reading a secret from a key vault?',
    back: '**Resource logs** — that is a data-plane operation, and it is not collected until a diagnostic setting is created. The activity log records control-plane operations and does not typically capture reads.',
    concept: 'activity-log',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-activity-creator',
    front: 'Where is the only record of who created a resource?',
    back: 'The activity log — which is why exporting it to a workspace is standard practice, since it only retains 90 days.',
    concept: 'activity-log',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-diag-destinations',
    front: 'Name the diagnostic setting destinations and what each is for.',
    back: 'Log Analytics workspace to query, correlate and alert; storage account for cheap long-term archive; event hub to stream to a SIEM outside Azure.',
    concept: 'diagnostic-settings',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-kql-shape',
    front: 'What is the shape of a KQL query?',
    back: 'A table name, then operators piped with `|`, each acting on the rows the previous one produced. Put the time filter immediately after the table name.',
    concept: 'kql',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-kql-summarize-bin',
    front: 'What does `summarize avg(X) by bin(TimeGenerated, 1h)` produce?',
    back: 'A time series — one row per hour with the average of X. Without `bin`, grouping by TimeGenerated creates a group per distinct millisecond.',
    concept: 'kql',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-kql-project-extend',
    front: '`project` or `extend`?',
    back: '`project` returns **only** the columns you list (and can rename or compute them). `extend` adds computed columns and keeps all the originals.',
    concept: 'kql',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-kql-case',
    front: 'Is KQL case sensitive?',
    back: 'Yes. Table and column names must match the schema exactly. Use `=~` or `tolower()` when the **data** may vary in case — AzureActivity is a documented example.',
    concept: 'kql',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-alert-anatomy',
    front: 'What are the three pieces of the Azure Monitor alerting model?',
    back: 'The **alert rule** detects, the **[[action-group|action group]]** notifies and automates, and the **[[alert-processing-rule|alert processing rule]]** modifies alerts as they fire.',
    concept: 'alert-rule',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-alert-stateful',
    front: 'Which alert types are stateless?',
    back: '**All activity log alerts**, including Service Health and Resource Health. They fire per event and stay in the Fired condition. Metric alerts are stateful by default.',
    concept: 'alert-rule',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-alert-resolve',
    front: 'When does a metric alert resolve?',
    back: 'When the condition is not met for **three consecutive checks**. Alert instances themselves are stored for 30 days.',
    concept: 'alert-rule',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-alert-suppression',
    front: 'How do you silence alerts during a maintenance window without losing coverage?',
    back: 'An **alert processing rule** with a schedule that removes all action groups for the scope. The rules keep evaluating and the alerts are still recorded.',
    concept: 'alert-processing-rule',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-alert-missing-data',
    front: 'Why prefer a metric alert over a log search alert for a missing heartbeat?',
    back: 'Microsoft notes log search alerts work best at detecting specific data, not its absence — logs are semi-structured and more latent, so absence detection misfires.',
    concept: 'alert-rule',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-connection-monitor-agent',
    front: 'What does Connection monitor need on an Azure VM used as a source?',
    back: 'The **Network Watcher agent** extension. Destinations need nothing. On-premises sources need Azure Arc and then the Azure Monitor Agent.',
    concept: 'connection-monitor',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-connection-monitor-metrics',
    front: 'Which Connection monitor metrics do you alert on?',
    back: '**ChecksFailedPercent** and **RoundTripTimeMs** (plus TestResult). Default warning thresholds are 750 ms round-trip time and 10% checks failed.',
    concept: 'connection-monitor',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-triage-order',
    front: 'What do you check first when a resource stops working and nobody deployed anything?',
    back: '**Resource Health**, then **Service Health** — they rule out the causes you cannot fix. Then the activity log for changes, then metrics for saturation.',
    concept: 'resource-health',
    domain: 'monitoring',
    tier: 'must',
  },

  // ------------------------------------------------------------------ backup
  {
    id: 'fc-backup-vs-dr',
    front: 'Ransomware encrypts a VM that is both backed up and replicated. Which one saves you?',
    back: '**Backup.** Replication is continuous, so the encrypted disks were replicated within minutes. Only backup keeps history to go back to.',
    concept: 'azure-backup',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-rpo-rto',
    front: 'Define RPO and RTO.',
    back: '**RPO** is how much data you can afford to lose, in time. **RTO** is how long you can afford to be down. They are business numbers that select the technology.',
    concept: 'azure-backup',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-vault-types',
    front: 'Recovery Services vault or Backup vault?',
    back: '**Recovery Services vault**: Azure VMs, SQL in Azure VMs, Azure Files, on-premises workloads — and Site Recovery. **Backup vault**: blobs, disks and PostgreSQL.',
    concept: 'recovery-services-vault',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-vault-redundancy-timing',
    front: 'When can a vault’s storage redundancy be changed?',
    back: 'Only before the first backup item is protected. Afterwards the setting is locked — the same is true of customer-managed key encryption.',
    concept: 'recovery-services-vault',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-soft-delete-backup',
    front: 'What does soft delete do in a Recovery Services vault?',
    back: 'Retains deleted backup data for **14 additional days at no cost**, so the item can be recovered intact. Enhanced soft delete makes the period configurable and can be locked always-on.',
    concept: 'recovery-services-vault',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-crr',
    front: 'What does Cross Region Restore add on top of geo-redundant storage?',
    back: 'The ability to restore from the paired region **at any time**, including for drills, rather than only after Microsoft declares an outage. It is vault-tier only and supports Create new and Restore disks.',
    concept: 'recovery-services-vault',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-enhanced-policy',
    front: 'What does an Enhanced VM backup policy offer that Standard does not?',
    back: 'Backups as often as every **4 hours** (4, 6, 8, 12 or 24), zone-redundant instant restore snapshots, and support for Trusted Launch VMs, Premium SSD v2 and Ultra Disks.',
    concept: 'backup-policy',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-enhanced-one-way',
    front: 'Can a VM protected with an Enhanced policy move back to a Standard one?',
    back: 'No — Azure Backup does not allow changing the policy type back to Standard. Migration from Standard to Enhanced is supported.',
    concept: 'backup-policy',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-instant-restore',
    front: 'What does instant restore retention control?',
    back: 'How long recovery snapshots stay in the operational tier for fast restores — **1 to 30 days, default 7**, never longer than vault retention, and lower when snapshots are more frequent.',
    concept: 'backup-policy',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-restore-options',
    front: 'Name the three Azure VM restore options.',
    back: '**Create new**, **Restore disks** (disks plus an ARM template, for special network configurations) and **Replace existing** — which requires the VM to still exist.',
    concept: 'azure-backup',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-replace-existing-limits',
    front: 'When can Replace existing not be used?',
    back: 'When the VM has been deleted, and for classic VMs, unmanaged VMs, generalized VMs and cross-region restores.',
    concept: 'azure-backup',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-file-recovery',
    front: 'How do you recover three deleted files without touching the running VM?',
    back: '**File recovery** — run the downloaded script to mount the recovery point as a drive, copy the files, then unmount.',
    concept: 'azure-backup',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-backup-reports',
    front: 'Why is Backup Reports empty on a vault that has run for a year?',
    back: 'No diagnostic setting is sending the vault’s backup data to a Log Analytics workspace — and enabling it now does not backfill history.',
    concept: 'recovery-services-vault',
    domain: 'monitoring',
    tier: 'should',
  },
  {
    id: 'fc-asr-lifecycle',
    front: 'Name the four Site Recovery operations in order.',
    back: '**Test failover** (a drill in an isolated network), **failover**, **commit**, **reprotect** (replication now runs in the reverse direction).',
    concept: 'site-recovery',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-asr-commit',
    front: 'What does Commit do after a Site Recovery failover?',
    back: 'Finishes the failover and **deletes all remaining recovery points**, so the recovery point can no longer be changed. Verify the failed-over VM first.',
    concept: 'site-recovery',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-asr-recovery-points',
    front: 'Latest or Latest processed — which gives the lowest RPO?',
    back: '**Latest**: it processes all data already sent to Site Recovery before failing over. **Latest processed** skips that work and gives the lowest RTO instead.',
    concept: 'site-recovery',
    domain: 'monitoring',
    tier: 'must',
  },
  {
    id: 'fc-recovery-plan',
    front: 'What is a Site Recovery recovery plan?',
    back: 'An ordered grouping of VMs for failover — database tier before application tier — with optional scripts and manual steps, turning a multi-VM failover into one rehearsed operation.',
    concept: 'site-recovery',
    domain: 'monitoring',
    tier: 'should',
  },
];
