import type { Flashcard } from '../schema';

export const NETWORKING_CARDS: Flashcard[] = [
  {
    id: 'fc-subnet-reserved',
    front: 'How many IP addresses does Azure reserve in every subnet?',
    back: 'Five: the network address, the default gateway, two for Azure DNS mapping, and the broadcast address. A /28 therefore has 11 usable addresses, not 14.',
    concept: 'subnet',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-vnet-region',
    front: 'Can a virtual network span two regions?',
    back: 'No. A virtual network exists in exactly one region and one subscription. Connect networks in different regions with global [[vnet-peering|peering]].',
    concept: 'vnet',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-public-ip-sku',
    front: 'What are the defaults for a Standard SKU public IP address?',
    back: 'Static allocation, zone-redundant where zones exist, and **closed by default** — inbound traffic needs an explicit NSG allow rule.',
    concept: 'public-ip',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-nsg-default-rules',
    front: 'What do the default NSG rules allow?',
    back: 'Inbound: traffic from within the virtual network and from the Azure load balancer; everything else is denied. Outbound: traffic to the virtual network and to the internet; everything else is denied.',
    concept: 'nsg',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-nsg-priority',
    front: 'How are NSG rules evaluated?',
    back: 'By priority, lowest number first, and the **first match wins** — no further rules are evaluated. Custom rules use 100–4096.',
    concept: 'nsg',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-nsg-both-levels',
    front: 'An NSG is on the subnet and another on the NIC. Which applies to inbound traffic?',
    back: 'Both. Inbound is evaluated at the subnet first, then the NIC; outbound is the reverse. Traffic must be allowed by both to pass.',
    concept: 'effective-security-rules',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-nsg-stateful',
    front: 'Do you need an outbound NSG rule for the reply to an allowed inbound connection?',
    back: 'No — NSGs are **stateful**. Return traffic for an allowed flow is permitted automatically.',
    concept: 'nsg',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-asg',
    front: 'What problem does an application security group solve?',
    back: 'It lets NSG rules name a **group of NICs** instead of IP ranges, so rules stay correct as machines are added and removed. Both ends of a rule using ASGs must be in the same virtual network.',
    concept: 'asg',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-service-tag',
    front: 'What is a service tag?',
    back: 'A Microsoft-maintained, automatically updated set of IP ranges for an Azure service — for example `Storage`, `AzureLoadBalancer` or `Internet` — used in place of literal addresses in NSG and route rules.',
    concept: 'service-tag',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-udr-precedence',
    front: 'What takes precedence: a user-defined route or a system route?',
    back: 'The user-defined route. Azure selects by longest prefix match, and for equal prefixes the order is UDR, then BGP route, then system route.',
    concept: 'route-table',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-next-hop-none',
    front: 'What does a route with next hop type "None" do?',
    back: 'Drops the traffic. It is how you black-hole a prefix deliberately.',
    concept: 'route-table',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-peering-transitive',
    front: 'Is VNet peering transitive?',
    back: 'No. If A peers with B and B peers with C, A cannot reach C. You need a direct peering, or a hub with a gateway or network virtual appliance and user-defined routes.',
    concept: 'vnet-peering',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-peering-overlap',
    front: 'What stops two virtual networks from being peered?',
    back: 'Overlapping address spaces. Peering requires non-overlapping ranges, locally and globally — re-address one network or connect it another way.',
    concept: 'vnet-peering',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-gateway-transit',
    front: 'What does "allow gateway transit" do in a peering?',
    back: 'It lets the peered network use this network’s VPN or ExpressRoute gateway. The other side must select "use remote gateways" — the two settings are a pair.',
    concept: 'hub-spoke',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-bastion-subnet',
    front: 'What subnet does Azure Bastion require?',
    back: 'A subnet named exactly **AzureBastionSubnet**, sized /26 or larger. Bastion gives browser-based RDP and SSH over TLS with no public IP on the target VM.',
    concept: 'bastion',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-service-vs-private-endpoint',
    front: 'Service endpoint or private endpoint — which gives the service a private IP in your VNet?',
    back: 'A **private endpoint**. A service endpoint keeps the public endpoint but routes to it over the Azure backbone and lets the service firewall trust the subnet.',
    concept: 'private-endpoint',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-private-endpoint-dns',
    front: 'What breaks most often when a private endpoint is created?',
    back: 'DNS. The resource’s public hostname must resolve to the private IP, which needs a private DNS zone linked to the virtual network — otherwise clients still reach the public endpoint.',
    concept: 'private-dns-zone',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-dns-autoregistration',
    front: 'What does autoregistration on a private DNS zone link do?',
    back: 'Azure creates and maintains A records for the VMs in the linked virtual network automatically. A network can be linked with autoregistration to only one zone.',
    concept: 'private-dns-zone',
    domain: 'networking',
    tier: 'should',
  },
  {
    id: 'fc-dns-ns-delegation',
    front: 'What must you change at the registrar to host a public domain in Azure DNS?',
    back: 'The domain’s name server (NS) records, pointing at the four Azure name servers listed on the zone. Creating the zone alone changes nothing.',
    concept: 'azure-dns',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-lb-skus',
    front: 'Basic or Standard load balancer — what are the key differences?',
    back: 'Standard is zone-redundant, secure by default (needs an NSG allow rule), supports larger backend pools and has an SLA. Basic has none of those.',
    concept: 'load-balancer',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-health-probe',
    front: 'What happens to traffic when a health probe fails for a backend instance?',
    back: 'The load balancer stops sending it **new** flows. Existing TCP connections continue until they end. An HTTP probe is healthy only on a 200 response.',
    concept: 'health-probe',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-probe-source',
    front: 'Which source address do Azure load balancer health probes come from?',
    back: '168.63.129.16, permitted by the default AllowAzureLoadBalancerInBound rule — unless a custom deny rule with a lower priority number blocks it.',
    concept: 'health-probe',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-nat-gateway',
    front: 'What does a NAT gateway provide?',
    back: 'Predictable, scalable **outbound** connectivity from a subnet using static public IPs. It does not accept inbound connections.',
    concept: 'nat-gateway',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-network-watcher-tools',
    front: 'Which Network Watcher tool answers “would this packet be allowed?”',
    back: '**IP flow verify** — it evaluates NSG rules for a specified five-tuple and names the rule that decided. **Next hop** answers where a packet would be routed.',
    concept: 'network-watcher',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-vpn-vs-expressroute',
    front: 'VPN gateway or ExpressRoute — which traverses the public internet?',
    back: 'The **VPN gateway** (an encrypted IPsec tunnel). ExpressRoute is a private circuit from a connectivity provider that never touches the public internet.',
    concept: 'expressroute',
    domain: 'networking',
    tier: 'must',
  },
  {
    id: 'fc-gateway-subnet',
    front: 'What subnet does a VPN or ExpressRoute gateway require?',
    back: 'A subnet named exactly **GatewaySubnet**. Do not attach an NSG to it.',
    concept: 'vpn-gateway',
    domain: 'networking',
    tier: 'must',
  },
];
