import type { Flashcard } from '../schema';

export const STORAGE_CARDS: Flashcard[] = [
  {
    id: 'fc-storage-account-name',
    front: 'What are the rules for a storage account name?',
    back: '3–24 characters, lowercase letters and numbers only, and **globally unique** — it becomes part of the public endpoint hostname.',
    concept: 'storage-account',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-redundancy-lrs',
    front: 'What does LRS protect against, and what does it not?',
    back: 'Three copies within a single datacentre — it survives disk, node and rack failures, but not the loss of the datacentre or the region.',
    concept: 'storage-redundancy',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-redundancy-zrs',
    front: 'What does ZRS protect against?',
    back: 'Copies across three availability zones in one region — it survives losing an entire datacentre, but not losing the region.',
    concept: 'storage-redundancy',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-redundancy-grs-read',
    front: 'GRS or RA-GRS: which lets you read the secondary copy before a failover?',
    back: '**RA-GRS**. Plain GRS keeps the secondary copy but it is not readable until Microsoft initiates a failover or you trigger a customer-managed one.',
    concept: 'storage-redundancy',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-access-tiers',
    front: 'Name the blob access tiers and their minimum retention periods.',
    back: 'Hot (no minimum), Cool (30 days), Cold (90 days), Archive (180 days). Deleting or moving data early incurs an early-deletion charge.',
    concept: 'access-tier',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-archive-rehydrate',
    front: 'Can you read a blob in the Archive tier directly?',
    back: 'No. Archive is offline — you must rehydrate the blob to Hot, Cool or Cold first, which takes hours depending on the rehydration priority.',
    concept: 'access-tier',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-lifecycle-scope',
    front: 'What does a lifecycle management policy act on?',
    back: 'Blobs, by rule — moving them between tiers or deleting them based on age or last access. It is defined on the storage account and runs on a schedule; it does not apply to file shares.',
    concept: 'lifecycle-management',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-soft-delete-vs-versioning',
    front: 'Blob soft delete or versioning — which protects against overwrites?',
    back: 'Both, differently. **Versioning** keeps a previous version on every overwrite. **Soft delete** retains deleted blobs (and overwritten data) for the retention period you set.',
    concept: 'blob-versioning',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-container-soft-delete',
    front: 'Does blob soft delete recover a deleted container?',
    back: 'No. Container soft delete is a separate setting — and restoring a container does not restore blobs deleted before the container was.',
    concept: 'blob-soft-delete',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-sas-types',
    front: 'Name the three types of shared access signature.',
    back: 'User delegation SAS (signed with Entra credentials — the most secure), service SAS and account SAS (both signed with a storage account key).',
    concept: 'sas',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-sas-revoke',
    front: 'How do you revoke a SAS before it expires?',
    back: 'Rotate the signing key — which invalidates every SAS signed with it — or associate the SAS with a [[stored-access-policy|stored access policy]] and change or delete the policy.',
    concept: 'sas',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-stored-access-policy',
    front: 'Why attach a SAS to a stored access policy?',
    back: 'Because the policy is server-side: you can change the expiry or permissions, or revoke the SAS entirely, without rotating the account key.',
    concept: 'stored-access-policy',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-storage-firewall-default',
    front: 'What happens when you switch a storage account’s network access to selected networks?',
    back: 'Everything is denied except the networks and IP ranges you allow — plus any trusted Azure services you have permitted. Check your own access before enabling it.',
    concept: 'storage-firewall',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-files-auth',
    front: 'What identity options does Azure Files support for SMB access?',
    back: 'The storage account key, or identity-based authentication over SMB with on-premises AD DS, Microsoft Entra Domain Services, or Microsoft Entra Kerberos for hybrid identities.',
    concept: 'files-identity-auth',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-files-permissions',
    front: 'How do share-level and NTFS permissions combine on an Azure file share?',
    back: 'Share-level RBAC roles decide who may mount the share; NTFS ACLs decide what they can do inside it. The **most restrictive** of the two applies.',
    concept: 'azure-files',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-share-snapshot',
    front: 'What is an Azure Files share snapshot?',
    back: 'A read-only, point-in-time, incremental copy of a share. Users can restore previous versions themselves, and a snapshot cannot be deleted while a later one depends on it.',
    concept: 'share-snapshot',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-object-replication',
    front: 'What does object replication do, and what does it require?',
    back: 'Asynchronously copies block blobs from a source container to a destination container in another account. It requires **blob versioning on both accounts** and change feed on the source.',
    concept: 'object-replication',
    domain: 'storage',
    tier: 'should',
  },
  {
    id: 'fc-azcopy-vs-explorer',
    front: 'AzCopy or Storage Explorer — which for a scripted, high-volume copy?',
    back: 'AzCopy: a command-line tool built for bulk and scheduled transfers. Storage Explorer is a GUI for browsing and ad-hoc work.',
    concept: 'azcopy',
    domain: 'storage',
    tier: 'should',
  },
  {
    id: 'fc-storage-encryption',
    front: 'Can you turn off encryption at rest for a storage account?',
    back: 'No. All data is encrypted with Storage Service Encryption. You can choose customer-managed keys in Key Vault instead of platform-managed keys, but not disable it.',
    concept: 'storage-encryption',
    domain: 'storage',
    tier: 'must',
  },
  {
    id: 'fc-access-keys-rotation',
    front: 'Why does a storage account have two access keys?',
    back: 'So you can rotate without downtime: move clients to key 2, regenerate key 1, then move back. Anything signed with the regenerated key stops working immediately.',
    concept: 'access-keys',
    domain: 'storage',
    tier: 'must',
  },
];
