import type { Concept } from '../schema';

export const COMPUTE_CONCEPTS: Concept[] = [
  {
    id: 'virtual-machine',
    name: 'Virtual machine (VM)',
    aliases: ['VM', 'Azure VM', 'IaaS', 'VM size', 'resize'],
    area: 'compute',
    kind: 'resource',
    tier: 'must',
    summary: 'On-demand, scalable compute with full control of the operating system; you manage the OS, patching and software.',
    simple: 'A VM is a computer in Azure that you rent. You choose its size and operating system and install whatever you need — but keeping it updated is your job.',
    why: 'Some workloads need OS-level control, specific software, or lift-and-shift from on-premises servers without rewriting them.',
    useWhen: ['Software needs OS access, custom drivers or unsupported runtimes', 'Lift-and-shift of existing servers', 'Full control over configuration'],
    avoidWhen: ['A standard web app or API — App Service removes patching and scaling work', 'Short containerized tasks — Container Instances or Container Apps are simpler'],
    howItWorks: [
      'A VM deployment creates several resources: the VM, an OS disk, a NIC, and usually a public IP and NSG (plus optional data disks).',
      'Sizes come in series optimized for general purpose, compute, memory, storage or GPU workloads.',
      'Resizing restarts the VM; if the new size isn’t available on the current hardware cluster, the VM must be deallocated first.',
      '**Stopped (deallocated)** releases compute and stops compute billing; stopping from inside the OS leaves it allocated and billed.',
      'Availability comes from zones, availability sets or scale sets — a single VM isn’t highly available.',
    ],
    example: 'A manufacturer runs a licensed MES application that requires Windows Server and a hardware dongle emulator, so it stays on VMs behind a load balancer.',
    mistakes: ['Shutting down from within the OS and still paying for compute.', 'Exposing RDP/SSH on a public IP instead of using Bastion.', 'Running a single VM for a production workload that needs high availability.'],
    examTips: [
      'List sizes you can resize to: `az vm list-vm-resize-options`.',
      'Stop billing for compute → deallocate (Stop in the portal or `az vm deallocate`).',
    ],
    troubleshooting: ['Can’t connect → check VM state, NSG rules (IP flow verify), and use boot diagnostics or serial console for OS-level issues.'],
    relations: {
      contains: [
        { to: 'managed-disk', label: 'OS and data disks' },
        { to: 'network-interface', label: 'Network connectivity' },
      ],
      dependsOn: [{ to: 'subnet', label: 'Placed in a subnet' }],
      security: [
        { to: 'encryption-at-host', label: 'End-to-end disk encryption' },
        { to: 'bastion', label: 'Secure RDP/SSH' },
        { to: 'managed-identity', label: 'Keyless access to Azure services' },
      ],
      integratesWith: [
        { to: 'availability-set', label: 'Fault and update domains' },
        { to: 'availability-zone', label: 'Zonal placement' },
        { to: 'vmss', label: 'Scale identical VMs' },
        { to: 'load-balancer', label: 'Distribute traffic' },
      ],
      monitoring: [
        { to: 'vm-insights', label: 'Guest performance and dependencies' },
        { to: 'azure-monitor-agent', label: 'Collect guest logs and metrics' },
      ],
      alternative: [
        { to: 'app-service', label: 'PaaS web hosting' },
        { to: 'container-instances', label: 'Run a container without a VM' },
      ],
    },
    cost: ['Compute billed per second while allocated; disks and public IPs are billed even when the VM is deallocated.'],
    place: ['subscription', 'resource-group'],
    sources: ['vm-availability', 'disk-types'],
  },
  {
    id: 'managed-disk',
    name: 'Managed disk',
    aliases: ['OS disk', 'data disk', 'temporary disk', 'Premium SSD', 'Premium SSD v2', 'Ultra Disk', 'Standard SSD', 'Standard HDD', 'disk snapshot'],
    area: 'compute',
    kind: 'resource',
    tier: 'must',
    summary: 'Block storage volumes for VMs managed by Azure: Ultra Disk, Premium SSD v2, Premium SSD, Standard SSD and Standard HDD.',
    simple: 'Managed disks are the hard drives of your VMs. Pick a faster (and pricier) type for busy databases and a cheaper type for light workloads.',
    why: 'Workloads have very different performance and cost needs, and Azure should handle the storage accounts, replication and scale behind the disks.',
    howItWorks: [
      '**Ultra Disk** and **Premium SSD v2**: set capacity, IOPS and throughput independently; can’t be OS disks; no host caching.',
      '**Premium SSD**: production performance with fixed size tiers; can be an OS disk.',
      '**Standard SSD**: web servers, lightly used apps, dev/test.',
      '**Standard HDD**: backups and non-critical data; OS disk use retires on September 8, 2028.',
      'The **temporary disk** is local to the host and can lose data on redeploy, resize or maintenance — never store important data there.',
      'Disks can be expanded (not shrunk); snapshots are billed on used size.',
      'Managed disks support LRS and ZRS redundancy.',
    ],
    example: 'A SQL Server VM uses Premium SSD v2 for data and log volumes tuned to 12,000 IOPS, and Premium SSD for the OS disk.',
    mistakes: ['Storing application data on the temporary disk.', 'Choosing Ultra Disk or Premium SSD v2 for the OS disk.'],
    examTips: ['OS disk options: Premium SSD, Standard SSD (Standard HDD retiring for OS use). Not Ultra or Premium SSD v2.'],
    relations: {
      partOf: [{ to: 'virtual-machine', label: 'Attached to VMs' }],
      security: [
        { to: 'encryption-at-host', label: 'Encrypts caches, temp disk and data flows' },
        { to: 'storage-encryption', label: 'Server-side encryption at rest' },
      ],
      integratesWith: [
        { to: 'azure-backup', label: 'VM backup snapshots disks' },
        { to: 'backup-vault', label: 'Azure Disk Backup' },
      ],
    },
    cost: ['Billed on the provisioned size tier, not used space (Premium SSD v2 and Ultra also bill IOPS and throughput).'],
    place: ['resource-group', 'virtual-machine'],
    sources: ['disk-types'],
  },
  {
    id: 'encryption-at-host',
    name: 'Encryption at host',
    aliases: ['EncryptionAtHost', 'host-based encryption', 'Azure Disk Encryption', 'ADE', 'disk encryption set'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'A VM setting that extends server-side encryption to temporary disks, disk caches and data flowing between the VM host and storage.',
    simple: 'Disks in Azure are always encrypted in storage. Encryption at host also encrypts the temporary disk and the cached data on the physical server running your VM.',
    why: 'Standard server-side encryption doesn’t cover temp disks or host caches. Encryption at host closes that gap without consuming VM CPU — and it replaces Azure Disk Encryption, which is retiring.',
    howItWorks: [
      '**Server-side encryption** (always on) encrypts managed disks at rest with platform-managed or customer-managed keys (via a disk encryption set); it doesn’t cover temp disks or caches.',
      '**Encryption at host** encrypts temp disks and caches at rest and data flows to storage; it works with custom images and doesn’t use guest CPU.',
      'The subscription must have the `EncryptionAtHost` feature registered, and the VM size must support it.',
      'To enable on an existing VM, deallocate it first.',
      '**Azure Disk Encryption** (BitLocker / DM-Crypt in the guest) retires on **September 15, 2028**; Microsoft recommends encryption at host for new VMs and migrating ADE VMs.',
    ],
    example: '`az vm update --resource-group rg-app --name vm-app01 --set securityProfile.encryptionAtHost=true` (run while the VM is deallocated).',
    mistakes: ['Trying to enable encryption at host on a running VM.', 'Choosing Azure Disk Encryption for a new deployment.'],
    examTips: [
      'The April 2026 outline says “Configure encryption at host” — not Azure Disk Encryption.',
      'Temp disk and caches must be encrypted → encryption at host.',
    ],
    relations: {
      partOf: [{ to: 'virtual-machine', label: 'A VM security profile setting' }],
      dependsOn: [{ to: 'managed-disk', label: 'Extends disk server-side encryption' }],
      integratesWith: [{ to: 'key-vault', label: 'Customer-managed keys via disk encryption sets' }],
    },
    sources: ['disk-encryption'],
  },
  {
    id: 'availability-set',
    name: 'Availability set',
    aliases: ['fault domain', 'update domain', 'FD', 'UD'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'A logical grouping that spreads VMs across fault domains (separate power and network) and update domains (separate maintenance) within a datacenter.',
    simple: 'An availability set makes sure your VMs aren’t all on the same rack or rebooted for maintenance at the same time.',
    why: 'Hardware failures and planned maintenance affect groups of servers. Spreading VMs means one event doesn’t take down every copy of your application.',
    useWhen: ['Region has no availability zones', 'Very low VM-to-VM latency is required'],
    avoidWhen: ['You need to survive a datacenter or zone failure — use availability zones'],
    howItWorks: [
      'Up to **3 fault domains** (shared power and network switch) and **20 update domains** (rebooted together during planned maintenance, one at a time).',
      'Two or more VMs in an availability set qualify for a **99.95%** SLA.',
      'A VM joins an availability set only when it is created, and can’t use both an availability set and a zone.',
      'No cost for the set itself.',
      'Microsoft recommends VM Scale Sets with Flexible orchestration for the broadest high-availability features.',
    ],
    examTips: ['Availability set: 99.95%. VMs across availability zones: 99.99%.', 'Adding an existing VM to an availability set requires recreating the VM (keeping its disks).'],
    visual: { type: 'interactive', id: 'availability-simulator', title: 'Simulate rack, maintenance and zone failures' },
    relations: {
      integratesWith: [{ to: 'virtual-machine', label: 'Groups VMs' }],
      alternative: [
        { to: 'availability-zone', label: 'Datacenter-level protection' },
        { to: 'vmss', label: 'Flexible orchestration is recommended' },
      ],
    },
    confusedWith: [{ id: 'availability-zone', difference: 'Availability sets protect against rack and maintenance events within one datacenter (99.95%). Zones protect against a whole datacenter failing (99.99%).' }],
    sources: ['availability-sets', 'vm-availability'],
  },
  {
    id: 'vmss',
    name: 'Virtual Machine Scale Sets',
    aliases: ['VMSS', 'scale set', 'Flexible orchestration', 'Uniform orchestration'],
    area: 'compute',
    kind: 'service',
    tier: 'must',
    summary: 'A group of load-balanced VMs managed together that can scale in and out automatically and spread across zones and fault domains.',
    simple: 'A scale set is a fleet of VMs managed as one unit. When traffic grows, it adds VMs; when traffic drops, it removes them.',
    why: 'Manually adding and configuring VMs for demand spikes is slow and error-prone; scale sets automate capacity and availability.',
    howItWorks: [
      '**Flexible** orchestration (recommended): standard VMs, up to 1,000 instances, mixed sizes and Spot/on-demand, Azure Backup and Site Recovery support, no default outbound access.',
      '**Uniform** orchestration: identical instances from a model, automatic OS image upgrades and upgrade policies; used by AKS and Service Fabric.',
      'The orchestration mode is chosen at creation and can’t be changed.',
      'Scale manually, on a schedule, or with metric-based autoscale rules; instance protection and scale-in policies control which VMs are removed.',
      'The scale set resource itself is free; you pay for the VMs, disks and networking.',
    ],
    example: 'A ticketing site runs a Flexible scale set across three zones, scaling from 3 to 20 instances when average CPU exceeds 70% for 10 minutes.',
    mistakes: ['Expecting a Flexible scale set’s instances to reach the internet without explicit outbound connectivity.', 'Setting scale-out and scale-in thresholds so close that the set keeps flapping.'],
    examTips: ['Orchestration mode can’t be changed after creation.', 'Across zones → 99.99%; across fault domains → 99.95%.'],
    visual: { type: 'interactive', id: 'autoscale-simulator', title: 'Tune autoscale rules against real load' },
    relations: {
      contains: [{ to: 'virtual-machine', label: 'Instances' }],
      integratesWith: [
        { to: 'autoscale', label: 'Metric and schedule rules' },
        { to: 'load-balancer', label: 'Distribute traffic across instances' },
        { to: 'availability-zone', label: 'Spread across zones' },
      ],
      networking: [{ to: 'nat-gateway', label: 'Explicit outbound for Flexible instances' }],
      alternative: [{ to: 'availability-set', label: 'Static groups without autoscale' }],
    },
    sources: ['vmss-modes', 'vm-availability'],
  },
  {
    id: 'autoscale',
    name: 'Autoscale',
    aliases: ['Azure Monitor autoscale', 'scale-out rule', 'scale-in rule', 'cool down', 'scale condition'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'Azure Monitor rules that change the instance count of scale sets, App Service plans and other resources based on metrics or schedules.',
    simple: 'Autoscale watches a number such as CPU and adds or removes servers automatically, within the minimum and maximum you set.',
    why: 'Paying for peak capacity all day wastes money; running minimum capacity during peaks hurts users.',
    howItWorks: [
      'A profile has **minimum**, **maximum** and **default** instance counts.',
      'Rules: a metric, aggregation, threshold, time window and action (increase or decrease by a count or percentage), plus a **cool down**.',
      'Pair every scale-out rule with a scale-in rule, with a gap between thresholds to avoid flapping.',
      'Schedule-based profiles set capacity for known periods such as business hours.',
    ],
    example: '`az monitor autoscale rule create --resource-group rg --autoscale-name web-autoscale --condition "Percentage CPU > 70 avg 10m" --scale out 2`',
    mistakes: ['Only creating a scale-out rule, so instances never scale back in.'],
    examTips: ['App Service autoscale rules require Standard tier or higher.', 'Minimum instance count protects availability even when load is zero.'],
    relations: {
      integratesWith: [
        { to: 'vmss', label: 'Scale VM instances' },
        { to: 'app-service-plan', label: 'Scale plan instances' },
        { to: 'metrics', label: 'Rules evaluate metrics' },
      ],
      partOf: [{ to: 'azure-monitor', label: 'An Azure Monitor feature' }],
    },
    sources: ['appservice-scale-up', 'vmss-modes'],
  },
  {
    id: 'arm-template',
    name: 'ARM template',
    aliases: ['Azure Resource Manager template', 'JSON template', 'deployment mode', 'incremental mode', 'complete mode', 'what-if', 'export template'],
    area: 'compute',
    kind: 'tool',
    tier: 'must',
    summary: 'A declarative JSON file describing Azure resources — parameters, variables, resources and outputs — deployed through Azure Resource Manager.',
    simple: 'An ARM template is a recipe written in JSON. Give it to Azure and it builds exactly what the recipe describes, the same way every time.',
    why: 'Clicking through the portal isn’t repeatable or reviewable. Templates make environments consistent, version-controlled and easy to recreate.',
    howItWorks: [
      'Sections: `$schema`, `contentVersion`, `parameters`, `variables`, `resources` (type, apiVersion, name, location, properties), `outputs`; functions such as `resourceGroup().location`, `uniqueString()` and `resourceId()`.',
      '**Incremental** mode (default): resources in the resource group but not in the template are left alone; resources in the template are created or updated — and properties you omit are **reset to defaults**.',
      '**Complete** mode: deletes resources in the resource group that aren’t in the template. Not recommended and being gradually deprecated; not supported at subscription scope or in the portal.',
      'Run **what-if** to preview changes before deploying.',
      '**Export template** from a resource group creates a snapshot (up to 200 resources, often with hard-coded values); the **deployment history** keeps the exact template that was deployed.',
      'You can’t change an existing resource’s location or type through a deployment.',
    ],
    example: '`az deployment group create --resource-group rg-app --template-file azuredeploy.json --parameters storageSku=Standard_ZRS`',
    mistakes: [
      'Using complete mode and deleting resources that weren’t in the template.',
      'Redeploying a VNet template without its subnets defined in the VNet’s subnets property and losing them.',
    ],
    examTips: [
      'Default deployment mode is incremental.',
      'Complete mode deletes resources not in the template — know this even though it is discouraged.',
      'Convert JSON to Bicep with `az bicep decompile --file main.json`.',
    ],
    visual: { type: 'interactive', id: 'deployment-modes', title: 'Incremental vs complete mode' },
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Deployed by ARM' }],
      alternative: [
        { to: 'bicep', label: 'Cleaner syntax that compiles to ARM JSON' },
        { to: 'azure-cli', label: 'Imperative scripts' },
      ],
    },
    sources: ['arm-deployment-modes', 'arm-export', 'bicep-decompile'],
  },
  {
    id: 'bicep',
    name: 'Bicep',
    aliases: ['Bicep file', '.bicep', 'bicep decompile', 'bicep build', 'module'],
    area: 'compute',
    kind: 'tool',
    tier: 'must',
    summary: 'A domain-specific language for declaratively deploying Azure resources that compiles to ARM template JSON.',
    simple: 'Bicep is a friendlier way to write ARM templates. It’s shorter and easier to read, and Azure turns it into the same JSON behind the scenes.',
    why: 'ARM JSON is verbose and hard to review. Bicep offers the same capabilities with less code, type checking and modules.',
    howItWorks: [
      'Declarations: `param`, `var`, `resource`, `module`, `output`, with decorators such as `@allowed` and `@description`.',
      'Symbolic names (`storage.id`) create dependencies automatically — no manual `dependsOn` in most cases.',
      '`az bicep build` compiles Bicep to JSON; `az bicep decompile --file main.json` converts JSON to Bicep on a best-effort basis.',
      'Deploy directly: `az deployment group create --resource-group rg --template-file main.bicep`.',
      'The portal can export resource groups as Bicep.',
    ],
    example: "param location string = resourceGroup().location\nresource st 'Microsoft.Storage/storageAccounts@2025-06-01' = {\n  name: 'st${uniqueString(resourceGroup().id)}'\n  location: location\n  sku: { name: 'Standard_ZRS' }\n  kind: 'StorageV2'\n}",
    mistakes: ['Assuming decompiled Bicep is perfect — review warnings and hard-coded values.'],
    examTips: ['Bicep and ARM JSON support the same deployment modes, scopes and resource types.'],
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Compiles to ARM JSON and deploys through ARM' }],
      alternative: [{ to: 'arm-template', label: 'JSON equivalent' }],
      integratesWith: [{ to: 'azure-cli', label: 'Bicep CLI ships with Azure CLI' }],
    },
    sources: ['bicep-decompile', 'arm-deployment-modes'],
  },
  {
    id: 'app-service',
    name: 'Azure App Service',
    aliases: ['web app', 'Web Apps', 'PaaS web hosting', 'azurewebsites.net'],
    area: 'compute',
    kind: 'service',
    tier: 'must',
    summary: 'A fully managed platform for hosting web apps, REST APIs and mobile back ends on Windows or Linux, with built-in scaling, slots, TLS and networking features.',
    simple: 'App Service runs your website or API without you managing servers. You upload the code; Azure handles the operating system, patching and load balancing.',
    why: 'Most web applications don’t need OS access. Offloading infrastructure work lets teams focus on the application.',
    useWhen: ['Web apps and APIs in .NET, Java, Node.js, Python, PHP or a custom container', 'You want slots, autoscale, custom domains and TLS without building them'],
    avoidWhen: ['The app needs OS-level control or unsupported software — use a VM', 'Event-driven microservices that scale to zero — consider Container Apps'],
    howItWorks: [
      'Every app runs in an [[app-service-plan|App Service plan]], which defines the region, OS, instance size and count, and pricing tier.',
      'Default hostname: `<app>.azurewebsites.net`; custom domains and TLS certificates need a paid tier.',
      '**Deployment slots** (Standard and above) enable staged releases with swaps.',
      '**Inbound** networking: access restrictions, private endpoints, app-assigned address. **Outbound**: VNet integration, Hybrid Connections.',
      'Backups: automatic hourly backups (Basic and above) and custom backups to a storage account.',
    ],
    example: 'An insurer hosts its customer portal on a Premium v3 Linux plan with a staging slot, a managed certificate for portal.contoso.com, and VNet integration to reach a private database.',
    mistakes: ['Choosing the Free or Shared tier for production and then needing custom TLS, slots or scale-out.'],
    examTips: [
      'App Service vs VM: choose App Service unless the scenario needs OS access or unsupported software.',
      'Many App Service scenario answers hinge on the tier: slots and autoscale need Standard+; custom domain TLS needs Basic+.',
    ],
    relations: {
      dependsOn: [{ to: 'app-service-plan', label: 'Runs on a plan’s instances' }],
      contains: [{ to: 'deployment-slot', label: 'Staging and production slots' }],
      security: [
        { to: 'app-service-certificate', label: 'TLS for custom domains' },
        { to: 'managed-identity', label: 'Access Azure resources without secrets' },
      ],
      networking: [
        { to: 'private-endpoint', label: 'Private inbound access' },
        { to: 'vnet-integration', label: 'Outbound to private resources' },
      ],
      integratesWith: [{ to: 'azure-dns', label: 'Custom domain records' }],
      monitoring: [{ to: 'diagnostic-settings', label: 'HTTP and application logs' }],
      alternative: [
        { to: 'virtual-machine', label: 'Full OS control' },
        { to: 'container-apps', label: 'Serverless containers' },
      ],
    },
    sources: ['appservice-plans', 'appservice-networking', 'appservice-slots'],
  },
  {
    id: 'app-service-plan',
    name: 'App Service plan',
    aliases: ['pricing tier', 'Basic', 'Standard', 'Premium v3', 'Isolated v2', 'scale up', 'scale out'],
    area: 'compute',
    kind: 'resource',
    tier: 'must',
    summary: 'The set of compute resources (region, OS, instance size, instance count and pricing tier) that one or more App Service apps run on.',
    simple: 'The plan is the server farm your web apps share. Its tier decides how powerful the servers are, how many you can have, and which features you get.',
    why: 'Separating compute from apps lets several apps share capacity and scale together, or be isolated on separate plans.',
    howItWorks: [
      '**Free** and **Shared**: shared compute, no scale-out — development only.',
      '**Basic**: dedicated instances, up to 3; custom domains and TLS; no slots or autoscale.',
      '**Standard**: up to 10 instances, **deployment slots** (5) and autoscale.',
      '**Premium (v3/v4)**: up to 30 instances, more slots, better performance and features.',
      '**Isolated v2**: App Service Environment — single-tenant in your VNet, up to 100 instances.',
      '**Scale up** = change tier; **scale out** = add instances. All apps and slots in a plan share its instances.',
    ],
    examTips: [
      'Slots → Standard or higher. Autoscale → Standard or higher. Custom domain + TLS → Basic or higher.',
      'Scale-out limits: Basic 3, Standard 10, Premium 30, Isolated 100.',
      'Apps in one plan compete for the same resources — move a noisy app to its own plan.',
    ],
    relations: {
      contains: [{ to: 'app-service', label: 'Apps share the plan' }],
      integratesWith: [{ to: 'autoscale', label: 'Scale out automatically' }],
      governance: [{ to: 'resource-lock', label: 'A ReadOnly lock blocks scaling the plan' }],
    },
    cost: ['Dedicated tiers bill per instance per hour whether apps are busy or idle.'],
    sources: ['appservice-plans', 'appservice-scale-up'],
  },
  {
    id: 'deployment-slot',
    name: 'Deployment slot',
    aliases: ['staging slot', 'slot swap', 'swap with preview', 'slot setting', 'sticky setting', 'traffic routing'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'A live App Service app with its own hostname, in the same plan, used to deploy and warm up a release before swapping it into production.',
    simple: 'A slot is a copy of your website where you test the new version. When it’s ready, you swap it with production instantly — and swap back if something breaks.',
    why: 'Deploying straight to production causes downtime and risky cold starts. Swapping a warmed-up slot gives near-zero-downtime releases with instant rollback.',
    howItWorks: [
      'Requires **Standard, Premium or Isolated** tier; Standard allows 5 slots.',
      'Each slot has a hostname like `<app>-staging.azurewebsites.net` and runs on the same plan instances.',
      'A swap applies production’s slot-specific settings to staging, warms it up, then switches routing — production never goes down.',
      '**Swapped**: app settings and connection strings (unless marked **Deployment slot setting**), framework versions, handler mappings, WebJobs content.',
      '**Stay with the slot**: custom domains, non-public certificates and TLS settings, scale settings, access restrictions, Always On, managed identities, VNet integration, diagnostic settings, CORS.',
      '**Swap with preview** pauses after applying settings; **auto swap** isn’t supported for Linux apps; **traffic routing** can send a percentage of users to a slot.',
    ],
    example: 'The team deploys v2.4 to staging, runs smoke tests against its URL, swaps into production at 9:00, and swaps back at 9:05 after spotting an error.',
    mistakes: ['Forgetting to mark the staging database connection string as a slot setting, so it follows the code into production.'],
    examTips: [
      'A setting that must stay with the environment → mark it as a deployment slot setting.',
      'Roll back a bad release → swap again.',
      'Custom domains and scale settings don’t swap.',
    ],
    visual: { type: 'interactive', id: 'slot-swap', title: 'Swap slots and watch the settings' },
    relations: {
      partOf: [{ to: 'app-service', label: 'A slot of a web app' }],
      dependsOn: [{ to: 'app-service-plan', label: 'Standard tier or higher' }],
    },
    sources: ['appservice-slots'],
  },
  {
    id: 'app-service-certificate',
    name: 'App Service TLS certificate',
    aliases: ['managed certificate', 'TLS binding', 'SNI SSL', 'IP SSL', 'custom domain certificate', 'asuid'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'Certificates that secure custom domains on App Service: free managed certificates, App Service certificates, Key Vault certificates or uploaded PFX files, bound with SNI or IP SSL.',
    simple: 'A TLS certificate is what makes https:// work on your own domain name. App Service can give you a free one or use a certificate you already have.',
    why: 'Browsers warn on or block sites without a valid certificate for the domain being used.',
    howItWorks: [
      'Adding certificates requires **Basic** or higher.',
      '**App Service managed certificate**: free and auto-renewed; no wildcard, not exportable, not for App Service Environment; the app must be publicly reachable for validation.',
      'Other options: purchased App Service certificate, import from Key Vault, or upload a password-protected PFX with the full chain.',
      '**SNI SSL** bindings are free and support many certificates; **IP SSL** gives a dedicated IP and needs Standard or higher.',
      'Custom domain validation uses a TXT record `asuid` (root) or `asuid.<subdomain>`, plus an A record (root) or CNAME (subdomain) to the app.',
    ],
    examTips: [
      'Wildcard certificate → not the free managed certificate.',
      'Apex domain → A record + TXT asuid; www subdomain → CNAME to <app>.azurewebsites.net + TXT asuid.www.',
    ],
    relations: {
      partOf: [{ to: 'app-service', label: 'Secures custom domains' }],
      integratesWith: [
        { to: 'azure-dns', label: 'Domain verification records' },
        { to: 'key-vault', label: 'Import certificates from Key Vault' },
      ],
    },
    sources: ['appservice-certs', 'appservice-custom-domain'],
  },
  {
    id: 'vnet-integration',
    name: 'App Service VNet integration',
    aliases: ['virtual network integration', 'regional VNet integration', 'outbound networking', 'Hybrid Connections', 'access restrictions'],
    area: 'compute',
    kind: 'feature',
    tier: 'must',
    summary: 'Lets an App Service app send outbound traffic into a virtual network in the same region to reach private resources; it doesn’t provide private inbound access.',
    simple: 'VNet integration is a one-way door out of your web app into your private network, so the app can reach private databases and services.',
    why: 'Apps often need to call databases, APIs or on-premises systems that aren’t exposed to the internet.',
    howItWorks: [
      'Regional VNet integration uses a dedicated subnet in a VNet in the **same region**; it can reach peered VNets, VPN/ExpressRoute-connected networks and service-endpoint-secured services.',
      'NSGs and route tables on the integration subnet apply to outbound traffic when routing all traffic into the VNet.',
      'It’s **outbound only** — for private inbound access use a private endpoint; to filter inbound use access restrictions.',
      '**Hybrid Connections** reach a single on-premises host and port through Azure Relay without a VPN.',
    ],
    examTips: [
      'App must reach a private SQL database → VNet integration (outbound). Users must reach the app privately → private endpoint (inbound).',
      'Allow only certain IPs to reach the app → access restrictions.',
    ],
    relations: {
      partOf: [{ to: 'app-service', label: 'Outbound networking feature' }],
      dependsOn: [{ to: 'subnet', label: 'Dedicated integration subnet' }],
      alternative: [{ to: 'private-endpoint', label: 'Private inbound instead' }],
    },
    confusedWith: [{ id: 'private-endpoint', difference: 'VNet integration is for traffic leaving the app. A private endpoint is for traffic coming into the app.' }],
    sources: ['appservice-networking'],
  },
  {
    id: 'container-registry',
    name: 'Azure Container Registry (ACR)',
    aliases: ['ACR', 'registry', 'azurecr.io', 'AcrPull', 'AcrPush', 'geo-replication'],
    area: 'compute',
    kind: 'service',
    tier: 'must',
    summary: 'A managed, private registry for container images and artifacts, in Basic, Standard and Premium SKUs.',
    simple: 'A container registry is a private library for your container images. Your apps pull images from it when they start.',
    why: 'Production images shouldn’t depend on public registries; teams need private, secured, geographically close image storage.',
    howItWorks: [
      'Login server: `<name>.azurecr.io`.',
      '**Basic** (10 GiB included), **Standard** (100 GiB), **Premium** (500 GiB). Premium adds geo-replication, private endpoints, public IP network rules and customer-managed keys.',
      'Change SKU at any time without downtime.',
      'Authenticate with Microsoft Entra identities (`az acr login`, token valid 3 hours), service principals or managed identities, using roles such as **AcrPull** and **AcrPush**.',
      'The **admin user** is disabled by default and not recommended for shared use.',
    ],
    example: 'A Container App pulls its image from acrcontoso.azurecr.io using a user-assigned managed identity with the AcrPull role.',
    mistakes: ['Enabling the admin user for CI/CD instead of a service principal or managed identity.'],
    examTips: ['Private endpoint or geo-replication needed → Premium.', 'Pull-only access for a workload → AcrPull.'],
    relations: {
      integratesWith: [
        { to: 'container-instances', label: 'Pull images' },
        { to: 'container-apps', label: 'Pull images' },
        { to: 'app-service', label: 'Custom containers' },
      ],
      security: [
        { to: 'managed-identity', label: 'Keyless image pulls' },
        { to: 'role-assignment', label: 'AcrPull and AcrPush roles' },
      ],
      networking: [{ to: 'private-endpoint', label: 'Private access (Premium)' }],
    },
    sources: ['acr-skus', 'acr-auth'],
  },
  {
    id: 'container-instances',
    name: 'Azure Container Instances (ACI)',
    aliases: ['ACI', 'container group', 'restart policy', 'azurecontainer.io'],
    area: 'compute',
    kind: 'service',
    tier: 'must',
    summary: 'Runs Linux or Windows containers on demand without managing servers or an orchestrator, billed per second for requested CPU and memory.',
    simple: 'Container Instances is the quickest way to run a container in Azure: give it an image, CPU and memory, and it starts in seconds.',
    why: 'Simple tasks, batch jobs and build agents don’t need a full orchestration platform.',
    useWhen: ['Short-lived tasks, batch jobs and simple apps', 'Quick testing of a container image'],
    avoidWhen: ['You need autoscaling, revisions or HTTP ingress with traffic splitting — use Container Apps'],
    howItWorks: [
      'A **container group** is a set of containers sharing a host, network and storage (multiple containers per group are Linux only).',
      'Specify CPU cores and memory (GB) per container.',
      '**Restart policies**: `Always` (default), `OnFailure`, `Never`.',
      'Public IP with a DNS name label: `<label>.<region>.azurecontainer.io`; the IP may change on restart.',
      'Mount Azure Files shares for persistence; deploy into a VNet subnet (outbound then needs a NAT gateway).',
    ],
    example: '`az container create --resource-group rg --name nightly-report --image acrcontoso.azurecr.io/report:1.4 --cpu 1 --memory 1.5 --restart-policy OnFailure --os-type Linux`',
    mistakes: ['Using the default Always restart policy for a run-once job, so it keeps restarting.'],
    examTips: ['Run a job once and stop when finished → restart policy Never or OnFailure.', 'Container data must survive restarts → mount an Azure file share.'],
    relations: {
      dependsOn: [{ to: 'container-registry', label: 'Pull private images' }],
      integratesWith: [{ to: 'azure-files', label: 'Persistent volumes' }],
      alternative: [
        { to: 'container-apps', label: 'Autoscaling, revisions and ingress' },
        { to: 'virtual-machine', label: 'Full control' },
      ],
    },
    sources: ['aci-overview'],
  },
  {
    id: 'container-apps',
    name: 'Azure Container Apps',
    aliases: ['ACA', 'Container Apps environment', 'revision', 'scale rule', 'KEDA', 'scale to zero', 'replicas'],
    area: 'compute',
    kind: 'service',
    tier: 'must',
    summary: 'A serverless platform for containerized apps and jobs with built-in ingress, revisions and KEDA-based autoscaling, including scale to zero.',
    simple: 'Container Apps runs your containers and automatically adds copies when requests or queue messages pile up — and can shrink to zero when nothing is happening.',
    why: 'Microservices and event-driven apps need autoscaling, service discovery and safe rollouts without operating Kubernetes.',
    useWhen: ['Microservices and APIs that scale with HTTP traffic or events', 'Background processing that can scale to zero'],
    avoidWhen: ['Direct access to Kubernetes APIs is required', 'A single simple container task — ACI is simpler'],
    howItWorks: [
      'Apps run in an **environment** — a secure boundary sharing a VNet and Log Analytics workspace. Workload profiles environments (Consumption and Dedicated) are the default.',
      'Scale limits per revision: **min replicas default 0**, **max replicas default 10** (configurable up to 1,000).',
      'Scale rules: **HTTP** (concurrent requests, default 10), **TCP** (concurrent connections), **custom** KEDA scalers (Service Bus, Event Hubs, Azure Queue, CPU, memory…).',
      'Scaling changes create a new **revision**; ingress can split traffic between revisions.',
      'Consumption plan CPU and memory come in pairs at a 1:2 ratio (for example 0.5 vCPU / 1 Gi) up to 4 vCPU / 8 Gi.',
      'No usage charges while scaled to zero.',
    ],
    example: '`az containerapp create --name orders-api --resource-group rg --environment cae-prod --image acrcontoso.azurecr.io/orders:2.1 --ingress external --target-port 8080 --min-replicas 1 --max-replicas 20 --scale-rule-name http --scale-rule-type http --scale-rule-http-concurrency 50`',
    mistakes: ['Disabling ingress and leaving min replicas at 0 with no event rule — the app scales to zero and can’t start again.'],
    examTips: ['Must never scale to zero (avoid cold starts) → set min replicas ≥ 1.', 'Scale on queue length → custom KEDA scale rule.'],
    relations: {
      dependsOn: [{ to: 'container-registry', label: 'Pull images' }],
      integratesWith: [
        { to: 'log-analytics-workspace', label: 'Environment log destination' },
        { to: 'queue-storage', label: 'Event-driven scaling' },
      ],
      security: [{ to: 'managed-identity', label: 'Pull images and reach services' }],
      alternative: [
        { to: 'container-instances', label: 'Simple single containers' },
        { to: 'app-service', label: 'Web apps without containers' },
      ],
    },
    sources: ['aca-scale', 'aca-environment', 'aca-containers'],
  },
];
