import type { Concept } from '../schema';

export const FOUNDATION_CONCEPTS: Concept[] = [
  {
    id: 'entra-tenant',
    name: 'Microsoft Entra tenant',
    aliases: ['tenant', 'directory', 'Azure AD tenant', 'Azure Active Directory tenant'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A dedicated instance of Microsoft Entra ID that holds an organization’s users, groups and app identities, and that Azure subscriptions trust for sign-in.',
    simple: 'The tenant is your organization’s identity directory in the Microsoft cloud — the place where every user account and group lives. Azure asks the tenant “who is this?” before letting anyone manage resources.',
    why: 'Resources need a trusted source of identities. Separating the directory (who you are) from subscriptions (where resources live) lets many subscriptions share one set of users and one set of security policies.',
    howItWorks: [
      'Every Azure subscription trusts exactly one tenant. One tenant can be trusted by many subscriptions.',
      'The tenant authenticates users, groups, service principals and managed identities.',
      '**Microsoft Entra roles** (for example Global Administrator) control the directory itself; **Azure roles** control Azure resources inside subscriptions.',
      'The root management group of the hierarchy is created for the tenant and uses the tenant ID as its ID.',
    ],
    example: 'Contoso has one tenant, contoso.onmicrosoft.com, with a verified custom domain contoso.com. Its production, development and sandbox subscriptions all trust that tenant, so an engineer signs in once and sees whichever subscriptions they have been granted roles in.',
    mistakes: [
      'Assuming a Global Administrator automatically has access to Azure resources. They must first elevate access (which grants User Access Administrator at root scope) or be assigned an Azure role.',
      'Changing a subscription’s directory without planning: Azure role assignments from the previous tenant are not transferred.',
    ],
    examTips: [
      'A subscription trusts one tenant; a tenant can have many subscriptions.',
      'Moving a subscription to another tenant removes existing Azure role assignments — they must be recreated in the new tenant.',
    ],
    relations: {
      contains: [
        { to: 'entra-user', label: 'Member and guest user accounts' },
        { to: 'entra-group', label: 'Security and Microsoft 365 groups' },
        { to: 'service-principal', label: 'App and workload identities' },
      ],
      integratesWith: [
        { to: 'subscription', label: 'Subscriptions trust one tenant for authentication' },
        { to: 'management-group', label: 'The root management group is created per tenant' },
      ],
      security: [
        { to: 'entra-roles', label: 'Directory roles such as Global Administrator' },
        { to: 'sspr', label: 'Self-service password reset is configured per tenant' },
      ],
    },
    confusedWith: [
      {
        id: 'subscription',
        difference: 'A tenant holds identities; a subscription holds resources and bills for them. A tenant can have many subscriptions, but each subscription trusts only one tenant.',
      },
    ],
    troubleshooting: [
      'User can sign in but sees no subscriptions → they have no Azure role assignment in any subscription that trusts this tenant (or the portal directory filter hides it).',
      'All role assignments disappeared after a subscription was moved → the subscription was associated with a different tenant; recreate the assignments there.',
    ],
    place: [],
    sources: ['subscription-tenant', 'roles-compare', 'management-groups'],
  },
  {
    id: 'azure-resource',
    name: 'Azure resource',
    aliases: ['resource', 'resource instance'],
    area: 'foundations',
    kind: 'principle',
    tier: 'must',
    summary: 'Any manageable item you create in Azure — a VM, storage account, virtual network, web app — managed through Azure Resource Manager.',
    simple: 'A resource is one “thing” you run or store in Azure. A virtual machine is a resource, a storage account is a resource, and even the network card attached to a VM is its own resource.',
    why: 'Treating everything as a resource with a consistent ID, location, tags and permissions means the same tools, policies and access rules work for every service.',
    howItWorks: [
      'Every resource belongs to exactly one resource group and one subscription.',
      'Each resource has a type defined by a resource provider, such as `Microsoft.Compute/virtualMachines`.',
      'Each resource has a unique resource ID that encodes its subscription, resource group, provider, type and name.',
      'Resource groups, subscriptions, management groups and tags are themselves resources.',
    ],
    example: 'Creating one VM in the portal typically creates several resources: the VM, its OS disk, a network interface, and often a public IP address and network security group.',
    examTips: ['Deleting a resource group deletes every resource inside it.', 'A resource can connect to resources in other resource groups (a web app can use a database elsewhere).'],
    relations: {
      partOf: [{ to: 'resource-group', label: 'Every resource lives in exactly one resource group' }],
      dependsOn: [
        { to: 'resource-provider', label: 'Its type is supplied by a resource provider' },
        { to: 'azure-resource-manager', label: 'Created, updated and deleted through ARM' },
      ],
      governance: [
        { to: 'tags', label: 'Name-value metadata for cost and ownership' },
        { to: 'resource-lock', label: 'Protects against deletion or change' },
        { to: 'azure-policy', label: 'Evaluated for compliance' },
      ],
      integratesWith: [{ to: 'resource-id', label: 'Identified by a unique resource ID' }],
    },
    place: ['entra-tenant', 'management-group', 'subscription', 'resource-group'],
    sources: ['arm-overview'],
  },
  {
    id: 'resource-id',
    name: 'Resource ID',
    aliases: ['resourceId', 'ARM ID'],
    area: 'foundations',
    kind: 'principle',
    tier: 'should',
    summary: 'The unique path that identifies a resource: /subscriptions/{id}/resourceGroups/{rg}/providers/{namespace}/{type}/{name}.',
    simple: 'A resource ID is like a full postal address for a resource. It says which subscription, which resource group, what kind of thing, and its name.',
    why: 'Scripts, templates, role assignments and policies need an unambiguous way to point at one specific resource — a name alone is not unique across subscriptions and resource groups.',
    howItWorks: [
      'Format: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProvider}/{resourceType}/{resourceName}`.',
      'Role assignment and lock scopes are expressed as resource IDs.',
      'Because the ID contains the resource group and subscription, moving a resource changes its resource ID.',
    ],
    example: '`/subscriptions/0000…/resourceGroups/rg-web-prod/providers/Microsoft.Storage/storageAccounts/stwebprod01` identifies one storage account.',
    examTips: ['After a resource move, scripts and references that used the old resource ID must be updated.'],
    relations: {
      partOf: [{ to: 'azure-resource-manager', label: 'The addressing scheme used by ARM' }],
      integratesWith: [
        { to: 'rbac-scope', label: 'Scopes are expressed as resource IDs' },
        { to: 'resource-move', label: 'Moving a resource changes its ID' },
      ],
    },
    place: ['azure-resource-manager'],
    sources: ['arm-overview', 'move-resources'],
  },
  {
    id: 'region',
    name: 'Azure region',
    aliases: ['location', 'datacenter region'],
    area: 'foundations',
    kind: 'principle',
    tier: 'must',
    summary: 'A geographic area containing one or more datacenters where you deploy resources, such as East US or West Europe.',
    simple: 'A region is where in the world your resources physically run. You pick it when you create most resources, and it affects speed, cost, data residency and which features are available.',
    why: 'Organizations need to run workloads close to users, keep data inside legal boundaries, and place copies far enough apart to survive large disasters.',
    useWhen: ['Choosing the location for a new resource or resource group', 'Designing multi-region disaster recovery'],
    howItWorks: [
      'Most resources are regional; some (for example Microsoft Entra ID or Azure DNS zones) are global.',
      'Many regions support availability zones. Newer regions are often unpaired and rely on zones for in-region redundancy.',
      'Moving a resource to another resource group or subscription never changes its region.',
      'Some services and VM sizes are available only in some regions.',
    ],
    example: 'A European retailer deploys its web tier to West Europe for latency and data residency, and replicates backups to North Europe, its paired region.',
    mistakes: [
      'Expecting a resource move to relocate a resource to another region. Region changes need a redeploy or Azure Resource Mover for supported resources.',
      'Placing a VM and the storage or database it depends on in different regions without a reason, adding latency and data transfer cost.',
    ],
    examTips: [
      'A virtual network exists in a single region (it can span that region’s availability zones).',
      'Moving between resource groups or subscriptions does not change a resource’s region.',
    ],
    relations: {
      contains: [{ to: 'availability-zone', label: 'Many regions have three or more zones' }],
      integratesWith: [
        { to: 'paired-region', label: 'Some regions are paired with another region' },
        { to: 'storage-redundancy', label: 'Geo-redundant storage replicates to the paired region' },
        { to: 'site-recovery', label: 'Replicates VMs to another region for DR' },
      ],
      networking: [{ to: 'vnet', label: 'A VNet is scoped to one region' }],
      governance: [{ to: 'azure-policy', label: 'Allowed locations policies restrict regions' }],
    },
    confusedWith: [
      {
        id: 'availability-zone',
        difference: 'A region is a geographic area; availability zones are physically separate datacenter groups inside one region. Zones protect against a datacenter failure, not a whole-region outage.',
      },
    ],
    cost: ['Prices differ by region.', 'Data transfer between regions is charged; transfer between zones in the same region is not.'],
    sources: ['regions-paired', 'availability-zones', 'move-resources'],
  },
  {
    id: 'availability-zone',
    name: 'Availability zone',
    aliases: ['AZ', 'zone', 'zonal', 'zone-redundant'],
    area: 'foundations',
    kind: 'principle',
    tier: 'must',
    summary: 'A physically separate group of datacenters within a region, with independent power, cooling and networking.',
    simple: 'Think of a region as a city and availability zones as separate buildings across town, each with its own power and network. If one building goes dark, the others keep working.',
    why: 'A single datacenter can fail. Spreading copies of an application or its data across zones keeps it running through a datacenter-level outage without leaving the region.',
    useWhen: ['Production workloads in regions that support zones', 'Data must stay in one region but still survive a datacenter failure'],
    avoidWhen: ['You need protection from a whole-region outage — zones alone do not provide that; add a second region.'],
    howItWorks: [
      '**Zone-redundant** resources are replicated across zones by the service, and Microsoft handles failover (for example ZRS storage, zone-redundant Standard public IPs).',
      '**Zonal** resources are pinned to one zone you choose (for example a VM in zone 2). You make them resilient by deploying several instances across zones.',
      'Logical zone numbers are mapped to physical zones per subscription, so “zone 1” in two subscriptions may be different datacenters.',
      'Azure does not charge for data transfer between zones in the same region.',
    ],
    example: 'An online store runs two VMs behind a zone-redundant Standard Load Balancer: one in zone 1 and one in zone 2. A power failure in one zone takes out one VM, and the load balancer keeps sending traffic to the survivor.',
    mistakes: [
      'Deploying a single zonal VM and assuming it is highly available.',
      'Assuming zone 1 in one subscription is the same physical zone as zone 1 in another subscription.',
    ],
    examTips: [
      'VMs across two or more availability zones earn a 99.99% VM connectivity SLA; an availability set earns 99.95%.',
      'A VM can use an availability zone or an availability set, not both.',
    ],
    relations: {
      partOf: [{ to: 'region', label: 'Zones exist inside a region' }],
      integratesWith: [
        { to: 'availability-set', label: 'Alternative in-datacenter protection for VMs' },
        { to: 'vmss', label: 'Scale sets can spread instances across zones' },
        { to: 'storage-redundancy', label: 'ZRS and GZRS replicate across zones' },
        { to: 'load-balancer', label: 'Standard Load Balancer frontends can be zone-redundant' },
      ],
    },
    confusedWith: [
      {
        id: 'availability-set',
        difference: 'An availability set spreads VMs across fault and update domains inside one datacenter; zones spread them across separate datacenters. Zones survive a datacenter failure; availability sets do not.',
      },
    ],
    place: ['region'],
    sources: ['availability-zones', 'vm-availability'],
  },
  {
    id: 'paired-region',
    name: 'Region pair',
    aliases: ['paired region', 'secondary region'],
    area: 'foundations',
    kind: 'principle',
    tier: 'should',
    summary: 'Two Azure regions, usually in the same geography, that Microsoft associates for geo-replication, staggered updates and prioritized recovery.',
    simple: 'Some regions have a “buddy” region, usually in the same country. A few services — like geo-redundant storage — automatically copy data to the buddy so a copy survives if the first region has a disaster.',
    why: 'Geo-redundant services need a predictable secondary location that keeps data in the same geography and is not updated or recovered at the same time as the primary.',
    howItWorks: [
      'Benefits: one region in each pair is prioritized for recovery during a geography-wide outage, and planned updates are staggered across the pair.',
      'Almost all pairs are in the same geography, which helps with data residency. A few pairs are asymmetric (for example Brazil South pairs with South Central US).',
      'Many newer regions are not paired and rely on availability zones for redundancy.',
      'For geo-redundant storage (GRS/GZRS), the secondary region is determined by the primary region and cannot be changed.',
    ],
    example: 'A storage account in East US configured with GRS asynchronously replicates to West US, its paired region.',
    mistakes: [
      'Assuming that deploying into a paired region automatically gives you high availability or failover. You still design and test your own DR.',
      'Relying on Microsoft-managed failover of geo-redundant storage as your primary DR plan; it is only performed in catastrophic situations.',
    ],
    examTips: ['GRS/GZRS copy data to the paired secondary region; you cannot choose a different secondary.'],
    relations: {
      integratesWith: [
        { to: 'region', label: 'A relationship between two regions' },
        { to: 'storage-redundancy', label: 'GRS and GZRS replicate to the paired region' },
        { to: 'recovery-services-vault', label: 'Cross Region Restore uses the paired region' },
      ],
    },
    place: ['region'],
    sources: ['regions-paired', 'storage-redundancy'],
  },
  {
    id: 'azure-resource-manager',
    name: 'Azure Resource Manager (ARM)',
    aliases: ['ARM', 'Resource Manager', 'management.azure.com', 'control plane'],
    area: 'foundations',
    kind: 'service',
    tier: 'must',
    summary: 'The deployment and management service for Azure: every create, update and delete request from any tool goes through ARM, which authenticates and authorizes it.',
    simple: 'Resource Manager is Azure’s front desk. Whether you click in the portal, run a CLI command or deploy a template, your request goes to the same desk, which checks who you are and what you’re allowed to do before passing it to the right service.',
    why: 'One consistent management layer means every tool behaves the same way, and access control, policy, locks, tags and activity logging apply to every service automatically.',
    howItWorks: [
      'Requests from the portal, Azure CLI, Azure PowerShell, REST APIs and SDKs all go to Resource Manager (`https://management.azure.com` in Azure global).',
      'Resource Manager authenticates the caller with Microsoft Entra ID and authorizes the request with Azure RBAC.',
      'It applies governance: Azure Policy, resource locks, and records the operation in the activity log.',
      'It forwards the request to the resource provider (for example `Microsoft.Compute`) that performs the operation.',
      'ARM templates and Bicep files are declarative: you describe the desired end state and ARM works out what to create or update.',
    ],
    example: 'An administrator runs `az vm create`. The CLI calls ARM, ARM checks the administrator has `Microsoft.Compute/virtualMachines/write` at that scope, checks policy (for example allowed VM sizes), then `Microsoft.Compute` builds the VM. The operation appears in the activity log.',
    mistakes: [
      'Assuming governance on the control plane also controls data. A delete lock on a storage account does not stop someone with data access from deleting blobs.',
    ],
    examTips: [
      'Resource locks, Azure Policy and Azure RBAC are enforced by ARM on control plane operations.',
      'Activity log entries record control plane operations (who created, changed or deleted a resource).',
    ],
    relations: {
      dependsOn: [
        { to: 'entra-tenant', label: 'Authenticates callers against the tenant' },
        { to: 'resource-provider', label: 'Forwards requests to resource providers' },
      ],
      security: [{ to: 'azure-rbac', label: 'Authorizes every request with Azure RBAC' }],
      governance: [
        { to: 'azure-policy', label: 'Evaluates policy on create and update' },
        { to: 'resource-lock', label: 'Enforces locks on control plane operations' },
        { to: 'tags', label: 'Tags are applied through ARM' },
      ],
      monitoring: [{ to: 'activity-log', label: 'Records control plane operations' }],
      integratesWith: [
        { to: 'arm-template', label: 'Declarative JSON deployments' },
        { to: 'bicep', label: 'Declarative Bicep deployments' },
        { to: 'control-plane-data-plane', label: 'ARM is the control plane' },
      ],
    },
    confusedWith: [
      {
        id: 'arm-template',
        difference: '“ARM” is the management service. An ARM template is a JSON file you send to that service to deploy resources.',
      },
    ],
    sources: ['arm-overview', 'control-data-plane'],
  },
  {
    id: 'resource-provider',
    name: 'Resource provider',
    aliases: ['provider namespace', 'Microsoft.Compute', 'Microsoft.Storage', 'Microsoft.Network'],
    area: 'foundations',
    kind: 'principle',
    tier: 'should',
    summary: 'The Azure service that supplies a set of resource types and their REST operations, such as Microsoft.Compute or Microsoft.Storage.',
    simple: 'Each Azure service has a “provider” that knows how to build its resources. `Microsoft.Storage` builds storage accounts; `Microsoft.Network` builds virtual networks.',
    why: 'Splitting Azure into providers lets each service define its own resource types and API versions while sharing one management layer.',
    howItWorks: [
      'Resource types are named `{provider}/{type}`, for example `Microsoft.KeyVault/vaults`.',
      'A subscription must be registered for a provider before you can create its resources. Some providers are registered by default, and the portal and template deployments usually register what they need.',
      'Registering requires permission for the provider’s `/register/action` operation, which is included in the Contributor and Owner roles.',
      'You cannot unregister a provider while resources of its types still exist in the subscription.',
    ],
    example: 'A deployment fails with an error that the subscription is not registered to use a namespace. The administrator runs `az provider register --namespace Microsoft.Batch` and retries.',
    troubleshooting: ['Deployment fails because the subscription is not registered for a namespace → register the resource provider (requires Contributor or Owner).'],
    relations: {
      partOf: [{ to: 'azure-resource-manager', label: 'ARM forwards requests to providers' }],
      contains: [{ to: 'azure-resource', label: 'Defines resource types' }],
      integratesWith: [{ to: 'subscription', label: 'Registered per subscription' }],
    },
    place: ['azure-resource-manager'],
    sources: ['resource-providers'],
  },
  {
    id: 'control-plane-data-plane',
    name: 'Control plane vs data plane',
    aliases: ['management plane', 'data plane', 'control plane'],
    area: 'foundations',
    kind: 'principle',
    tier: 'must',
    summary: 'Control plane operations manage resources through Azure Resource Manager; data plane operations use a resource’s own endpoint to work with what is inside it.',
    simple: 'Creating a storage account is like building a warehouse (control plane). Putting boxes in and taking boxes out is using the warehouse (data plane). Different rules can apply to each.',
    why: 'Separating management from use means you can let someone manage a resource without reading its data — or read data without being able to delete the resource.',
    howItWorks: [
      'Control plane requests go to `https://management.azure.com`; Resource Manager applies Azure RBAC, Azure Policy, locks and activity logging.',
      'Data plane requests go to the resource’s endpoint, such as `https://myaccount.blob.core.windows.net`, and may use other credentials (RDP, a database login, a SAS token).',
      'Azure RBAC has separate permissions for data: `DataActions` (for example in Storage Blob Data Reader) versus management `Actions`.',
      'Data plane access keeps working even if the control plane is unavailable.',
    ],
    example: 'A Contributor can create and delete storage accounts but, without a data role such as Storage Blob Data Contributor, cannot read blobs using Microsoft Entra authorization. Contributor can still list the account keys, which grant full data access — one reason organizations disallow Shared Key authorization.',
    mistakes: [
      'Assuming a delete lock protects the data inside a resource. It blocks deleting the resource, not deleting blobs or rows.',
      'Granting Owner to someone who only needs to read blobs, instead of a data-plane role.',
    ],
    examTips: [
      'Locks apply only to control plane operations.',
      'Roles such as Storage Blob Data Reader grant data plane access through DataActions.',
    ],
    relations: {
      partOf: [{ to: 'azure-resource-manager', label: 'ARM handles the control plane' }],
      security: [
        { to: 'azure-rbac', label: 'Actions (control plane) vs DataActions (data plane)' },
        { to: 'sas', label: 'SAS tokens grant data plane access only' },
      ],
      governance: [{ to: 'resource-lock', label: 'Locks apply to the control plane only' }],
      monitoring: [
        { to: 'activity-log', label: 'Control plane operations' },
        { to: 'diagnostic-settings', label: 'Resource logs capture data plane activity' },
      ],
    },
    sources: ['control-data-plane', 'locks', 'rbac-overview'],
  },
  {
    id: 'azure-portal',
    name: 'Azure portal',
    aliases: ['portal', 'portal.azure.com'],
    area: 'foundations',
    kind: 'tool',
    tier: 'should',
    summary: 'The browser-based graphical console for creating, configuring and monitoring Azure resources.',
    simple: 'The portal is the Azure website where you click through forms to build and manage things.',
    why: 'Visual forms and dashboards are the fastest way to explore a service, see all its options and check the state of an environment.',
    useWhen: ['Exploring a service or setting for the first time', 'One-off changes and visual investigation (metrics, topology, costs)'],
    avoidWhen: ['A change must be repeated consistently across environments — use scripts or templates'],
    howItWorks: [
      'The portal calls the same Azure Resource Manager APIs as the CLI and PowerShell, so the same permissions and policies apply.',
      'Most create forms offer a template or automation view so you can capture what you configured.',
    ],
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Calls ARM like every other tool' }],
      alternative: [
        { to: 'azure-cli', label: 'Scriptable command line' },
        { to: 'azure-powershell', label: 'PowerShell cmdlets' },
        { to: 'arm-template', label: 'Declarative, repeatable deployments' },
      ],
      integratesWith: [{ to: 'cloud-shell', label: 'Cloud Shell opens inside the portal' }],
    },
    sources: ['arm-overview'],
  },
  {
    id: 'cloud-shell',
    name: 'Azure Cloud Shell',
    aliases: ['shell.azure.com'],
    area: 'foundations',
    kind: 'tool',
    tier: 'should',
    summary: 'An authenticated, browser-based terminal with Bash or PowerShell and the Azure CLI and Azure PowerShell preinstalled.',
    simple: 'Cloud Shell is a command line that runs in your browser and is already signed in to Azure, so you can run commands without installing anything.',
    why: 'Administrators often need to run a quick command from any machine without installing tools or managing credentials.',
    howItWorks: [
      'Choose Bash or PowerShell; both include the Azure CLI and Azure PowerShell.',
      'Sessions run on a temporary host and time out after 20 minutes without interactive activity.',
      'Files in `$HOME` persist using a 5-GB Azure file share in a storage account; regular storage costs apply.',
      'Available from portal.azure.com, shell.azure.com and the Azure mobile app.',
    ],
    relations: {
      dependsOn: [{ to: 'azure-files', label: 'Persists files in an Azure file share' }],
      integratesWith: [
        { to: 'azure-cli', label: 'Preinstalled' },
        { to: 'azure-powershell', label: 'Preinstalled' },
        { to: 'azure-portal', label: 'Launch from the portal toolbar' },
      ],
    },
    sources: ['cloud-shell'],
  },
  {
    id: 'azure-cli',
    name: 'Azure CLI',
    aliases: ['az', 'az cli', 'command-line interface'],
    area: 'foundations',
    kind: 'tool',
    tier: 'must',
    summary: 'A cross-platform command-line tool (`az`) for creating and managing Azure resources, well suited to Bash scripting.',
    simple: 'The Azure CLI lets you type commands like `az group create` instead of clicking through the portal, so tasks can be repeated and automated.',
    why: 'Scripts are repeatable, reviewable and fast — essential when the same change must be made across many resources or environments.',
    useWhen: ['Automating tasks in Bash or pipelines', 'Querying and filtering resources with `--query` (JMESPath)'],
    howItWorks: [
      'Commands follow `az <group> <subgroup> <command> --parameters`, for example `az network vnet subnet create`.',
      '`--output table|json|tsv` controls formatting; `--query` filters JSON output.',
      'Calls Azure Resource Manager, so RBAC, policy and locks apply exactly as in the portal.',
    ],
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Calls ARM APIs' }],
      alternative: [
        { to: 'azure-powershell', label: 'Same capabilities as PowerShell cmdlets' },
        { to: 'azure-portal', label: 'Graphical alternative' },
      ],
      integratesWith: [
        { to: 'cloud-shell', label: 'Preinstalled in Cloud Shell' },
        { to: 'bicep', label: '`az deployment group create` deploys Bicep files' },
      ],
    },
    sources: ['arm-overview'],
  },
  {
    id: 'azure-powershell',
    name: 'Azure PowerShell',
    aliases: ['Az module', 'PowerShell Az', 'New-AzVM'],
    area: 'foundations',
    kind: 'tool',
    tier: 'must',
    summary: 'The Az PowerShell module: cmdlets such as New-AzResourceGroup that manage Azure resources and return objects you can pipe.',
    simple: 'Azure PowerShell gives you commands like `New-AzVM` that work well if you already use PowerShell to manage Windows servers.',
    why: 'PowerShell’s object pipeline makes it easy to filter, transform and act on many resources in one script.',
    useWhen: ['Automating in PowerShell environments', 'Working with objects returned by one cmdlet in the next'],
    howItWorks: [
      'Cmdlets follow Verb-AzNoun naming: `Get-AzVM`, `New-AzStorageAccount`, `Set-AzVirtualNetwork`.',
      'Sign in with `Connect-AzAccount`; choose a subscription with `Set-AzContext`.',
      'Calls Azure Resource Manager, so the same permissions and policies apply.',
    ],
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Calls ARM APIs' }],
      alternative: [
        { to: 'azure-cli', label: 'Cross-platform `az` commands' },
        { to: 'azure-portal', label: 'Graphical alternative' },
      ],
      integratesWith: [{ to: 'cloud-shell', label: 'Preinstalled in Cloud Shell' }],
    },
    sources: ['arm-overview'],
  },
];
