import type { Concept } from '../schema';

export const GOVERNANCE_CONCEPTS: Concept[] = [
  {
    id: 'management-group',
    name: 'Management group',
    aliases: ['MG', 'Tenant root group', 'root management group'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A container above subscriptions that lets you apply Azure Policy and role assignments once to many subscriptions.',
    simple: 'A management group is a folder for subscriptions. Put rules or permissions on the folder and every subscription inside gets them.',
    why: 'Organizations with many subscriptions need governance that is applied consistently and automatically — including to subscriptions created later.',
    useWhen: ['The same policy or access must apply to several subscriptions', 'Separating production and non-production governance'],
    avoidWhen: ['You want to separate billing — that is what subscriptions do', 'You want to apply tags or locks — neither is supported on management groups'],
    howItWorks: [
      'One hierarchy per directory, starting at the **Tenant root group** whose ID is the tenant ID; it can’t be moved or deleted.',
      'Up to 10,000 management groups per directory, nested up to **six levels** (not counting the root or subscription level).',
      'Every management group and subscription has exactly **one parent**.',
      'New subscriptions are placed under the root management group by default.',
      'Moving a subscription requires write permission on the management groups involved and Owner-level rights on the subscription; hierarchy changes can take up to 30 minutes to show.',
    ],
    example: 'Contoso → Platform, Landing zones (Corp, Online), Sandbox. “Allowed locations” is assigned at Contoso; “Deny public IP” is assigned at Corp.',
    mistakes: [
      'Designing the tree to mirror the org chart instead of governance needs, leading to deep hierarchies that are hard to change.',
      'Trying to add a resource lock or tags at management group scope.',
    ],
    examTips: [
      'Six levels of depth below the root; one parent each; 10,000 per directory.',
      'Locks and tags can’t be applied to management groups. Policy and RBAC can.',
    ],
    relations: {
      partOf: [{ to: 'entra-tenant', label: 'One hierarchy per tenant' }],
      contains: [{ to: 'subscription', label: 'Subscriptions and child management groups' }],
      governance: [
        { to: 'azure-policy', label: 'Assign policy once for many subscriptions' },
        { to: 'budget', label: 'Budgets can be scoped to management groups' },
      ],
      security: [{ to: 'azure-rbac', label: 'Role assignments inherited by all subscriptions' }],
    },
    confusedWith: [
      { id: 'resource-group', difference: 'Management groups contain subscriptions and exist for governance. Resource groups contain resources and exist for lifecycle management.' },
    ],
    place: ['entra-tenant'],
    sources: ['management-groups'],
  },
  {
    id: 'subscription',
    name: 'Azure subscription',
    aliases: ['sub', 'billing subscription'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A billing and management boundary that holds resource groups, trusts one Microsoft Entra tenant, and has its own quotas and role assignments.',
    simple: 'A subscription is an account that Azure sends the bill for. Everything you create lives in one, and you can use separate subscriptions to keep costs, limits and access apart.',
    why: 'Separating workloads into subscriptions isolates billing, quotas and the blast radius of mistakes, and lets different teams be owners of their own environments.',
    useWhen: ['Separate invoices or cost ownership', 'Separate production from development for access and quota isolation'],
    howItWorks: [
      'Trusts exactly one Microsoft Entra tenant for authentication.',
      'Contains resource groups; has one parent management group.',
      'Resource providers are registered per subscription.',
      'Moving a subscription to a different tenant removes its Azure role assignments.',
      'Classic administrator roles (Service Administrator, Co-Administrator) are retired — access is granted with Azure RBAC.',
    ],
    example: 'Fabrikam uses one subscription per environment per business unit (Retail-Prod, Retail-Dev) so budgets and access match ownership.',
    mistakes: ['Putting production and experiments in one subscription, so a developer’s quota usage or mistake affects production.'],
    examTips: [
      'Subscription = billing boundary. Resource group = lifecycle container. Management group = governance container.',
      'Questions mentioning Co-Administrator are outdated — the modern answer is an Azure role such as Owner at subscription scope.',
    ],
    relations: {
      partOf: [{ to: 'management-group', label: 'Exactly one parent' }],
      contains: [{ to: 'resource-group', label: 'Holds resource groups' }],
      dependsOn: [{ to: 'entra-tenant', label: 'Trusts one tenant' }],
      governance: [
        { to: 'budget', label: 'Cost tracking and alerts' },
        { to: 'azure-policy', label: 'Policy assignments' },
        { to: 'resource-lock', label: 'Subscription-level locks' },
      ],
      integratesWith: [{ to: 'resource-provider', label: 'Registered per subscription' }],
    },
    place: ['entra-tenant', 'management-group'],
    sources: ['subscription-tenant', 'roles-compare', 'management-groups'],
  },
  {
    id: 'resource-group',
    name: 'Resource group',
    aliases: ['RG', 'resourceGroups'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A logical container for resources that share a lifecycle; every resource belongs to exactly one resource group.',
    simple: 'A resource group is a box for everything that belongs to one project or workload. Delete the box and everything in it is deleted too.',
    why: 'Deploying, securing, monitoring and deleting related resources together is far easier than handling each one separately.',
    howItWorks: [
      'Each resource exists in only one resource group; resources can connect to resources in other groups.',
      'The resource group has a location where its **metadata** is stored; its resources can be in other regions.',
      'Deleting a resource group deletes all resources in it (a delete lock on any resource inside makes the whole delete fail).',
      'Tags on a resource group are **not** inherited by its resources.',
      'Resources can move between resource groups; the resource group itself can’t be moved to another subscription.',
    ],
    example: 'rg-shop-prod-web holds the App Service plan, web app and Application Insights for one store front; the shared hub network lives in rg-network-prod with a different lifecycle.',
    mistakes: ['Grouping by resource type (all VMs together) rather than by lifecycle.', 'Assuming a resource group in West Europe forces its resources into West Europe.'],
    examTips: ['“Delete everything for this project in one step” → put it all in one resource group.'],
    relations: {
      partOf: [{ to: 'subscription', label: 'Lives in a subscription' }],
      contains: [{ to: 'azure-resource', label: 'Resources with a shared lifecycle' }],
      governance: [
        { to: 'resource-lock', label: 'Locks inherited by resources' },
        { to: 'tags', label: 'Tags are not inherited' },
        { to: 'resource-move', label: 'Move resources between groups' },
      ],
      security: [{ to: 'rbac-scope', label: 'A common scope for team access' }],
    },
    place: ['entra-tenant', 'management-group', 'subscription'],
    sources: ['arm-overview', 'move-resources'],
  },
  {
    id: 'resource-move',
    name: 'Moving resources',
    aliases: ['move resources', 'validateMoveResources', 'Azure Resource Mover'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Moving resources to another resource group or subscription in the same tenant; the region does not change.',
    simple: 'You can move resources to a different box (resource group) or account (subscription). They keep running, but they stay in the same region.',
    why: 'Reorganizations, ownership changes and billing changes shouldn’t require rebuilding working resources.',
    howItWorks: [
      'Source and destination must be in the same Microsoft Entra tenant; the destination subscription needs the resource provider registered.',
      'Source and destination resource groups are locked for writes during the move (up to four hours); resources keep running.',
      'The resource ID changes; **role assignments on moved resources don’t move** and must be recreated.',
      'Cross-subscription moves require dependent resources (VM, disks, NICs, public IPs) to move together.',
      'A read-only lock on the source or destination resource group or subscription blocks the move.',
      'Up to 800 resources per move operation. To change region, use Azure Resource Mover or redeploy.',
    ],
    example: '`az resource move --destination-group rg-new --ids <vmId> <diskId> <nicId>`',
    mistakes: ['Expecting a move to another subscription to change the region.', 'Moving a VM without its disks and NIC across subscriptions.'],
    examTips: [
      'Validate first with the validateMoveResources operation.',
      'Moving to another region is not a resource move — use Azure Resource Mover.',
    ],
    troubleshooting: [
      'Move fails with MissingMoveDependentResources → include the dependent resources.',
      'Move fails with RequestDisallowedByPolicy → a policy at the destination blocks the resource.',
      'Move blocked → check for read-only locks on either resource group or the subscription.',
    ],
    relations: {
      dependsOn: [{ to: 'resource-group', label: 'Changes the resource group or subscription' }],
      integratesWith: [
        { to: 'resource-id', label: 'The resource ID changes' },
        { to: 'role-assignment', label: 'Direct role assignments are left behind' },
      ],
      governance: [
        { to: 'resource-lock', label: 'Read-only locks block moves' },
        { to: 'azure-policy', label: 'Destination policies are enforced' },
      ],
    },
    sources: ['move-resources'],
  },
  {
    id: 'azure-policy',
    name: 'Azure Policy',
    aliases: ['policy', 'policy definition', 'policy assignment', 'compliance', 'remediation'],
    area: 'identity-governance',
    kind: 'service',
    tier: 'must',
    summary: 'Enforces organizational standards on resource configuration and reports compliance, using policy definitions assigned at a scope.',
    simple: 'Azure Policy is a set of rules for what resources are allowed to look like — for example “only in these regions” or “must have a cost-center tag”. It can block, fix or report anything that breaks the rules.',
    why: 'RBAC stops the wrong people making changes; it can’t stop the right people making non-compliant ones. Policy enforces standards no matter who deploys.',
    useWhen: ['Restricting regions, SKUs or resource types', 'Requiring or adding tags', 'Auditing security configuration at scale', 'Automatically deploying settings such as diagnostic settings'],
    avoidWhen: ['Controlling who can perform an action — that is Azure RBAC', 'Preventing deletion of a specific critical resource — use a resource lock'],
    howItWorks: [
      '**Definition**: a JSON rule plus an effect. **Initiative**: a group of definitions. **Assignment**: attaches a definition or initiative to a management group, subscription, resource group or resource.',
      'Assignments are inherited by child scopes; exclusions (`notScopes`) remove child scopes; exemptions exempt specific resources while tracking them.',
      'Evaluation happens when resources are created or updated, when assignments change, and in a standard compliance scan every 24 hours.',
      'Policy is explicit-deny: a child assignment can’t override a parent’s deny.',
      '`modify` and `deployIfNotExists` assignments use a managed identity, and existing resources are fixed with remediation tasks.',
      'Limits include 200 assignments per scope and 500 definitions per scope.',
    ],
    example: 'A platform team assigns an initiative at the Landing zones management group: Allowed locations (deny), Require a tag on resource groups (deny), and a diagnostic settings policy (deployIfNotExists).',
    mistakes: [
      'Rolling out deny policies directly to production without first using audit to see the impact.',
      'Assigning a deployIfNotExists policy and expecting existing resources to change without a remediation task.',
    ],
    examTips: [
      'Existing non-compliant resources are not deleted or blocked by a new deny policy; they show as non-compliant.',
      'Resource Policy Contributor can manage policy assignments; Contributor can’t create them.',
    ],
    troubleshooting: [
      'Deployment fails with RequestDisallowedByPolicy → open the error details to find the assignment and definition, then comply, request an exemption or adjust the assignment.',
      'Compliance state hasn’t updated → evaluation runs on change and every 24 hours; you can trigger an on-demand scan.',
    ],
    relations: {
      contains: [
        { to: 'policy-initiative', label: 'Groups of definitions' },
        { to: 'policy-effect', label: 'What happens on a match' },
        { to: 'policy-exemption', label: 'Tracked exceptions' },
      ],
      dependsOn: [{ to: 'azure-resource-manager', label: 'Evaluated on ARM requests' }],
      integratesWith: [
        { to: 'management-group', label: 'Assign once for many subscriptions' },
        { to: 'managed-identity', label: 'Required for modify and deployIfNotExists' },
        { to: 'tags', label: 'Require, add or inherit tags' },
      ],
      alternative: [
        { to: 'azure-rbac', label: 'Controls who may act' },
        { to: 'resource-lock', label: 'Protects specific resources' },
      ],
      monitoring: [{ to: 'activity-log', label: 'Policy events recorded' }],
    },
    confusedWith: [
      { id: 'azure-rbac', difference: 'RBAC: can this user perform this action? Policy: is the resulting resource configuration allowed? A user with Owner is still blocked by a deny policy.' },
      { id: 'resource-lock', difference: 'Locks protect particular resources from deletion or change for everyone. Policy evaluates configuration rules across many resources.' },
    ],
    cost: ['Azure Policy for Azure resources is free.'],
    sources: ['policy-overview', 'policy-effects'],
  },
  {
    id: 'policy-initiative',
    name: 'Policy initiative',
    aliases: ['policy set', 'policySetDefinition', 'initiative definition'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'A collection of policy definitions assigned and tracked as one unit.',
    simple: 'An initiative is a bundle of rules. Assign the bundle once instead of assigning each rule separately.',
    why: 'Standards usually involve many related rules (for example a security baseline); managing them together keeps assignments and compliance reports manageable.',
    howItWorks: ['Up to 1,000 policies per initiative.', 'Microsoft recommends using initiatives even for a single policy so more can be added later without new assignments.'],
    relations: { partOf: [{ to: 'azure-policy', label: 'Groups definitions' }] },
    place: ['azure-policy'],
    sources: ['policy-overview'],
  },
  {
    id: 'policy-effect',
    name: 'Policy effect',
    aliases: ['deny', 'audit', 'modify', 'append', 'deployIfNotExists', 'auditIfNotExists', 'denyAction', 'DINE'],
    area: 'identity-governance',
    kind: 'setting',
    tier: 'must',
    summary: 'What Azure Policy does when a resource matches a rule: deny, audit, modify, append, deployIfNotExists, auditIfNotExists, denyAction, disabled and others.',
    simple: 'The effect is the consequence of breaking a rule — block the request, write it down, fix it automatically, or deploy something that’s missing.',
    why: 'Different standards need different enforcement: some must be blocked, some fixed automatically, some only reported.',
    howItWorks: [
      '**deny**: blocks the create or update request.',
      '**audit**: allows it but marks the resource non-compliant.',
      '**modify**: adds, updates or removes properties or tags during the request (needs a managed identity).',
      '**append**: adds fields to the request.',
      '**auditIfNotExists / deployIfNotExists**: check for a related resource (such as a diagnostic setting) after the request succeeds; DINE deploys it.',
      '**denyAction**: blocks specific actions, such as delete, on resources.',
      '**disabled**: turns the policy off for an assignment.',
      'Evaluation order: disabled → append and modify → deny → audit → manual → auditIfNotExists → denyAction; deployIfNotExists and auditIfNotExists run after the resource provider succeeds.',
    ],
    examTips: [
      'Automatically add a tag → modify. Block creation → deny. Report only → audit. Deploy a missing setting → deployIfNotExists.',
    ],
    relations: { partOf: [{ to: 'azure-policy', label: 'Defined in the policy rule' }] },
    place: ['azure-policy'],
    sources: ['policy-effects'],
  },
  {
    id: 'policy-exemption',
    name: 'Policy exemption',
    aliases: ['exemption', 'waiver', 'mitigated', 'notScopes', 'exclusion'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'should',
    summary: 'Excuses a scope or resource from a policy assignment while keeping it visible in compliance reporting as “Exempt”.',
    simple: 'An exemption is a documented “this one is allowed to break the rule”, optionally with an expiry date.',
    why: 'Real environments need exceptions. Recording them — with a reason and expiry — keeps compliance reporting honest.',
    howItWorks: [
      'Categories: **Mitigated** (intent met another way) and **Waiver** (non-compliance accepted temporarily).',
      'Optional `expiresOn` — after expiry the exemption is no longer honoured.',
      'Unlike an assignment exclusion (`notScopes`), exempt resources are still tracked and shown as Exempt.',
    ],
    relations: { partOf: [{ to: 'azure-policy', label: 'Exceptions to assignments' }] },
    confusedWith: [{ id: 'azure-policy', difference: 'An exclusion removes a scope from evaluation entirely; an exemption keeps it in reports as Exempt.' }],
    place: ['azure-policy'],
    sources: ['policy-exemptions'],
  },
  {
    id: 'tags',
    name: 'Tags',
    aliases: ['resource tags', 'tag', 'CostCenter tag', 'Tag Contributor'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Name-value pairs applied to subscriptions, resource groups and resources to organize them, most often for cost reporting and ownership.',
    simple: 'Tags are sticky labels such as “CostCenter: 4410” or “Owner: web-team” that you put on resources so you can find, group and charge back costs later.',
    why: 'Resource names alone can’t answer “who owns this?” or “what does this project cost?”. Tags make every resource self-describing.',
    howItWorks: [
      'Supported on subscriptions, resource groups and resources — **not management groups**.',
      '**Not inherited**: resources don’t receive tags from their resource group or subscription. Use Azure Policy to require, add or inherit tags.',
      'Up to 50 tag name-value pairs per resource, resource group or subscription.',
      'Tag names are case-insensitive for operations; tag values are case-sensitive.',
      'Names can’t contain `<`, `>`, `%`, `&`, `\\`, `?` or `/`.',
      'The **Tag Contributor** role can manage tags without access to the resources themselves.',
      'Tags appear in cost analysis and usage files, so costs can be grouped by tag.',
    ],
    example: 'Every resource carries Environment, CostCenter and Owner. A policy denies resource groups without CostCenter and a modify policy copies it to resources.',
    mistakes: ['Storing secrets or personal data in tags — they are plain text visible to readers.', 'Relying on resource group tags for resource-level cost reports.'],
    examTips: [
      'Tags don’t inherit; locks and policies do.',
      '`az tag update --operation merge` adds tags without removing existing ones; replacing the tag set removes others.',
    ],
    relations: {
      governance: [{ to: 'azure-policy', label: 'Enforce, add or inherit tags' }],
      integratesWith: [
        { to: 'budget', label: 'Filter budgets and cost analysis by tag' },
        { to: 'resource-group', label: 'Applied to resource groups without inheritance' },
      ],
    },
    cost: ['Tags are free; they are the main way to allocate costs to teams and projects.'],
    sources: ['tags'],
  },
  {
    id: 'resource-lock',
    name: 'Resource lock',
    aliases: ['lock', 'CanNotDelete', 'ReadOnly', 'delete lock', 'read-only lock'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Prevents deleting (CanNotDelete) or changing (ReadOnly) a subscription, resource group or resource — for every user, including Owners.',
    simple: 'A lock is a “do not remove” or “do not touch” sticker. Even an administrator must take the sticker off before deleting or changing the resource.',
    why: 'Accidents happen with powerful permissions. Locks protect critical resources such as production networks or storage from a mistaken delete.',
    useWhen: ['Critical shared resources must not be deleted accidentally', 'A resource group must be frozen during an audit'],
    avoidWhen: ['You need to protect data inside a resource — locks don’t affect data plane operations', 'You want to control who can act — use Azure RBAC'],
    howItWorks: [
      'Portal names: **Delete** and **Read-only**. CLI/API: `CanNotDelete` and `ReadOnly`.',
      'Apply at subscription, resource group or resource scope (not management groups). Child resources inherit locks; the most restrictive wins.',
      'Only Owner and User Access Administrator (or roles with `Microsoft.Authorization/locks/*`) can create or remove locks.',
      'Locks apply to the **control plane** only. A lock on a storage account doesn’t stop deleting blobs.',
      'A delete lock on any resource makes deleting its resource group fail.',
    ],
    example: '`az lock create --name protect-hub --lock-type CanNotDelete --resource-group rg-network-prod`',
    mistakes: [
      'Putting a ReadOnly lock on a resource group containing VMs, then being unable to start or restart them.',
      'Using a ReadOnly lock on a storage account and breaking tools that need to list the account keys.',
    ],
    examTips: [
      'ReadOnly blocks surprising operations that use POST: listing storage account keys, starting or restarting VMs in a locked resource group, scaling an App Service plan.',
      'A CanNotDelete lock also blocks deleting role assignments at that scope.',
      'Read-only locks on the source or target block resource moves.',
    ],
    troubleshooting: [
      'Owner can’t delete a resource → check Locks on the resource, its resource group and subscription.',
      'VM won’t start and the error mentions a scope lock → a ReadOnly lock exists at the resource group or subscription.',
    ],
    relations: {
      dependsOn: [{ to: 'azure-resource-manager', label: 'Enforced on control plane requests' }],
      integratesWith: [
        { to: 'resource-group', label: 'Inherited by resources in the group' },
        { to: 'subscription', label: 'Subscription-level locks' },
      ],
      alternative: [{ to: 'azure-policy', label: 'denyAction can block deletes across many resources' }],
      security: [{ to: 'azure-rbac', label: 'Owner or User Access Administrator manage locks' }],
    },
    confusedWith: [{ id: 'azure-rbac', difference: 'RBAC grants or withholds permission per identity. A lock overrides permissions for everyone until it is removed.' }],
    sources: ['locks'],
  },
  {
    id: 'budget',
    name: 'Budget',
    aliases: ['Cost Management budget', 'cost alert', 'forecasted alert', 'actual cost alert'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'A Cost Management spending threshold for a scope that sends notifications (and can trigger action groups) when actual or forecasted costs cross set percentages.',
    simple: 'A budget is a spending limit that warns you. It emails you when costs reach, say, 80% — but it never switches anything off by itself.',
    why: 'Cloud spend grows quietly. Early, automated warnings let teams act before the invoice arrives.',
    howItWorks: [
      'Scopes include management groups, subscriptions and resource groups (plus billing scopes).',
      'Reset period: monthly, quarterly or annually.',
      'Alert conditions on **actual** or **forecasted** cost; up to five thresholds and five email recipients per budget.',
      'Budgets are evaluated about once every 24 hours; cost data can take 8–24 hours to appear.',
      '**Budgets don’t stop resources.** Action groups (subscription and resource group scopes) can trigger automation if you build it.',
    ],
    example: 'The data team’s resource group has a monthly budget of 5,000 with a forecasted alert at 90% and an actual alert at 100%, which calls an action group that posts to their on-call channel.',
    mistakes: ['Believing a budget caps spending.'],
    examTips: ['“Be notified before exceeding” → forecasted alert. “Automatically stop resources” → budget + action group + automation (a budget alone won’t).'],
    relations: {
      integratesWith: [
        { to: 'action-group', label: 'Trigger automation or notifications' },
        { to: 'tags', label: 'Filter costs by tag' },
      ],
      governance: [{ to: 'azure-advisor', label: 'Advisor suggests cost savings' }],
    },
    sources: ['budgets'],
  },
  {
    id: 'azure-advisor',
    name: 'Azure Advisor',
    aliases: ['Advisor', 'recommendations', 'Advisor score'],
    area: 'identity-governance',
    kind: 'service',
    tier: 'must',
    summary: 'A free service that analyses your resources and recommends improvements in five categories: Reliability, Security, Performance, Cost and Operational excellence.',
    simple: 'Advisor is a checklist of improvements Azure spots for you — for example “this VM is barely used, resize it to save money”.',
    why: 'Administrators can’t manually review every resource for waste, risk and misconfiguration.',
    howItWorks: [
      'Categories: **Reliability, Security, Performance, Cost, Operational excellence**.',
      'Visible to Owner, Contributor and Reader at the relevant scope.',
      'Recommendations can be postponed or dismissed; implemented changes can take up to a day to be recognized.',
      'Security recommendations come from Microsoft Defender for Cloud.',
    ],
    examTips: ['Right-size or shut down underused VMs → Advisor Cost recommendations.'],
    relations: {
      integratesWith: [
        { to: 'budget', label: 'Act on cost insights' },
        { to: 'virtual-machine', label: 'Right-sizing recommendations' },
      ],
    },
    sources: ['advisor'],
  },
];
