import type { Concept } from '../schema';

export const IDENTITY_CONCEPTS: Concept[] = [
  {
    id: 'entra-id',
    name: 'Microsoft Entra ID',
    aliases: ['Azure AD', 'Azure Active Directory', 'AAD', 'Entra'],
    area: 'identity-governance',
    kind: 'service',
    tier: 'must',
    summary: 'Microsoft’s cloud identity and access management service: it signs in users, groups and workloads and issues the tokens Azure trusts.',
    simple: 'Entra ID is the login system for Microsoft’s cloud. When you sign in to the Azure portal, Microsoft 365 or an app your company uses, Entra ID checks who you are.',
    why: 'Every access decision starts with a trusted identity. A central directory means one account per person, one place to enforce password and sign-in policies, and one place to remove access when someone leaves.',
    howItWorks: [
      'Each organization gets a [[entra-tenant|tenant]] — a dedicated instance of Entra ID.',
      'Users, groups, app registrations, service principals and managed identities are directory objects.',
      'Entra ID authenticates; Azure RBAC and Microsoft Entra roles authorize.',
      'Licences (Free, P1, P2 and Microsoft 365 plans) unlock features such as dynamic groups (P1) or self-service password reset for cloud users.',
    ],
    example: 'When an engineer at Tailwind Traders leaves, IT disables their Entra ID account once — and access to the Azure portal, Microsoft 365 and every connected SaaS app stops together.',
    examTips: ['Older material says “Azure AD”; the exam uses Microsoft Entra ID. The concepts are the same.'],
    relations: {
      contains: [
        { to: 'entra-user', label: 'User accounts' },
        { to: 'entra-group', label: 'Groups' },
        { to: 'service-principal', label: 'Application identities' },
      ],
      partOf: [{ to: 'entra-tenant', label: 'Each tenant is an instance of Entra ID' }],
      security: [
        { to: 'sspr', label: 'Self-service password reset' },
        { to: 'entra-roles', label: 'Directory administrator roles' },
      ],
      integratesWith: [
        { to: 'azure-rbac', label: 'Identities receive Azure role assignments' },
        { to: 'b2b-collaboration', label: 'Invites external users as guests' },
        { to: 'managed-identity', label: 'Workload identities for Azure resources' },
      ],
    },
    confusedWith: [
      { id: 'azure-rbac', difference: 'Entra ID proves who someone is. Azure RBAC decides what that identity may do with Azure resources.' },
    ],
    sources: ['roles-compare', 'rbac-overview'],
  },
  {
    id: 'entra-user',
    name: 'Microsoft Entra user',
    aliases: ['user account', 'member user', 'UPN', 'user principal name'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A directory object representing a person (or a guest) who signs in with a user principal name such as ada@contoso.com.',
    simple: 'A user is one person’s account. It has a sign-in name, a password or passwordless method, and properties such as department and job title.',
    why: 'Access and auditing need to be tied to a specific individual so actions can be traced and access removed when roles change.',
    howItWorks: [
      '**Member** users belong to the organization; **guest** users are external people invited for collaboration (`userType` shows the difference).',
      'Users can be cloud-only or synchronized from on-premises Active Directory with Microsoft Entra Connect.',
      'Properties such as `department`, `jobTitle` and `usageLocation` drive dynamic group rules and licensing.',
      'A usage location is needed before most licences can be assigned.',
    ],
    example: 'HR sets Department = Finance on new hires. A dynamic group rule on that property puts them in the Finance group, which carries their licences and app access automatically.',
    mistakes: [
      'Leaving department and job title empty — dynamic groups and licensing automation then have nothing to key on.',
      'Assigning Azure roles to individual users instead of groups, which makes access reviews and leaver processes harder.',
    ],
    examTips: [
      'Bulk create users from a CSV template in the portal, or script creation with PowerShell or the Azure CLI.',
      'A user cannot be assigned a licence without a usage location (group-based licensing uses the tenant location if none is set).',
    ],
    relations: {
      partOf: [{ to: 'entra-id', label: 'Stored in the directory' }],
      integratesWith: [
        { to: 'entra-group', label: 'Members of groups' },
        { to: 'dynamic-group', label: 'Properties drive dynamic membership' },
        { to: 'group-based-licensing', label: 'Receive licences through groups' },
      ],
      security: [
        { to: 'sspr', label: 'Can reset their own password' },
        { to: 'role-assignment', label: 'Can be a security principal' },
      ],
    },
    confusedWith: [
      { id: 'guest-user', difference: 'Guests are users too, but they authenticate with their home organization or account and have limited directory access by default.' },
    ],
    place: ['entra-tenant', 'entra-id'],
    sources: ['dynamic-groups', 'group-licensing'],
  },
  {
    id: 'entra-group',
    name: 'Microsoft Entra group',
    aliases: ['security group', 'Microsoft 365 group', 'M365 group', 'assigned group'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A collection of users (and, for security groups, devices or service principals) used to grant access, licences and roles once instead of per person.',
    simple: 'A group is a list of accounts. Give the group access to something and everyone in the list gets it; remove someone from the list and their access goes away.',
    why: 'Managing access per individual does not scale and leaves stale permissions behind. Groups make access follow membership.',
    howItWorks: [
      '**Security groups** grant access to resources, apps and Azure roles. They can contain users, devices, service principals and other groups.',
      '**Microsoft 365 groups** add a shared mailbox, calendar, SharePoint site and files; they contain users only.',
      'Membership is **assigned** (added manually) or **dynamic** (calculated from a rule).',
      'Azure role assignments to a group apply to nested members too, because group membership is transitive for Azure RBAC.',
    ],
    example: 'The “App Team – Prod” security group holds Contributor on the production application resource group. Onboarding a developer means adding them to one group.',
    mistakes: [
      'Using nested groups for group-based licensing — only direct members of the licensed group receive licences.',
      'Expecting to add members manually to a dynamic group.',
    ],
    examTips: [
      'Groups that can have Microsoft Entra roles assigned must use assigned membership, not dynamic.',
      'Microsoft 365 groups cannot contain devices.',
    ],
    relations: {
      partOf: [{ to: 'entra-id', label: 'Stored in the directory' }],
      contains: [{ to: 'entra-user', label: 'Members' }],
      integratesWith: [
        { to: 'dynamic-group', label: 'Rule-based membership' },
        { to: 'group-based-licensing', label: 'Assign licences to a group' },
      ],
      security: [{ to: 'role-assignment', label: 'The preferred security principal for Azure roles' }],
    },
    place: ['entra-tenant', 'entra-id'],
    sources: ['dynamic-groups', 'group-licensing', 'rbac-overview'],
  },
  {
    id: 'dynamic-group',
    name: 'Dynamic membership group',
    aliases: ['dynamic group', 'membership rule', 'dynamic device group', 'dynamic user group'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'A group whose members are calculated automatically from a rule on user or device properties, such as user.department -eq "Sales".',
    simple: 'Instead of adding people one by one, you write a rule — “everyone whose department is Sales” — and Entra ID keeps the group up to date by itself.',
    why: 'Joiners, movers and leavers are constant. Rules keep membership (and everything granted through it) correct without someone remembering to update groups.',
    useWhen: ['Membership can be derived from reliable HR or device attributes', 'Licences or access should follow department, location or device type'],
    avoidWhen: ['You need to add exceptions by hand — dynamic groups do not allow manual members', 'The group must be assignable to Microsoft Entra roles'],
    howItWorks: [
      'Requires a Microsoft Entra ID P1 licence (or Intune for Education) for each unique user who is a member of dynamic groups. Device members need no licence.',
      'A rule targets **users or devices**, never both. Microsoft 365 groups can only have user rules.',
      'Example rules: `user.department -eq "Sales"`; all members but not guests: `(user.objectId -ne null) -and (user.userType -eq "Member")`.',
      'Up to 15,000 dynamic membership groups per tenant.',
      'Membership is evaluated by the service; changes are not instant.',
    ],
    example: 'Northwind creates a dynamic security group with `user.country -eq "Germany"` and assigns it the licences and apps German staff need.',
    mistakes: ['Trying to add a VIP manually to a dynamic group — change the attribute or use a separate assigned group.', 'Writing a rule that mixes user and device properties.'],
    examTips: [
      'Scenario wants membership “automatically based on department” → dynamic group, which requires Entra ID P1.',
      'A group used to assign Microsoft Entra roles can’t be dynamic.',
    ],
    troubleshooting: ['New hire not in the group → check the attribute value (spelling and case in the source data) and allow time for processing.'],
    relations: {
      partOf: [{ to: 'entra-group', label: 'A membership type of a group' }],
      dependsOn: [{ to: 'entra-user', label: 'Evaluates user or device properties' }],
      integratesWith: [{ to: 'group-based-licensing', label: 'Licences follow rule-based membership' }],
    },
    place: ['entra-tenant', 'entra-id', 'entra-group'],
    sources: ['dynamic-groups'],
  },
  {
    id: 'group-based-licensing',
    name: 'Group-based licensing',
    aliases: ['license assignment', 'licenses', 'licence assignment'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Assigning product licences to a group so every direct member receives them, and loses them when removed.',
    simple: 'Rather than giving each person a Microsoft 365 or Entra licence by hand, you give the licence to a group. Join the group, get the licence.',
    why: 'Per-user licence assignment is slow and error-prone, and forgotten licences cost money. Groups keep licences aligned with membership.',
    howItWorks: [
      'Works with security groups, mail-enabled security groups and Microsoft 365 groups.',
      '**Nested groups are not supported** — only first-level members receive licences.',
      'Users without a usage location inherit the tenant location for group-based licensing.',
      'Requires at least the Groups Administrator, License Administrator or User Administrator role.',
      'Errors show on the group: not enough licences, conflicting service plans, missing dependent services, usage location problems.',
    ],
    example: 'Contoso assigns Microsoft 365 E5 to the dynamic group “All full-time employees”. Contractors are excluded by the rule, so they never consume E5 licences.',
    mistakes: ['Licensing a parent group that contains other groups and expecting nested members to be licensed.', 'Removing a user from the old licensed group before adding them to the new one, causing a gap in service.'],
    examTips: ['When users move between licensed groups, add to the new group first and remove from the old one after confirming.'],
    troubleshooting: ['A member has no licence → check the group for licence errors (insufficient licences, conflicting plans, usage location) and whether the user is a direct member.'],
    relations: {
      dependsOn: [{ to: 'entra-group', label: 'Licences are assigned to groups' }],
      integratesWith: [
        { to: 'dynamic-group', label: 'Combine with rules for automatic licensing' },
        { to: 'entra-user', label: 'Members receive the licences' },
      ],
    },
    place: ['entra-tenant', 'entra-id'],
    sources: ['group-licensing'],
  },
  {
    id: 'b2b-collaboration',
    name: 'B2B collaboration',
    aliases: ['external identities', 'external collaboration settings', 'guest invitation', 'cross-tenant access'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Microsoft Entra External ID capability that invites people from other organizations as guest users, controlled by external collaboration and cross-tenant access settings.',
    simple: 'B2B lets you invite a partner’s employee into your directory so they can use your apps or resources with their own work account — no new password for them to remember.',
    why: 'Partners and contractors need access without the organization creating and managing separate accounts and passwords for them.',
    howItWorks: [
      'Invited guests appear as users with `userType` Guest and authenticate against their home identity provider.',
      '**Guest user access** has three levels: same as members; *limited access to properties and memberships of directory objects* (default); restricted to their own objects (most restrictive).',
      '**Guest invite settings** control who can invite: anyone including guests (default), members and specific admin roles, only users in specific admin roles, or no one.',
      'The **Guest Inviter** role can invite guests even when inviting is limited to specific admin roles.',
      '**Collaboration restrictions** use either an allow list or a deny list of domains.',
      '**Cross-tenant access settings** manage inbound and outbound B2B collaboration with specific Microsoft Entra organizations.',
    ],
    example: 'Fabrikam allows invitations only from admins and the Guest Inviter role, and adds an allow list containing only its two audit firms’ domains.',
    mistakes: ['Leaving the default “anyone can invite” setting when policy says only admins may invite guests.', 'Using both allow and deny lists — you choose one or the other.'],
    examTips: [
      'By default, all users, including guests, can invite external users.',
      'To let a non-admin invite guests when only admin roles can invite, assign the Guest Inviter role.',
    ],
    relations: {
      partOf: [{ to: 'entra-id', label: 'Part of Microsoft Entra External ID' }],
      contains: [{ to: 'guest-user', label: 'Creates guest user objects' }],
      security: [{ to: 'entra-roles', label: 'Guest Inviter and User Administrator can invite' }],
    },
    place: ['entra-tenant', 'entra-id'],
    sources: ['external-collab'],
  },
  {
    id: 'guest-user',
    name: 'Guest user',
    aliases: ['external user', 'B2B guest', 'userType Guest'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A user object for an external person invited through B2B collaboration; they sign in with their own organization’s or personal account.',
    simple: 'A guest is a visitor badge in your directory. The visitor proves who they are with their own company login, and you decide what they can reach.',
    why: 'External people need scoped, auditable access that can be removed without affecting their home account.',
    howItWorks: [
      'Guests can be assigned Azure roles and added to groups like members.',
      'By default, guests have limited access to directory information.',
      'Guests who use personal Microsoft accounts can’t use Microsoft Entra self-service password reset — they reset with their identity provider.',
    ],
    examTips: ['Guest sign-in activity appears in both the home tenant and the resource tenant sign-in logs.'],
    relations: {
      partOf: [{ to: 'b2b-collaboration', label: 'Created by invitation' }],
      integratesWith: [
        { to: 'entra-group', label: 'Can be group members' },
        { to: 'role-assignment', label: 'Can receive Azure roles' },
      ],
    },
    place: ['entra-tenant', 'entra-id'],
    sources: ['external-collab', 'sspr-howitworks'],
  },
  {
    id: 'sspr',
    name: 'Self-service password reset (SSPR)',
    aliases: ['password reset', 'password writeback', 'authentication methods'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'must',
    summary: 'Lets users reset or change their own password after proving their identity with registered authentication methods.',
    simple: 'Forgot your password? SSPR lets you prove it’s you — with the Authenticator app or a code sent to your phone — and set a new one without calling the help desk.',
    why: 'Password resets are one of the most common help desk tickets. SSPR removes the wait for users and the cost for IT while keeping verification strong.',
    howItWorks: [
      'Scope: enable for **None**, **Selected** (specific groups) or **All** users.',
      'Methods: Microsoft Authenticator notifications, OATH software tokens, OATH hardware tokens (preview), SMS, voice call, email one-time passcode.',
      'Number of methods required to reset: **one or two**.',
      'Registration can be required at sign-in, with reconfirmation every 0–730 days (0 means never).',
      'Administrator accounts always get a stronger two-gate policy, regardless of your settings.',
      '**Password writeback** (through Microsoft Entra Connect or cloud sync) sends resets of synchronized users back to on-premises Active Directory.',
    ],
    example: 'Contoso pilots SSPR for the “Helpdesk-Pilot” group with two required methods, then expands to all users once registration reaches 90%.',
    mistakes: [
      'Assuming Entra ID Free covers password **reset** for cloud users — Free covers password change; reset needs Entra ID P1/P2 or Microsoft 365 Business Standard/Premium.',
      'Expecting synchronized users to reset passwords without writeback.',
    ],
    examTips: [
      'Cloud-only password **change**: Entra ID Free. Cloud-only **reset**: Microsoft 365 Business Standard, Business Premium, or Entra ID P1/P2.',
      'Hybrid reset with on-premises writeback: Microsoft 365 Business Premium or Entra ID P1/P2.',
      'SSPR can be enabled for a selected group during a pilot.',
    ],
    troubleshooting: [
      'Synchronized user is told to contact an admin → password writeback isn’t configured.',
      'User can’t reset → check they are in scope (a selected group) and have registered enough methods.',
    ],
    relations: {
      partOf: [{ to: 'entra-id', label: 'Configured per tenant' }],
      dependsOn: [{ to: 'entra-user', label: 'Users register authentication methods' }],
      governance: [{ to: 'entra-group', label: 'Scope can be limited to selected groups' }],
    },
    cost: ['Password reset for cloud users requires Entra ID P1/P2 or Microsoft 365 Business Standard/Premium licences.'],
    place: ['entra-tenant', 'entra-id'],
    sources: ['sspr-licensing', 'sspr-howitworks'],
  },
  {
    id: 'azure-rbac',
    name: 'Azure role-based access control (Azure RBAC)',
    aliases: ['RBAC', 'IAM', 'access control', 'Access control (IAM)'],
    area: 'identity-governance',
    kind: 'service',
    tier: 'must',
    summary: 'The authorization system for Azure resources: role assignments grant a security principal a role definition at a scope.',
    simple: 'RBAC is how Azure decides what you may do. You get a role (like “Reader”) for a place (like one resource group), and that combination defines your permissions there.',
    why: 'Different people need different permissions in different places. RBAC grants exactly the access needed — least privilege — without sharing admin accounts.',
    howItWorks: [
      'A **role assignment** = security principal (user, group, service principal, managed identity) + role definition + scope.',
      'Scopes: management group, subscription, resource group, resource. Assignments are inherited by child scopes.',
      'The model is **additive**: effective permissions are the union of all assignments, so Contributor at the subscription plus Reader on a resource group is effectively Contributor.',
      'Evaluation: deny assignments are checked first; then allowed permissions are `Actions` minus `NotActions` (and `DataActions` minus `NotDataActions`); conditions can further restrict.',
      'Group membership is transitive: members of nested groups receive the role.',
    ],
    example: 'Auditors get Reader at the root-level “Contoso” management group; each application team gets Contributor on its own resource groups; only the platform team has Owner at subscription scope.',
    mistakes: [
      'Assigning Owner when Contributor suffices — Owner can also grant access to others.',
      'Assuming a Reader role on a child scope restricts someone who already has Contributor higher up. Permissions add up; they are not overridden.',
    ],
    examTips: [
      'Contributor can manage everything but **cannot assign roles**. Owner, User Access Administrator and Role Based Access Control Administrator can assign roles.',
      'A Global Administrator has no Azure resource access by default; they can elevate to User Access Administrator at root scope.',
    ],
    troubleshooting: [
      'User sees the resource but can’t change it → check effective access with **Check access** at that scope; they may only have Reader.',
      'New access not working yet → sign out and back in so a new token includes updated group membership.',
    ],
    relations: {
      contains: [
        { to: 'role-assignment', label: 'Principal + role + scope' },
        { to: 'role-definition', label: 'Collections of permissions' },
      ],
      dependsOn: [
        { to: 'entra-id', label: 'Security principals come from the tenant' },
        { to: 'azure-resource-manager', label: 'ARM authorizes every request with RBAC' },
      ],
      integratesWith: [
        { to: 'rbac-scope', label: 'Assignments apply at a scope' },
        { to: 'managed-identity', label: 'Workloads receive roles too' },
      ],
      governance: [{ to: 'azure-policy', label: 'Policy controls resource state; RBAC controls user actions' }],
      monitoring: [{ to: 'activity-log', label: 'Role assignment changes are logged' }],
    },
    confusedWith: [
      { id: 'entra-roles', difference: 'Azure roles control Azure resources (VMs, storage). Microsoft Entra roles control the directory (users, groups, domains).' },
      { id: 'azure-policy', difference: 'RBAC decides whether a person may perform an action. Policy decides whether the resulting resource configuration is allowed, regardless of who asks.' },
    ],
    cost: ['Azure RBAC has no additional cost.'],
    sources: ['rbac-overview', 'roles-compare'],
  },
  {
    id: 'role-assignment',
    name: 'Role assignment',
    aliases: ['assign role', 'access assignment'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'The object that attaches a role definition to a security principal at a specific scope — the thing that actually grants access.',
    simple: 'A role assignment is the sentence “this person or group gets this role, here.” Remove the sentence and the access is gone.',
    why: 'Separating the list of permissions (role definition) from who gets them and where (assignment) lets one role be reused everywhere.',
    howItWorks: [
      'Created in **Access control (IAM)** at the scope, or with `az role assignment create` / `New-AzRoleAssignment`.',
      'Assignments at a scope are inherited by everything beneath it.',
      'Assignments do not move with resources: moving a resource to another resource group or subscription leaves its direct role assignments behind.',
      'A role assignment is an extension resource of the scope it is applied to.',
    ],
    example: '`az role assignment create --assignee-object-id <groupId> --assignee-principal-type Group --role "Virtual Machine Contributor" --scope /subscriptions/<id>/resourceGroups/rg-app`',
    mistakes: ['Assigning roles to individuals rather than groups.', 'Forgetting to recreate direct role assignments after moving resources.'],
    examTips: ['“Interpret access assignments” questions show several assignments at different scopes — add them up from the top of the hierarchy down to the resource.'],
    relations: {
      partOf: [{ to: 'azure-rbac', label: 'The building block of RBAC' }],
      dependsOn: [
        { to: 'role-definition', label: 'Which permissions' },
        { to: 'rbac-scope', label: 'Where they apply' },
        { to: 'entra-group', label: 'Who receives them (preferably a group)' },
      ],
      governance: [{ to: 'resource-lock', label: 'A CanNotDelete lock blocks deleting role assignments at that scope' }],
    },
    place: ['azure-rbac'],
    sources: ['rbac-overview', 'move-resources', 'locks'],
  },
  {
    id: 'role-definition',
    name: 'Role definition',
    aliases: ['built-in role', 'Owner', 'Contributor', 'Reader', 'User Access Administrator', 'Role Based Access Control Administrator'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'must',
    summary: 'A named collection of permissions (Actions, NotActions, DataActions, NotDataActions) such as Owner, Contributor or Reader.',
    simple: 'A role definition is a job description listing what someone in that role can do — for example “read everything” (Reader) or “change everything except who has access” (Contributor).',
    why: 'Reusable, well-understood permission sets are safer and easier to audit than granting individual operations.',
    howItWorks: [
      '**Owner**: full access, including assigning roles.',
      '**Contributor**: full management access, but cannot assign roles.',
      '**Reader**: view resources, no changes.',
      '**User Access Administrator**: manage user access to Azure resources.',
      '**Role Based Access Control Administrator**: assign roles, but can’t manage access in other ways such as Azure Policy.',
      'Service-specific roles (for example Virtual Machine Contributor, Storage Blob Data Reader) narrow permissions to one service or to data.',
    ],
    examTips: [
      'Need someone to manage resources but not grant access → Contributor.',
      'Need someone to grant access without managing resources → User Access Administrator or Role Based Access Control Administrator.',
    ],
    relations: {
      partOf: [{ to: 'azure-rbac', label: 'Defines permissions' }],
      alternative: [{ to: 'custom-role', label: 'When no built-in role fits' }],
      integratesWith: [{ to: 'control-plane-data-plane', label: 'Actions vs DataActions' }],
    },
    place: ['azure-rbac'],
    sources: ['roles-compare', 'rbac-overview'],
  },
  {
    id: 'rbac-scope',
    name: 'RBAC scope',
    aliases: ['scope', 'assignment scope', 'inheritance'],
    area: 'identity-governance',
    kind: 'principle',
    tier: 'must',
    summary: 'The level at which a role assignment applies — management group, subscription, resource group or resource — inherited by everything below.',
    simple: 'Scope is “where” your permission works. A role on a resource group covers every resource in that group; a role on one VM covers only that VM.',
    why: 'Choosing the narrowest scope that still meets the need limits the blast radius of mistakes and compromised accounts.',
    howItWorks: [
      'Management group → subscription → resource group → resource, each inheriting from its parent.',
      'The same principal can have different roles at different scopes; effective access is their sum.',
      'Scopes are written as resource IDs, for example `/subscriptions/<id>/resourceGroups/rg-web`.',
    ],
    examTips: ['“Least privilege” in a question means the narrowest scope and the least powerful role that meet the requirement.'],
    relations: {
      partOf: [{ to: 'azure-rbac', label: 'Where assignments apply' }],
      integratesWith: [
        { to: 'management-group', label: 'Broadest assignable scope' },
        { to: 'resource-group', label: 'Common scope for team access' },
        { to: 'resource-id', label: 'Expressed as a resource ID' },
      ],
    },
    place: ['azure-rbac'],
    sources: ['rbac-overview'],
  },
  {
    id: 'entra-roles',
    name: 'Microsoft Entra roles',
    aliases: ['directory roles', 'Global Administrator', 'User Administrator', 'Billing Administrator', 'Guest Inviter'],
    area: 'identity-governance',
    kind: 'role',
    tier: 'must',
    summary: 'Administrative roles for the directory itself — users, groups, domains, licences and settings — such as Global Administrator and User Administrator.',
    simple: 'Entra roles are for running the identity directory: creating users, resetting passwords, managing groups. They don’t, by themselves, let you touch VMs or storage.',
    why: 'Directory administration and resource administration are different jobs with different risks, so they use separate role systems.',
    howItWorks: [
      'Scopes: the tenant, an administrative unit, or an individual object.',
      '**Global Administrator**: manages all directory settings; can elevate to User Access Administrator for Azure resources.',
      '**User Administrator**: manages users and groups, including resetting passwords for non-privileged users.',
      '**Guest Inviter**: can invite external users.',
    ],
    examTips: ['Creating users and groups → an Entra role (for example User Administrator), not an Azure RBAC role.'],
    relations: {
      partOf: [{ to: 'entra-id', label: 'Directory administration' }],
      alternative: [{ to: 'azure-rbac', label: 'Access to Azure resources' }],
    },
    confusedWith: [{ id: 'azure-rbac', difference: 'Entra roles manage the directory; Azure roles manage Azure resources. A Global Administrator is not automatically an Owner of subscriptions.' }],
    place: ['entra-tenant', 'entra-id'],
    sources: ['roles-compare'],
  },
  {
    id: 'custom-role',
    name: 'Azure custom role',
    aliases: ['custom role definition', 'AssignableScopes', 'NotActions'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'should',
    summary: 'A role definition you create when built-in roles grant too much or too little, with your own Actions, NotActions, DataActions and AssignableScopes.',
    simple: 'If no ready-made role matches the job, you write your own list of allowed operations — for example “can restart VMs but not delete them.”',
    why: 'Least privilege sometimes needs a permission set Microsoft doesn’t ship as a built-in role.',
    howItWorks: [
      'JSON properties: `Name`, `IsCustom`, `Description`, `Actions`, `NotActions`, `DataActions`, `NotDataActions`, `AssignableScopes`.',
      '`NotActions` subtracts from `Actions`; it is not a deny — another role can still grant that permission.',
      'Up to 5,000 custom roles per tenant.',
      '`AssignableScopes` can’t use the root scope `/` or wildcards, and can include only one management group.',
      'Custom roles with `DataActions` can’t be assigned at management group scope.',
      'Creating one requires `Microsoft.Authorization/roleDefinitions/write` on all assignable scopes (for example Owner or User Access Administrator).',
    ],
    example: 'A “VM Operator” custom role allows `Microsoft.Compute/virtualMachines/start/action`, `restart/action` and `deallocate/action` plus read, assigned to the operations group on production resource groups.',
    mistakes: ['Treating NotActions as an explicit deny.', 'Trying to delete a custom role that still has assignments.'],
    examTips: ['Start from a built-in role (clone it) and remove what isn’t needed.'],
    relations: {
      alternative: [{ to: 'role-definition', label: 'Built-in roles' }],
      partOf: [{ to: 'azure-rbac', label: 'A role definition you author' }],
    },
    place: ['azure-rbac'],
    sources: ['rbac-custom-roles'],
  },
  {
    id: 'managed-identity',
    name: 'Managed identity',
    aliases: ['system-assigned identity', 'user-assigned identity', 'MSI', 'managed service identity'],
    area: 'identity-governance',
    kind: 'feature',
    tier: 'should',
    summary: 'An automatically managed identity in Microsoft Entra ID that Azure resources use to authenticate to other services without storing credentials.',
    simple: 'A managed identity gives an Azure resource — like a web app or VM — its own login that Azure looks after. The app can reach storage or Key Vault without a password in its code.',
    why: 'Secrets in configuration files leak, expire and need rotation. Managed identities remove the secret entirely.',
    useWhen: ['An app or VM needs to call Azure Storage, Key Vault, SQL or other Entra-protected services'],
    avoidWhen: ['The caller runs outside Azure and can’t obtain a managed identity token (use a service principal or workload identity federation)'],
    howItWorks: [
      '**System-assigned**: created with the resource, shares its lifecycle (deleted with it), can’t be shared.',
      '**User-assigned**: a standalone Azure resource with its own lifecycle that can be attached to many resources; Microsoft recommends it for Microsoft services.',
      'Both are special service principals; grant them access with Azure RBAC role assignments.',
      'No credentials to manage and no extra cost.',
    ],
    example: 'A web app’s system-assigned identity gets Storage Blob Data Reader on one container, so the app reads images with no connection string.',
    mistakes: ['Enabling the identity but forgetting the role assignment.', 'Using a system-assigned identity when several resources need the same permissions.'],
    examTips: [
      'Identity must survive deleting and recreating the resource, or be shared by multiple VMs → user-assigned.',
      'Identity should disappear automatically with the resource → system-assigned.',
    ],
    relations: {
      partOf: [{ to: 'entra-id', label: 'A special service principal' }],
      security: [
        { to: 'role-assignment', label: 'Granted access through Azure roles' },
        { to: 'key-vault', label: 'Read secrets without stored credentials' },
      ],
      integratesWith: [
        { to: 'app-service', label: 'Common consumer' },
        { to: 'virtual-machine', label: 'Common consumer' },
      ],
      alternative: [{ to: 'service-principal', label: 'App registration with credentials' }],
    },
    sources: ['managed-identities'],
  },
  {
    id: 'service-principal',
    name: 'Service principal',
    aliases: ['app registration', 'enterprise application', 'application identity'],
    area: 'identity-governance',
    kind: 'resource',
    tier: 'should',
    summary: 'The identity of an application in a tenant, used by apps, scripts and pipelines to authenticate and receive role assignments.',
    simple: 'A service principal is a login for software instead of a person — for example a deployment pipeline that needs to create resources.',
    why: 'Automation must run with its own, limited permissions instead of a person’s account.',
    howItWorks: [
      'Can authenticate with a client secret, a certificate or federated credentials.',
      'Receives Azure roles like any other security principal.',
      'Managed identities are service principals whose credentials Azure manages for you.',
    ],
    mistakes: ['Giving a pipeline service principal Owner at subscription scope when Contributor on specific resource groups is enough.'],
    relations: {
      partOf: [{ to: 'entra-id', label: 'A directory object' }],
      alternative: [{ to: 'managed-identity', label: 'No credentials to manage when running in Azure' }],
      security: [{ to: 'role-assignment', label: 'Receives Azure roles' }],
    },
    sources: ['managed-identities', 'rbac-overview'],
  },
];
