import type { Concept } from '../schema';

export const MONITORING_CONCEPTS: Concept[] = [
  {
    id: 'azure-monitor',
    name: 'Azure Monitor',
    aliases: ['monitoring', 'observability', 'Monitor'],
    area: 'monitoring',
    kind: 'service',
    tier: 'must',
    summary: 'Azure’s platform for collecting, analysing and acting on metrics and logs from Azure resources, guest operating systems and applications.',
    simple: 'Azure Monitor is the control room: it gathers numbers and records from everything you run, shows them on charts, and raises the alarm when something looks wrong.',
    why: 'You can’t operate what you can’t see. One platform for data, dashboards, queries and alerts avoids a separate tool per service.',
    howItWorks: [
      'Two data stores: **Metrics** (numeric time series, fast, collected automatically) and **Logs** (rich records in Log Analytics, queried with KQL).',
      'Platform metrics and the activity log are collected automatically; **resource logs** require diagnostic settings; guest OS data requires the Azure Monitor Agent.',
      'Insights (VM, storage, network) provide curated views; alerts and autoscale act on the data.',
    ],
    visual: {
      type: 'flow',
      title: 'How monitoring data flows',
      alt: 'Azure resources emit platform metrics, activity log and resource logs; the Azure Monitor Agent collects guest data. Metrics and logs feed alerts, which trigger action groups.',
      spec: {
        root: {
          type: 'group',
          id: 'am-root',
          label: 'Azure Monitor',
          kind: 'plain',
          children: [
            {
              type: 'group',
              id: 'am-sources',
              label: 'Sources',
              kind: 'boundary',
              direction: 'col',
              children: [
                { type: 'node', id: 'am-res', label: 'Azure resource', sub: 'Platform metrics, resource logs', icon: 'server' },
                { type: 'node', id: 'am-guest', label: 'VM guest OS', sub: 'Via Azure Monitor Agent', icon: 'vm', concept: 'azure-monitor-agent' },
                { type: 'node', id: 'am-sub', label: 'Subscription', sub: 'Activity log', icon: 'subscription', concept: 'activity-log' },
              ],
            },
            {
              type: 'group',
              id: 'am-stores',
              label: 'Data platform',
              kind: 'boundary',
              direction: 'col',
              children: [
                { type: 'node', id: 'am-metrics', label: 'Metrics', sub: '93 days, automatic', icon: 'monitor', concept: 'metrics' },
                { type: 'node', id: 'am-logs', label: 'Log Analytics workspace', sub: 'KQL queries', icon: 'log-analytics', concept: 'log-analytics-workspace' },
              ],
            },
            {
              type: 'group',
              id: 'am-act',
              label: 'Act',
              kind: 'boundary',
              direction: 'col',
              children: [
                { type: 'node', id: 'am-alert', label: 'Alert rule', sub: 'Metric, log, activity log', icon: 'alert', concept: 'alert-rule' },
                { type: 'node', id: 'am-ag', label: 'Action group', sub: 'Email, SMS, webhook…', icon: 'users', concept: 'action-group' },
              ],
            },
          ],
        },
        edges: [
          { from: 'am-res', to: 'am-metrics', label: 'automatic', tone: 'data' },
          { from: 'am-res', to: 'am-logs', label: 'diagnostic setting', tone: 'data', style: 'dashed' },
          { from: 'am-guest', to: 'am-logs', label: 'DCR', tone: 'data' },
          { from: 'am-sub', to: 'am-logs', label: 'export', tone: 'data', style: 'dashed' },
          { from: 'am-metrics', to: 'am-alert' },
          { from: 'am-logs', to: 'am-alert' },
          { from: 'am-alert', to: 'am-ag', tone: 'allow' },
        ],
        flows: [
          { id: 'am-cpu', label: 'CPU spike alert', path: ['am-res', 'am-metrics', 'am-alert', 'am-ag'], tone: 'data', description: 'A platform metric crosses a threshold, a **metric alert** fires, and its **action group** notifies the on-call engineer.' },
          { id: 'am-log', label: 'Resource log query', path: ['am-res', 'am-logs', 'am-alert', 'am-ag'], tone: 'data', description: 'Resource logs reach Log Analytics only through a **diagnostic setting**, where a **log search alert** runs a KQL query on a schedule.' },
        ],
      },
    },
    relations: {
      contains: [
        { to: 'metrics', label: 'Numeric time series' },
        { to: 'log-analytics-workspace', label: 'Log data store' },
        { to: 'alert-rule', label: 'Detect conditions' },
        { to: 'autoscale', label: 'Scale on metrics' },
      ],
      integratesWith: [
        { to: 'diagnostic-settings', label: 'Route resource logs' },
        { to: 'azure-monitor-agent', label: 'Collect guest data' },
        { to: 'vm-insights', label: 'Curated VM monitoring' },
      ],
    },
    sources: ['metrics-overview', 'diagnostic-settings', 'alerts-overview'],
  },
  {
    id: 'metrics',
    name: 'Azure Monitor Metrics',
    aliases: ['platform metrics', 'metrics explorer', 'dimensions', 'aggregation'],
    area: 'monitoring',
    kind: 'feature',
    tier: 'must',
    summary: 'Numeric time-series data such as CPU percentage or request count, collected automatically every minute for most Azure resources and kept for 93 days.',
    simple: 'Metrics are the gauges on a dashboard — numbers over time, like CPU use or free disk space — available immediately without any setup.',
    why: 'Fast, cheap numeric data is ideal for charts, near real-time alerts and autoscale decisions.',
    howItWorks: [
      '**Platform metrics** are collected automatically (typically every minute) at no cost.',
      'Retention is **93 days**; a single metrics explorer chart shows up to 30 days at a time.',
      'Aggregations: Sum, Count, Average, Min, Max. Choosing the right one matters — average CPU hides short spikes that Max reveals.',
      '**Dimensions** (for example disk, instance or API name) let you filter and split a metric.',
      'Guest OS metrics need the Azure Monitor Agent; send metrics to Log Analytics with diagnostic settings for long-term analysis.',
    ],
    examTips: ['Longer than 93 days of metric history → route metrics to a Log Analytics workspace.', 'Split a metric by instance → use a dimension.'],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Half of the data platform' }],
      integratesWith: [
        { to: 'alert-rule', label: 'Metric alerts' },
        { to: 'autoscale', label: 'Autoscale rules' },
      ],
      alternative: [{ to: 'log-analytics-workspace', label: 'Rich log records and long retention' }],
    },
    sources: ['metrics-overview'],
  },
  {
    id: 'activity-log',
    name: 'Activity log',
    aliases: ['AzureActivity', 'control plane log', 'who changed it'],
    area: 'monitoring',
    kind: 'feature',
    tier: 'must',
    summary: 'A subscription-level record of control plane operations — who created, changed or deleted what, and when — kept for 90 days by default.',
    simple: 'The activity log is Azure’s visitor book: every create, change or delete of a resource is written down with who did it.',
    why: 'When something breaks after “nobody changed anything”, you need an authoritative record of management operations.',
    howItWorks: [
      'Collected automatically at no cost; entries can’t be modified or deleted.',
      'Records control plane operations (and service health, resource health, policy, autoscale events) — **not** data plane operations such as reading blobs.',
      'Retained **90 days**. Keep longer by exporting with a subscription diagnostic setting to Log Analytics (table `AzureActivity`), storage or Event Hubs.',
      'Activity log alerts are always stateless.',
    ],
    example: '`AzureActivity | where OperationNameValue has "networkSecurityGroups/securityRules/write" | project TimeGenerated, Caller, ResourceGroup`',
    examTips: ['Find who deleted a VM last week → activity log. Find who read a blob → resource logs (storage diagnostic settings).', 'Keep activity logs for a year → export to Log Analytics or storage.'],
    troubleshooting: ['App broke at 14:05 → filter the activity log to operations around 14:00 on the affected resource group and check Change history.'],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Platform log' }],
      dependsOn: [{ to: 'azure-resource-manager', label: 'Records control plane requests' }],
      integratesWith: [
        { to: 'diagnostic-settings', label: 'Export for longer retention' },
        { to: 'alert-rule', label: 'Activity log alerts' },
      ],
    },
    confusedWith: [{ id: 'diagnostic-settings', difference: 'The activity log records management operations automatically. Resource logs record what happens inside a resource and require a diagnostic setting.' }],
    sources: ['activity-log', 'alerts-overview'],
  },
  {
    id: 'diagnostic-settings',
    name: 'Diagnostic settings',
    aliases: ['resource logs', 'diagnostic logs', 'allLogs', 'AllMetrics'],
    area: 'monitoring',
    kind: 'setting',
    tier: 'must',
    summary: 'Configuration on a resource (or subscription) that sends resource logs, metrics or the activity log to Log Analytics, a storage account, Event Hubs or a partner solution.',
    simple: 'A diagnostic setting is a forwarding address for a resource’s detailed logs. Without one, those logs aren’t kept anywhere.',
    why: 'Resource logs are detailed and costly to store, so Azure only collects them where you ask — and you choose the destination that fits the purpose.',
    howItWorks: [
      '**Resource logs are not collected by default** — create a diagnostic setting.',
      'Destinations: **Log Analytics workspace** (query and alert), **storage account** (cheap archive), **Event Hubs** (stream to a SIEM), partner solutions.',
      'Up to **five** diagnostic settings per resource; select log categories or category groups (`allLogs`, `audit`) and `AllMetrics`.',
      'Storage and Event Hubs destinations must be in the same region as a regional resource.',
      'Data typically appears within about 90 minutes.',
    ],
    example: '`az monitor diagnostic-settings create --name to-law --resource <storageBlobServiceId> --workspace <workspaceId> --logs \'[{"categoryGroup":"allLogs","enabled":true}]\'`',
    mistakes: ['Expecting a Log Analytics query to show a resource’s logs without a diagnostic setting.', 'Sending logs to a storage account in a different region.'],
    examTips: ['Query logs with KQL → Log Analytics. Archive for years cheaply → storage account. Stream to a third-party SIEM → Event Hubs.'],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Routes platform logs' }],
      integratesWith: [
        { to: 'log-analytics-workspace', label: 'Query and alert destination' },
        { to: 'storage-account', label: 'Archive destination' },
        { to: 'activity-log', label: 'Subscription export' },
      ],
      governance: [{ to: 'azure-policy', label: 'deployIfNotExists policies create them at scale' }],
    },
    sources: ['diagnostic-settings'],
  },
  {
    id: 'log-analytics-workspace',
    name: 'Log Analytics workspace',
    aliases: ['LAW', 'Azure Monitor Logs', 'workspace', 'data retention'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'The Azure Monitor Logs store where log data from resources, agents and services is kept and queried with KQL.',
    simple: 'A Log Analytics workspace is a searchable database of everything your systems write down. You ask it questions in a query language called KQL.',
    why: 'Correlating events across many resources needs one queryable store with access control and retention settings.',
    howItWorks: [
      'Receives resource logs (diagnostic settings), guest data (Azure Monitor Agent with DCRs), activity logs and service data.',
      'Data lands in tables such as `AzureActivity`, `Heartbeat`, `Perf`, `Event`, `Syslog` and resource-specific tables.',
      'Default retention is 30 days and can be extended.',
      'Log search alerts, workbooks and Insights run on workspace data.',
    ],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Logs store' }],
      integratesWith: [
        { to: 'kql', label: 'Query language' },
        { to: 'diagnostic-settings', label: 'Receives resource logs' },
        { to: 'azure-monitor-agent', label: 'Receives guest data' },
        { to: 'recovery-services-vault', label: 'Backup reports' },
      ],
    },
    cost: ['Billed on data ingestion and retention beyond the included period — collect only what you need.'],
    sources: ['diagnostic-settings', 'backup-reports', 'activity-log'],
  },
  {
    id: 'azure-monitor-agent',
    name: 'Azure Monitor Agent (AMA)',
    aliases: ['AMA', 'data collection rule', 'DCR', 'Log Analytics agent', 'MMA'],
    area: 'monitoring',
    kind: 'tool',
    tier: 'must',
    summary: 'The agent that collects guest OS logs and performance data from VMs, scale sets and Arc-enabled servers according to data collection rules.',
    simple: 'The Azure Monitor Agent is a small program inside the VM that reads things only the operating system knows — event logs, memory use, syslog — and sends them to Azure Monitor.',
    why: 'Platform metrics can’t see inside the guest OS. Memory, disk space inside the OS, event logs and application logs need an agent.',
    howItWorks: [
      '**Data collection rules (DCRs)** define what to collect (Windows events, performance counters, syslog, text logs), transformations and destinations.',
      'Associate a DCR with machines; one agent can serve many DCRs.',
      'Replaces the **Log Analytics agent (retired August 2024)** and the diagnostics extensions.',
      'Installed as a VM extension, through Azure Policy, or by enabling VM insights; the agent is free — you pay for ingested data.',
    ],
    examTips: ['Collect Windows event logs from VMs → install AMA + create a DCR. The Log Analytics (MMA) agent is not the current answer.'],
    relations: {
      dependsOn: [{ to: 'virtual-machine', label: 'Runs in the guest OS' }],
      integratesWith: [
        { to: 'log-analytics-workspace', label: 'Sends logs' },
        { to: 'vm-insights', label: 'Powers VM insights' },
        { to: 'connection-monitor', label: 'On-premises sources use AMA with Azure Arc' },
      ],
      partOf: [{ to: 'azure-monitor', label: 'Guest data collection' }],
    },
    sources: ['ama-overview'],
  },
  {
    id: 'kql',
    name: 'Kusto Query Language (KQL)',
    aliases: ['Kusto', 'log query', 'summarize', 'where', 'project', 'render'],
    area: 'monitoring',
    kind: 'tool',
    tier: 'must',
    summary: 'The read-only query language for Log Analytics: a table name followed by pipe-separated operators such as where, summarize, project and render.',
    simple: 'KQL is how you ask your logs questions: start with a table, then filter, count and chart it step by step, each step separated by a pipe.',
    why: 'Finding a pattern in millions of log records needs a concise, fast query language.',
    howItWorks: [
      'Start with a table, then pipe: `Perf | where CounterName == "% Processor Time" | summarize avg(CounterValue) by bin(TimeGenerated, 5m), Computer | render timechart`.',
      '`where` filters rows; `project` selects columns; `summarize` aggregates (`count()`, `avg()`, `dcount()`); `bin()` groups time; `ago(1h)` makes relative times; `order by`/`top` sorts; `extend` adds calculated columns.',
      'Queries run against a scope: a workspace, resource group or resource.',
    ],
    example: '`AzureActivity | where TimeGenerated > ago(7d) | where ActivityStatusValue == "Failure" | summarize count() by Caller`',
    examTips: ['Count events per computer per hour → `summarize count() by Computer, bin(TimeGenerated, 1h)`.', 'Filter early with `where` for faster, cheaper queries.'],
    visual: { type: 'interactive', id: 'kql-builder', title: 'Build a query operator by operator' },
    relations: {
      dependsOn: [{ to: 'log-analytics-workspace', label: 'Queries workspace tables' }],
      integratesWith: [{ to: 'alert-rule', label: 'Log search alerts run KQL' }],
    },
    sources: ['activity-log', 'diagnostic-settings'],
  },
  {
    id: 'alert-rule',
    name: 'Alert rule',
    aliases: ['metric alert', 'log search alert', 'activity log alert', 'severity', 'dynamic threshold', 'stateful alert'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'Defines a scope, a signal and a condition; when the condition is met an alert fires and the attached action groups run.',
    simple: 'An alert rule is a tripwire: “if CPU stays above 90% for 10 minutes, tell the on-call team.”',
    why: 'Nobody watches dashboards all day. Alerts turn data into timely action.',
    howItWorks: [
      '**Metric alerts**: evaluate metrics, support multiple conditions and dynamic thresholds; one rule can cover many resources of the same type in a region.',
      '**Log search alerts**: run a KQL query on a schedule.',
      '**Activity log alerts**: fire on control plane events, Service Health or Resource Health events — always stateless.',
      'Severity **Sev 0 (critical)** to **Sev 4 (verbose)**.',
      '**Stateful** alerts fire once and resolve when the condition clears (metric alerts resolve after three consecutive healthy checks); **stateless** alerts fire every time.',
      'Fired alerts are stored for 30 days; creating rules needs Monitoring Contributor (or equivalent).',
    ],
    example: '`az monitor metrics alert create --name vm-cpu-high --resource-group rg-ops --scopes <vmId> --condition "avg Percentage CPU > 90" --window-size 10m --evaluation-frequency 5m --severity 2 --action ag-oncall`',
    mistakes: ['Alerting on every short spike instead of a sustained window.', 'Creating an alert without an action group, so nobody is notified.'],
    examTips: ['Notify when someone deletes a resource → activity log alert.', 'Notify when an error appears in logs → log search alert.'],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Act on data' }],
      dependsOn: [
        { to: 'metrics', label: 'Metric signals' },
        { to: 'log-analytics-workspace', label: 'Log signals' },
      ],
      integratesWith: [
        { to: 'action-group', label: 'What happens when it fires' },
        { to: 'alert-processing-rule', label: 'Suppress or add actions' },
        { to: 'activity-log', label: 'Activity log alerts' },
      ],
    },
    sources: ['alerts-overview'],
  },
  {
    id: 'action-group',
    name: 'Action group',
    aliases: ['notification', 'webhook', 'runbook action', 'ITSM'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'A reusable list of notifications (email, SMS, push, voice) and actions (webhooks, Logic Apps, Functions, Automation runbooks, ITSM, Event Hubs) triggered by alerts.',
    simple: 'An action group is the “who to call and what to do” list that many alerts can share.',
    why: 'Defining responders once and reusing them keeps notification lists consistent across hundreds of alerts.',
    howItWorks: [
      'Notification types: email, SMS, Azure mobile app push, voice.',
      'Action types: Automation runbook, Azure Function, ITSM, Logic App, secure webhook, webhook, Event Hubs.',
      'Referenced by alert rules, alert processing rules and budgets (subscription and resource group scopes).',
    ],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Alert response' }],
      integratesWith: [
        { to: 'alert-rule', label: 'Called when alerts fire' },
        { to: 'budget', label: 'Called by budget alerts' },
        { to: 'alert-processing-rule', label: 'Added at scale' },
      ],
    },
    sources: ['alerts-overview', 'budgets'],
  },
  {
    id: 'alert-processing-rule',
    name: 'Alert processing rule',
    aliases: ['action rule', 'suppression', 'maintenance window'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'Modifies fired alerts in a scope — suppressing their notifications or adding action groups — optionally on a schedule such as a maintenance window.',
    simple: 'An alert processing rule is a “do not disturb” switch (or an extra contact list) applied to many alerts at once, for example during planned maintenance.',
    why: 'Planned maintenance triggers floods of expected alerts, and some alert sources have no place to attach action groups.',
    howItWorks: [
      'Formerly called **action rules**.',
      'Rule types: **suppression** (remove all action groups) or **apply action groups** (add).',
      'Scope: resources, resource groups or a whole subscription (in the same subscription as the rule), with filters such as severity, resource type or alert rule.',
      'Schedule: always, a one-time window, or recurring (daily or weekly).',
      'Suppressed alerts still fire and remain visible — only notifications are suppressed.',
      'Don’t apply to Service Health alerts; changes can take up to 30 minutes.',
    ],
    examTips: [
      'Stop notifications every Saturday 22:00–02:00 for patching → alert processing rule with a recurring suppression schedule.',
      'Send all Azure Backup alerts to the backup team → alert processing rule that applies an action group.',
    ],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Alert management' }],
      integratesWith: [
        { to: 'alert-rule', label: 'Acts on fired alerts' },
        { to: 'action-group', label: 'Adds or removes action groups' },
        { to: 'azure-backup', label: 'Route built-in backup alerts' },
      ],
    },
    sources: ['alert-processing-rules'],
  },
  {
    id: 'vm-insights',
    name: 'Insights (VM, storage and network)',
    aliases: ['VM insights', 'Storage insights', 'Network insights', 'workbooks'],
    area: 'monitoring',
    kind: 'feature',
    tier: 'must',
    summary: 'Curated Azure Monitor experiences — built on metrics, logs and workbooks — for monitoring virtual machines, storage accounts and networks at scale.',
    simple: 'Insights are ready-made dashboards for common resources, so you don’t have to build every chart and query yourself.',
    why: 'Most organizations need the same views of VM performance, storage health and network topology; curated insights provide them immediately.',
    howItWorks: [
      '**VM insights** collects guest performance data with the Azure Monitor Agent and a data collection rule, with at-scale performance views.',
      '**Storage insights** uses platform metrics for capacity, availability, transactions and latency across accounts — no agent needed.',
      '**Network insights** shows the health and topology of network resources and links to Network Watcher tools.',
    ],
    relations: {
      partOf: [{ to: 'azure-monitor', label: 'Curated experiences' }],
      dependsOn: [{ to: 'azure-monitor-agent', label: 'VM insights guest data' }],
      integratesWith: [
        { to: 'virtual-machine', label: 'VM insights' },
        { to: 'storage-account', label: 'Storage insights' },
        { to: 'network-watcher', label: 'Network insights' },
      ],
    },
    sources: ['ama-overview', 'metrics-overview', 'network-watcher'],
  },
  {
    id: 'connection-monitor',
    name: 'Connection monitor',
    aliases: ['Network Watcher connection monitor', 'test group', 'checks failed', 'round-trip time'],
    area: 'monitoring',
    kind: 'feature',
    tier: 'must',
    summary: 'A Network Watcher feature that continuously tests connectivity between sources and destinations, measuring checks failed and round-trip time.',
    simple: 'Connection monitor keeps pinging the paths you care about — say, web VM to database — and warns you when they get slow or fail.',
    why: 'Connectivity problems are often intermittent. Continuous tests catch them and show where on the path they happen.',
    howItWorks: [
      'Structure: connection monitor → **test groups** → sources, destinations and **test configurations** (TCP, HTTP or ICMP; port; frequency; thresholds).',
      'Sources: Azure VMs and scale sets with the **Network Watcher agent** extension; on-premises machines with **Azure Arc** and the **Azure Monitor Agent**.',
      'Destinations: Azure VMs, Arc hosts, URLs, FQDNs or IP addresses.',
      'Metrics such as `ChecksFailedPercent` and `RoundTripTimeMs` can drive alerts; results also go to Log Analytics.',
      'Connection monitor (classic) is no longer available.',
    ],
    examTips: ['Continuously monitor latency between an on-premises server and an Azure VM → Connection monitor (Arc + AMA on-premises).'],
    relations: {
      partOf: [{ to: 'network-watcher', label: 'Network Watcher monitoring' }],
      integratesWith: [
        { to: 'alert-rule', label: 'Alert on checks failed or RTT' },
        { to: 'log-analytics-workspace', label: 'Stores results' },
      ],
    },
    sources: ['connection-monitor'],
  },
  {
    id: 'resource-health',
    name: 'Resource Health and Service Health',
    aliases: ['Service Health', 'Resource Health', 'Azure status', 'health advisory'],
    area: 'monitoring',
    kind: 'feature',
    tier: 'should',
    summary: 'Resource Health reports whether an individual resource is available; Service Health reports Azure incidents, planned maintenance and advisories affecting your subscriptions.',
    simple: 'Resource Health answers “is my VM okay?”; Service Health answers “is Azure itself having a problem in my region?”',
    why: 'Before debugging your configuration for hours, check whether the platform is the cause.',
    howItWorks: [
      'Both can trigger **activity log alerts**, so teams are notified automatically.',
      'Their events are recorded in the activity log.',
    ],
    examTips: ['Be notified of Azure incidents affecting your region → Service Health alert (an activity log alert).'],
    relations: {
      integratesWith: [
        { to: 'activity-log', label: 'Health events are logged' },
        { to: 'alert-rule', label: 'Activity log alerts' },
      ],
    },
    sources: ['alerts-overview', 'activity-log'],
  },
  {
    id: 'azure-backup',
    name: 'Azure Backup',
    aliases: ['backup', 'restore point', 'backup job', 'Resiliency', 'backup center'],
    area: 'monitoring',
    kind: 'service',
    tier: 'must',
    summary: 'A managed service that backs up Azure VMs, SQL and SAP HANA in VMs, Azure Files, blobs, disks and on-premises workloads into vaults, with policy-based schedules and retention.',
    simple: 'Azure Backup keeps dated copies of your servers and data so you can go back in time after deletion, corruption or ransomware.',
    why: 'Redundancy and replication copy mistakes instantly. Backups preserve history you can restore from.',
    howItWorks: [
      'Backups are stored in a **Recovery Services vault** (VMs, SQL/SAP HANA in VMs, Azure Files, MARS/DPM/MABS) or a **Backup vault** (blobs, disks, PostgreSQL, AKS and newer workloads).',
      'A **backup policy** sets schedule and retention; on-demand backups can be taken any time.',
      'VM restores: create a new VM, restore disks, replace existing disks, restore files, or restore to another region/subscription/zone when enabled.',
      'Monitoring and management are centralized in the **Resiliency** experience (previously Backup center); reports use diagnostic settings to Log Analytics.',
    ],
    relations: {
      contains: [
        { to: 'recovery-services-vault', label: 'Vault for VMs and files' },
        { to: 'backup-vault', label: 'Vault for newer workloads' },
        { to: 'backup-policy', label: 'Schedules and retention' },
      ],
      integratesWith: [
        { to: 'virtual-machine', label: 'VM backup' },
        { to: 'azure-files', label: 'File share backup' },
      ],
      monitoring: [
        { to: 'alert-processing-rule', label: 'Route backup alerts' },
        { to: 'log-analytics-workspace', label: 'Backup reports' },
      ],
      alternative: [{ to: 'site-recovery', label: 'Disaster recovery replication' }],
    },
    confusedWith: [{ id: 'site-recovery', difference: 'Backup keeps historical restore points (days to years) to recover data. Site Recovery continuously replicates VMs to another region to recover the whole workload quickly.' }],
    sources: ['rsv-overview', 'backup-vault', 'backup-monitoring'],
  },
  {
    id: 'recovery-services-vault',
    name: 'Recovery Services vault',
    aliases: ['RSV', 'vault', 'Cross Region Restore', 'CRR', 'soft delete for backups'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'The vault that stores backups of Azure VMs, SQL Server and SAP HANA in VMs, Azure Files and on-premises workloads, and that also hosts Azure Site Recovery.',
    simple: 'A Recovery Services vault is the secure safe where backups of your VMs and file shares are kept.',
    why: 'Backup data must be stored separately from the resources it protects, with its own security, redundancy and retention.',
    howItWorks: [
      'Protects Azure VMs, SQL Server and SAP HANA in VMs, Azure Files, and on-premises data through the MARS agent, DPM or Azure Backup Server; also used by Site Recovery.',
      '**Storage redundancy** (LRS, ZRS, GRS) should be set before protecting items.',
      '**Soft delete** keeps deleted backup data for 14 more days at no cost; **enhanced soft delete** allows longer, always-on retention.',
      '**Cross Region Restore** (GRS vault) restores VMs in the paired region at any time.',
      '**Customer-managed keys** must be configured before protecting any items.',
      'Built-in roles: Backup Contributor, Backup Operator, Backup Reader.',
    ],
    examTips: ['Restore VMs in the secondary region without waiting for Microsoft → enable Cross Region Restore on a GRS vault.', 'Backup data deleted by an attacker → recover within the soft delete period.'],
    relations: {
      partOf: [{ to: 'azure-backup', label: 'Vault type' }],
      integratesWith: [
        { to: 'backup-policy', label: 'Policies live in the vault' },
        { to: 'site-recovery', label: 'Also hosts Site Recovery' },
        { to: 'paired-region', label: 'Cross Region Restore' },
      ],
      monitoring: [{ to: 'diagnostic-settings', label: 'Backup reports' }],
    },
    confusedWith: [{ id: 'backup-vault', difference: 'Recovery Services vaults protect VMs, SQL/SAP HANA in VMs, Azure Files and on-premises workloads. Backup vaults protect newer workloads such as blobs, disks, PostgreSQL and AKS.' }],
    sources: ['rsv-overview', 'vm-restore'],
  },
  {
    id: 'backup-vault',
    name: 'Backup vault',
    aliases: ['Azure Backup vault', 'blob backup', 'disk backup'],
    area: 'monitoring',
    kind: 'resource',
    tier: 'must',
    summary: 'The vault type for newer Azure Backup workloads such as Azure Blobs, Azure Disks, Azure Database for PostgreSQL and AKS.',
    simple: 'A Backup vault is the newer kind of backup safe, used for things like blob containers and managed disks.',
    why: 'Newer workloads use a different backup architecture that authenticates to data sources with the vault’s managed identity.',
    howItWorks: [
      'Storage redundancy is chosen at creation.',
      'The vault’s managed identity needs roles on the resources it protects (for example on a storage account or disk).',
      'Supports Microsoft-managed or customer-managed keys.',
    ],
    examTips: ['Back up Azure Blobs or managed disks → Backup vault. Back up Azure VMs → Recovery Services vault.'],
    relations: {
      partOf: [{ to: 'azure-backup', label: 'Vault type' }],
      dependsOn: [{ to: 'managed-identity', label: 'Vault identity accesses data sources' }],
      integratesWith: [
        { to: 'blob-storage', label: 'Blob backup' },
        { to: 'managed-disk', label: 'Disk backup' },
      ],
    },
    sources: ['backup-vault'],
  },
  {
    id: 'backup-policy',
    name: 'Backup policy',
    aliases: ['Enhanced policy', 'Standard policy', 'instant restore', 'retention', 'on-demand backup'],
    area: 'monitoring',
    kind: 'setting',
    tier: 'must',
    summary: 'Defines when backups run and how long restore points are kept; Azure VMs use Standard (daily) or Enhanced (multiple times per day) policies.',
    simple: 'A backup policy is the schedule: how often to take a backup and how long to keep each copy.',
    why: 'How much data you can afford to lose (RPO) and how far back you must go set the backup frequency and retention.',
    howItWorks: [
      '**Standard** VM policy: once a day; instant restore snapshots kept 1–5 days.',
      '**Enhanced** VM policy: every 4, 6, 8, 12 or 24 hours; instant restore 1–30 days; required for Premium SSD v2, Ultra Disks and Trusted Launch VMs; can’t be switched back to Standard.',
      'Retention can be set for daily, weekly, monthly and yearly recovery points.',
      'Instant restore uses snapshots and is faster than restoring from the vault tier.',
    ],
    examTips: ['RPO of 4 hours for a VM → Enhanced policy.', 'VM with Premium SSD v2 disks → Enhanced policy.'],
    relations: {
      partOf: [{ to: 'recovery-services-vault', label: 'Stored in the vault' }],
      integratesWith: [{ to: 'virtual-machine', label: 'Assigned to protected VMs' }],
    },
    sources: ['vm-backup-enhanced'],
  },
  {
    id: 'site-recovery',
    name: 'Azure Site Recovery (ASR)',
    aliases: ['ASR', 'disaster recovery', 'failover', 'test failover', 'reprotect', 'recovery plan', 'RPO', 'RTO'],
    area: 'monitoring',
    kind: 'service',
    tier: 'must',
    summary: 'Continuously replicates VMs to a secondary region so the workload can fail over with minimal data loss, then fail back.',
    simple: 'Site Recovery keeps a live copy of your servers in another region. If the main region goes down, you switch to the copy and keep working.',
    why: 'Restoring many VMs from backup after a regional outage takes too long. Replication gives a much lower recovery time and data loss.',
    useWhen: ['The business needs a low RTO and RPO for a regional disaster', 'Rehearsing DR without affecting production'],
    avoidWhen: ['Recovering from accidental deletion or corruption days ago — replication copies that too; use backups'],
    howItWorks: [
      'Azure-to-Azure replication installs the **Mobility service** extension automatically and caches changes in a **cache storage account in the source region**.',
      'Target resources are created with an `-asr` suffix (resource group, VNet) and replica disks with `-ASRReplica`.',
      'Crash-consistent recovery points every 5 minutes; default recovery point retention is one day; app-consistent snapshots are off by default.',
      '**Test failover** into an isolated network first — no production impact.',
      'Failover recovery point options: **Latest processed** (lowest RTO), **Latest** (lowest RPO), **Latest app-consistent**, **Custom**.',
      'After failover: **Commit**, then **Re-protect** to replicate back, and later fail back.',
      'Recovery plans orchestrate the failover of multi-VM applications.',
    ],
    example: 'A hospital replicates its patient portal VMs from West Europe to North Europe and runs a quarterly test failover into an isolated test VNet.',
    mistakes: ['Treating Site Recovery as a backup — deleted data replicates too.', 'Never running a test failover, then discovering network mapping or DNS issues during a real disaster.'],
    examTips: [
      'Validate DR without downtime → test failover.',
      'After failover, replicate back to the original region → re-protect.',
      'Minimize data loss when failing over → Latest recovery point; minimize time → Latest processed.',
    ],
    visual: { type: 'interactive', id: 'backup-dr-timeline', title: 'Which protection saves you?' },
    relations: {
      dependsOn: [
        { to: 'recovery-services-vault', label: 'Managed from a vault' },
        { to: 'region', label: 'Replicates to another region' },
      ],
      integratesWith: [
        { to: 'virtual-machine', label: 'Replicates VMs' },
        { to: 'vnet', label: 'Network mapping to target VNets' },
      ],
      alternative: [{ to: 'azure-backup', label: 'Point-in-time data recovery' }],
    },
    confusedWith: [{ id: 'azure-backup', difference: 'Site Recovery = keep the business running in another region (minutes of data loss). Backup = recover data from a point in time (hours or days of history).' }],
    sources: ['asr-architecture', 'asr-failover'],
  },
];
