import type { Concept } from '../schema';

export const NETWORKING_CONCEPTS: Concept[] = [
  {
    id: 'vnet',
    name: 'Virtual network (VNet)',
    aliases: ['VNet', 'virtual network', 'address space'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A private, isolated network in one Azure region, defined by one or more address spaces and divided into subnets.',
    simple: 'A virtual network is your own private network inside Azure. Resources in it can talk to each other privately, and you decide what reaches in and out.',
    why: 'Workloads need private connectivity, isolation from other customers, and control over routing and filtering — just like an on-premises network.',
    howItWorks: [
      'A VNet exists in **one region** but spans that region’s availability zones.',
      'Use private ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, or 100.64.0.0/10). Some ranges are forbidden, including 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4 and 168.63.129.16/32.',
      'Address spaces can be added or changed; subnets can be resized only when nothing is deployed in them.',
      'VNets connect to each other with peering or VPN gateways, and to on-premises with VPN Gateway or ExpressRoute.',
      'Azure-provided DNS resolves names within the VNet; custom DNS servers can be set at VNet or NIC level.',
      'There is no broadcast or multicast — it is a Layer 3 network.',
    ],
    example: 'A hub VNet 10.0.0.0/16 holds shared services; spoke VNets 10.1.0.0/16 and 10.2.0.0/16 hold applications and are peered to the hub.',
    mistakes: [
      'Choosing overlapping address spaces for VNets (or with on-premises) that must later be peered or connected.',
      'Sizing subnets too small and discovering they can’t be resized once resources are deployed.',
    ],
    examTips: ['A VNet can’t span regions — use peering (global peering across regions).', 'Plan non-overlapping address spaces before peering.'],
    visual: { type: 'interactive', id: 'subnet-planner', title: 'Plan an address space' },
    relations: {
      contains: [{ to: 'subnet', label: 'Divided into subnets' }],
      partOf: [{ to: 'region', label: 'Scoped to one region' }],
      integratesWith: [
        { to: 'vnet-peering', label: 'Connect VNets privately' },
        { to: 'vpn-gateway', label: 'Hybrid and VNet-to-VNet connectivity' },
        { to: 'azure-dns', label: 'Name resolution and private zones' },
      ],
      monitoring: [{ to: 'network-watcher', label: 'Diagnostics enabled per region' }],
    },
    place: ['subscription', 'resource-group'],
    sources: ['vnet-faq'],
  },
  {
    id: 'subnet',
    name: 'Subnet',
    aliases: ['subnetwork', 'CIDR', 'reserved IP addresses', 'GatewaySubnet', 'AzureBastionSubnet'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A range of addresses inside a VNet where resources are placed; NSGs and route tables are commonly applied per subnet.',
    simple: 'Subnets split a virtual network into smaller neighbourhoods — for example one for web servers and one for databases — so each can have its own rules.',
    why: 'Grouping resources by role lets you apply filtering, routing and delegation to the whole group at once.',
    howItWorks: [
      'Azure reserves **five addresses** in every subnet: the network address, `.1` default gateway, `.2` and `.3` for Azure DNS, and the last (broadcast) address. A /24 has 251 usable addresses.',
      'Smallest IPv4 subnet is /29 (3 usable); largest is /2.',
      'A subnet can have one NSG and one route table.',
      'Some services require dedicated, specially named subnets, such as `AzureBastionSubnet` (/26 or larger) and `GatewaySubnet`.',
      'Subnets in new VNets can be private — without default outbound internet access.',
    ],
    example: '10.1.0.0/16 → snet-web 10.1.1.0/24, snet-app 10.1.2.0/24, snet-data 10.1.3.0/24, AzureBastionSubnet 10.1.255.0/26.',
    mistakes: ['Forgetting the five reserved addresses when sizing.', 'Deploying other resources into AzureBastionSubnet or GatewaySubnet.'],
    examTips: ['“How many VMs fit in a /28?” → 16 − 5 = 11 usable addresses.', 'Resizing a subnet requires it to be empty.'],
    relations: {
      partOf: [{ to: 'vnet', label: 'Carved from the address space' }],
      security: [{ to: 'nsg', label: 'Subnet-level filtering' }],
      networking: [
        { to: 'route-table', label: 'Custom routing' },
        { to: 'service-endpoint', label: 'Enabled per subnet' },
        { to: 'nat-gateway', label: 'Explicit outbound per subnet' },
      ],
      contains: [{ to: 'network-interface', label: 'NICs get addresses from the subnet' }],
    },
    place: ['subscription', 'resource-group', 'vnet'],
    sources: ['vnet-faq', 'bastion-config', 'default-outbound'],
  },
  {
    id: 'public-ip',
    name: 'Public IP address',
    aliases: ['Standard public IP', 'Basic public IP', 'static IP', 'DNS name label'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A resource that gives Azure resources an internet-routable IPv4 or IPv6 address; the Standard SKU is static, zone-aware and closed by default.',
    simple: 'A public IP is an internet address you attach to something — a VM, load balancer or gateway — so the internet can reach it or so it can reach out with a known address.',
    why: 'Internet-facing services and outbound connections that partners must allow-list need predictable public addresses.',
    howItWorks: [
      '**Basic SKU public IPs were retired on September 30, 2025.** Standard is the current SKU (Standard v2 works with Standard v2 NAT gateway).',
      'Standard public IPs are always **static** and **secure by default** — inbound traffic is blocked unless an NSG allows it.',
      'They can be zonal or zone-redundant; the zone can’t be changed after creation.',
      'Attach to a VM NIC, public load balancer frontend, NAT gateway, VPN or ExpressRoute gateway, Application Gateway, Azure Firewall or Bastion.',
      'Optional DNS name label: `<label>.<region>.cloudapp.azure.com`.',
      'Load balancer and public IP SKUs must match.',
    ],
    mistakes: ['Assuming a new Standard public IP on a VM makes the VM reachable — an NSG must allow the inbound port.', 'Giving every VM a public IP instead of using Bastion for administration.'],
    examTips: ['Static by definition, secure by default, zone-redundant option — the Standard SKU behaviours the exam expects.'],
    relations: {
      integratesWith: [
        { to: 'network-interface', label: 'Attach to a VM NIC' },
        { to: 'load-balancer', label: 'Public load balancer frontend' },
        { to: 'nat-gateway', label: 'Outbound SNAT addresses' },
        { to: 'bastion', label: 'Required by Bastion (most SKUs)' },
      ],
      security: [{ to: 'nsg', label: 'Must allow inbound traffic' }],
    },
    cost: ['Public IPv4 addresses carry a charge; IPv6 addresses don’t.'],
    sources: ['public-ip'],
  },
  {
    id: 'network-interface',
    name: 'Network interface (NIC)',
    aliases: ['NIC', 'IP configuration', 'private IP address', 'IP forwarding'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'The resource that connects a VM to a subnet, holding its private IP configuration, optional public IP and NSG.',
    simple: 'A NIC is the virtual network card of a VM. It gets an address from the subnet and can have its own firewall rules.',
    why: 'Separating the network interface from the VM lets IP settings, security and routing features be managed independently.',
    howItWorks: [
      'Private IPs can be dynamic or static; in Resource Manager they don’t change until the NIC is deleted or the address is changed.',
      'A NIC can have its own NSG, evaluated after the subnet NSG for inbound traffic and before it for outbound.',
      '**Enable IP forwarding** must be turned on for a network virtual appliance NIC to forward traffic not addressed to it.',
      'NICs can join application security groups.',
    ],
    relations: {
      partOf: [{ to: 'virtual-machine', label: 'Attached to a VM' }],
      dependsOn: [{ to: 'subnet', label: 'Gets its address from a subnet' }],
      security: [
        { to: 'nsg', label: 'NIC-level NSG' },
        { to: 'asg', label: 'Member of application security groups' },
      ],
      integratesWith: [
        { to: 'public-ip', label: 'Optional public address' },
        { to: 'effective-security-rules', label: 'View the combined rules for this NIC' },
      ],
    },
    place: ['resource-group', 'vnet', 'subnet'],
    sources: ['vnet-faq', 'routing'],
  },
  {
    id: 'nat-gateway',
    name: 'NAT gateway',
    aliases: ['Azure NAT Gateway', 'outbound connectivity', 'SNAT', 'default outbound access'],
    area: 'networking',
    kind: 'service',
    tier: 'should',
    summary: 'A managed service that provides outbound internet connectivity for a subnet using static public IP addresses or prefixes.',
    simple: 'A NAT gateway lets private VMs reach the internet (for updates or APIs) through a known public address, without letting the internet start connections to them.',
    why: 'Private subnets have no default outbound internet access, and implicit default outbound IPs are unpredictable. A NAT gateway provides explicit, scalable, known outbound addresses.',
    howItWorks: [
      'Associated with subnets; all outbound internet traffic from those subnets uses its public IPs.',
      'Microsoft recommends a NAT gateway as the explicit outbound method for most scenarios.',
      'Inbound connections from the internet are not allowed through a NAT gateway.',
      'Alternatives: a Standard Load Balancer outbound rule, a public IP on the NIC, or routing through Azure Firewall or an NVA.',
    ],
    example: 'A payment API partner allow-lists one IP; the app subnet’s NAT gateway makes every VM egress through that IP.',
    examTips: ['VM in a private subnet can’t reach Windows Update or activate Windows → add explicit outbound connectivity such as a NAT gateway.'],
    relations: {
      integratesWith: [
        { to: 'subnet', label: 'Associated per subnet' },
        { to: 'public-ip', label: 'Uses Standard public IPs or prefixes' },
      ],
      alternative: [
        { to: 'load-balancer', label: 'Outbound rules' },
        { to: 'network-virtual-appliance', label: 'Route outbound through a firewall' },
      ],
    },
    sources: ['default-outbound'],
  },
  {
    id: 'nsg',
    name: 'Network security group (NSG)',
    aliases: ['NSG', 'security rule', 'inbound rule', 'priority', 'default security rules'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A stateful set of allow and deny rules, evaluated by priority, that filters traffic to and from subnets and network interfaces.',
    simple: 'An NSG is a firewall rulebook for a subnet or a VM’s network card. Rules are checked from the lowest number up, and the first matching rule decides.',
    why: 'Every workload should receive only the traffic it needs. NSGs provide basic layer 3/4 filtering at no extra cost.',
    howItWorks: [
      'Rules have priority **100–4096**, source, destination, protocol, port range, direction and action. Lower numbers are processed first; processing stops at the first match.',
      'Sources and destinations can be IP addresses/CIDR ranges, **service tags** (Internet, VirtualNetwork, AzureLoadBalancer…) or **application security groups**.',
      '**Stateful**: return traffic for an allowed flow is allowed automatically.',
      'Default inbound rules: AllowVNetInBound (65000), AllowAzureLoadBalancerInBound (65001), DenyAllInbound (65500). Default outbound: AllowVnetOutBound (65000), AllowInternetOutBound (65001), DenyAllOutBound (65500). They can’t be deleted, only overridden.',
      'Associate with a subnet, a NIC, or both. Inbound: subnet NSG then NIC NSG. Outbound: NIC NSG then subnet NSG. Traffic must be allowed by both.',
      'Rule changes affect new connections, not existing ones.',
    ],
    example: 'snet-web NSG: 100 Allow Internet → TCP 443; 110 Allow AzureLoadBalancer → TCP 443; the default DenyAllInbound blocks everything else from the internet.',
    mistakes: [
      'Allowing a port on the NIC NSG while the subnet NSG still denies it.',
      'Forgetting that AllowVNetInBound lets every VM in the VNet (and peered VNets) reach every port unless you add higher-priority deny rules.',
      'Blocking the AzureLoadBalancer service tag and making all load balancer backends unhealthy.',
    ],
    examTips: [
      'Lowest priority number wins; the first match stops evaluation.',
      'Inbound: subnet NSG first, then NIC. Both must allow.',
      'NSGs are stateful — no rule is needed for return traffic.',
    ],
    troubleshooting: [
      'Can’t RDP/SSH to a VM → use IP flow verify to see which NSG rule denies the traffic.',
      'Unsure what really applies → view Effective security rules on the NIC.',
    ],
    visual: { type: 'interactive', id: 'nsg-evaluator', title: 'Send packets through two NSGs' },
    relations: {
      integratesWith: [
        { to: 'subnet', label: 'Associate to subnets' },
        { to: 'network-interface', label: 'Associate to NICs' },
        { to: 'asg', label: 'Use ASGs as sources and destinations' },
        { to: 'service-tag', label: 'Use service tags in rules' },
      ],
      monitoring: [
        { to: 'network-watcher', label: 'IP flow verify, NSG diagnostics' },
        { to: 'effective-security-rules', label: 'Combined view of applied rules' },
      ],
      alternative: [{ to: 'network-virtual-appliance', label: 'Layer 7 inspection with a firewall' }],
    },
    confusedWith: [
      { id: 'route-table', difference: 'An NSG decides whether traffic is allowed. A route table decides where allowed traffic goes next.' },
      { id: 'storage-firewall', difference: 'NSGs filter traffic in your VNet. The storage firewall filters who can reach a storage account’s public endpoint.' },
    ],
    cost: ['NSGs have no charge.'],
    place: ['vnet', 'subnet'],
    sources: ['nsg-overview', 'vnet-faq'],
  },
  {
    id: 'asg',
    name: 'Application security group (ASG)',
    aliases: ['ASG', 'application security group'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A named group of NICs used as the source or destination in NSG rules, so rules follow application roles instead of IP addresses.',
    simple: 'An ASG is a label like “web servers”. Write the firewall rule for the label, and every VM with that label follows it — even as VMs are added or re-addressed.',
    why: 'IP-based rules break when VMs are added, scaled or re-addressed. Role-based groups keep rules readable and correct.',
    howItWorks: [
      'Add NICs to one or more ASGs, then use the ASGs in NSG rules.',
      'All NICs in an ASG must be in the **same virtual network**.',
      'Rules apply only to NICs that are members of the referenced ASG.',
      'Because AllowVNetInBound allows intra-VNet traffic, add explicit deny rules where tiers must be isolated.',
    ],
    example: '100 Internet → AsgWeb TCP 80 Allow; 110 AsgLogic → AsgDb TCP 1433 Allow; 120 Any → AsgDb TCP 1433 Deny.',
    examTips: ['ASGs can’t span virtual networks.'],
    relations: {
      partOf: [{ to: 'nsg', label: 'Used inside NSG rules' }],
      dependsOn: [{ to: 'network-interface', label: 'NICs are the members' }],
    },
    place: ['vnet'],
    sources: ['asg'],
  },
  {
    id: 'service-tag',
    name: 'Service tag',
    aliases: ['VirtualNetwork tag', 'Internet tag', 'AzureLoadBalancer tag', 'Storage service tag'],
    area: 'networking',
    kind: 'setting',
    tier: 'should',
    summary: 'A Microsoft-maintained name for a group of IP prefixes — such as Internet, VirtualNetwork, AzureLoadBalancer or Storage — usable in NSG rules and routes.',
    simple: 'A service tag is a shortcut for “all the IP addresses of this Azure service”, kept up to date by Microsoft.',
    why: 'Azure service IP ranges change. Tags avoid maintaining long, fragile IP lists.',
    howItWorks: [
      'Common tags: `VirtualNetwork`, `Internet`, `AzureLoadBalancer`, `Storage` (and regional variants such as `Storage.EastUS`).',
      'Service tags can also be used as address prefixes in user-defined routes.',
    ],
    relations: { partOf: [{ to: 'nsg', label: 'Used in rules' }] },
    sources: ['nsg-overview', 'routing'],
  },
  {
    id: 'effective-security-rules',
    name: 'Effective security rules',
    aliases: ['effective NSG rules', 'IP flow verify', 'NSG diagnostics'],
    area: 'networking',
    kind: 'tool',
    tier: 'must',
    summary: 'The combined set of NSG rules actually applied to a network interface from both its subnet NSG and NIC NSG.',
    simple: 'Effective rules answer “what firewall rules really apply to this VM?” by combining every rulebook that affects it.',
    why: 'With NSGs on both subnet and NIC plus service tags, reading rules separately is error-prone. The effective view removes guesswork.',
    howItWorks: [
      'View on the NIC (or VM networking) and in Network Watcher.',
      'Service tags and ASGs are expanded so you can see which prefixes match.',
      '**IP flow verify** tests one packet (direction, protocol, local and remote IP and port) and names the rule that allows or denies it.',
    ],
    examTips: ['Which NSG rule blocks traffic to a VM → IP flow verify. Which rules apply in total → effective security rules.'],
    relations: {
      dependsOn: [
        { to: 'nsg', label: 'Aggregates NSG rules' },
        { to: 'network-interface', label: 'Viewed per NIC' },
      ],
      partOf: [{ to: 'network-watcher', label: 'Diagnostic view' }],
    },
    sources: ['network-watcher', 'nsg-overview'],
  },
  {
    id: 'route-table',
    name: 'Route table (user-defined routes)',
    aliases: ['UDR', 'user-defined route', 'next hop', 'system routes', 'forced tunneling', 'effective routes'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A resource holding user-defined routes that override Azure’s system routes for the subnets it is associated with.',
    simple: 'Azure automatically knows how to send traffic. A route table lets you change that — for example “send all internet-bound traffic through our firewall first.”',
    why: 'Security designs often require traffic to pass through a firewall or appliance, which default routing wouldn’t do.',
    howItWorks: [
      'System routes send VNet traffic within the VNet, `0.0.0.0/0` to the Internet, and some private ranges to None.',
      'UDR next hop types: **Virtual appliance** (with a next hop IP), **Virtual network gateway** (VPN gateway), **None** (drop), **Virtual network**, **Internet**.',
      'Route selection uses **longest prefix match**; for the same prefix, a UDR beats BGP, which beats system routes.',
      'Each subnet can have zero or one route table; one route table can serve many subnets. Up to 400 routes per table by default.',
      'An NVA’s NIC needs **IP forwarding** enabled; the OS must forward traffic too.',
      'Routing 0.0.0.0/0 to an appliance or gateway is **forced tunneling**.',
    ],
    example: 'snet-app route table: 0.0.0.0/0 → Virtual appliance 10.0.100.4 (hub firewall); 10.2.0.0/16 → Virtual appliance 10.0.100.4 so spoke-to-spoke traffic is inspected.',
    mistakes: [
      'Pointing a route at an NVA whose NIC doesn’t have IP forwarding enabled — traffic is dropped.',
      'Putting the NVA in the same subnet whose route table sends traffic to it, causing a loop.',
      'Adding a 0.0.0.0/0 UDR to GatewaySubnet.',
    ],
    examTips: [
      'Next hop “None” drops traffic.',
      'Troubleshoot with Network Watcher **Next hop** or the NIC’s **Effective routes**.',
      'Virtual network peering and service endpoints can’t be chosen as UDR next hops.',
    ],
    troubleshooting: ['VM can’t reach a destination but NSGs allow it → run Next hop; a UDR may send traffic to None or to an appliance that drops it.'],
    visual: { type: 'interactive', id: 'route-simulator', title: 'Find the next hop' },
    relations: {
      integratesWith: [
        { to: 'subnet', label: 'Associated per subnet' },
        { to: 'network-virtual-appliance', label: 'Next hop Virtual appliance' },
        { to: 'vpn-gateway', label: 'Next hop Virtual network gateway' },
      ],
      monitoring: [{ to: 'network-watcher', label: 'Next hop and effective routes' }],
      alternative: [{ to: 'nsg', label: 'Filtering rather than routing' }],
    },
    place: ['vnet', 'subnet'],
    sources: ['routing'],
  },
  {
    id: 'network-virtual-appliance',
    name: 'Network virtual appliance (NVA)',
    aliases: ['NVA', 'firewall appliance', 'Azure Firewall', 'virtual appliance'],
    area: 'networking',
    kind: 'resource',
    tier: 'should',
    summary: 'A VM or managed service (such as Azure Firewall) that inspects, filters or routes traffic sent to it with user-defined routes.',
    simple: 'An NVA is a security checkpoint you place in the network. Routes send traffic through it so it can be inspected before continuing.',
    why: 'Organizations need centralized inspection, logging and filtering beyond what NSGs provide.',
    howItWorks: [
      'Traffic reaches it through UDRs with next hop **Virtual appliance** and the appliance’s private IP (or an internal load balancer IP).',
      'VM-based appliances need IP forwarding enabled on the NIC.',
      'Typically placed in a hub VNet and used by peered spokes (service chaining).',
    ],
    relations: {
      dependsOn: [{ to: 'route-table', label: 'Traffic steered with UDRs' }],
      integratesWith: [{ to: 'hub-spoke', label: 'Central inspection in the hub' }],
      alternative: [{ to: 'nsg', label: 'Basic layer 3/4 filtering' }],
    },
    sources: ['routing', 'peering'],
  },
  {
    id: 'vnet-peering',
    name: 'Virtual network peering',
    aliases: ['peering', 'global VNet peering', 'gateway transit', 'use remote gateways', 'allow forwarded traffic'],
    area: 'networking',
    kind: 'feature',
    tier: 'must',
    summary: 'A private, low-latency connection between two VNets over the Microsoft backbone, in the same or different regions, subscriptions or tenants.',
    simple: 'Peering links two virtual networks so their resources talk as if they were on one network — privately and without gateways.',
    why: 'Workloads split across VNets (by team, environment or region) still need fast private connectivity.',
    howItWorks: [
      'Local peering (same region) and **global** peering (across regions).',
      'Address spaces **must not overlap**.',
      'Peering is **not transitive**: A↔B and B↔C doesn’t give A↔C. Use a hub NVA/firewall with UDRs, or peer A and C directly.',
      'A peering has a link in each VNet; **Initiated** means only one side exists, **Connected** means both are in place.',
      'Settings: allow access to the remote VNet, **allow forwarded traffic** (needed for traffic forwarded by an NVA), **allow gateway transit** (hub) and **use remote gateways** (spoke).',
      'Up to 500 peerings per VNet by default. If a peered VNet’s address space changes, **sync** the peering.',
      'No gateway or encryption is involved; there is a data transfer charge.',
    ],
    example: 'Spokes peer with the hub and use the hub’s VPN gateway through gateway transit, so one gateway serves every spoke’s connection to on-premises.',
    mistakes: [
      'Expecting spoke-to-spoke connectivity through the hub without an NVA and UDRs.',
      'Creating only one side of the peering and leaving it in Initiated state.',
      'Enabling “use remote gateways” in a spoke that already has its own gateway.',
    ],
    examTips: [
      'Peering isn’t transitive — the single most-tested peering fact.',
      'Overlapping address spaces can’t be peered.',
      'Hub = allow gateway transit; spoke = use remote gateways.',
    ],
    troubleshooting: [
      'Peering stuck in Initiated → create the matching peering from the other VNet.',
      'VMs in peered VNets can’t talk → check NSGs, UDRs, and whether traffic relies on transitive routing.',
      'Verify with effective routes: next hop type Virtual network peering.',
    ],
    visual: { type: 'interactive', id: 'peering-simulator', title: 'Test connectivity across peerings' },
    relations: {
      dependsOn: [{ to: 'vnet', label: 'Connects two VNets' }],
      integratesWith: [
        { to: 'hub-spoke', label: 'The basis of hub-and-spoke' },
        { to: 'vpn-gateway', label: 'Gateway transit' },
        { to: 'route-table', label: 'UDRs for transitive designs' },
      ],
      security: [{ to: 'nsg', label: 'NSGs still filter peered traffic' }],
      alternative: [{ to: 'vpn-gateway', label: 'VNet-to-VNet VPN connection' }],
    },
    cost: ['No charge to create a peering; data transferred across it is charged (more for global peering).'],
    sources: ['peering', 'vnet-faq'],
  },
  {
    id: 'hub-spoke',
    name: 'Hub-and-spoke topology',
    aliases: ['hub and spoke', 'hub VNet', 'spoke VNet', 'service chaining'],
    area: 'networking',
    kind: 'principle',
    tier: 'should',
    summary: 'A design where a central hub VNet hosts shared services (firewall, gateways, Bastion) and peered spoke VNets host workloads.',
    simple: 'Like an airport hub: every spoke network connects to one central network that holds the shared security and connectivity services.',
    why: 'Centralizing shared services reduces cost and gives one place to enforce inspection, while spokes stay isolated from each other.',
    howItWorks: [
      'Spokes peer to the hub; spokes don’t peer with each other.',
      'Spoke-to-spoke or spoke-to-internet traffic is routed to a hub firewall with UDRs.',
      'Gateway transit lets spokes use the hub’s VPN or ExpressRoute gateway.',
    ],
    relations: {
      dependsOn: [{ to: 'vnet-peering', label: 'Hub and spokes are peered' }],
      integratesWith: [
        { to: 'network-virtual-appliance', label: 'Central firewall' },
        { to: 'bastion', label: 'Shared administrative access' },
        { to: 'private-dns-zone', label: 'Central DNS zones linked to spokes' },
      ],
    },
    sources: ['peering'],
  },
  {
    id: 'vpn-gateway',
    name: 'VPN gateway',
    aliases: ['virtual network gateway', 'site-to-site VPN', 'point-to-site VPN', 'GatewaySubnet'],
    area: 'networking',
    kind: 'service',
    tier: 'advanced',
    summary: 'A virtual network gateway that sends encrypted traffic between an Azure VNet and on-premises networks or other VNets over the internet.',
    simple: 'A VPN gateway is an encrypted tunnel entrance in your virtual network, connecting it securely to your office network or to users’ laptops.',
    why: 'Hybrid organizations need private connectivity between on-premises and Azure without dedicated circuits.',
    howItWorks: [
      'Deployed into a subnet named `GatewaySubnet`.',
      'Site-to-site connects networks; point-to-site connects individual clients.',
      'Peered spokes can use it through gateway transit.',
    ],
    relations: {
      partOf: [{ to: 'vnet', label: 'Deployed in GatewaySubnet' }],
      alternative: [{ to: 'expressroute', label: 'Private dedicated connectivity' }],
      integratesWith: [{ to: 'vnet-peering', label: 'Gateway transit for spokes' }],
    },
    sources: ['peering', 'routing'],
  },
  {
    id: 'expressroute',
    name: 'ExpressRoute',
    aliases: ['private circuit', 'ExpressRoute gateway'],
    area: 'networking',
    kind: 'service',
    tier: 'advanced',
    summary: 'A private, dedicated connection between on-premises networks and Microsoft’s cloud through a connectivity provider, not over the public internet.',
    simple: 'ExpressRoute is a private highway from your datacenter into Azure, rather than a tunnel across the public internet.',
    why: 'Some workloads need predictable performance, higher throughput or connectivity that avoids the internet.',
    relations: { alternative: [{ to: 'vpn-gateway', label: 'Encrypted tunnels over the internet' }] },
    sources: ['peering'],
  },
  {
    id: 'bastion',
    name: 'Azure Bastion',
    aliases: ['Bastion', 'AzureBastionSubnet', 'jump box'],
    area: 'networking',
    kind: 'service',
    tier: 'must',
    summary: 'A managed service for RDP and SSH to VMs over TLS from the Azure portal (or native clients), so VMs need no public IP addresses.',
    simple: 'Bastion is a secure doorway into your VMs through the browser. You never have to expose the VMs’ remote desktop or SSH ports to the internet.',
    why: 'Public RDP and SSH endpoints are constantly attacked. Bastion removes them while still giving administrators access.',
    howItWorks: [
      'Deployed into a subnet named exactly **AzureBastionSubnet**, **/26 or larger**, in the same VNet as the Bastion host.',
      'Needs a **Standard, static** public IP (except the Developer SKU and private-only deployments).',
      'SKUs: **Developer**, **Basic**, **Standard** (host scaling, custom ports, shareable links, native client support), **Premium** (session recording, private-only deployment).',
      'Connects to VMs in the same VNet and in peered VNets.',
      'NSGs on the VM subnet must allow RDP/SSH from the AzureBastionSubnet range.',
    ],
    example: 'Operators connect to production VMs through Bastion in the hub; no VM in any spoke has a public IP.',
    mistakes: ['Creating the subnet as /27 or naming it anything other than AzureBastionSubnet.', 'Blocking inbound 3389/22 from the Bastion subnet in the VM subnet’s NSG.'],
    examTips: [
      'Subnet name AzureBastionSubnet, size /26 or larger.',
      'Connect with the local RDP/SSH client (native client) → Standard SKU or higher.',
      'Record sessions → Premium.',
    ],
    relations: {
      dependsOn: [
        { to: 'subnet', label: 'AzureBastionSubnet' },
        { to: 'public-ip', label: 'Standard static public IP' },
      ],
      integratesWith: [
        { to: 'virtual-machine', label: 'RDP/SSH target' },
        { to: 'vnet-peering', label: 'Reach VMs in peered VNets' },
      ],
      security: [{ to: 'nsg', label: 'VM NSGs must allow Bastion traffic' }],
    },
    place: ['vnet', 'subnet'],
    sources: ['bastion-config'],
  },
  {
    id: 'service-endpoint',
    name: 'Service endpoint',
    aliases: ['VNet service endpoint', 'Microsoft.Storage endpoint', 'Microsoft.Sql endpoint'],
    area: 'networking',
    kind: 'feature',
    tier: 'must',
    summary: 'A subnet setting that extends the VNet’s identity to an Azure PaaS service over the Azure backbone, so the service can allow that subnet in its firewall.',
    simple: 'A service endpoint lets a storage account (or other service) recognize “this traffic really comes from my private subnet”, so you can allow only that subnet. The service still uses its public address.',
    why: 'PaaS firewalls need a way to trust specific subnets without exposing the service to the whole internet.',
    useWhen: ['You want to lock a PaaS service to specific Azure subnets simply and at no extra cost'],
    avoidWhen: ['On-premises clients must reach the service privately', 'The service must have a private IP address or no public endpoint at all — use a private endpoint'],
    howItWorks: [
      'Enable per subnet for a service, for example `Microsoft.Storage`.',
      'Then add a virtual network rule on the service (such as the storage firewall).',
      'Traffic from the subnet reaches the service with the subnet’s private source address — the service’s **public** endpoint is still used.',
      'No additional cost.',
    ],
    mistakes: ['Enabling the endpoint on the subnet but not adding the network rule on the service (or the reverse).'],
    examTips: ['Service endpoint = public endpoint, trusted subnet. Private endpoint = private IP in your VNet.'],
    relations: {
      partOf: [{ to: 'subnet', label: 'Enabled per subnet' }],
      integratesWith: [{ to: 'storage-firewall', label: 'Virtual network rules' }],
      alternative: [{ to: 'private-endpoint', label: 'A private IP for the service' }],
    },
    confusedWith: [
      {
        id: 'private-endpoint',
        difference: 'A service endpoint keeps the service on its public IP but lets it trust your subnet. A private endpoint gives the service a private IP inside your VNet, reachable from peered and on-premises networks, and works with public access disabled.',
      },
    ],
    cost: ['No charge.'],
    place: ['vnet', 'subnet'],
    sources: ['vnet-faq', 'storage-firewall'],
  },
  {
    id: 'private-endpoint',
    name: 'Private endpoint',
    aliases: ['Private Link', 'privatelink', 'private link endpoint'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A network interface with a private IP from your subnet that connects privately to a specific Azure PaaS resource through Azure Private Link.',
    simple: 'A private endpoint brings a service — like one storage account — inside your network with its own private address, so traffic never needs its public address.',
    why: 'Sensitive data services shouldn’t be reachable from the internet, and on-premises or peered networks need private access to them.',
    useWhen: ['Public network access to the service must be disabled', 'On-premises or peered networks need private access', 'Access should be limited to one specific resource instance'],
    avoidWhen: ['Simple subnet-based trust is enough and DNS changes are undesirable — a service endpoint may suffice'],
    howItWorks: [
      'Creates a NIC with a private IP in your subnet, mapped to one resource and sub-resource (for example the `blob` endpoint of a storage account).',
      '**DNS is the critical part**: the public name `mystorage.blob.core.windows.net` CNAMEs to `mystorage.privatelink.blob.core.windows.net`; a private DNS zone `privatelink.blob.core.windows.net` linked to the VNet returns the private IP.',
      'Clients keep using the normal service name; connection strings don’t change.',
      'DNS resolution isn’t access control — disable public network access on the service to block the public path.',
      'On-premises clients need DNS forwarding (for example Azure DNS Private Resolver) to resolve the private zone.',
    ],
    example: 'An app VM resolves stfinance.blob.core.windows.net to 10.1.3.5 through the linked private DNS zone; the storage account has public network access disabled.',
    mistakes: [
      'Creating the private endpoint without a linked private DNS zone, so clients still resolve the public IP.',
      'Naming the private DNS zone after the account instead of using the recommended privatelink zone name.',
    ],
    examTips: [
      'Private endpoint + private DNS zone (privatelink.<service> zone) linked to the VNet.',
      'Service reachable privately from on-premises over VPN/ExpressRoute → private endpoint, not service endpoint.',
    ],
    troubleshooting: [
      'App still uses the public IP → run nslookup; check the privatelink zone exists, has the A record, and is linked to the client’s VNet.',
      'Name resolves to the private IP but access fails → check NSGs, routes and the service’s own authorization.',
    ],
    visual: { type: 'interactive', id: 'private-endpoint-dns', title: 'Resolve the name from inside and outside' },
    relations: {
      dependsOn: [
        { to: 'subnet', label: 'Private IP from your subnet' },
        { to: 'private-dns-zone', label: 'Name resolution to the private IP' },
      ],
      integratesWith: [
        { to: 'storage-account', label: 'Blob, file, queue, table endpoints' },
        { to: 'app-service', label: 'Private inbound access to apps' },
        { to: 'key-vault', label: 'Private access to vaults' },
        { to: 'container-registry', label: 'Private registry access (Premium)' },
      ],
      security: [{ to: 'storage-firewall', label: 'Disable public network access' }],
      alternative: [{ to: 'service-endpoint', label: 'Subnet trust over the public endpoint' }],
    },
    confusedWith: [{ id: 'service-endpoint', difference: 'Private endpoint: private IP in your VNet for one resource. Service endpoint: the service keeps its public IP but trusts your subnet.' }],
    cost: ['Private endpoints are billed per hour and per GB processed; service endpoints are free.'],
    place: ['vnet', 'subnet'],
    sources: ['private-endpoint-dns'],
  },
  {
    id: 'azure-dns',
    name: 'Azure DNS',
    aliases: ['DNS zone', 'public DNS zone', 'record set', 'name servers', 'A record', 'CNAME'],
    area: 'networking',
    kind: 'service',
    tier: 'must',
    summary: 'Hosts public DNS zones on Microsoft’s global name servers and private DNS zones for name resolution inside VNets.',
    simple: 'Azure DNS is the phone book service: it turns names like www.contoso.com into IP addresses, for the internet (public zones) or only inside your networks (private zones).',
    why: 'Every connection starts with a name lookup. Hosting DNS alongside resources lets records be managed with the same tools, access control and automation.',
    howItWorks: [
      'A **public zone** hosts records for a domain you own; delegate it by setting the zone’s name servers at your domain registrar.',
      'Records are grouped into **record sets** (A, AAAA, CNAME, MX, TXT, SRV and others).',
      'Azure DNS doesn’t register domain names — you buy the domain elsewhere and delegate it.',
      '**Private zones** resolve names only for linked VNets.',
      'VMs using Azure-provided DNS send queries to the virtual IP 168.63.129.16.',
    ],
    mistakes: ['Creating the zone but never updating the registrar’s name servers, so the internet never queries Azure DNS.'],
    examTips: ['Delegation: copy the Azure DNS name servers into the registrar’s NS settings.'],
    relations: {
      contains: [{ to: 'private-dns-zone', label: 'Private zones for VNets' }],
      integratesWith: [
        { to: 'app-service', label: 'Custom domain records' },
        { to: 'vnet', label: 'Name resolution in the VNet' },
      ],
    },
    sources: ['dns-autoregistration', 'appservice-custom-domain', 'vnet-faq'],
  },
  {
    id: 'private-dns-zone',
    name: 'Private DNS zone',
    aliases: ['Azure Private DNS', 'virtual network link', 'autoregistration', 'privatelink zone'],
    area: 'networking',
    kind: 'resource',
    tier: 'must',
    summary: 'A DNS zone resolvable only from linked virtual networks, used for internal names and private endpoint resolution, optionally auto-registering VM records.',
    simple: 'A private DNS zone is an internal phone book that only your linked networks can read — perfect for names like db01.corp.internal or private endpoints.',
    why: 'Internal resources need friendly, stable names without exposing them to the internet.',
    howItWorks: [
      'Link the zone to one or more VNets with **virtual network links**.',
      'Enable **autoregistration** on a link to create A records for VMs (primary NIC) in that VNet automatically.',
      'A VNet can be linked to **only one** private zone with autoregistration enabled; a zone can be linked to many VNets.',
      'Autoregistration creates records for VMs only; add other records (such as internal load balancers) manually.',
      'Private endpoints use recommended zone names such as `privatelink.blob.core.windows.net`.',
    ],
    examTips: ['VM names should appear in DNS automatically → link the VNet to the zone with autoregistration.', 'Only one autoregistration zone per VNet.'],
    troubleshooting: ['Name doesn’t resolve from a spoke VNet → the zone isn’t linked to that VNet (or the VNet uses a custom DNS server that doesn’t forward to Azure DNS).'],
    relations: {
      partOf: [{ to: 'azure-dns', label: 'Private zones' }],
      integratesWith: [
        { to: 'private-endpoint', label: 'Resolves private endpoint IPs' },
        { to: 'vnet', label: 'Linked to VNets' },
        { to: 'hub-spoke', label: 'Central zones linked to every spoke' },
      ],
    },
    sources: ['dns-autoregistration', 'private-endpoint-dns'],
  },
  {
    id: 'load-balancer',
    name: 'Azure Load Balancer',
    aliases: ['Standard Load Balancer', 'internal load balancer', 'ILB', 'public load balancer', 'load-balancing rule', 'inbound NAT rule', 'HA ports'],
    area: 'networking',
    kind: 'service',
    tier: 'must',
    summary: 'A layer 4 (TCP/UDP) load balancer that distributes flows from a frontend IP to healthy instances in a backend pool.',
    simple: 'A load balancer is a traffic director that spreads incoming connections across several identical VMs and stops sending traffic to any that fail their health check.',
    why: 'One VM is a single point of failure and a capacity limit. Balancing across healthy instances adds both availability and scale.',
    howItWorks: [
      '**Basic Load Balancer was retired on September 30, 2025** — Standard is the current SKU (Gateway SKU exists for third-party appliances).',
      '**Frontend**: a public IP (public load balancer) or private IP (internal load balancer).',
      '**Backend pool**: VMs or scale set instances in one VNet, added by NIC or IP.',
      '**Health probes**: TCP, HTTP or HTTPS; failing instances receive no new connections.',
      '**Load-balancing rules** map frontend IP:port to backend port for all pool members; **inbound NAT rules** forward a frontend port to one specific instance; **outbound rules** configure SNAT.',
      'Standard is **secure by default**: inbound traffic needs an NSG allow rule. **HA ports** (internal only) balance all ports and protocols.',
      'Distribution uses a five-tuple hash; session persistence can be None, Client IP, or Client IP and protocol.',
    ],
    example: 'Three web VMs across zones sit behind a zone-redundant public Standard Load Balancer with an HTTP probe on /health and a rule for TCP 443.',
    mistakes: [
      'Probing a port the application doesn’t listen on — every instance is marked unhealthy.',
      'NSG blocking traffic from the AzureLoadBalancer service tag to the probe port.',
      'Expecting HTTP path-based routing or TLS termination — that’s Application Gateway (layer 7).',
    ],
    examTips: [
      'RDP to one specific VM through the load balancer → inbound NAT rule.',
      'Internal load balancer for a firewall pair on every port → HA ports rule.',
      'Standard Load Balancer requires Standard public IPs.',
    ],
    troubleshooting: [
      'All backends unhealthy → check the app listens on the probe port/path (HTTP 200), the guest OS firewall, and NSG rules allowing AzureLoadBalancer.',
      'Traffic reaches only one VM → session persistence or long-lived connections, not necessarily a fault.',
    ],
    visual: { type: 'interactive', id: 'lb-probe-simulator', title: 'Why are my backends unhealthy?' },
    relations: {
      contains: [{ to: 'health-probe', label: 'Decides which instances are healthy' }],
      integratesWith: [
        { to: 'public-ip', label: 'Public frontend' },
        { to: 'vmss', label: 'Balance scale set instances' },
        { to: 'availability-zone', label: 'Zone-redundant frontends' },
      ],
      security: [{ to: 'nsg', label: 'Must allow inbound and probe traffic' }],
      monitoring: [{ to: 'metrics', label: 'Health probe status and data path availability' }],
    },
    sources: ['lb-skus', 'lb-components', 'lb-probes'],
  },
  {
    id: 'health-probe',
    name: 'Load balancer health probe',
    aliases: ['probe', 'HTTP probe', 'TCP probe', '168.63.129.16'],
    area: 'networking',
    kind: 'setting',
    tier: 'must',
    summary: 'A periodic TCP, HTTP or HTTPS check that decides whether a backend instance receives new connections.',
    simple: 'A health probe is the load balancer knocking on each server’s door every few seconds. No answer means no new visitors are sent there.',
    why: 'Sending users to a failed instance causes errors. Probes remove unhealthy instances automatically.',
    howItWorks: [
      'TCP probe: healthy if the TCP handshake succeeds. HTTP/HTTPS probe: healthy only if the path returns **200**.',
      'Interval defaults to 5 seconds in the portal (15 seconds through the API/CLI); a threshold sets how many consecutive results change state.',
      'Probes come from **168.63.129.16**, allowed by the default NSG rule for the AzureLoadBalancer service tag — the guest firewall must allow it too.',
      'An unhealthy instance gets no new connections; existing TCP connections continue.',
    ],
    examTips: ['HTTP probe returning 301, 401 or 500 counts as down — only 200 is healthy.'],
    relations: {
      partOf: [{ to: 'load-balancer', label: 'Defined on the load balancer' }],
      security: [{ to: 'nsg', label: 'AllowAzureLoadBalancerInBound' }],
    },
    sources: ['lb-probes'],
  },
  {
    id: 'network-watcher',
    name: 'Azure Network Watcher',
    aliases: ['Network Watcher', 'IP flow verify', 'next hop', 'connection troubleshoot', 'packet capture', 'VNet flow logs', 'topology'],
    area: 'networking',
    kind: 'service',
    tier: 'must',
    summary: 'A regional set of tools to monitor, diagnose and log IaaS network traffic: IP flow verify, next hop, effective security rules, connection troubleshoot, packet capture, flow logs and Connection monitor.',
    simple: 'Network Watcher is the network engineer’s toolbox in Azure — each tool answers one question such as “is this packet allowed?” or “where does this traffic go next?”',
    why: 'Virtual networks are invisible. Without purpose-built tools, connectivity problems become guesswork.',
    howItWorks: [
      'Enabled automatically in a region when you create or update a VNet there.',
      '**IP flow verify**: is a packet allowed or denied to/from a VM, and by which NSG rule?',
      '**NSG diagnostics**: detailed NSG evaluation for a flow, including adding rules.',
      '**Next hop**: the next hop type and route table for a destination — for routing problems.',
      '**Effective security rules**: all NSG rules applied to a NIC.',
      '**Connection troubleshoot**: a point-in-time end-to-end connection test from a VM.',
      '**Packet capture**: capture traffic on a VM (uses the Network Watcher extension).',
      '**VPN troubleshoot**, **Topology**, **Connection monitor**, and **flow logs** with traffic analytics.',
      'NSG flow logs can no longer be newly created and retire on September 30, 2027 — use **virtual network flow logs**.',
    ],
    examTips: [
      'Blocked by a security rule? → IP flow verify. Wrong route? → Next hop. Continuous monitoring? → Connection monitor. Log all traffic? → VNet flow logs.',
    ],
    visual: {
      type: 'flow',
      title: 'Pick the right Network Watcher tool',
      alt: 'A connection passes DNS, routing, NSG filtering and the target service; each stage maps to a Network Watcher tool.',
      spec: {
        root: {
          type: 'group',
          id: 'nw-root',
          label: 'Troubleshooting path',
          kind: 'plain',
          children: [
            { type: 'node', id: 'nw-vm', label: 'Source VM', sub: 'Where it starts', icon: 'vm' },
            { type: 'node', id: 'nw-route', label: 'Routing', sub: 'Tool: Next hop', icon: 'route', concept: 'route-table', detail: 'Next hop shows the next hop type (Internet, Virtual appliance, None…) and which route table decided it.' },
            { type: 'node', id: 'nw-nsg', label: 'NSG filtering', sub: 'Tool: IP flow verify', icon: 'nsg', concept: 'nsg', detail: 'IP flow verify names the exact rule that allows or denies the packet. Effective security rules lists everything applied.' },
            { type: 'node', id: 'nw-target', label: 'Destination', sub: 'Tool: Connection troubleshoot', icon: 'server', detail: 'Connection troubleshoot tests the whole path at a point in time; Connection monitor keeps testing continuously.' },
          ],
        },
        edges: [
          { from: 'nw-vm', to: 'nw-route', tone: 'data' },
          { from: 'nw-route', to: 'nw-nsg', tone: 'data' },
          { from: 'nw-nsg', to: 'nw-target', tone: 'data' },
        ],
        flows: [{ id: 'nw-flow', label: 'Follow a packet', path: ['nw-vm', 'nw-route', 'nw-nsg', 'nw-target'], tone: 'data', description: 'Check each stage in order: route, filter, then the destination itself.' }],
      },
    },
    relations: {
      contains: [
        { to: 'effective-security-rules', label: 'NSG views and tests' },
        { to: 'connection-monitor', label: 'Continuous connectivity tests' },
      ],
      monitoring: [
        { to: 'nsg', label: 'IP flow verify and NSG diagnostics' },
        { to: 'route-table', label: 'Next hop' },
        { to: 'vnet', label: 'Topology and flow logs' },
      ],
      integratesWith: [{ to: 'log-analytics-workspace', label: 'Traffic analytics and Connection monitor data' }],
    },
    sources: ['network-watcher', 'connection-monitor'],
  },
];
