import type { Concept } from '../schema';

export const STORAGE_CONCEPTS: Concept[] = [
  {
    id: 'storage-account',
    name: 'Storage account',
    aliases: ['general-purpose v2', 'GPv2', 'StorageV2', 'premium block blob account', 'FileStorage'],
    area: 'storage',
    kind: 'resource',
    tier: 'must',
    summary: 'A uniquely named namespace for Azure Storage data that hosts blobs, file shares, queues and tables with one set of redundancy, networking and encryption settings.',
    simple: 'A storage account is your data warehouse in Azure. Inside it you can keep files, blobs, message queues and simple tables, and the warehouse-wide settings decide how many copies exist and who can reach it.',
    why: 'Grouping data services under one account gives every object a globally unique address and lets you set durability, network access and security once.',
    useWhen: ['Storing unstructured data, file shares, queues or NoSQL key-value tables'],
    howItWorks: [
      '**Standard general-purpose v2** supports Blob (including Data Lake Storage), Files, Queue and Table with every redundancy option — recommended for most scenarios.',
      '**Premium block blobs** (SSD, LRS/ZRS) for high transaction rates and low latency; **premium file shares** (SSD, LRS/ZRS, SMB and NFS); **premium page blobs** for page blobs.',
      'Names are 3–24 characters, lowercase letters and numbers only, and globally unique — they become endpoints such as `https://<name>.blob.core.windows.net`.',
      'The account type can’t be changed after creation; create a new account and copy data instead.',
      'General-purpose v1 and legacy Blob Storage accounts are retired or scheduled for retirement — upgrade to GPv2.',
    ],
    example: 'Contoso Media uses a GPv2 account with ZRS for its website images and a separate premium file shares account for low-latency render farm scratch storage.',
    mistakes: [
      'Choosing a premium account type and later needing geo-redundancy or access tiers — premium accounts support LRS/ZRS and no hot/cool/cold/archive tiers.',
      'Using uppercase letters or hyphens in the account name.',
    ],
    examTips: [
      'Need GRS/RA-GRS/GZRS → Standard general-purpose v2.',
      'Need NFS file shares → premium (SSD) file shares.',
      'Moving an account to another region means creating a new account and copying the data (for example with AzCopy).',
    ],
    relations: {
      contains: [
        { to: 'blob-storage', label: 'Object storage' },
        { to: 'azure-files', label: 'SMB and NFS file shares' },
        { to: 'queue-storage', label: 'Messages' },
        { to: 'table-storage', label: 'Key-value entities' },
      ],
      dependsOn: [{ to: 'storage-redundancy', label: 'Redundancy set per account' }],
      security: [
        { to: 'access-keys', label: 'Shared Key authorization' },
        { to: 'sas', label: 'Delegated access' },
        { to: 'storage-encryption', label: 'Always-on encryption at rest' },
      ],
      networking: [
        { to: 'storage-firewall', label: 'Public endpoint network rules' },
        { to: 'private-endpoint', label: 'Private IP in your VNet' },
        { to: 'service-endpoint', label: 'Allow selected subnets' },
      ],
      monitoring: [{ to: 'diagnostic-settings', label: 'Resource logs for each service' }],
      governance: [{ to: 'resource-lock', label: 'Protect the account from deletion' }],
    },
    cost: ['Billed on region, account type, access tier, capacity, redundancy, transactions and data egress.'],
    troubleshooting: ['403 errors from an allowed identity → check the firewall first; network rules are evaluated before authorization.'],
    place: ['subscription', 'resource-group'],
    sources: ['storage-account-overview', 'storage-redundancy'],
  },
  {
    id: 'blob-storage',
    name: 'Blob Storage',
    aliases: ['blobs', 'container', 'block blob', 'append blob', 'page blob', 'object storage'],
    area: 'storage',
    kind: 'service',
    tier: 'must',
    summary: 'Object storage for unstructured data — documents, images, video, backups, logs — organized into containers.',
    simple: 'Blob Storage holds any kind of file-like data in the cloud. You put blobs into containers, a bit like files into folders, and reach them over HTTPS.',
    why: 'Applications need cheap, massively scalable storage for unstructured data that any client can reach over HTTP.',
    howItWorks: [
      '**Block blobs** for files and media; **append blobs** for logging; **page blobs** for random read/write such as unmanaged disks.',
      'Containers group blobs; anonymous read access can be allowed per container only if the account allows it.',
      'Access tiers (hot, cool, cold, archive) apply to block blobs.',
      'Data protection: soft delete for blobs and containers, versioning, object replication, lifecycle management.',
    ],
    examTips: ['Access tiers, lifecycle management tiering and object replication apply to block blobs.'],
    relations: {
      partOf: [{ to: 'storage-account', label: 'A service in the account' }],
      integratesWith: [
        { to: 'access-tier', label: 'Hot, cool, cold, archive' },
        { to: 'lifecycle-management', label: 'Automate tiering and deletion' },
        { to: 'object-replication', label: 'Copy to another account' },
      ],
      security: [
        { to: 'blob-soft-delete', label: 'Recover deleted blobs and containers' },
        { to: 'blob-versioning', label: 'Keep previous versions' },
        { to: 'sas', label: 'Time-limited delegated access' },
      ],
      alternative: [{ to: 'azure-files', label: 'SMB/NFS shares for lift-and-shift apps' }],
    },
    place: ['subscription', 'resource-group', 'storage-account'],
    sources: ['storage-account-overview', 'access-tiers'],
  },
  {
    id: 'azure-files',
    name: 'Azure Files',
    aliases: ['file share', 'SMB share', 'NFS share', 'classic file shares'],
    area: 'storage',
    kind: 'service',
    tier: 'must',
    summary: 'Fully managed file shares accessible over SMB (Windows, Linux, macOS) or NFS 4.1 (Linux).',
    simple: 'Azure Files is a shared network drive in the cloud. Servers and PCs can map it just like a file server share.',
    why: 'Many applications and users expect a traditional file share. Azure Files provides one without running and patching file servers.',
    useWhen: ['Lift-and-shift apps that read and write a file share', 'Replacing or extending on-premises file servers', 'Shared configuration or profile storage (for example FSLogix)'],
    avoidWhen: ['Serving web content or massive object data over HTTP — use Blob Storage'],
    howItWorks: [
      '**SMB** 3.1.1/3.0/2.1 over TCP port 445 — often blocked outbound by ISPs, so on-premises access usually goes over VPN or ExpressRoute with a private endpoint.',
      '**NFS 4.1** is Linux-only, requires SSD (premium) shares with LRS/ZRS, has no identity-based authentication and isn’t reachable from the internet (use a service or private endpoint).',
      'SMB supports identity-based access with AD DS, Microsoft Entra Domain Services or Microsoft Entra Kerberos, with share-level Azure roles plus Windows ACLs.',
      'Share soft delete is on by default for new accounts (7 days); share snapshots provide read-only point-in-time copies.',
      'Standard (HDD) shares support LRS/ZRS/GRS/GZRS; there is no read access to the secondary (no RA-GRS/RA-GZRS).',
    ],
    example: 'A law firm replaces its branch file server with an Azure file share joined to AD DS, mapped as the S: drive over its site-to-site VPN.',
    mistakes: ['Testing a mount from home and failing because port 445 is blocked.', 'Expecting NFS shares to support Microsoft Entra or AD DS authentication.'],
    examTips: [
      'Mount failures from on-premises → check outbound TCP 445.',
      'Azure Files doesn’t support RA-GRS or RA-GZRS.',
    ],
    troubleshooting: ['Mount error from on-premises → port 445 blocked; use VPN/ExpressRoute with a private endpoint or Azure File Sync.'],
    relations: {
      partOf: [{ to: 'storage-account', label: 'Classic file shares live in an account' }],
      security: [
        { to: 'files-identity-auth', label: 'AD DS / Entra Kerberos / Entra DS' },
        { to: 'access-keys', label: 'Key-based mount (not recommended)' },
      ],
      integratesWith: [
        { to: 'share-snapshot', label: 'Point-in-time copies' },
        { to: 'azure-backup', label: 'Backup for SMB shares' },
        { to: 'cloud-shell', label: 'Persists Cloud Shell $HOME' },
      ],
      networking: [{ to: 'private-endpoint', label: 'Private SMB access' }],
      alternative: [{ to: 'blob-storage', label: 'Object storage over HTTP' }],
    },
    place: ['subscription', 'resource-group', 'storage-account'],
    sources: ['files-planning', 'files-soft-delete'],
  },
  {
    id: 'queue-storage',
    name: 'Queue Storage',
    aliases: ['storage queue', 'queues'],
    area: 'storage',
    kind: 'service',
    tier: 'should',
    summary: 'A simple message queue in a storage account for decoupling application components with asynchronous messages.',
    simple: 'A queue is a to-do list for applications: one part drops messages in, another part picks them up and processes them later.',
    why: 'Decoupling producers from workers smooths out load spikes and keeps one component’s failure from breaking another.',
    relations: {
      partOf: [{ to: 'storage-account', label: 'A service in the account' }],
      integratesWith: [{ to: 'container-apps', label: 'Scale workers on queue length' }],
    },
    place: ['storage-account'],
    sources: ['storage-account-overview'],
  },
  {
    id: 'table-storage',
    name: 'Table Storage',
    aliases: ['storage table', 'tables'],
    area: 'storage',
    kind: 'service',
    tier: 'should',
    summary: 'A NoSQL key-value store for structured, schemaless entities in a storage account.',
    simple: 'Table Storage stores simple records (like a spreadsheet without fixed columns) cheaply at large scale.',
    why: 'Some data — device settings, user preferences, logs — needs fast lookups by key without a full relational database.',
    relations: { partOf: [{ to: 'storage-account', label: 'A service in the account' }] },
    place: ['storage-account'],
    sources: ['storage-account-overview'],
  },
  {
    id: 'storage-redundancy',
    name: 'Storage redundancy',
    aliases: ['LRS', 'ZRS', 'GRS', 'GZRS', 'RA-GRS', 'RA-GZRS', 'replication', 'geo-redundant storage'],
    area: 'storage',
    kind: 'setting',
    tier: 'must',
    summary: 'How many copies of storage account data Azure keeps and where: LRS, ZRS, GRS, GZRS, and read-access RA-GRS and RA-GZRS.',
    simple: 'Azure always keeps several copies of your data. Redundancy decides whether those copies sit in one building, across several buildings in a region, or also in a second region far away.',
    why: 'Hardware, datacenters and even regions can fail. Redundancy lets you pick how much failure your data must survive — and how much you pay for it.',
    howItWorks: [
      '**LRS**: three copies in one datacenter; survives drive, server and rack failures, not a datacenter disaster.',
      '**ZRS**: synchronous copies across three availability zones; reads and writes continue if a zone fails.',
      '**GRS**: LRS in the primary region plus an **asynchronous** copy (LRS) in the paired secondary region. The secondary isn’t readable until a failover.',
      '**GZRS**: ZRS in the primary plus an asynchronous LRS copy in the secondary.',
      '**RA-GRS / RA-GZRS**: as above, with the secondary always readable at `<account>-secondary.blob.core.windows.net`.',
      'Because geo-replication is asynchronous, a failover can lose recently written data.',
      'Redundancy doesn’t protect against deletion or overwrite — every copy receives the change.',
    ],
    example: 'A retailer keeps order documents on RA-GZRS: a zone outage causes no interruption, and during a regional outage the order-history page reads from the secondary endpoint.',
    mistakes: [
      'Treating redundancy as a backup. Accidental deletes replicate everywhere — use soft delete and versioning.',
      'Choosing ZRS or GZRS for data that must use the archive tier.',
    ],
    examTips: [
      'Survive a zone outage → ZRS (or GZRS). Survive a regional outage → GRS/GZRS. Read during a regional outage without failover → RA-GRS/RA-GZRS.',
      'Archive tier is supported only with LRS, GRS and RA-GRS.',
      'Azure Files doesn’t support RA-GRS/RA-GZRS; premium accounts support only LRS and ZRS.',
      'Durability: LRS at least 11 nines, ZRS at least 12 nines, GRS/GZRS at least 16 nines.',
    ],
    visual: { type: 'interactive', id: 'redundancy-explorer', title: 'Break things and see what survives' },
    relations: {
      partOf: [{ to: 'storage-account', label: 'An account-wide setting' }],
      dependsOn: [
        { to: 'availability-zone', label: 'ZRS and GZRS use zones' },
        { to: 'paired-region', label: 'GRS and GZRS use the paired region' },
      ],
      alternative: [{ to: 'blob-soft-delete', label: 'Protects against deletion, which redundancy does not' }],
    },
    confusedWith: [
      { id: 'blob-soft-delete', difference: 'Redundancy protects against infrastructure failure. Soft delete and versioning protect against people and apps deleting or overwriting data.' },
    ],
    cost: ['Cost rises from LRS → ZRS → GRS → GZRS; read-access options cost more again.'],
    place: ['storage-account'],
    sources: ['storage-redundancy', 'access-tiers'],
  },
  {
    id: 'storage-encryption',
    name: 'Storage encryption',
    aliases: ['SSE', 'customer-managed keys', 'CMK', 'infrastructure encryption', 'encryption scope', 'double encryption'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'All Azure Storage data is encrypted at rest with AES-256; you choose Microsoft-managed or customer-managed keys and can add infrastructure encryption or encryption scopes.',
    simple: 'Everything written to Azure Storage is automatically scrambled on disk. You can let Microsoft hold the keys, or hold them yourself in Key Vault.',
    why: 'Compliance and security require data to be unreadable if storage media leaves Microsoft’s control, and some regulations require customer control of the keys.',
    howItWorks: [
      'Server-side encryption is always on, can’t be disabled and costs nothing.',
      '**Microsoft-managed keys** by default; **customer-managed keys** stored in Azure Key Vault or Key Vault Managed HSM; **customer-provided keys** supplied per request for Blob Storage.',
      '**Encryption scopes** use different keys for different containers or blobs in one account.',
      '**Infrastructure encryption** adds a second AES-256 layer with a separate key; it must be enabled when the account is created.',
    ],
    examTips: [
      'Double encryption required → enable infrastructure encryption at account creation.',
      'Organization must control and rotate keys → customer-managed keys in Key Vault.',
    ],
    relations: {
      partOf: [{ to: 'storage-account', label: 'Configured per account' }],
      dependsOn: [{ to: 'key-vault', label: 'Holds customer-managed keys' }],
      security: [{ to: 'managed-identity', label: 'The account uses an identity to reach Key Vault' }],
    },
    place: ['storage-account'],
    sources: ['storage-encryption'],
  },
  {
    id: 'key-vault',
    name: 'Azure Key Vault',
    aliases: ['Key Vault', 'secrets', 'Managed HSM'],
    area: 'identity-governance',
    kind: 'service',
    tier: 'should',
    summary: 'A service for securely storing and controlling access to secrets, encryption keys and certificates.',
    simple: 'Key Vault is a safe for passwords, connection strings, certificates and encryption keys, so they never sit in code or config files.',
    why: 'Secrets scattered in configuration leak. A vault centralizes them with access control, logging and rotation.',
    howItWorks: [
      'Stores secrets, keys and certificates; access is controlled with Azure RBAC.',
      'Used for storage and disk customer-managed keys and App Service certificates.',
      'Applications read secrets with a managed identity.',
    ],
    relations: {
      security: [{ to: 'managed-identity', label: 'Apps authenticate without secrets' }],
      integratesWith: [
        { to: 'storage-encryption', label: 'Customer-managed keys' },
        { to: 'app-service-certificate', label: 'Import certificates' },
      ],
      networking: [{ to: 'private-endpoint', label: 'privatelink.vaultcore.azure.net' }],
    },
    sources: ['storage-encryption', 'private-endpoint-dns'],
  },
  {
    id: 'azcopy',
    name: 'AzCopy',
    aliases: ['azcopy copy', 'azcopy sync', 'azcopy login'],
    area: 'storage',
    kind: 'tool',
    tier: 'must',
    summary: 'A command-line tool for copying data to, from and between storage accounts (Blob and Azure Files), authorized with Microsoft Entra ID or a SAS token.',
    simple: 'AzCopy is a fast copy command for moving lots of files into or out of Azure Storage.',
    why: 'Portal uploads don’t scale. AzCopy handles large, parallel, resumable transfers and scripted synchronization.',
    howItWorks: [
      'Commands include `copy`, `sync`, `make`, `list`, `remove`, `login` and `jobs`. There is no rename command.',
      'Authorize with `azcopy login` (user, managed identity or service principal) or append a SAS token to the URL.',
      'With Microsoft Entra authorization the identity needs a **data** role such as Storage Blob Data Contributor — being the account Owner isn’t enough.',
      'Example: `azcopy copy "C:\\data" "https://<account>.blob.core.windows.net/backup?<SAS>" --recursive=true`',
    ],
    mistakes: ['Signing in as the subscription Owner and getting authorization errors because no Storage Blob Data role is assigned.'],
    examTips: ['Copy between two storage accounts or from Amazon S3 → AzCopy.'],
    relations: {
      dependsOn: [
        { to: 'sas', label: 'Token-based authorization' },
        { to: 'role-assignment', label: 'Data roles for Entra authorization' },
      ],
      integratesWith: [
        { to: 'blob-storage', label: 'Copy blobs' },
        { to: 'azure-files', label: 'Copy files' },
      ],
      alternative: [{ to: 'storage-explorer', label: 'Graphical tool' }],
    },
    sources: ['azcopy'],
  },
  {
    id: 'storage-explorer',
    name: 'Azure Storage Explorer',
    aliases: ['Storage Explorer', 'Storage browser'],
    area: 'storage',
    kind: 'tool',
    tier: 'must',
    summary: 'A free desktop app for Windows, macOS and Linux to browse and manage blobs, files, queues and tables.',
    simple: 'Storage Explorer is a file-manager style app for your storage accounts — drag, drop, copy and set properties without writing commands.',
    why: 'Administrators often need to inspect or fix data interactively, which is slow in the portal and awkward on the command line.',
    howItWorks: [
      'Connect by signing in with Microsoft Entra ID, with an account name and key, a SAS, or a connection string.',
      'Uses AzCopy under the hood for transfers.',
      'Browsing file shares with Entra sign-in also needs a role that can read account metadata, such as Reader and Data Access.',
    ],
    relations: {
      alternative: [{ to: 'azcopy', label: 'Scriptable transfers' }],
      integratesWith: [{ to: 'storage-account', label: 'Manage all data services' }],
    },
    sources: ['azcopy', 'files-share-permissions'],
  },
  {
    id: 'access-tier',
    name: 'Blob access tiers',
    aliases: ['hot tier', 'cool tier', 'cold tier', 'archive tier', 'rehydration', 'early deletion'],
    area: 'storage',
    kind: 'setting',
    tier: 'must',
    summary: 'Hot, cool, cold and archive tiers trade storage cost against access cost for block blobs, with minimum retention periods for the cooler tiers.',
    simple: 'Tiers are like storage shelves: the front shelf (hot) is expensive to rent but cheap to grab from; the basement (archive) is cheap to rent but slow and costly to get things back from.',
    why: 'Most data is read often at first and rarely later. Tiers let you pay for how the data is actually used.',
    howItWorks: [
      '**Hot**: online, highest storage cost, lowest access cost.',
      '**Cool**: online, minimum 30 days. **Cold**: online, minimum 90 days.',
      '**Archive**: offline, minimum 180 days; must be **rehydrated** to an online tier before reading — up to 15 hours, with Standard or High priority.',
      'Deleting, overwriting or moving a blob before its minimum period incurs a prorated early deletion charge.',
      'The account default tier can be hot, cool or cold (not archive); new GPv2 accounts default to hot.',
      'Tiers apply only to block blobs; premium block blob accounts don’t use these tiers.',
    ],
    example: 'Invoices are hot for 30 days while customers download them, move to cool, then cold after 90 days, and archive after a year for compliance.',
    mistakes: ['Archiving data that someone may need within minutes.', 'Moving data out of cool after 10 days and being surprised by early deletion charges.'],
    examTips: [
      'Archive isn’t supported on ZRS, GZRS or RA-GZRS accounts.',
      'Lifecycle management can move blobs to archive but can’t rehydrate them.',
      'Need to read an archived blob → rehydrate (Set Blob Tier or copy to an online tier).',
    ],
    visual: { type: 'diagram', id: 'access-tiers', alt: 'Hot, cool, cold and archive tiers compared by storage cost, access cost, minimum retention and latency.' },
    relations: {
      partOf: [{ to: 'blob-storage', label: 'Block blob setting' }],
      integratesWith: [
        { to: 'lifecycle-management', label: 'Automate tier moves' },
        { to: 'storage-redundancy', label: 'Archive needs LRS/GRS/RA-GRS' },
      ],
    },
    cost: ['Cooler tiers: lower storage price, higher read and transaction prices, plus early deletion charges.'],
    place: ['storage-account', 'blob-storage'],
    sources: ['access-tiers'],
  },
  {
    id: 'blob-soft-delete',
    name: 'Soft delete for blobs and containers',
    aliases: ['soft delete', 'container soft delete', 'undelete blob', 'restore container'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'Keeps deleted (or overwritten) blobs and deleted containers recoverable for a retention period of 1–365 days.',
    simple: 'Soft delete is a recycle bin for Blob Storage. Delete something by mistake and you can bring it back until the retention period ends.',
    why: 'The most common data loss isn’t hardware failure — it’s people and scripts deleting the wrong thing.',
    howItWorks: [
      '**Blob soft delete** (1–365 days) protects blobs, snapshots and versions from deletion and overwrite. Restore with **Undelete**.',
      '**Container soft delete** (1–365 days, default 7) restores a whole container with its contents — only to its **original name**.',
      'Neither protects against deleting the storage account (use a resource lock) or against metadata changes.',
      'Soft-deleted data is billed at the same rate as active data.',
      'Changing the retention period applies only to data deleted after the change.',
    ],
    example: 'A cleanup script deletes the “contracts” container. Container soft delete (14 days) lets the administrator restore it — with every blob — the next morning.',
    mistakes: [
      'Relying on blob soft delete to recover a deleted container — that needs container soft delete.',
      'Creating a new container with the deleted container’s name, which prevents restoring it.',
    ],
    examTips: [
      'Retention range is 1–365 days for both blob and container soft delete.',
      'Recover a deleted storage account? Soft delete doesn’t help — prevent it with a CanNotDelete lock.',
      'Microsoft recommends blob soft delete, container soft delete and versioning together.',
    ],
    visual: { type: 'interactive', id: 'blob-protection', title: 'Delete, overwrite, recover' },
    relations: {
      partOf: [{ to: 'blob-storage', label: 'Data protection' }],
      integratesWith: [{ to: 'blob-versioning', label: 'Combine for full protection' }],
      governance: [{ to: 'resource-lock', label: 'Protects the account itself' }],
      alternative: [{ to: 'storage-redundancy', label: 'Protects against infrastructure failure, not deletes' }],
    },
    place: ['storage-account', 'blob-storage'],
    sources: ['blob-soft-delete', 'container-soft-delete'],
  },
  {
    id: 'blob-versioning',
    name: 'Blob versioning',
    aliases: ['versioning', 'previous version', 'version ID'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'Automatically keeps the previous state of a blob as an immutable version every time it is written or deleted.',
    simple: 'Versioning is like “version history” for documents. Every change keeps the old copy, so you can go back to yesterday’s file.',
    why: 'Overwrites are as destructive as deletes. Versions let you roll back to any earlier state of a blob.',
    howItWorks: [
      'Each write (Put Blob, Put Block List, Copy Blob, Set Blob Metadata) creates a new version; the version ID is a timestamp.',
      'Deleting a blob turns the current version into a previous version.',
      'Restore by **copying a previous version over the base blob**.',
      'Not supported on accounts with a hierarchical namespace (Data Lake Storage).',
      'Every version is billed; use lifecycle management to delete old versions.',
    ],
    mistakes: ['Enabling versioning on frequently overwritten blobs without a lifecycle rule, then paying for thousands of versions.'],
    examTips: ['Object replication requires versioning on both accounts.', 'Restore an overwritten blob → promote a previous version.'],
    relations: {
      partOf: [{ to: 'blob-storage', label: 'Data protection' }],
      integratesWith: [
        { to: 'blob-soft-delete', label: 'Complements soft delete' },
        { to: 'object-replication', label: 'Required by object replication' },
        { to: 'lifecycle-management', label: 'Delete old versions' },
      ],
    },
    cost: ['Previous versions are billed like active data.'],
    place: ['storage-account', 'blob-storage'],
    sources: ['blob-versioning'],
  },
  {
    id: 'lifecycle-management',
    name: 'Lifecycle management',
    aliases: ['lifecycle policy', 'tierToCool', 'tierToArchive', 'daysAfterModificationGreaterThan'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'Rule-based policies that move blobs between access tiers or delete blobs, versions and snapshots based on age or last access.',
    simple: 'Lifecycle management is an automatic clean-up and filing rule: “after 30 days move to cool, after a year archive, after seven years delete.”',
    why: 'Manually moving or deleting millions of blobs isn’t realistic, and forgotten data quietly costs money.',
    howItWorks: [
      'A policy is JSON: rules with **filters** (blob types, prefixes, blob index tags) and **actions** on base blobs, snapshots and versions.',
      'Conditions use days since creation, last modification or last access (if access tracking is enabled).',
      'Actions include `tierToCool`, `tierToCold`, `tierToArchive` and `delete`.',
      'New or changed policies can take up to 24 hours to take effect.',
      'Lifecycle management can’t rehydrate blobs from archive.',
    ],
    example: '"baseBlob": { "tierToCool": { "daysAfterModificationGreaterThan": 30 }, "delete": { "daysAfterModificationGreaterThan": 2555 } }',
    mistakes: ['Expecting a new rule to act immediately.', 'Writing an archive rule for an account that uses ZRS.'],
    examTips: ['Rules can target a path prefix such as `container1/logs`.'],
    relations: {
      partOf: [{ to: 'blob-storage', label: 'Automates blob data' }],
      integratesWith: [
        { to: 'access-tier', label: 'Moves between tiers' },
        { to: 'blob-versioning', label: 'Deletes old versions' },
      ],
    },
    cost: ['The feature is free; you pay for the tier change operations.'],
    place: ['storage-account', 'blob-storage'],
    sources: ['lifecycle'],
  },
  {
    id: 'object-replication',
    name: 'Object replication',
    aliases: ['blob replication', 'replication policy'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'Asynchronously copies block blobs from a container in one storage account to a container in another account.',
    simple: 'Object replication automatically copies new and changed blobs from one account to another — for example to a second region closer to other users.',
    why: 'Reduces read latency for distant users, keeps a copy under different ownership, and supports data distribution — with more control than account-wide geo-redundancy.',
    howItWorks: [
      'Requires **blob versioning on both** accounts and **change feed on the source**.',
      'Supported on GPv2 and premium block blob accounts, not with a hierarchical namespace; only block blobs.',
      'The destination container is read-only while the policy is active.',
      'A source can replicate to at most two destination accounts; up to 1,000 rules per policy.',
      'By default only blobs created after the rule are copied; you can include existing blobs.',
      'Cross-tenant replication is disallowed by default on accounts created since December 15, 2023.',
    ],
    mistakes: ['Forgetting to enable change feed on the source.', 'Expecting to write to the destination container.'],
    examTips: ['Prerequisites question: versioning on source and destination + change feed on source.'],
    relations: {
      partOf: [{ to: 'blob-storage', label: 'Blob data distribution' }],
      dependsOn: [{ to: 'blob-versioning', label: 'Required on both accounts' }],
      alternative: [{ to: 'storage-redundancy', label: 'Account-wide replication to the paired region' }],
    },
    confusedWith: [{ id: 'storage-redundancy', difference: 'GRS replicates the whole account to a fixed paired region. Object replication copies chosen containers to any account you pick.' }],
    place: ['storage-account', 'blob-storage'],
    sources: ['object-replication'],
  },
  {
    id: 'share-snapshot',
    name: 'Azure Files share snapshot',
    aliases: ['file share snapshot', 'previous versions', 'share soft delete'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'A read-only, incremental, point-in-time copy of an entire file share used to restore files or the whole share.',
    simple: 'A share snapshot is a photo of the whole file share at a moment in time. If a file is changed or deleted, you copy it back from the photo.',
    why: 'File shares need quick self-service recovery of individual files after mistakes or corruption.',
    howItWorks: [
      'Up to 200 snapshots per share, retained up to 10 years; incremental, so only changes use capacity.',
      'Restore files in the portal, with Windows **Previous Versions**, or by copying.',
      'Deleting a share deletes its snapshots — enable **share soft delete** (on by default for new accounts, 7 days, 1–365) to recover deleted shares.',
      'Share soft delete works at share level only, not for individual files.',
      'Azure Backup for Azure Files schedules and retains snapshots for SMB shares.',
    ],
    examTips: ['Recover an individual deleted file → snapshot (or backup). Recover a deleted share → share soft delete.'],
    relations: {
      partOf: [{ to: 'azure-files', label: 'File share protection' }],
      integratesWith: [{ to: 'azure-backup', label: 'Managed snapshot schedules' }],
    },
    place: ['storage-account', 'azure-files'],
    sources: ['files-snapshots', 'files-soft-delete'],
  },
  {
    id: 'files-identity-auth',
    name: 'Identity-based access for Azure Files',
    aliases: ['AD DS authentication', 'Microsoft Entra Kerberos', 'Entra Domain Services', 'share-level permissions', 'Storage File Data SMB Share Contributor'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'SMB file share access using Kerberos identities from AD DS, Microsoft Entra Domain Services or Microsoft Entra Kerberos, authorized by share-level Azure roles and Windows ACLs.',
    simple: 'Instead of everyone mounting a share with one shared key, people use their normal work sign-in, and permissions work like a traditional Windows file server.',
    why: 'Storage account keys give full, unauditable, all-or-nothing access. Identity-based access gives per-user permissions and familiar NTFS ACLs.',
    howItWorks: [
      '**One identity source per storage account**: on-premises AD DS, Microsoft Entra Domain Services or Microsoft Entra Kerberos.',
      'AD DS supports hybrid identities (synced to Entra ID). Microsoft Entra Kerberos supports hybrid and cloud-only identities on Entra-joined or hybrid-joined clients.',
      '**Share-level** permissions use Azure roles: Storage File Data SMB Share Reader, Contributor, Elevated Contributor (can change ACLs), and others.',
      '**Directory and file-level** permissions are Windows ACLs.',
      'A **default share-level permission** can apply to all authenticated identities (it starts as none).',
      'Role assignments usually propagate within 30 minutes. Not supported for NFS shares.',
    ],
    example: 'Finance staff get Storage File Data SMB Share Contributor on the finance share; NTFS ACLs then restrict the “Payroll” folder to the payroll group.',
    mistakes: ['Assigning share-level roles and forgetting Windows ACLs (or the reverse).', 'Assigning a share role to a cloud-only user when the account uses AD DS authentication.'],
    examTips: [
      'Users need to modify NTFS permissions → Storage File Data SMB Share Elevated Contributor.',
      'Read-only access to the share → Storage File Data SMB Share Reader.',
    ],
    relations: {
      partOf: [{ to: 'azure-files', label: 'SMB authentication' }],
      dependsOn: [{ to: 'entra-id', label: 'Identities synchronized or cloud-native' }],
      security: [{ to: 'role-assignment', label: 'Share-level Azure roles' }],
      alternative: [{ to: 'access-keys', label: 'Key-based mounting (not recommended)' }],
    },
    place: ['storage-account', 'azure-files'],
    sources: ['files-identity', 'files-share-permissions'],
  },
  {
    id: 'access-keys',
    name: 'Storage account access keys',
    aliases: ['account key', 'Shared Key', 'key rotation', 'connection string'],
    area: 'storage',
    kind: 'setting',
    tier: 'must',
    summary: 'Two 512-bit keys that grant full access to all data in a storage account and can sign SAS tokens.',
    simple: 'Access keys are master keys to the whole storage account. Anyone holding one can read, change or delete any data.',
    why: 'Shared Key authorization is simple and universally supported, which is why many older tools use it — and why the keys must be protected.',
    howItWorks: [
      'Two keys (key1 and key2) allow rotation without downtime: move apps to key2, regenerate key1, move apps back, regenerate key2.',
      'Regenerating a key invalidates account SAS and service SAS signed with it; user delegation SAS isn’t affected.',
      'A key expiration policy creates rotation reminders.',
      'Listing keys requires `listkeys/action` — included in Owner, Contributor and Storage Account Key Operator Service Role.',
      'You can disallow Shared Key authorization so only Microsoft Entra ID works.',
    ],
    mistakes: ['Embedding keys in application code or config instead of using managed identities or Key Vault.'],
    examTips: [
      'Revoke all service and account SAS tokens immediately → regenerate the key that signed them.',
      'A ReadOnly lock on the storage account blocks listing keys.',
    ],
    relations: {
      partOf: [{ to: 'storage-account', label: 'Account credentials' }],
      integratesWith: [{ to: 'sas', label: 'Sign account and service SAS' }],
      security: [
        { to: 'key-vault', label: 'Store keys securely' },
        { to: 'managed-identity', label: 'Preferred keyless alternative' },
      ],
      governance: [{ to: 'resource-lock', label: 'ReadOnly blocks listing keys' }],
    },
    place: ['storage-account'],
    sources: ['access-keys', 'locks'],
  },
  {
    id: 'sas',
    name: 'Shared access signature (SAS)',
    aliases: ['SAS token', 'user delegation SAS', 'service SAS', 'account SAS', 'SAS URL'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'A signed URI that grants limited, time-bound access to storage resources without sharing account keys.',
    simple: 'A SAS is a temporary pass: “this person may read this one container until Friday.” You hand out the link, not the master key.',
    why: 'Clients and partners often need narrow, temporary access to specific data. Keys give too much; a SAS grants exactly what’s needed.',
    howItWorks: [
      '**User delegation SAS**: signed with a key obtained through Microsoft Entra credentials — Microsoft’s recommended type.',
      '**Service SAS**: signed with an account key; one service. Can be linked to a **stored access policy**.',
      '**Account SAS**: signed with an account key; one or more services and service-level operations.',
      'A SAS defines permissions, start and expiry, allowed IP ranges and protocol (HTTPS only is recommended).',
      'Network rules still apply — a valid SAS doesn’t bypass the storage firewall.',
      'Use a near-term expiry; set the start time in the past (or omit it) to avoid clock skew failures.',
    ],
    example: 'A partner receives a user delegation SAS with read and list permissions on one container, HTTPS only, valid for 48 hours.',
    mistakes: [
      'Issuing long-lived ad hoc service SAS tokens with no way to revoke them except rotating the account key.',
      'Granting account SAS with write and delete to a client that only needs to read one blob.',
    ],
    examTips: [
      'Revoke a service SAS without rotating keys → link it to a stored access policy and change or delete the policy.',
      'Stored access policies don’t work with account SAS or user delegation SAS.',
      'An expired or invalid SAS returns 403 Forbidden.',
    ],
    visual: { type: 'interactive', id: 'sas-builder', title: 'Build a SAS and read every parameter' },
    relations: {
      dependsOn: [
        { to: 'access-keys', label: 'Service and account SAS are signed with a key' },
        { to: 'entra-id', label: 'User delegation SAS uses Entra credentials' },
      ],
      integratesWith: [{ to: 'stored-access-policy', label: 'Revocable service SAS' }],
      networking: [{ to: 'storage-firewall', label: 'Firewall rules still apply' }],
      partOf: [{ to: 'storage-account', label: 'Delegated data access' }],
    },
    place: ['storage-account'],
    sources: ['sas-overview', 'stored-access-policy', 'access-keys'],
  },
  {
    id: 'stored-access-policy',
    name: 'Stored access policy',
    aliases: ['signed identifier', 'container access policy'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'A server-side policy on a container, file share, queue or table that defines SAS permissions and expiry, so linked service SAS tokens can be changed or revoked.',
    simple: 'A stored access policy is a rule kept on the storage side. Tokens point to the rule, so changing or deleting the rule changes or cancels every token that uses it.',
    why: 'Ad hoc SAS tokens can’t be revoked individually. Linking them to a policy gives administrators a kill switch.',
    howItWorks: [
      'Up to **five** stored access policies per container, file share, queue or table.',
      'Only **service SAS** tokens can use them.',
      'Revoke by deleting the policy, renaming its identifier, or setting its expiry in the past. Changes can take up to 30 seconds.',
      'A setting can’t be defined in both the SAS token and the policy.',
    ],
    examTips: ['“Revoke access for SAS tokens issued to a partner without affecting other applications” → stored access policy.'],
    relations: {
      partOf: [{ to: 'sas', label: 'Controls service SAS' }],
      integratesWith: [{ to: 'blob-storage', label: 'Defined on containers' }],
    },
    place: ['storage-account', 'blob-storage'],
    sources: ['stored-access-policy', 'sas-overview'],
  },
  {
    id: 'storage-firewall',
    name: 'Storage firewall and network rules',
    aliases: ['storage network rules', 'selected networks', 'trusted Microsoft services', 'resource instance rules', 'public network access'],
    area: 'storage',
    kind: 'feature',
    tier: 'must',
    summary: 'Rules that decide which networks can reach a storage account’s public endpoint: virtual network rules, IP rules, resource instance rules and trusted service exceptions.',
    simple: 'The storage firewall is a guest list at the door. Only the listed networks can even knock; they still need permission to access the data.',
    why: 'Even with strong authorization, data exposed to the entire internet is a larger attack surface. Network rules shrink it.',
    howItWorks: [
      '**Virtual network rules** allow specific subnets that have a `Microsoft.Storage` service endpoint (up to 400).',
      '**IP rules** allow public IP ranges only — not private addresses (up to 400).',
      '**Resource instance rules** allow specific Azure resources; **trusted services** exceptions allow listed Azure services.',
      'Once rules are configured, other sources get 403 errors; allowed sources still need authorization.',
      'Traffic from a subnet with a service endpoint uses its private address, so IP rules for that network’s public IP no longer match it.',
      'Private endpoints give access through a private IP and can be used with public network access disabled.',
    ],
    example: 'The finance storage account allows only the app subnet (service endpoint) and the head office public IP range; everything else is refused.',
    mistakes: [
      'Adding a VM’s private IP to the IP rules — IP rules accept public addresses only.',
      'Adding a service endpoint and keeping an IP rule for the subnet’s public IP, expecting the IP rule to still apply.',
    ],
    examTips: ['A SAS with an IP restriction doesn’t bypass network rules.', 'Limits: 400 IP rules, 400 virtual network rules, 200 private endpoints per account.'],
    troubleshooting: [
      'Portal shows “This request is not authorized” when browsing containers from home → your client IP isn’t allowed by the firewall.',
      'VM in an allowed subnet still denied → confirm the subnet has the Microsoft.Storage service endpoint.',
    ],
    relations: {
      partOf: [{ to: 'storage-account', label: 'Public endpoint protection' }],
      networking: [
        { to: 'service-endpoint', label: 'Required for virtual network rules' },
        { to: 'private-endpoint', label: 'Private access alternative' },
      ],
    },
    place: ['storage-account'],
    sources: ['storage-firewall'],
  },
];
