import {
  Activity,
  AppWindow,
  ArchiveRestore,
  Bell,
  Box,
  Boxes,
  Building,
  Cable,
  Cloud,
  CodeXml,
  Coins,
  Container,
  Database,
  DatabaseBackup,
  EthernetPort,
  FileKey,
  Files,
  FolderTree,
  Folder,
  Globe,
  HardDrive,
  Inbox,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Lock,
  MapPin,
  Network,
  Package,
  PlugZap,
  Route,
  Router,
  ScrollText,
  Server,
  Shield,
  ShieldCheck,
  Split,
  Table2,
  Tag,
  User,
  UserCog,
  Users,
  Waypoints,
  Zap,
  Blocks,
  ChartLine,
  Earth,
  Workflow,
  BadgeCheck,
  Castle,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';
import type { IconKey } from '@/content/schema';

export const ICONS: Record<IconKey, LucideIcon> = {
  tenant: Landmark,
  'management-group': FolderTree,
  subscription: BadgeCheck,
  'resource-group': Folder,
  user: User,
  users: Users,
  group: Users,
  identity: UserCog,
  role: KeyRound,
  policy: ScrollText,
  lock: Lock,
  tag: Tag,
  cost: Coins,
  vm: Server,
  vmss: Layers,
  'app-service': AppWindow,
  container: Container,
  'container-apps': Boxes,
  registry: Package,
  function: Zap,
  storage: Database,
  blob: Box,
  files: Files,
  queue: Inbox,
  table: Table2,
  disk: HardDrive,
  database: Database,
  vnet: Network,
  subnet: Blocks,
  nsg: Shield,
  firewall: Castle,
  route: Route,
  lb: Split,
  'app-gateway': Workflow,
  'public-ip': Globe,
  nic: EthernetPort,
  dns: MapPin,
  'private-endpoint': PlugZap,
  bastion: ShieldCheck,
  gateway: Router,
  peering: Waypoints,
  nat: Cable,
  internet: Earth,
  onprem: Building,
  monitor: Activity,
  'log-analytics': ChartLine,
  alert: Bell,
  backup: DatabaseBackup,
  recovery: ArchiveRestore,
  'key-vault': FileKey,
  code: CodeXml,
  region: Globe,
  zone: Layers,
  globe: Globe,
  shield: Shield,
  server: Server,
  laptop: Laptop,
  cloud: Cloud,
};

export function Icon({ name, ...props }: { name: IconKey } & LucideProps) {
  const Cmp = ICONS[name] ?? Box;
  return <Cmp aria-hidden="true" strokeWidth={1.75} {...props} />;
}
